MovingBlocks/Terasology

engine/src/main/java/org/terasology/rendering/primitives/ChunkTessellator.java
engine/src/main/java/org/terasology/rendering/primitives/ChunkVertexFlag.java
engine/src/main/resources/assets/shaders/chunk_frag.glsl
engine/src/main/resources/assets/shaders/chunk_vert.glsl

This supersedes #1465 by simply using a block hint to specify the water level. I'm surprised that is was to easy to fix.
A screenshot from PolyWorld illustrates the improvement:
Kudos go to @MarcinSc for the idea of using block hints.
Closes #1371
Closes #1466

Use block hints to specify water surface height

---

engine/src/main/java/org/terasology/config/RenderingConfig.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/videoSettings/ScreenshotSize.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/videoSettings/ScreenshotSizeBinding.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/videoSettings/VideoSettingsScreen.java
engine/src/main/java/org/terasology/rendering/opengl/DefaultRenderingProcess.java
engine/src/main/resources/assets/ui/menu/videoMenuScreen.ui

Added a option to change the size of the screenshots you take.
Changed oberwriteRtWidth and overwriteRtHeight in DefaultRenderingProcess.

Added a option to change the size of the screenshots you take.

---

engine/build.gradle
modules/Core/build.gradle

This should help prevent the situation when a a developer ends up with a reflections.cache that doesn't reflect their current compile state.

Remove Reflections.cache after jar build

---

engine/src/main/java/org/terasology/engine/modes/loadProcesses/InitialiseRemoteWorld.java
engine/src/main/java/org/terasology/engine/modes/loadProcesses/InitialiseWorld.java
engine/src/main/java/org/terasology/network/ServerInfoMessage.java
engine/src/main/java/org/terasology/network/internal/NetworkSystemImpl.java
engine/src/main/java/org/terasology/network/internal/ServerInfoMessageImpl.java
engine/src/main/java/org/terasology/protobuf/NetData.java
engine/src/main/java/org/terasology/rendering/cameras/Camera.java
engine/src/main/java/org/terasology/rendering/cameras/PerspectiveCamera.java
engine/src/main/java/org/terasology/world/generation/World.java
engine/src/main/java/org/terasology/world/generation/WorldBuilder.java
engine/src/main/java/org/terasology/world/generation/WorldImpl.java
engine/src/main/protobuf/NetMessage.proto

Currently a fixed height of 32 blocks is used to compute surface reflections. This PR makes this value flexible through a getter/setter in `Camera` and also uses a newly introduced sea level parameter to find meaningful values for this.
Every reflection level requires a rendering pass which is why only one reflection level is supported.
As the world generator defines this value, it must also be communicated to remote clients. This is done through the `ServerInfoMessage` class.

Support different camera reflection heights

---

engine/src/main/java/org/terasology/persistence/typeHandling/extensionTypes/EntityRefTypeHandler.java
engine/src/main/java/org/terasology/persistence/typeHandling/protobuf/ProtobufPersistedData.java

Primary symptom was the player's inventory ending up as 80 slots instead of 40. Backwards compatibility for older integer entity refs has been moved into the protobuf serialization handling layer.

Fixed an issue with lists of entity ref being loaded twice

---

engine/src/main/java/org/terasology/logic/console/commandSystem/CommandParameter.java

As per the comments in the previous PR for command parameters, corrects the usage string to correctly indicate that varargs are optional. Also moves the ... into the bracket and removes one repetition.

Corrected the usage string for vararg/array parameters.

---

engine/src/main/java/org/terasology/engine/modes/StateLoading.java
engine/src/main/java/org/terasology/engine/modes/loadProcesses/InitialiseWorld.java
engine/src/main/java/org/terasology/engine/modes/loadProcesses/InitialiseWorldGenerator.java

The TtA world gen creates the world later than the others (which is fine but this is why I hadn't noticed earlier). So this PR defers reading out the sea level until after world gen. initialization has completed.
Tested with TtA, Cities, Perlin and PolyWorld.
Fixes #1483

Defer reading sea level until after world gen init.

---

engine/src/main/java/org/terasology/engine/splash/SplashScreen.java

This PR fixes the headless server that can be run by Jenkins:
Before:
http://jenkins.movingblocks.net/job/TerasologyHeadlessServer/1/console
After:
http://jenkins.movingblocks.net/job/TerasologyHeadlessServer/2/console

Disable splashscreen in headless mode

---

facades/PC/build.gradle

Currently, running Terasology through the gradle command line with `runPC` or `startServer` does not include the PC facade's resource folder, which contains the logback config file.
As a consequence, logback uses its own default values. This includes the default log level that is at DEBUG causing major log spills.
This PR fixes that by adding the resources folder to the classpath. 
As a byproduct, it also enables the splash screen for `runPC`.

Fix resource classpath in gradle runs

---

build.gradle
engine/build.gradle
engine/src/main/java/org/terasology/rendering/nui/layouts/miglayout/MigComponent.java
engine/src/main/java/org/terasology/rendering/nui/layouts/miglayout/MigLayout.java

Closes #1464 
@immortius I wasn't able to upgrade gestalt-module (from 2.1.0 to 2.2.2) and/or reflections (from 0.9.9-RC1 to 0.9.9). 
`APIScanner.scan()` crashes on the inner class `PlaySoundNode$PlaySoundTask`. It is enumerated by `getTypesAnnotatedWith(API.class)` but calling `getAnnotation(API.class)` returns null.

Updated lwjgl, slf4j, miglayout, netty, groovy

---

engine/src/main/java/org/terasology/rendering/world/RenderableWorld.java
engine/src/main/java/org/terasology/rendering/world/RenderableWorldImpl.java
engine/src/main/java/org/terasology/rendering/world/WorldRendererLwjgl.java

This PR *mostly* just moves things around:
* it moves the content of the WorldRendererLwjgl's methods render() and renderWorld() into individual methods called only by render().
* it removes the renderWorld() method altogether 
* it moves a few methods so that they are closer to where they are called
However, it also does a few additional things:
* it changes the signature of RenderableWorld.updateAndQueueVisibleChunks() and the method's implementation in RenderableWorldImpl.
* it wraps mainDirectionaLight initialization in its own method, to remove some clutter from the constructor
* **it disable the light geometry stencil pass** as it currently doesn't seem to do much and it prevents a torch in hand to light up the environment nearby.

WorldRendererLwjgl.render() method refactoring

---

engine-tests/src/test/java/org/terasology/logic/location/LocationComponentTest.java
engine-tests/src/test/java/org/terasology/persistence/EntitySerializerTest.java
engine-tests/src/test/java/org/terasology/persistence/internal/StorageManagerTest.java
engine/src/main/java/org/terasology/entitySystem/entity/internal/PojoEntityManager.java

While this pull request contains mostly test fixes for #1517, it also changes the argument less create method of the EntityManager to ensure that the storage manager notices the creation of a otherwise component less entity.
@immortius Maybe we should make it possible to listen for create events anyway?
Otherwise we must adjust the other create methods to ensure that they add at least 1 component and not for example an empty list.

Mostly test fixes; It adjusts also EntityManager#create

---

facades/PC/src/main/java/org/terasology/engine/Terasology.java

Minor changes to the PC facade:
* Passed cmd. line args are printed out on start to indicate whether they were recognized or not. Helpful in particular for headless builds and for people that can't type properly :innocent: .
* Support the explicit disabling of the OpenAL sound system

Print out command line args. on start and support disabling OpenAL

---

engine/src/main/java/org/terasology/editor/properties/SceneProperties.java
engine/src/main/java/org/terasology/engine/modes/loadProcesses/InitialiseRemoteWorld.java
engine/src/main/java/org/terasology/engine/modes/loadProcesses/InitialiseWorld.java
engine/src/main/java/org/terasology/engine/subsystem/RenderingSubsystemFactory.java
engine/src/main/java/org/terasology/engine/subsystem/headless/renderer/HeadlessRenderingSubsystemFactory.java
engine/src/main/java/org/terasology/engine/subsystem/headless/renderer/HeadlessWorldRenderer.java
engine/src/main/java/org/terasology/engine/subsystem/lwjgl/LwjglRenderingSubsystemFactory.java
engine/src/main/java/org/terasology/rendering/backdrop/BackdropProvider.java
engine/src/main/java/org/terasology/rendering/backdrop/BackdropRenderer.java
engine/src/main/java/org/terasology/rendering/backdrop/Skysphere.java
engine/src/main/java/org/terasology/rendering/opengl/DefaultRenderingProcess.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersBase.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersLightShaft.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersSky.java
engine/src/main/java/org/terasology/rendering/world/WorldRenderer.java
engine/src/main/java/org/terasology/rendering/world/WorldRendererLwjgl.java

In this PR the current skysphere is mantained as an implementation of two new interfaces: **BackdropProvider** and **BackdropRenderer**, both available through the CoreRegistry. Almost every other change is a consequence. 
The few unrelated changes are some easy optimizations I stumbled upon, some renaming to remove abbreviations and some unused imports removals.

BackdropProvider, BackdropRenderer

---

engine/src/main/java/org/terasology/persistence/internal/DelayedEntityRefCopyStrategy.java

Reasoning: Not all modules do properly apply the null object pattern for EntityRefs.
This fixes #1531

Handle null EntityRefs in DelayedEntityRefCopyStrategy.

---

engine-tests/src/test/java/org/terasology/persistence/WorldSerializerTest.java
engine/src/main/java/org/terasology/logic/behavior/BehaviorNodeFactory.java
engine/src/main/java/org/terasology/world/block/items/BlockItemFactory.java

Promote entity builder usage: It is just not more correct in terms of life cycle events but it is also needed for a future improvment of the autosaving.
The plan is to get rid of EntityRef#setPersistent so that it is simpler to just record the changes of non persistent entities.

Promote entity builder usage

---

engine/build.gradle

Updated to gestalt-module 2.2.3, fixing #1310

Fix for #1310

---

engine-tests/src/test/java/org/terasology/world/propagation/BetweenChunkPropagationTest.java
engine/src/main/java/org/terasology/logic/console/commands/ServerCommands.java
engine/src/main/java/org/terasology/persistence/internal/AbstractStorageManager.java
engine/src/main/java/org/terasology/persistence/internal/ReadOnlyStorageManager.java
engine/src/main/java/org/terasology/persistence/internal/ReadWriteStorageManager.java
engine/src/main/java/org/terasology/world/chunks/ChunkProvider.java
engine/src/main/java/org/terasology/world/chunks/localChunkProvider/LocalChunkProvider.java
engine/src/main/java/org/terasology/world/chunks/remoteChunkProvider/RemoteChunkProvider.java

This is a follow-up PR for #1526 based on the suggestions that were made there.
* The command was renamed to `reloadChunk` as it better reflects what it does.
* The command returns a human-readable message whether the command was successful or not.
* Storing to disk is explicitly disabled. It will reload the previously saved status or trigger regeneration.
* The read-only storage manager now also destroys entities in unloaded chunks correctly.
Entities from chunks that are reloaded will survive unharmed.

Disable storing chunks on reload

---

engine/src/main/resources/assets/shaders/chunk_frag.glsl
engine/src/main/resources/assets/shaders/post_frag.glsl

Reasoning:
This should fix the following error message generated by a buggy graphic
driver(See #1215 & http://forum.terasology.org/threads/black-window-nothing.1204/):
"Only GLSL version > 110 allows postfix "F" or "f" for float
WARNING: 0:475: Only GLSL version > 110 allows postfix "F" or "f" for float"
In GLSL shader version 1.10 it is not allowed to use the suffix,
but we explictly state via #version that version 1.20 should be used.
So it is a bug if a graphic driver complains about it.

Don't use the float suffix f in post_frag.glsl.

---

engine/src/main/java/org/terasology/persistence/internal/SaveTransaction.java

The first patch fixes  a small autosave issue::
When a entity got created and detroyed between two autosaves,
then the entity manager private to the saving thread needs still to
recreate the creation of that entity to ensure that entity referenes 
to it get properly invalidated. The recrecation however failed,
sometimes, because the nextId value of the entity manager
did not get incremented properly.
Steps to reproduce: Throw a torch from a stack and recollect it. 
This causes an entity to be created and destroyed.
Without this patch you get an error message at the next
autosave(In this case it makes no diference otherwise, as the recollected torch
does not got referenced by any entity)..
The second patch ist just a cleanup in the same code area.

Autosave fix and cleanup

---

engine-tests/src/test/java/org/terasology/math/ChunkMathTest.java
engine-tests/src/test/java/org/terasology/math/TeraMathTest.java
engine/src/main/java/org/terasology/math/ChunkMath.java
engine/src/main/java/org/terasology/math/TeraMath.java
engine/src/main/java/org/terasology/monitoring/gui/ChunkMonitorDisplay.java
engine/src/main/java/org/terasology/network/internal/NetClient.java
engine/src/main/java/org/terasology/network/internal/ServerImpl.java
engine/src/main/java/org/terasology/persistence/internal/SaveTransaction.java
engine/src/main/java/org/terasology/rendering/nui/layers/ingame/metrics/DebugOverlay.java
engine/src/main/java/org/terasology/rendering/world/ChunkMeshUpdateManager.java
engine/src/main/java/org/terasology/world/block/items/BlockItemSystem.java
engine/src/main/java/org/terasology/world/chunks/internal/ChunkRelevanceRegion.java
engine/src/main/java/org/terasology/world/chunks/localChunkProvider/LocalChunkProvider.java
engine/src/main/java/org/terasology/world/chunks/remoteChunkProvider/RemoteChunkProvider.java
engine/src/main/java/org/terasology/world/internal/ChunkViewCoreImpl.java
engine/src/main/java/org/terasology/world/internal/WorldProviderCoreImpl.java
engine/src/main/java/org/terasology/world/propagation/AbstractFullWorldView.java
engine/src/main/java/org/terasology/world/propagation/LocalChunkView.java
engine/src/main/java/org/terasology/world/propagation/StandardBatchPropagator.java
engine/src/main/java/org/terasology/world/propagation/SunlightRegenBatchPropagator.java
modules/Core/src/main/java/org/terasology/core/world/generator/facetProviders/HeightMapSurfaceHeightProvider.java

The goal of this PR is to prepare moving the TeraMath class to the project TeraMath, where it is needed. In the next iteration, `Vector3i`, `Region3i`, etc. can be moved there also.
I therefore split the class into *general* math code that stays (can be moved transparently to TeraMath later) and *chunk/block-related* code, which shouldn't be in a generic math library. This is now in `ChunkMath`.
I guess that ChunkMath is not ideal for all methods. Some should be somewhere else, but the focus here is on the TeraMath refactoring.
This PR already fixes all uses in engine and Core and supports a transition phase for modules through the `@Deprecate` annotation.

Extracted ChunkMath from TeraMath

---

engine/src/main/java/org/terasology/engine/subsystem/lwjgl/LwjglGraphics.java

Improved LwjglGraphics.checkOpenGL() to be more informative and specific in case of GPU compatibility problems.

Improved LwjglGraphics.checkOpenGL() output

---

engine-tests/src/test/java/org/terasology/utilities/FastNoiseTest.java
engine-tests/src/test/java/org/terasology/utilities/NoiseTest.java
engine/src/main/java/org/terasology/utilities/procedural/FastNoise.java
engine/src/main/java/org/terasology/utilities/procedural/NoiseTable.java

This PR adds `FastNoise`, a 2D and 3D noise based on two NoiseTables and a few related tests. It ..
* is compatible to the `Noise2D` and `Noise3D` interfaces
* is about 2x faster than SimplexNoise and 5x faster than PerlinNoise (see tests)
* produces white noise (equal frequency on all levels)
* produces normalized values (output is always in [0..1])
* produces equal-distributed values (same probability)
* has high resolution (values differ in ranges < 0.000015)
* supports only discrete input values: noise(3.4) == noise(2.7) :cry: 
* has a range of only 256 values: noise(256) == noise(0) :cry:

Add FastNoise (based on NoiseTable)

---

engine/src/main/java/org/terasology/rendering/world/RenderableWorld.java
engine/src/main/java/org/terasology/rendering/world/RenderableWorldImpl.java
engine/src/main/java/org/terasology/rendering/world/WorldRendererLwjgl.java
engine/src/main/java/org/terasology/world/chunks/ChunkConstants.java
engine/src/main/java/org/terasology/world/chunks/internal/ChunkImpl.java

Renderer changes: 
* moved some of the WorldRendererLwjgl.update() functionality in a codeblock that is executed only once per frame, in preRenderUpdate()
* split RenderableWorldImpl.updateAndQueueVisibleChunks() method in generateVBOs() and queueVisibleChunks() methods
* eliminated RenderableWorldImpl.processChunk() method: its code is now in queueVisibleChunks()
* removed WorldRendererLwjgl.getTime() method: no usages and it's best to get the time from the Time class, I reasoned
* removed WorldRendererLwjgl.updateTick(): its code is now in update()
Also addressed *part* of issue #1536, regarding the ChunkConstant class. Modified ChunkImpl class accordingly. 
See comments for some additional notes on specific lines.

Changes to WorldRendererLwjgl update() method, addressed part of issue #1536

---

modules/Core/build.gradle

This is one way to fix #1558 although it is a bit of a goofy way (bases the origin dir to scan on `<classes>/org` which avoids `<classes>/test/org`). Better to tidy up the organization of tests / dependency order but that's a bigger change.
I've tested it with Pathfinding: the reflection cache file is smaller with the Nanoware fork's Core build.gradle (http://jenkins.terasology.org/view/Nanoware/job/NanoPathfinding/lastSuccessfulBuild/artifact/build/libs/Pathfinding-0.1.0-SNAPSHOT.jar) vs the regular Pathfinding. No more crashing with the new jar.
@immortius any concerns?

Ignore test classes for reflection cache in modules

---

engine/src/main/java/org/terasology/engine/subsystem/lwjgl/LwjglGraphics.java

Mini PR as I realized that for some reason I didn't include OpenGL 2.0 in the checks even though it is used in the code.
I also added a comment to highlight that some of the extensions required eventually became part of Opengl 3.0.

Further refined LwjglGraphics.checkOpenGL() method.

---

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/CieCamColors.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/PlayerSettingsScreen.java
engine/src/main/java/org/terasology/rendering/nui/widgets/UISlider.java
engine/src/main/resources/assets/skins/framed_image.skin
engine/src/main/resources/assets/ui/menu/playerMenuScreen.ui

Currently, the player can pick a color in the full RGB spectrum. I'd like to restrict that to a number of distinguishable colors that have almost identical chroma (think of it as color intensity) and luminosity (similar to brightness).
I think that this has two advantages: 
* It's easier to choose: the player just needs to pick the hue of the color, the engine makes sure that it is recognizable on de-saturated (preferably dark) background.
* Bright/dark colors - in particular black and white - are reserved for other uses. This contrast allows for highlighting (system messages, admin users, etc).
This PR also adds a frame box around the color image (to mitigate contrast effects and to look nicer).
I added two sets of colors. The first one (L60C50) looks like this (very smooth color …

Replace player color RGB sliders with CieCAM color hue

---

engine/build.gradle
facades/PC/src/main/java/org/terasology/engine/Terasology.java

The relevant change is that not only `RuntimeException`s are caught, but all `Throwable`s. This was an issue in the past with reflection-based code as it often throws `NoSuchMethodError`, `NoSuchFieldError` etc. I also had a few `ExceptionInInitializerError`s due to the initialization of the VERTICAL_SEGMENTS constant.
Locking CR to 2.0.0 makes it more robust to failures of Artifactory (it doesn't look for newer versions if 2.0.0 is present) and enables us to build new jars without integrating them in the main project.
**EDIT:** Fixes #1557

Lock CrashReporter version to 2.0.0 and also report Errors

---

modules/Core/src/main/java/org/terasology/core/world/generator/rasterizers/FloraRasterizer.java

@msteiger  please review. I am not sure if it is intended that intNoise returns negative numbers. Also there is no javadoc on the intNoise method. Could you add some please? I would find it interesting to know what the expected return values are. e.g. if they are supposed to be negative or not.

Prevent an index out of bounds exception due to negative noise.

---

engine-tests/src/test/java/org/terasology/persistence/internal/StorageManagerTest.java
engine/src/main/java/org/terasology/entitySystem/entity/EntityRef.java
engine/src/main/java/org/terasology/entitySystem/entity/internal/BaseEntityRef.java
engine/src/main/java/org/terasology/entitySystem/entity/internal/EntityDestroySubscriber.java
engine/src/main/java/org/terasology/entitySystem/entity/internal/EntityInfoComponent.java
engine/src/main/java/org/terasology/entitySystem/entity/internal/NullEntityRef.java
engine/src/main/java/org/terasology/entitySystem/entity/internal/PojoEntityManager.java
engine/src/main/java/org/terasology/persistence/internal/DelayedEntityRef.java
engine/src/main/java/org/terasology/persistence/internal/DelayedEntityRefCopyStrategy.java
engine/src/main/java/org/terasology/persistence/internal/EntitySetDeltaRecorder.java
engine/src/main/java/org/terasology/persistence/internal/ReadWriteStorageManager.java
engine/src/main/java/org/terasology/rendering/logic/MeshRenderer.java
engine/src/main/resources/assets/prefabs/player/player.prefab

While it is a performance optimization that isn't based on any profiling I think it is reasonable to do it: This change basically halves the memory usage for non persistent entities.
See comments of commits for further details.

Don't track changes of non persistent entities for autosave

---

modules/Core/src/main/java/org/terasology/core/world/generator/facetProviders/DefaultTreeProvider.java
modules/Core/src/main/java/org/terasology/core/world/generator/facetProviders/PositionFilters.java
modules/Core/src/main/java/org/terasology/core/world/generator/facetProviders/SurfaceObjectProvider.java

- Fix some issues with [-1,1] noise being treated as [0,1] with vegetation probability.
- Half the amount of trees.
Desert
Mountains
Forest
Plains (see the red tree!)

Fix issues with too much vegetation being generated

---

engine/src/main/java/org/terasology/editor/properties/SceneProperties.java
engine/src/main/java/org/terasology/engine/modes/StateIngame.java
engine/src/main/java/org/terasology/engine/subsystem/headless/HeadlessGraphics.java
engine/src/main/java/org/terasology/engine/subsystem/lwjgl/LwjglRenderingSubsystemFactory.java
engine/src/main/java/org/terasology/logic/players/MenuControlSystem.java
engine/src/main/java/org/terasology/rendering/opengl/LwjglRenderingProcess.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersChunk.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersCombine.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersDebug.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersHdr.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersLightGeometryPass.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersLightShaft.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersOcDistortion.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersPost.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersPrePost.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersSSAO.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersSobel.java
engine/src/main/java/org/terasology/rendering/world/WorldRendererImpl.java

Note: WorldRendererLwjgl has been renamed to WorldRendererImpl and DefaultRenderingProcess has been renamed to LwjglRenderingProcess, as the former is now more generic and the latter has always been
lwjgl-dependent. 
Most changes, i.e. in Shader*.java classes, are due to this renaming. The files to focus on are therefore WorldRendererImpl, LwjglRenderingProcess and StateIngame.
Also moved stopping of all sounds from WorldRenderer.dispose() to StateInGame.dispose().

Moved all opengl commands from WorldRendererLwjgl to DefaultRenderingProcess

---

engine-tests/src/main/java/org/terasology/HeadlessEnvironment.java
engine/build.gradle
engine/src/main/java/org/terasology/engine/subsystem/lwjgl/LwjglGraphics.java
engine/src/main/java/org/terasology/rendering/assets/texture/PNGTextureLoader.java
engine/src/main/java/org/terasology/world/block/DefaultColorSource.java
engine/src/main/java/org/terasology/world/block/loader/WorldAtlasImpl.java

I stumbled over this when I noticed a stray import on Slick's logging system in engine-tests.
Slick2D is no longer maintained and only the PNGDecoder is used. Interestingly, Slick just integrated an older version of TWL's one-class-file JAR `PNGDecoder` (X11 license).
This PR removes the dependency to Slick2D altogether and relies on the latest version of `PNGDecoder` directly. I uploaded it including source to Artifactory.

Remove Slick2D dependencies

---

engine/src/main/java/org/terasology/engine/TerasologyEngine.java

Reasoning: Previously NoClassDefFoundError resulted in a silent crash,
if you started the game without crash reporter.

Log non RuntimeExceptions too.

---

engine/src/main/java/org/terasology/network/ClientInfoComponent.java
engine/src/main/java/org/terasology/network/internal/AbstractClient.java
engine/src/main/resources/assets/prefabs/player/clientInfo.prefab

Reasoning: This makes it possible in future to manage offline players.
e.g. adding rights to them or renaming them to free a name once we
introduce unique player names.
This commit makes players also keep their name/color settings accross
sessions. In the future it propably makes sense to add a commands/UI
for changing player names and colors. The current player settings UI 
can now (tempoarly?) only be used to set the initial player color and name.

Keep the client infos even if the players leave.

---

.gitignore
modules/Core/module.txt
modules/CoreSampleGameplay/.gitignore
modules/CoreSampleGameplay/build.gradle
modules/CoreSampleGameplay/module.txt
modules/CoreSampleGameplay/src/main/java/org/terasology/coresamplegameplay/PlayerStartingInventorySystem.java

This adds another module alonside Core to provide gameplay related systems that do not pertain to the base set of content.  Particularly,  the starting inventory.
The new module presents itself the same as the core previously did as "Core Gameplay" in the UI.
Some feedback and verification of the following would be appreciated:
- .gitignore, I am fairly sure I got it right.  Did I miss anything?
- The module name, "CoreSampleGameplay".  Is this suitable?  Any better ideas of a name?
- Is there anything else that should be moved over to this gameplay module?

Add CoreSampleGameplay module

---

engine/src/main/java/org/terasology/engine/TerasologyConstants.java
engine/src/main/java/org/terasology/engine/TerasologyEngine.java
engine/src/main/java/org/terasology/engine/module/ModuleManager.java
engine/src/main/java/org/terasology/engine/subsystem/headless/mode/StateHeadlessSetup.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/CreateGameScreen.java

- Fix blank gameplay template drop down when first going to the create game menu.  Resolves #1610
- New behavior after selecting a gameplay template: 
- clear all selected modules (resolves #1535)
- find all available world generators by recursing through the module dependencies
- always set the default world generator as per the gameplay module
- Encapsulate the module metadata extension for getting the gameplay default world generator.

Fix the headless server unable to find a world generator and other things

---

engine/src/main/java/org/terasology/audio/system/AudioSystem.java
engine/src/main/java/org/terasology/input/internal/BindCommands.java
engine/src/main/java/org/terasology/logic/chat/ChatSystem.java
engine/src/main/java/org/terasology/logic/console/ConsoleImpl.java
engine/src/main/java/org/terasology/logic/console/commandSystem/AbstractCommand.java
engine/src/main/java/org/terasology/logic/console/commandSystem/annotations/Command.java
engine/src/main/java/org/terasology/logic/console/commands/ClientCommands.java
engine/src/main/java/org/terasology/logic/console/commands/CoreCommands.java
engine/src/main/java/org/terasology/logic/console/commands/ServerCommands.java
engine/src/main/java/org/terasology/logic/console/suggesters/OnlineUsernameSuggester.java
engine/src/main/java/org/terasology/logic/debug/MovementDebugCommands.java
engine/src/main/java/org/terasology/logic/health/HealthSystem.java
engine/src/main/java/org/terasology/logic/inventory/ItemCommands.java
engine/src/main/java/org/terasology/logic/permission/PermissionCommands.java
engine/src/main/java/org/terasology/logic/permission/PermissionManager.java
engine/src/main/java/org/terasology/logic/permission/PermissionSystem.java
engine/src/main/java/org/terasology/logic/players/LocalPlayer.java
engine/src/main/java/org/terasology/logic/players/PlayerSystem.java
engine/src/main/java/org/terasology/world/block/entity/BlockCommands.java
engine/src/main/resources/assets/prefabs/player/clientInfo.prefab
engine/src/main/resources/assets/prefabs/player/player.prefab

This patch series introduces more granular permissions
* There is now a "chat" permission which every player has per default. So new players that join a server can chat.
* There is now a "userManagment" permission which allows the player to perform user management tasks like giving permissions.
* Even with the permission "userManagment"  you can now only give or remove permissions which you already own.
* There is now a "cheat" permission which allows the user to use non global, non debug cheats.
* Commands default now to a new  "debug" permission. On a typical server no one should have this permission.
* Commands that do someting you can also archive with the UI no longer require any permissions
* The op permission has been removed, as it no longer has any use.
* The usePermissionKey …

Fine granular permissions

---

engine/src/main/java/org/terasology/engine/module/ModuleManager.java

Tiny check for `null` that was necessary for my setup. Most probably related to #1611.

Fix NPE in getDefaultWorldGenerator()

---

engine-tests/src/test/java/org/terasology/logic/location/LocationComponentTest.java
engine/src/main/java/org/terasology/logic/console/Console.java
engine/src/main/java/org/terasology/logic/console/ConsoleImpl.java
engine/src/main/java/org/terasology/logic/console/commands/CoreCommands.java
engine/src/main/java/org/terasology/logic/health/HealthSystem.java
engine/src/main/java/org/terasology/logic/players/PlayerSystem.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/videoSettings/ScreenshotFormatBinding.java

This PR 
* removes the four duplicate commands methods
* renames one method to avoid name conflicts: `health(int amount)` vs. `health()` -> `healthMax()`
* fixes logging of duplicate method warning
* fixes the `teleport` method (resets ghosting mode though)
* nothing about `kill` - it worked fine for me already
* fixes all (4) CheckStyle errors (Tabs and string comparison)
* fixes the `reloadScreen` command
Fixes #1602
Fixes #1552

Fix various command-related issues

---

engine/src/main/java/org/terasology/engine/subsystem/lwjgl/LwjglGraphics.java
engine/src/main/java/org/terasology/rendering/assets/texture/TextureDataFactory.java
engine/src/main/java/org/terasology/rendering/assets/texture/TextureUtil.java

Moved `imageToByteBuffer` from `LwjglGraphics` to `TextureUtil`.
Also added a tiny fix in `TextureDataFactory` about creating single-color textures.

Remove duplicate image converter util

---

engine/src/main/java/org/terasology/config/Config.java
engine/src/main/java/org/terasology/config/NetworkConfig.java
engine/src/main/java/org/terasology/config/TransientConfig.java
engine/src/main/java/org/terasology/engine/modes/loadProcesses/StartServer.java
facades/PC/src/main/java/org/terasology/engine/Terasology.java

This is an update of PR #1604 by @unpause.
It adds a command line argument: "-serverPort=xxxxx"
Fixed #1603 
Sidenote: using an invalid port is one situation where `TerasologyEngine` does not get disposed properly. This is due to the fact that dispose() does not clean up.

Added an option to change the server port via a command line argument (updated)

---

engine/src/main/java/org/terasology/engine/subsystem/lwjgl/LwjglGraphics.java

Class LwjglGraphics now checks for driver's compatibility with OpenGL 2.1. 
OpenGL 2.1 is necessary as it requires the implementation to support GLSL 1.20, which is the GLSL version used by Terasology's shaders. 
GLSL 1.20 is enforced by the GLSLShader class prepending a "#version 120" statement in each shader. No change has been made to that class.

Added opengl 2.1 check.

---

engine/src/main/resources/assets/skins/loadingScreen.skin
engine/src/main/resources/assets/ui/loadingScreen.ui

Currently, the loading screen image ships with the game, but is not in use. This PR overrides the `mainmenu` skin for the loading screen with a customized skin that sets the background image.
This allows modules to customize the loading screen by adding a file: 
overrides\engine\textures\loadingBackground.png

Use loading screen background image

---

engine/src/main/java/org/terasology/config/NetworkConfig.java
engine/src/main/java/org/terasology/config/ServerInfo.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/CombinedListBinding.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/JoinGameScreen.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/OnlineServerListBinding.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/ServerListDownloader.java
engine/src/main/resources/assets/skins/mainmenu.skin
engine/src/main/resources/assets/ui/menu/joinGameScreen.ui

This PR modifies the "Join Game" screen by adding the functionality to download a list of available game servers from an external source.
This source is a Jetty-based servlet, hosted on a Heroku instance (connected to a Amazon EC2 PostgreSQL database). It runs in my personal account, but I'm happy to transfer it (no credit card required). The GitHub repository is here: https://github.com/MovingBlocks/master-server

Download list of available game servers

---

engine/src/main/java/org/terasology/engine/LoggingContext.java
facades/PC/src/main/resources/logback.xml

This PR does two things:
* Log files are put into a timestamped sub-folder now.
* Only folders that are older than 5 days are deleted on game start.
Fixes #1631

Delete log files only after five days

---

modules/Core/src/main/java/org/terasology/core/world/generator/facetProviders/HeightMapSurfaceHeightProvider.java
modules/Core/src/main/java/org/terasology/core/world/generator/worldGenerators/HeightMapWorldGenerator.java

Assets can now be loaded in WorldViewer, which now allows for loading the HeightMap world:
Surprisingly, it is by far the slowest world generator of all. I'm not sure why the code was like it was, but it offered many possibilities for performance improvements.
This PR performs a few of them leading to a speed-up of about 20x-50x at equal quality. Moreover, it makes the surface provider independent of chunk size and uses a dynamic scale factor instead. I also lowered the sea level for additional land mass (see the screenshot). 
In the default setting, the terrain repeats after 2048 blocks, but biomes/vegetation/etc. is procedural and thus different.

Tune-up for height-map based world generator

---

engine/src/main/java/org/terasology/world/generation/BaseFacetedWorldGenerator.java
engine/src/main/java/org/terasology/world/generator/WorldGenerator.java
modules/Core/src/main/java/org/terasology/core/world/generator/AbstractBaseWorldGenerator.java

Adds the missing getter for the `WorldGenerator.setWorldSeed()` method. This method also need to be added to [AnotherWorld](https://github.com/Terasology/AnotherWorld)s `PluggableWorldGenerator`.
A use case is WorldViewer who wants to display the seed that is currently used.

Add WorldGenerator.getWorldSeed()

---

engine/src/main/java/org/terasology/rendering/opengl/LwjglRenderingProcess.java

To take a screenshot the game video resolution is temporarily lowered or increased to match screenshot size. Once the screenshot is taken the resolution should be set back to the previous values. A small cut and paste error prevented this in the height dimension, but this was noticeable only (and especially) when attempting to take screenshots of reduced size. This commit fixes the problem by changing the faulty line to its intended form.

Fixed small bug in screenshot code.

---

engine/src/main/java/org/terasology/utilities/procedural/SubSampledNoise.java

This replaces calls to `size().x` and `size().y` in `SubSampledNoise` with `sizeX` and `sizeY` respectively.
This avoids the unneeded allocation of Vector2i instances. Since this was done very often, it quickly amortized causing intense GC cleanup cycles.
The effect can be observed e.g. in JVisualVM. The number of allocated Vector2i instance decreases:

Tune-Up for SubSampledNoise

---

engine-tests/src/main/java/org/terasology/testUtil/ModuleManagerFactory.java
engine/src/main/java/org/terasology/engine/TerasologyEngine.java
engine/src/main/java/org/terasology/engine/module/ModuleExtension.java
engine/src/main/java/org/terasology/engine/module/ModuleManagerImpl.java
engine/src/main/java/org/terasology/engine/module/StandardModuleExtension.java
engine/src/main/java/org/terasology/engine/subsystem/headless/mode/StateHeadlessSetup.java
engine/src/main/java/org/terasology/network/internal/NetworkSystemImpl.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/CreateGameScreen.java

This PR extracts an interface out of the `ModuleManager` class. It also separates the querying of module metadata, which is independent from the actual implementation of `ModuleManager`.
As a consequence, the module manager can no longer directly override the retrieval of this metadata. However, it can customize the loading process and thus retain its influence.
Only the first 4 lines in the constructor of `ModuleManagerImpl` were changed. GitHub gets confused with the renaming/modification.

Refactor ModuleManager

---

engine/src/main/java/org/terasology/rendering/opengl/FBO.java
engine/src/main/java/org/terasology/rendering/opengl/LwjglRenderingProcess.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersPost.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersSobel.java

This is the first of a number of PR aiming to refactor the class LwjglRenderingProcess. 
The destination I am aiming for (minus feedback and some changes that have already taken place in this PR) is available in [this branch](https://github.com/emanuele3d/Terasology/tree/RendererChangesBKP). While there are no functional changes (the look and performance of Terasology's renderer should stay the same) the changes to the code are substantial, primarily in the interest of readability, maintainability and, eventually, ease of adding new capabilities. For this reason I won't submit that branch as a PR, only as a reference of where I'm heading.
Now, some background info: OpenGL's FrameBuffers can be thought of boxes with a number of internal slots (attachment points). Once something is placed …

Rendering Process Refactoring - FBO creation

---

engine-tests/src/main/java/org/terasology/DisplayEnvironment.java
engine/src/main/java/org/terasology/editor/properties/SceneProperties.java
engine/src/main/java/org/terasology/engine/modes/loadProcesses/InitialiseGraphics.java
engine/src/main/java/org/terasology/engine/subsystem/headless/HeadlessGraphics.java
engine/src/main/java/org/terasology/engine/subsystem/lwjgl/LwjglGraphics.java
engine/src/main/java/org/terasology/logic/players/MenuControlSystem.java
engine/src/main/java/org/terasology/rendering/opengl/FBO.java
engine/src/main/java/org/terasology/rendering/opengl/LwjglRenderingProcess.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersChunk.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersCombine.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersDebug.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersHdr.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersLightGeometryPass.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersLightShaft.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersOcDistortion.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersPost.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersPrePost.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersSSAO.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersSobel.java
engine/src/main/java/org/terasology/rendering/world/WorldRendererImpl.java

The [first commit](https://github.com/MovingBlocks/Terasology/commit/47ec5d348448357c9dc59bce418aa738882576d8) is an easy and hopefully uncontroversial one:
* it takes advantage of FBO.Dimensions instances throughout to simplify FBO generation code and dimensions handling, making more explicit the sizes of the FBOs involved and any change to them.
* it also add a couple of small method wrapping unsightly glViewport() calls into setViewportToFullScale() and setViewportTo().
The [second commit](https://github.com/MovingBlocks/Terasology/commit/09a6c9203d256a0e7d212c0171bd238e190166ed) is only a little more involved because it changes the LwjglRenderingProcess class from a singleton obtainable via its getInstance() method to an object instantiated by the WorldRenderer upon construction, and …

LwjglRenderingProcess no longer a singleton, Dimension instances used more extensively

---

README.markdown
engine/src/main/java/org/terasology/logic/actions/TunnelAction.java

Railgun has been a shadow of itself for too long. No more!
This simply tweaks the config (and pulls out a couple magic numbers) to make it vastly more destructive again. Naturally that also makes it more laggy.
The main source of the lag is the resulting physics from bouncy loose blocks, and a few shots down into the ground will push any machine to its knees. Shooting up to decapitate hills and trees is more amusing and forgiving. The exact way blocks are chosen as targets is also highly inefficient but I'm not sure how much it impacts the performance (it may be what can freeze the game for a moment, then the physics drags down the FPS after)
Making this in part to see if anybody is interested in a little homework to add on top of this:
I might turn this into a separate ticket if nobody …

Beefs up the railgun again

---

engine/src/main/java/org/terasology/world/generator/internal/WorldGeneratorManager.java

Make WorldGeneratorManager report unresolvable modules to clarify why some world generators are not listed.

Warn on unresolvable modules in WorldGeneratorManager

---

engine/src/main/java/org/terasology/world/generation/FacetProvider.java
engine/src/main/java/org/terasology/world/generation/WorldImpl.java
modules/Core/src/main/java/org/terasology/core/world/generator/facetProviders/HeightMapSurfaceHeightProvider.java

I would actually prefer to move the empty method implementations into a new class `AbstractFacetProvider` or `FacetProviderAdapter`, but this would require changing dozends of files. 
Also, default methods were introduced specifically for *interface evolution*, so this is probably a good fit - it just feels strange.

Introduce initialize() method for FacetProvider

---

engine/src/main/java/org/terasology/logic/characters/KinematicCharacterMover.java
engine/src/main/java/org/terasology/world/block/items/BlockItemSystem.java

Without this patch it is not possible to place blocks in certain
situations:
1. You couldn't place a block at character height if you walked towards
another path blocking block that is below or above the placement position.
e.g. place a block infront of you, walk towards it till limit.
Try placing a block on top of it.
2. Blocks couldn't be placed in a neighbour block that is 1 lower than
the current character position even when the character wasn't lowered
already from the edge (and capsule collision shape).
If in doubt the block placement will now be allowed which can lead in
certain corner situations to blocks that collide with the character.
e.g. when you walk very far on the edge and then plae a block below you.
You will then sink in the block till you hit the next block below it so …

Fix block plaement near player.

---

engine/src/main/java/org/terasology/rendering/opengl/GraphicState.java
engine/src/main/java/org/terasology/rendering/opengl/LwjglRenderingProcess.java
engine/src/main/java/org/terasology/rendering/world/WorldRendererImpl.java

This PR extracts a number of opengl-related methods from the rendering process and places them in a new GraphicState class. 
The first commit mostly operates the extraction by moving the methods (unmodified) from one class to another. More interesting are the changes to the WorldRendererImpl, in particular the order of operations in its initRenderingSupport() method becomes crucial for the correct construction and setting of objects supporting the renderer.
The second commit takes the opportunity to go through the new class and refactor it. Many methods and variables have their name changed here. Also, the GraphicState class is modified in this commit to obtain a number of references to FBOs which are then refreshed only when necessary. Previously they were obtained through the …

Introducing GraphicState

---

engine/src/main/java/org/terasology/engine/ComponentSystemManager.java
engine/src/main/java/org/terasology/logic/config/ModuleConfigComponent.java
engine/src/main/java/org/terasology/logic/config/ModuleConfigManager.java
engine/src/main/java/org/terasology/logic/config/ModuleConfigSystem.java

1. New component and system that allows for easy and powerful module configuration (for "modpack" developers). Decided to put it in engine, to have just one way of doing it, rather than 1 per module/module-author.
2. Preparation for optional modules - make sure that if a system is being created and it depends on a module that is optional, Terasology still starts instead of crashes with NoClassDefFoundError and just logs an error. Probably has to stay being an error, since it might be due to some other problems. Maybe just a log error message should be improved?

Two small changes

---

README.markdown

The shield are based on [shields.io](http://shields.io) and Jenkins. More shields can be found on their website. I updated the Jenkins plugin to achieve a common style (thanks @skaldarnar).
Other suggestions are welcome.

Add more shield icons to README

---

engine/src/main/java/org/terasology/rendering/nui/widgets/UIScrollbar.java

Fixing divide-by-zero crash.  Previewing a new "Core Gameplay/Perlin" world with a window size that is too large results in scrollbar range of 0, and causes a crash with the following stack trace:
java.lang.ArithmeticException: / by zero
at org.terasology.rendering.nui.widgets.UIScrollbar.pixelOffsetFor(UIScrollbar.java:171) ~[classes/:na]
at org.terasology.rendering.nui.widgets.UIScrollbar.onDraw(UIScrollbar.java:142) ~[classes/:na]
at org.terasology.rendering.nui.internal.CanvasImpl.drawWidget(CanvasImpl.java:376) ~[classes/:na]
at org.terasology.rendering.nui.layouts.ScrollableArea.layoutWithJustVertical(ScrollableArea.java:153) ~[classes/:na]
at org.terasology.rendering.nui.layouts.ScrollableArea.onDraw(ScrollableArea.java:95) ~[classes/:na]
at …

Scrollbar: check for division-by-zero, and remove handle when larger than scrollbar size

---

engine/src/main/java/org/terasology/world/generation/WorldBuilder.java

The old WorldBuilder implementation called setSeed() on providers when they were added.  This does the same, simply caching the last seed set in a Long field (after passing through to already added providers) and also passing it through to new providers if non-null.  Helps with backwards compatibility, so updating modules like AnotherWorld to use the new API is relatively painless.

Cached seed in WorldBuilder to remove order-dependence between setSeed() and addProvider()

---

engine/src/main/java/org/terasology/monitoring/PerformanceMonitor.java
engine/src/main/java/org/terasology/monitoring/impl/PerformanceMonitorImpl.java

I wanted to learn more about the PerformanceMonitor, in the context of creating a new set of metrics that can be seen pressing the F4 key. In the process of going through the code I saw a number of
opportunities for improving the javadocs and, to a minor extent, improving the readability of the code.
This PR attempts to fullfill those opportunities. 
The [first commit](36cf9bf23b42f76793a5d5968ef4e25986aa9706) should be relatively uncontroversial: it just adds or refine javadocs to PerformanceMonitor and does some minor refactoring to PerformanceMonitorImpl. I imagine however the wording on some of the javadocs could be further refined.
The usefulness of the [second commit](ba965b1cd7c842d3433a9c28fdfb17c9d02173cc) is perhaps more debatable: primarily it makes the rollCycle() method more …

PerformanceMonitor: augmented javadocs, some refactoring

---

engine/src/main/java/org/terasology/engine/LoggingContext.java
facades/PC/src/main/java/org/terasology/engine/Terasology.java
facades/PC/src/main/resources/logback.xml

With these changes only the logging subfolder that is actually used is reported to CrashReporter.
Fixes https://github.com/MovingBlocks/CrashReporter/issues/19

Report only latest log folder to CrashReporter

---

config/gradle/common.gradle
engine/src/main/java/org/terasology/input/Keyboard.java
engine/src/main/java/org/terasology/rendering/collada/ColladaLoader.java
engine/src/main/java/org/terasology/world/chunks/deflate/TeraStandardDeflator.java

I stumbled over this when one of the Jenkins slave agents complained about invalid chars in java source files. So I replaced all non-ASCII characters and used escaped unicode instead. Easy fix.
That said, explicitly defining the encoding to `UTF-8` for `javac` should fix the same issue at least for the java compiler.
While I think that sticking with plain ASCII is reasonable for source files (translation files are certainly different), I didn't want to enforce this and went for `UTF-8` instead.

Fix character encoding issues in source files

---

engine/src/main/java/org/terasology/rendering/nui/internal/LwjglCanvasRenderer.java
engine/src/main/java/org/terasology/rendering/opengl/GLSLShader.java

This PR refactors the GLSLShader class by splitting large methods into smaller ones. It also
* removes the highly fragile parsing of error logs and reports them as-is instead.
* removes the JOptionPane dialog and throws an exception instead.
Everything else remains the same: As usual, `AssetManagerImpl` logs the thrown exception and returns `null` instead. Callers can then decide to use a fall-back shader or throw an exception. Uncaugt exceptions will crash the application and trigger the CrashReporter.
I'm not overly happy with throwing `RuntimeException`. Anyone knows a better match?
Fixes #1649

Improve reporting of shader compiler errors

---

engine/src/main/java/org/terasology/logic/characters/CharacterComponent.java
engine/src/main/java/org/terasology/logic/players/PlayerFactory.java
engine/src/main/java/org/terasology/logic/players/PlayerSystem.java

This was more effort that I first thought since..
* The height of an entity depends on the type of collision object
* The entity was created by `PlayerFactory` only after the final spawning pos. was set
So I moved a few bits from `PlayerSystem` to `PlayerFactory`, which also looks cleaner to me now. The system deals with events and entities while the factory deals with creating new player instances. Just as the names incline.
Fixes #1711

Read entity height from player prefab

---

engine/src/main/java/org/terasology/engine/TerasologyEngine.java
engine/src/main/java/org/terasology/engine/subsystem/headless/HeadlessGraphics.java
engine/src/main/java/org/terasology/engine/subsystem/lwjgl/LwjglGraphics.java

Since Terasology no longer compiles on eclipse (see #1771), I decided to explicitly specify the mapping of lambdas to `AssetFactory` instances to avoid type inference altogether. This circumvents the [OpenJDK "bug" 8033810](https://bugs.openjdk.java.net/browse/JDK-8033810).
This is certainly more verbose than before, probably less elegant, but maybe more instructive and it compiles fine on both compilers.

Explicitly specify lambda types for asset factories

---

engine-tests/src/main/java/org/terasology/HeadlessEnvironment.java
engine-tests/src/test/java/org/terasology/entitySystem/PojoEntityManagerTest.java
engine-tests/src/test/java/org/terasology/entitySystem/PojoPrefabManagerTest.java
engine-tests/src/test/java/org/terasology/entitySystem/PrefabTest.java
engine-tests/src/test/java/org/terasology/persistence/EntitySerializerTest.java
engine/src/main/java/org/terasology/engine/TerasologyEngine.java
engine/src/main/java/org/terasology/engine/subsystem/lwjgl/LwjglGraphics.java

This adds explicit type casts for lambdas in engine-test. See #1771 for details.
It also formats the expressions in engine a little and adds a short comment to it.

Add typecasts for lambdas for eclipse compiler

---

engine/src/main/java/org/terasology/rendering/nui/layers/ingame/metrics/DebugOverlay.java
engine/src/main/java/org/terasology/rendering/nui/layers/ingame/metrics/RenderingExecTimeMeansMode.java

Added a new mode to the DebugOverlay, specialized on execution time running means for rendering code only. 
While functional, the new mode filters out (does not display) activities registered with the performance monitor that are not prefixed by the strings "WorldRenderer::" or "PostProcessor::". At the time of this commit no activity is prefixed with those strings and as such the new mode displays only its title. Those prefixes will be added some time after PR #1745 has been dealt with.
Additionally, differently from various time-related modes already in place, the new mode sorts the list of post-filter activities alphabetically, and formats each item to list the time value on the left and the activity name on the right, after a separator. I.e.:
```
0.31ms - PostProcessor::Activity 1 …
```

Added new mode for the DebugOverlay (the stats cycled with F4)

---

engine/src/main/java/org/terasology/rendering/nui/databinding/ListSelectionBinding.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/JoinGameScreen.java
engine/src/main/resources/assets/ui/menu/joinGameScreen.ui

The PR separates user-defined game servers from those that are retrieved online through a "tabbed" list:
The second commit also moves the editing controls to the "custom" tab and the download status label to the "online" tab. This clarifies the different server types better than adding the `(custom)` tag to the name as it was before.

Use card layout for different server types

---

engine/src/main/java/org/terasology/config/NetworkConfig.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/ServerListDownloader.java

Heroku is changing its hosting policy and pricing scheme, which is less suitable for 24/7 online services. 
I hereby suggest changing the default server URL in `NetworkConfig` to [master-server.terasology.org](https://master-server.terasology.org), which can be configured to redirect request to any URL. This should facilitate migrating away from Heroku.
**NOTE**: the URL must be configured to forward to `master-server.herokuapp.com` before this PR can be merged.
This PR also contains a few related tweaks (partly based on new Java 8 features).

Use terasology.org as default host for master-server

---

engine-tests/build.gradle

This PR adds JaCoCo to the engine-tests project, which computes code coverage. The resulting exec file can be visualized by the Jenkins JaCoCo plugin, for example:
http://jenkins.terasology.org/job/TerasologyTemp/lastBuild/jacoco/
I excluded the `o.t.protobuf` package from both JaCoCo and the Jenkins plugins (which reports 0% coverage otherwise).

Compute unit test coverage using JaCoCo

---

engine/src/main/java/org/terasology/config/ServerInfo.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/AddServerPopup.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/JoinGameScreen.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/ServerListDownloader.java
engine/src/main/java/org/terasology/rendering/nui/layouts/ColumnLayout.java
engine/src/main/resources/assets/ui/menu/addServerPopup.ui
engine/src/main/resources/assets/ui/menu/joinGameScreen.ui

This PR deals with a few related issues around the join game dialog:
* The entry "Online" was renamed to "Listed" (now at the left and default) - Fixes #1786 
* Servers are now retrieved as a stream (plus an artificially delay to achieve an animation)
* Add the "Owner" field - editable for custom entries
* Evaluate the "active" field. Inactive servers are not listed.
* Add `extendLast` layout hint for `ColumnLayout`: the last entry takes all the excess space.
* The module list is no longer truncated and scrollable instead

Rework join game dialog

---

engine/src/main/java/org/terasology/logic/behavior/nui/BehaviorEditorScreen.java
engine/src/main/java/org/terasology/logic/debug/DebugPropertiesSystem.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/PreviewWorldScreen.java
engine/src/main/java/org/terasology/rendering/nui/layouts/PropertyLayout.java
engine/src/main/java/org/terasology/rendering/nui/properties/PropertyProvider.java

This PR refactors `PropertyProvider` to support customized bindings such as notifications. 
I also implemented custom bindings that decorate other bindings and send `PropertyChangeEvents` on "set" calls. The commit is https://github.com/msteiger/Terasology/commit/8e5131f31b54ac7c5aded4e495871aef26e01b48, but not part of this PR, since I doubt that String-based identification of modified fields is ideal. I'm open to suggestions.
Ping @synopia

Refactor PropertyProvider to support notifications

---

engine-tests/src/main/java/org/terasology/HeadlessEnvironment.java
engine-tests/src/main/java/org/terasology/TerasologyTestingEnvironment.java
engine/src/main/java/org/terasology/config/BindsConfig.java
engine/src/main/java/org/terasology/config/InputConfig.java
engine/src/main/java/org/terasology/config/RenderingConfig.java
engine/src/main/java/org/terasology/editor/TeraEd.java
engine/src/main/java/org/terasology/editor/properties/ReflectionProvider.java
engine/src/main/java/org/terasology/editor/properties/SceneProperties.java
engine/src/main/java/org/terasology/editor/ui/MainWindow.java
engine/src/main/java/org/terasology/engine/modes/StateIngame.java
engine/src/main/java/org/terasology/engine/modes/StateLoading.java
engine/src/main/java/org/terasology/engine/modes/loadProcesses/CacheBlocks.java
engine/src/main/java/org/terasology/engine/modes/loadProcesses/InitialiseRemoteWorld.java
engine/src/main/java/org/terasology/engine/modes/loadProcesses/InitialiseWorld.java
engine/src/main/java/org/terasology/engine/modes/loadProcesses/LoadPrefabs.java
engine/src/main/java/org/terasology/engine/subsystem/RenderingSubsystemFactory.java
engine/src/main/java/org/terasology/engine/subsystem/headless/mode/HeadlessStateChangeListener.java
engine/src/main/java/org/terasology/engine/subsystem/headless/mode/StateHeadlessSetup.java
engine/src/main/java/org/terasology/engine/subsystem/headless/renderer/HeadlessRenderingSubsystemFactory.java
engine/src/main/java/org/terasology/engine/subsystem/headless/renderer/HeadlessWorldRenderer.java
engine/src/main/java/org/terasology/engine/subsystem/lwjgl/LwjglRenderingSubsystemFactory.java
engine/src/main/java/org/terasology/logic/players/DebugControlSystem.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/inputSettings/InputSettingsScreen.java
engine/src/main/java/org/terasology/rendering/world/WorldRendererImpl.java
facades/PC/src/main/java/org/terasology/engine/Terasology.java

Reduces CoreRegistry usage.
It does not conflict with #1797

Remove CoreRegistry usage: Part IV

---

engine/src/main/java/org/terasology/world/block/loader/AutoBlockProvider.java

Auto blocks were lacking a BlockSounds definition. Set to the default block sounds.

Fix for #1806

---

engine/src/main/java/org/terasology/identity/PublicIdentityCertificate.java
engine/src/main/java/org/terasology/network/internal/NetMessageUtil.java

There was a 1 in 256 chance of certificates failing to verify as signed/self signed due to incorrect conversion between BigInteger and byte[].

Fix for certificate test failure.

---

engine-tests/src/test/java/org/terasology/entitySystem/PojoEventSystemTests.java
engine-tests/src/test/java/org/terasology/entitySystem/PojoPrefabManagerTest.java
engine-tests/src/test/java/org/terasology/entitySystem/PrefabTest.java
engine/src/main/java/org/terasology/config/RenderingConfig.java
engine/src/main/java/org/terasology/engine/bootstrap/ApplyModulesUtil.java
engine/src/main/java/org/terasology/engine/bootstrap/EntitySystemSetupUtil.java
engine/src/main/java/org/terasology/engine/modes/loadProcesses/LoadEntities.java
engine/src/main/java/org/terasology/engine/modes/loadProcesses/RegisterInputSystem.java
engine/src/main/java/org/terasology/engine/subsystem/headless/mode/HeadlessStateChangeListener.java
engine/src/main/java/org/terasology/engine/subsystem/lwjgl/LwjglGraphics.java
engine/src/main/java/org/terasology/engine/subsystem/lwjgl/LwjglInput.java
engine/src/main/java/org/terasology/entitySystem/prefab/internal/PojoPrefabManager.java
engine/src/main/java/org/terasology/entitySystem/prefab/internal/PrefabDeltaFormat.java
engine/src/main/java/org/terasology/entitySystem/prefab/internal/PrefabFormat.java
engine/src/main/java/org/terasology/input/InputSystem.java
engine/src/main/java/org/terasology/input/internal/BindableButtonImpl.java

Another pull request to reduce CoreRegistry usage.
It also fixes the PojoPrefabManager#exists method which was broken. I am not sure if that was causing any noticable bugs.
The place where the prefab formats get now registered isn't ideal, but it's the only place where it currently can be done. See discusion with @immortius in https://github.com/MovingBlocks/gestalt/issues/35 for more information.
Also noteworthy about this pull request is that the patch 465cd39e7aa157c7e4bc4bb65b84a7f9d3bc8447 moves the `applyBinds` call from `RegisterInputSystem#step` to `InputSystem#initialise`. That  way the `InputSystem` is initialized when the `applyBinds` method gets called. 
I also think it might be a good idea to move the  `applyBinds` logic from BindsConfig to InputSystem as the former is to me …

Remove CoreRegistry usage: Part V

---

engine/src/main/java/org/terasology/logic/players/FirstPersonRenderer.java
engine/src/main/java/org/terasology/rendering/iconmesh/IconMeshFactory.java

- Centers icon meshes around their origin.  
- Adjust FirstPersonRenderer so that higher dpi textures occupy the same space as the 16x16 counterparts when held.
I used the ItemRendering module to show the origin...
Before:
After:

Adjustments for IconMeshes to center around their origin

---

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/SelectModulesScreen.java

Only explicitly selected modules get set on the config.  This checks instead the selected modules from the UI which respect dependencies.

Prevent the world generator selection from reverting

---

engine/src/main/java/org/terasology/engine/TerasologyEngine.java
engine/src/main/java/org/terasology/engine/bootstrap/EnvironmentSwitchHandler.java
engine/src/main/java/org/terasology/engine/modes/StateIngame.java
engine/src/main/java/org/terasology/engine/modes/loadProcesses/JoinServer.java
engine/src/main/java/org/terasology/engine/modes/loadProcesses/RegisterMods.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/PreviewWorldScreen.java

A new EnvironmentSwitchHandler class has been introduced that has
now the job of switching the environment of the asset manager.
It ensures that oudated prefab formats gets unregistered
in time.
ApplyModulesUtil has been removed as it's job gets now done by
EnvironmentSwitchHandler.
This should fix #1815, but I haven't tested it yet. 
@Josharias Can you please check if this fixes your issue?
@immortius I hope you are fine with that solution. If you don't agree I can give further arguments why I didn't go for the ClassFactory approach.

Make sure that outdated prefab formats get unregistered.

---

engine/src/main/java/org/terasology/engine/modes/StateLoading.java
engine/src/main/java/org/terasology/engine/modes/StateMainMenu.java
engine/src/main/java/org/terasology/engine/modes/loadProcesses/InitialiseGraphics.java
engine/src/main/java/org/terasology/engine/subsystem/headless/HeadlessGraphics.java
engine/src/main/java/org/terasology/engine/subsystem/headless/mode/StateHeadlessSetup.java
engine/src/main/java/org/terasology/engine/subsystem/lwjgl/LwjglGraphics.java
engine/src/main/java/org/terasology/engine/subsystem/lwjgl/LwjglInput.java
engine/src/main/java/org/terasology/input/device/MouseDevice.java
engine/src/main/java/org/terasology/input/device/nulldevices/NullMouseDevice.java
engine/src/main/java/org/terasology/input/lwjgl/LwjglMouseDevice.java
engine/src/main/java/org/terasology/rendering/nui/internal/NUIManagerInternal.java

This pull request gives NUIManager a better fitting life cycle and context instance.
The NUIManager is no longer in the engine context.
Where previously it just got "refreshed" now a new instance gets created.
Namely the first NUIManager like the first sub context for the duration
of the main menu.
When the starts loading a new NUIManager gets created that lifes again
like it's owning Context till the end of the game.
This patch fixes the issue that caused interations require two activations
when a window got closed with escape (#1761).
The first patch moves the mouse grap triggering from LwjglInput to NUIManager so that LwjglInput does not require a  NUIManager instance (which is no longer in the engine context).
@immortius I hope this change is acceptable for you and hopefully you even …

Give NUIManager a better fitting life cycle and context instance.

---

engine/src/main/java/org/terasology/persistence/typeHandling/StringRepresentationTypeHandler.java
engine/src/main/java/org/terasology/persistence/typeHandling/coreTypes/NumberTypeHandler.java
engine/src/main/java/org/terasology/persistence/typeHandling/coreTypes/StringTypeHandler.java
engine/src/main/java/org/terasology/persistence/typeHandling/extensionTypes/BlockFamilyTypeHandler.java
engine/src/main/java/org/terasology/persistence/typeHandling/extensionTypes/BlockTypeHandler.java
engine/src/main/java/org/terasology/persistence/typeHandling/extensionTypes/CollisionGroupTypeHandler.java
engine/src/main/java/org/terasology/persistence/typeHandling/extensionTypes/ColorTypeHandler.java
engine/src/main/java/org/terasology/persistence/typeHandling/extensionTypes/PrefabTypeHandler.java
engine/src/main/java/org/terasology/persistence/typeHandling/mathTypes/BorderTypeHandler.java
engine/src/main/java/org/terasology/persistence/typeHandling/mathTypes/IntegerRangeHandler.java
engine/src/main/java/org/terasology/persistence/typeHandling/mathTypes/Quat4fTypeHandler.java
engine/src/main/java/org/terasology/persistence/typeHandling/mathTypes/Rect2fTypeHandler.java
engine/src/main/java/org/terasology/persistence/typeHandling/mathTypes/Rect2iTypeHandler.java
engine/src/main/java/org/terasology/persistence/typeHandling/mathTypes/Region3iTypeHandler.java
engine/src/main/java/org/terasology/persistence/typeHandling/mathTypes/Vector2fTypeHandler.java
engine/src/main/java/org/terasology/persistence/typeHandling/mathTypes/Vector2iTypeHandler.java
engine/src/main/java/org/terasology/persistence/typeHandling/mathTypes/Vector3fTypeHandler.java
engine/src/main/java/org/terasology/persistence/typeHandling/mathTypes/Vector3iTypeHandler.java
engine/src/main/java/org/terasology/persistence/typeHandling/mathTypes/Vector4fTypeHandler.java

This needs some discussion. 
I would like to be a little more flexible with components and strings.  Currently if you let a null string be sent to the serializer for saving a world, it crashes the game.  It would lower the bar to entry for new module developers if we allowed for null values without crashes, less things to know and code around.
Could we be a little more lenient in these cases?  Is there any other considerations to making this kind of change?  Possibly this could be extended to other types as well?

Avoid causing crashes when a component has a null string.

---

engine/src/main/java/org/terasology/engine/subsystem/headless/mode/StateHeadlessSetup.java

Fix a NullPointerException in headless server caused by #1834.
NUIManager calls isCapturingMouse of InputSystem during loading which used to fail with a NullPointerException because the InputSystem did not get dependency injected.
@immortius  please review

Fix a NullPointerException in headless server 

---

engine/src/main/java/org/terasology/engine/subsystem/headless/renderer/HeadlessCanvasRenderer.java
engine/src/main/java/org/terasology/logic/console/ConsoleImpl.java
engine/src/main/java/org/terasology/rendering/FontUnderline.java
engine/src/main/java/org/terasology/rendering/assets/font/Font.java
engine/src/main/java/org/terasology/rendering/assets/font/FontData.java
engine/src/main/java/org/terasology/rendering/assets/font/FontDataBuilder.java
engine/src/main/java/org/terasology/rendering/assets/font/FontFormat.java
engine/src/main/java/org/terasology/rendering/assets/font/FontImpl.java
engine/src/main/java/org/terasology/rendering/assets/font/FontMeshBuilder.java
engine/src/main/java/org/terasology/rendering/nui/Canvas.java
engine/src/main/java/org/terasology/rendering/nui/internal/CanvasImpl.java
engine/src/main/java/org/terasology/rendering/nui/internal/CanvasRenderer.java
engine/src/main/java/org/terasology/rendering/nui/internal/LwjglCanvasRenderer.java
engine/src/main/java/org/terasology/rendering/nui/skin/UISkinBuilder.java
engine/src/main/java/org/terasology/rendering/nui/skin/UISkinFormat.java
engine/src/main/java/org/terasology/rendering/nui/skin/UIStyle.java
engine/src/main/java/org/terasology/rendering/nui/skin/UIStyleFragment.java
engine/src/main/java/org/terasology/rendering/nui/widgets/UIText.java
engine/src/main/resources/assets/materials/ui/UIUnderline.mat

Addressing #1813
* Font assets now make available the vertical base of the font
* FontMeshBuilder now processes underlining, generating an additional mesh linked to an underline material
* FontMeshBuilder is now threadsafe
* FontUnderline added with support for unicode characters to mark underline start/end positions
* text-underline style added int UIStyle
* drawTextRaw methods now have parameters for switching on underline
* drawText now uses text-underline style option to underline text
I skipped underline thickness support... there's probably a bunch of underline attributes that should live with the font, but are not supported by the current format we use. Could introduce through a supplemental format. In the mean time fonts are always 2px below the base of a font, 1px thick. This …

Added support for underlined text

---

engine/src/main/java/org/terasology/engine/modes/loadProcesses/InitialiseWorld.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/PreviewWorldScreen.java
engine/src/main/java/org/terasology/world/generation/BaseFacetedWorldGenerator.java
engine/src/main/java/org/terasology/world/generator/RegisterWorldGenerator.java
engine/src/main/java/org/terasology/world/generator/internal/WorldGeneratorManager.java
modules/Core/src/main/java/org/terasology/core/world/generator/worldGenerators/FlatWorldGenerator.java
modules/Core/src/main/java/org/terasology/core/world/generator/worldGenerators/HeightMapWorldGenerator.java
modules/Core/src/main/java/org/terasology/core/world/generator/worldGenerators/PerlinFacetedWorldGenerator.java

Add depenency injection support to WorldGenerators to get rid of CoreRegistry usage.

Remove CoreRegistry usage: Part VII - Add depenency injection support to WorldGenerators.

---

engine/src/main/java/org/terasology/logic/characters/CharacterMovementSystemUtility.java
engine/src/main/java/org/terasology/logic/characters/CharacterStateEvent.java
engine/src/main/java/org/terasology/logic/characters/ClientCharacterPredictionSystem.java
engine/src/main/java/org/terasology/logic/characters/ServerCharacterPredictionSystem.java

Moved logic out of CharacterStateEvent to reduce CoreRegistry usage.
The Pathfinding module needs to be adjusted for this pull request.

Remove CoreRegistry usage: Part VIII - Moved logic out of CharacterStateEvent

---

engine/build.gradle

This avoids checking repeatedly for new versions, which is not necessary.

Fix TeraMath version to 1.1.0

---

engine/src/main/java/org/terasology/audio/formats/OggStreamingSoundData.java

Fix for #1849
* Surrounded reset of OggStreamingSound's stream in a doPrivileged block.

Fix for #1849

---

modules/Core/src/main/java/org/terasology/core/world/generator/rasterizers/SolidRasterizer.java

Fixes height map terrain generation's grass (#1851)
(Actual fixes SolidRasterizer's hardcoded sea level handling)

Fix for #1851

---

engine/build.gradle
engine/src/main/java/org/terasology/engine/subsystem/lwjgl/LwjglGraphics.java

- Updated to gestalt-asset-core 4.1.2
- Fixed handling of default filtering for font vs texture assets to work with overrides.

Fix for texture overrides

---

engine/src/main/java/org/terasology/rendering/world/ChunkMeshUpdateManager.java
engine/src/main/java/org/terasology/world/ChunkView.java
engine/src/main/java/org/terasology/world/chunks/CoreChunk.java
engine/src/main/java/org/terasology/world/chunks/internal/ChunkImpl.java
engine/src/main/java/org/terasology/world/chunks/localChunkProvider/LocalChunkProvider.java
engine/src/main/java/org/terasology/world/internal/ChunkViewCoreImpl.java
engine/src/main/java/org/terasology/world/internal/WorldProviderCoreImpl.java
engine/src/main/java/org/terasology/world/propagation/light/LightMerger.java

Introduces read/write lock separation for chunks. Tesselation takes a read lock, which blocks the chunk provider from disposing the chunk.
This needs to be tested to ensure it doesn't introduce stutters.

Fix for #1856

---

engine/src/main/java/org/terasology/world/block/entity/BlockEntitySystem.java
engine/src/main/java/org/terasology/world/block/regions/ActAsBlockComponent.java
engine/src/main/java/org/terasology/world/block/regions/BlockRegionSystem.java

- Allow block regions to drop all the blocks in the region instead of the single block that they act like (opt in).
- Automatically add health to the region entity similar to the ActAsBlock block would have.
- Simplify the ActAsBlock CreateBlockDropsEvent handler into a single event handler.

Improvements to the BlockRegion system

---

engine/src/main/java/org/terasology/engine/module/RemoteModuleExtension.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/FileDownloader.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/ModuleListDownloader.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/RemoteModule.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/SelectModulesScreen.java
engine/src/main/resources/assets/skins/mainmenu.skin
engine/src/main/resources/assets/ui/menu/selectModsScreen.ui
modules/Core/build.gradle
modules/CoreSampleGameplay/build.gradle

The information about modules based on their `module.txt` is retrieved from [meta.terasology.org](http://meta.terasology.org). On demand, modules can be downloaded (from Artifactory) and installed without need to restart the game.
Fixes #1754 and fixes #1787 (supercedes #1875).

Add support for downloading modules at runtime.

---

engine/src/main/java/org/terasology/world/chunks/remoteChunkProvider/RemoteChunkProvider.java

Remote client was broken, as you got a NullPointerException. This commit fixes it again.

Fix a full stopper NullPointerExcpetion in remote client.

---

engine/src/main/java/org/terasology/engine/modes/loadProcesses/InitialiseRemoteWorld.java
engine/src/main/java/org/terasology/engine/modes/loadProcesses/InitialiseWorld.java
engine/src/main/java/org/terasology/world/block/BlockManager.java
engine/src/main/java/org/terasology/world/internal/WorldProviderCoreImpl.java
engine/src/main/resources/assets/blocks/unloaded.block

There is currently a lot of spam about attempts to access unloaded blocks.  e.g.
* right at start, when the chunk isn't loaded yet but the game already performs a ray cast to check which block the player is currently looking at
* When you throw an item into a chunk that isn't loaded there will be infinite spam about unloaded block access as the phsyic engine tries to handle the interaction of the item with the world.
This pull requests solves both issues by
* Firstly not spamming warnings about it
* Introducing a new block type engine:unloaded that all unloaded blocks have. Unloaded blocks can neither be penetrated nor be destroyed.
Thus if you try to throw an item in an unloaded chunk it will just bounce back.

Better handling of unloaded blocks

---

engine/src/main/java/org/terasology/engine/bootstrap/EnvironmentSwitchHandler.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/PreviewWorldScreen.java
engine/src/main/java/org/terasology/rendering/nui/properties/PropertyProvider.java
modules/Core/src/main/java/org/terasology/core/world/generator/facetProviders/HeightMapSurfaceHeightProvider.java

This PR changes the current property binding scheme for world gen. configuration. Previously, fields were modified directly through PropertyProvider's reflection system. This has the drawback that world gens are not notified (or only afterwards) that a parameter has changed.
This PR uses copies of configuration components and calls worldConfig.setProperty() as usual. This allows the world gen. to update accordingly (reload a height map, clear caches) or even decline the new parameter set.
I had to change `handleSwitchToPreviewEnvironment.handleSwitchToPreviewEnvironment` so it would update the `ComponentLibrary` with the new module environment. It also uses the sub-context now. Unfortunately, this update cannot be undone atm. Since this is using the sub-context only, it should be ok …

Update world gen. configuration with Component clones

---

modules/Core/src/main/java/org/terasology/core/world/generator/facetProviders/SurfaceObjectProvider.java

It seems like the JVM escape analysis cannot do its job due to the unknown list of filter predicates. Easy to fix though.

Reuse vector instance in SurfaceObjectProvider

---

engine/src/main/java/org/terasology/rendering/assets/mesh/ObjMeshFormat.java

Meshes without normals were allowed before and still are, but transparency checks seem to fail even for opaque meshes.

Allow obj meshes without texture coords.

---

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/CreateGameScreen.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/SelectModulesScreen.java

Modules that are explicitly selected are currently not preserved across restart, because the selection of the gameplay module was overwriting it.
Also, the list of available world generators was not refreshed when the module selection screen is closed.
I also moved the updating of the gameplay dropdown box to the onOpened() method. It was calling `set()` from within the `get()` method, which can easily cause infinite loops.
**Steps to test**: Select Core Gameplay and Cities. Going back to the Create Game screen does (not) list the Cities world gen. until restart. On restart the Cities module is (not) selected.

Usability tweaks for module and world gen. selection

---

engine/src/main/java/org/terasology/rendering/nui/widgets/browser/ui/BrowserWidget.java

Previously, the BrowserWidget would asume all the interactions done inside regardless if one of its children had an interaction region specified.  This prevented custom widgets rendered inside from showing tooltips and being clicked on.

Allow widgets inside the browser to still be interacted with

---

engine/src/main/java/org/terasology/entitySystem/entity/EntityStore.java
engine/src/main/java/org/terasology/world/chunks/internal/ReadyChunkInfo.java
engine/src/main/java/org/terasology/world/chunks/localChunkProvider/LocalChunkProvider.java
engine/src/main/java/org/terasology/world/generation/BaseFacetedWorldGenerator.java
engine/src/main/java/org/terasology/world/generation/EntityBuffer.java
engine/src/main/java/org/terasology/world/generation/EntityProvider.java
engine/src/main/java/org/terasology/world/generation/World.java
engine/src/main/java/org/terasology/world/generation/WorldBuilder.java
engine/src/main/java/org/terasology/world/generation/WorldImpl.java
engine/src/main/java/org/terasology/world/generation/impl/EntityBufferImpl.java
engine/src/main/java/org/terasology/world/generator/WorldGenerator.java
modules/Core/src/main/java/org/terasology/core/world/generator/AbstractBaseWorldGenerator.java

This is a functional draft/concept that allows world generators to create arbitrary entities. See [this image for an illustration](http://i.imgur.com/pyHC4Ap.png).
The idea is that `EntityProvider` instances can be registered in the world generator. Since entities need to be created on the game thread, the responsible components are first queued in `EntityStore` containers  before they are actually created as part of the chunk finalization process.
One issue is that Prefab components need to be copied and the copy library is part of the `EntityManager`. Thus, prefabs are stored as well.
~~Multiplayer / loading from file storage has not yet been considered well enough.~~
Comments?

Support entity generation for world gens.

---

engine/src/main/java/org/terasology/engine/subsystem/headless/renderer/HeadlessCanvasRenderer.java
engine/src/main/java/org/terasology/rendering/nui/Canvas.java
engine/src/main/java/org/terasology/rendering/nui/internal/CanvasImpl.java
engine/src/main/java/org/terasology/rendering/nui/internal/CanvasRenderer.java
engine/src/main/java/org/terasology/rendering/nui/internal/LwjglCanvasRenderer.java
engine/src/main/java/org/terasology/rendering/opengl/LwjglFrameBufferObject.java

This PR updates the implementation of framebuffer objects (FBOs):
* Use nearest neighbor filtering instead of bilinear filtering to avoid ugly borders with scaled textures.
* Use standard viewport rather than inverting the y-axis and adding 1
* Dispose and reload FBO when the linked texture was disposed
* Use an immutable vector to store FBO size.
In both old and current implementation, FBOs are created by `Canvas.subRegionFBO`, but are never disposed. Maybe this could be triggered on texture asset disposal? Or maybe FBOs should be assets, too?
I did not find any usages of the subRegionFBO() method. If there were, they might need tweaks (flip y-axis).

Improve support for Canvas FBOs

---

modules/Core/assets/blocks/flora/tree/BirchTrunk.block
modules/Core/assets/blocks/flora/tree/OakTrunk.block
modules/Core/assets/blocks/flora/tree/PineTrunk.block

For some reason, when PlantPack is enabled, trees lose their bark.  I still havent figured out why this happens (hoping maybe someone has an insight), but this works around the situation for now.
To test:
1. Create a Core Gameplay game with also the PlantPack enabled
2. Find a tree
3. Despair or rejoice (depending on whether you are testing before or after)

Fix tree trunks when the PlantPack module is also enabled.

---

engine/src/main/java/org/terasology/engine/subsystem/common/ConfigurationSubsystem.java

This will allow headless servers to run without CoreGameplay,  but still avoid breaking if there are no modules selected.  For the most part,  the default.cfg will take care of ensuring CoreGameplay gets selected at minimum.  This should still catch the times where there is invalid module names in the config file.

Only add the CoreGameplay module if the module selection is empty

---

build.gradle
config/gradle/common.gradle
engine/build.gradle

In order to avoid complications with reflections, the gestalt library dependencies should be updated as well.
An alternative to updating simultaneously would be relying on gestalt including a set of "basic" libraries such as reflections, gson, guava, slf4j.

Update most library versions to latest

---

engine/src/main/java/org/terasology/entitySystem/event/internal/EventSystemImpl.java

Currently, the entire game crashes if a `@ReceiveEvent` method in a module throws an exception.
I think that it should log the exception and continue instead. This leads to improved game experience and is also easier to debug the broken code.

Harden EventSystem against failures in modules

---

engine/src/main/java/org/terasology/entitySystem/metadata/MetadataUtil.java
engine/src/main/java/org/terasology/reflection/metadata/AbstractClassLibrary.java

Currently, component names are solely defined by their class names. This can be a problem for world generator configurations. The facet providers' configuration data is attached as a component to the world entity so it can be saved/loaded through the entity system. These names need to be unique - see #1924.
This leads to some rather long names such as `PerlinHillsAndMountainsProvider.PerlinHillsAndMountainsProviderConfiguration`
This PR resolves the issue by adding the enclosing class name (if available) to the component name. The nested class name could then simply be `Configuration` for more than one facet provider.
This PR also adds a warning if two different classes are registered for the same component name.
Closes #1924

Compose component name for nested classes

---

engine/src/main/java/org/terasology/engine/modes/StateLoading.java

This also resolves https://github.com/Terasology/EventualSkills/issues/4.

Bring back the previously saved game time when loading a game.

---

engine/src/main/java/org/terasology/rendering/nui/internal/CanvasImpl.java

This brings the `calculateRestrictedSize` method in `Canvas` in line with the `drawWidget()` method.
As a result, the size/borders/margins of custom widget skins is computed correctly.

Fix widget size for custom skins

---

engine-tests/src/test/java/org/terasology/world/generation/WorldBuilderTest.java
engine/src/main/java/org/terasology/world/generation/Facet.java
engine/src/main/java/org/terasology/world/generation/WorldBuilder.java

Providers are processed in the order they are added to the WorldBuilder. This ensures deterministic behavior.
Fixes #1912

Add Updates annotation in facet depencency chain

---

engine/src/main/java/org/terasology/engine/bootstrap/ClassMetaLibrary.java
engine/src/main/java/org/terasology/engine/bootstrap/ClassMetaLibraryImpl.java
engine/src/main/java/org/terasology/engine/bootstrap/EnvironmentSwitchHandler.java
engine/src/main/java/org/terasology/persistence/typeHandling/RegisterTypeHandler.java
engine/src/main/java/org/terasology/persistence/typeHandling/SerializationContext.java
engine/src/main/java/org/terasology/persistence/typeHandling/gson/GsonSerializationContext.java
engine/src/main/java/org/terasology/persistence/typeHandling/protobuf/ProtobufDeserializationContext.java
engine/src/main/java/org/terasology/persistence/typeHandling/protobuf/ProtobufSerializationContext.java

This PR adds the `@RegisterTypeHandler` annotation that allows modules to register custom type handlers.
A simple implementation: [Tasks/TimedTaskTypeHandler](https://github.com/Terasology/Tasks/blob/develop/src/main/java/org/terasology/tasks/persistence/TimedTaskTypeHandler.java)
Delegates to custom implementations, similar to UIFormat: [Tasks/TaskTypeHandler](https://github.com/Terasology/Tasks/blob/develop/src/main/java/org/terasology/tasks/persistence/TaskTypeHandler.java)

Add support for custom type handlers

---

engine/src/main/java/org/terasology/world/chunks/internal/ChunkRelevanceRegion.java
engine/src/main/java/org/terasology/world/chunks/localChunkProvider/LocalChunkProvider.java

Send chunks to client before light calculation is done. (Fix #1859)
This fixes #1859 and improves (but not fully solves) the situation described in #1886
Reasoning:
The light calculation gets only performed once the adjacent chunks got
loaded. So if wait for the light calculation before we mark a chunk as
relevant for a client then we would transfer less chunks to the client
then the relevance region is large. the client would then again perform
the light calculation too based on that reduced chunk count and would
reduce the view distance again. That is why it makes sense to detect
chunks as relevant even when no light calculation has been performed yet.

Send chunks to client before light calculation is done. (Fix #1859)

---

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/PlayerSettingsScreen.java
engine/src/main/java/org/terasology/rendering/nui/widgets/UIButton.java
engine/src/main/resources/assets/i18n/menu.lang
engine/src/main/resources/assets/i18n/menu_en.lang
engine/src/main/resources/assets/ui/menu/playerMenuScreen.ui

Resolves #1957
- Adds a OK/Cancel button to the player settings screen,  only committing the changes if OK is pressed.
- Adds validation to the player name to not allow blank names.
- Allows buttons to show tooltips even if disabled (so that the validation message could be shown)
- Shows the validation message when hovering over the OK button or player name text box.
- Uses the translation system for the validation message.
Controversial things, please comment on:
- Using tooltips for validation messages
- There is no validation message if the mouse is not over the OK button or name text box.
- Tooltips on both text box and button?  or just one?  or none?

Avoid blank player names

---

engine/src/main/java/org/terasology/input/InputSystem.java

This allows help text providers to enumerate all active key bindings for a functionality.

Provide a list of active key bindings

---

engine-tests/src/test/java/org/terasology/persistence/TemplateEngineTest.java
engine/src/main/java/org/terasology/i18n/TranslationSystemImpl.java
engine/src/main/java/org/terasology/persistence/TemplateEngine.java
engine/src/main/java/org/terasology/persistence/TemplateEngineImpl.java

Also makes the string template engine available for modules.
Required by [Dialogs](https://github.com/Terasology/Dialogs).

Extract string template engine from i18n system

---

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/ConfirmPopup.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/SelectModulesScreen.java
engine/src/main/resources/assets/ui/confirmPopup.ui

This pull request makes the "Download" button in the module selection screen also download all required modules.
Before the download starts the user is asked to confirm that he indeed wants to download that number of modules.
Only modules that haven't been downloaded in the newest version will be downloaded. If a module is however at a snapshot version it will always be redownloaded, as we can't tell if it has changed or not.

Make the download button in the module selection screen also download all required modules

---

engine/src/main/java/org/terasology/input/cameraTarget/PlayerTargetSystem.java
engine/src/main/java/org/terasology/input/cameraTarget/TargetSystem.java
engine/src/main/java/org/terasology/logic/players/LocalPlayerSystem.java
engine/src/main/java/org/terasology/logic/players/PlayerTargetChangedEvent.java

This PR adds notification events whenever an entity comes into the local player's interaction range. It decouples the camera system from the player system somewhat by using player coordinates / interaction range instead of camera coordinates.
Demonstration: https://youtu.be/RA5mb7WGSWo
This is quite similar to CameraTargetSystem, which does a few things differently though.
The original camera system is still in use in two situations:
* Compute focal distance for blur effects
* Designate work areas for BehaviorTree-related code.
Sending a ping to @immortius who was talking about a cleaner separation between camera and player already.

Use player coordinates for target localization

---

engine/src/main/java/org/terasology/registry/CoreRegistry.java
engine/src/main/java/org/terasology/registry/In.java
engine/src/main/java/org/terasology/registry/Share.java
engine/src/main/java/org/terasology/registry/package-info.java

Since all of the classes in the package now are API compatible,  tag the whole package with API.

Allow InjectionHelper to be used in modules.

---

engine/src/main/java/org/terasology/rendering/nui/internal/CanvasImpl.java

The main meat of this is adding a base implementation of onDraw into AbstractWidget.  This allows tooltips to be displayed even if there is no other interaction region added from the subclass.  Without this, it becomes confusing why setting a tooltip on your custom widget does by default show a tooltip until you also add an interaction region.
The UIButton is back to its former self by not adding an interaction region when it is disabled.  Tooltips on a disabled buttons now happen naturally and no longer need this special treatment.
The other noise in here is getting all other widgets to call this base onDraw method.  There could be controversy on whether it is actually needed on the everything.  I did the everything for completeness sake without regard to usefulness.  Advice welcomed on …

More seamless tooltip functionality for custom widgets

---

engine-tests/src/test/java/org/terasology/registry/CoreRegistryTest.java
engine/src/main/java/org/terasology/registry/CoreRegistry.java

Fix for issue #2014 assuming that the CoreRegistry class should act independently of its Context when the argument for the get method is Context.class

Bugfix #2014

---

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/inputSettings/InputSettingsScreen.java
engine/src/main/resources/assets/skins/mainmenu.skin
engine/src/main/resources/assets/ui/menu/createGameScreen.ui
engine/src/main/resources/assets/ui/menu/joinGameScreen.ui
engine/src/main/resources/assets/ui/menu/previewWorldScreen.ui
engine/src/main/resources/assets/ui/menu/selectGameScreen.ui
engine/src/main/resources/assets/ui/menu/selectModsScreen.ui

This PR replaces the obsolete `title` font with the (larger) Noto font. The difference in rendered size made a few adjustments necessary.
All subtitles should be at the same vertical position.
I guess we could remove the two obsolete fonts `default` and `title` now.
Fixes #2029

Use Noto font for screen titles

---

facades/TeraEd/build.gradle

This is a more of a workaround rather than a proper fix. Maybe we should file a feature request over at gradle?
Adapted from http://stackoverflow.com/questions/28728488/rename-gradle-task
Fixes #2045

Rename gradle run task for shader editor

---

engine-tests/src/test/java/org/terasology/documentation/BindingScraper.java

In response to #1975 item no. 2 - this snippet scapes all default key bindings from the code in engine.
It currently produces the following output:
`1` : Toolbar Slot 1
`2` : Toolbar Slot 2
`3` : Toolbar Slot 3
`4` : Toolbar Slot 4
`5` : Toolbar Slot 5
`6` : Toolbar Slot 6
`7` : Toolbar Slot 7
`8` : Toolbar Slot 8
`9` : Toolbar Slot 9
`0` : Toolbar Slot 10
`Q` : Drop Item
`W` : Forwards
`E` : Use Target
`I` : Open Inventory
`Left Ctrl` : Crouch / Descend
`A` : Strafe Left
`S` : Backwards
`D` : Strafe Right
`Left Shift` : Toggle Speed Temporarily
`Space` : Jump / Ascend
`Caps Lock` : Toggle Speed Permanently
`F5` : Toggle Behavior editor
`Escape` : Ingame Menu
`Tab` : Show online players
`T` : Toggle Chat
`H` : Hide HUD
`Grave` : Toggle Console
`Home` : Increase View Distance
`End` : …

Add utility to extract default key bindings from code

---

build.gradle

The most significant change in 1.1.0 is that `@author` tags are now flagged.

Use CodeMetric config 1.1.0

---

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/PreviewWorldScreen.java

Previously, only the module that defined the world generator and its dependencies participated in world configuration.  This allows the Cave module to present its settings alongside the default Perlin settings.

Let all enabled modules participate in world configuration

---

engine/src/main/java/org/terasology/engine/TerasologyEngine.java
engine/src/main/java/org/terasology/utilities/concurrency/TaskProcessor.java

Currently, uncaught errors in `TaskProcessor` are forwarded to the thread's default `UncaughtExceptionHandler`, which just prints the stack trace.
As a result, the threads die silently and game stalls while waiting for chunks.
The change in `TerasologyEngine` fixes the missing stacktrace/error report in the log file.
The change in `TaskProcessor` looks awful, but it seems to be the cleanest way to terminate.
Since the `LocalChunkProvider` is disposed only when leaving the game, it still does not get disposed in that situation leaving the other thread pools alive.
PR #1760 would actually fix this issue, because the `ThreadPoolSubsystem` is disposed properly.
Related/partly fixed: #2066 and https://github.com/MovingBlocks/CrashReporter/issues/23

Terminate on dying task processors

---

README.markdown
engine-tests/src/test/java/org/terasology/documentation/BindingScraper.java
engine/src/main/java/org/terasology/config/BindsConfig.java
engine/src/main/java/org/terasology/input/DefaultBindings.java
engine/src/main/java/org/terasology/input/binds/general/ConsoleButton.java
engine/src/main/java/org/terasology/logic/players/DebugControlSystem.java
engine/src/main/resources/default.cfg

Making PR just for documentation purposes to not miss the switch for the debug system from F1 to F2 and to highlight console now being *both* the grave key and F1.

Move debug key to F2 (console now F1 and `) and tweak at doc/utility about double-bound keys

---

engine/src/main/java/org/terasology/logic/characters/CharacterComponent.java
engine/src/main/java/org/terasology/logic/characters/CharacterHeldItemComponent.java
engine/src/main/java/org/terasology/logic/characters/CharacterHeldItemSystem.java
engine/src/main/java/org/terasology/logic/characters/events/ChangeHeldItemRequest.java
engine/src/main/java/org/terasology/logic/characters/events/HeldItemChangedEvent.java
engine/src/main/java/org/terasology/logic/inventory/CharacterInventorySystem.java
engine/src/main/java/org/terasology/logic/inventory/SelectedInventorySlotComponent.java
engine/src/main/java/org/terasology/logic/inventory/events/ChangeSelectedInventorySlotRequest.java
engine/src/main/java/org/terasology/logic/players/FirstPersonRenderer.java
engine/src/main/java/org/terasology/logic/players/LocalPlayerSystem.java
engine/src/main/java/org/terasology/logic/players/PlayerSystem.java
engine/src/main/java/org/terasology/rendering/nui/layers/hud/HudToolbar.java
engine/src/main/resources/assets/prefabs/player/player.prefab

The main benefit of this is to start decoupling the inventory system from the other systems.  It adds a "held item" system that will help when adding new features like dual wielding and/or different inventory systems by encapsulating the logic from each system to its own.
There is no change in functionality with this.  I used this short list of things to do in order to test both on a local game and a remote game hosted by a headless server:
- drop item
- switch item in selected slot
- switch from item to null to item
- switch from item to item
- scrollwheel up and down
- use item
- use item continuously by holding button
- attack with item
- attack with item continuously by holding button
- pick up an item into selected empty slot

Decouple the selected inventory slot from the player systems

---

engine/src/main/java/org/terasology/rendering/assets/texture/TextureData.java
engine/src/main/java/org/terasology/rendering/opengl/LwjglFrameBufferObject.java

Currently, the FBO texture was created without backing texture data. Some machines (graphics card drivers?) seem to auto-generate matching buffers while others don't.
The existing check in the constructor did not work, because it was bypassed by the `if` statement.
Fixes #2076 and https://github.com/Terasology/Minimap/issues/4.

Fix creation of FBO textures

---

engine/src/main/java/org/terasology/protobuf/ChunksProtobuf.java
engine/src/main/java/org/terasology/protobuf/EntityData.java
engine/src/main/java/org/terasology/protobuf/NetData.java

This reduces the total amount of compiler warnings by ~300, but will be overwritten when the protobuf code changes.
In the long run we should consider generating a compiled JAR file instead. This would also significantly simplify the CheckStyle config setup.

Suppress all warnings in auto-generated source code

---

engine/src/main/java/org/terasology/logic/players/MenuControlSystem.java
engine/src/main/java/org/terasology/rendering/opengl/FrameBuffersManager.java
engine/src/main/java/org/terasology/rendering/opengl/GraphicState.java
engine/src/main/java/org/terasology/rendering/opengl/PostProcessor.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersChunk.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersCombine.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersDebug.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersHdr.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersLightGeometryPass.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersLightShaft.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersOcDistortion.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersPost.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersPrePost.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersSSAO.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersSobel.java
engine/src/main/java/org/terasology/rendering/world/WorldRendererImpl.java
facades/TeraEd/src/main/java/org/terasology/editor/properties/SceneProperties.java

With the work I did around six months ago, the class LwjglRenderingProcess had been progressively stripped of much of its functionality and classes such as the PostProcessor and GraphicState made their appearance.
This PR finally addresses what is left in the LwjglRenderingProcess class (FBO-related functionality) and refactors it into a FrameBuffersManager class.
The first [commit](https://github.com/MovingBlocks/Terasology/commit/ca92f309968a099f24c7649693de3c377ae9eb1d) simply deals with the immediate consequences of the renaming.
The second [commit](https://github.com/MovingBlocks/Terasology/commit/59e8d892aebbe8f0993a3d5ed3e0d0946651f48e) is where the "meat" is, as the newly renamed class is considerably refactored.
The third …

Introducing FrameBuffersManager

---

engine/src/main/java/org/terasology/logic/behavior/nui/BehaviorEditorScreen.java

This fixes the broken viewing of behavior trees (e.g. when you have spawned a deer in the wild animals module and then press F5 and select the behavior of the deer).

Fix the broken viewing of behavior trees.

---

engine/src/main/java/org/terasology/world/chunks/localChunkProvider/LocalChunkProvider.java

It used to get sent when a old chunk got loaded.

Send OnChunkGenerated when a new chunk gets generated.

---

engine/src/main/java/org/terasology/logic/characters/CharacterSystem.java
engine/src/main/java/org/terasology/logic/players/LocalPlayer.java
engine/src/main/java/org/terasology/physics/Physics.java
engine/src/main/java/org/terasology/physics/bullet/BulletPhysics.java

Add Character back in to ray tests to allow PvP combat.  Be wary of Mr Barsack and his axe!
Add the ability to exclude entities from a physics ray test so that a player cannot hit or activate their own character.
This also fixes the problem of being not able to place blocks close to your feet because of the mismatched ray trace filters.  This problem is 
mentioned in https://github.com/MovingBlocks/Terasology/pull/2157.

Add Character back in to ray tests to allow PvP combat

---

engine/src/main/java/org/terasology/logic/players/CameraClientSystem.java
engine/src/main/java/org/terasology/logic/players/FirstPersonClientSystem.java

Rethought the way the events for this work.  This separates the mounting from the resetting of the camera a bit better.  Where a camera reset actually recreates the client side camera entity,  which naturally tiggers a mount.  Also,  force a camera reset when the character respawns.

Fix camera linking to a respawned character.

---

engine/src/main/java/org/terasology/logic/behavior/BehaviorSystem.java

The behavior system did not clear the entity list properly. It tried
to work with unloaded entities. This resulted in a NullPointerException
when the behavior node tried to work with a component from the
unloaded entity.

Fix crash when a entity with a behavior gets unloaded.

---

engine/src/main/java/org/terasology/engine/modes/loadProcesses/CreateWorldEntity.java
engine/src/main/java/org/terasology/logic/common/lifespan/LifespanComponent.java
engine/src/main/java/org/terasology/logic/common/lifespan/LifespanSystem.java
engine/src/main/java/org/terasology/logic/location/Location.java
engine/src/main/java/org/terasology/logic/location/LocationResynchEvent.java
engine/src/main/java/org/terasology/logic/time/TimeAuthoritySystem.java
engine/src/main/java/org/terasology/logic/time/TimeClientSystem.java
engine/src/main/java/org/terasology/logic/time/TimeResynchEvent.java
engine/src/main/java/org/terasology/physics/bullet/BulletPhysics.java
engine/src/main/java/org/terasology/physics/bullet/EntityMotionState.java
engine/src/main/java/org/terasology/physics/engine/PhysicsSystem.java
engine/src/main/java/org/terasology/physics/events/PhysicsResynchEvent.java
engine/src/main/java/org/terasology/rendering/nui/layers/ingame/metrics/DebugOverlay.java

When rigid bodies are removed,  an area around them is woken up so that bodies resting on top can fall.  This allows large amounts of rigid bodies in the world without actively calculating physics on them (like say from the railgun).  The falling bodies problem was solved before by always setting the bodies to an active state, now it only activates a region around the removed body.
You will see framerates improve a couple seconds after a number of railgun hits.  Previous to this change it would drop the framerate down really low until the entities were removed entirely by the LifespanComponent.

Allow rigid bodies to settle and sleep - time for more explosions!

---

engine/src/main/java/org/terasology/logic/behavior/tree/PlaySoundNode.java
engine/src/main/java/org/terasology/logic/particles/BlockParticleEffectComponent.java
engine/src/main/java/org/terasology/logic/particles/BlockParticleEmitterSystem.java
engine/src/main/java/org/terasology/world/block/items/BlockItemSystem.java
engine/src/main/resources/assets/prefabs/particleEffects/defaultBlockParticles.prefab
engine/src/main/resources/assets/prefabs/particleEffects/dustEffect.prefab
engine/src/main/resources/assets/prefabs/particleEffects/smokeExplosion.prefab
modules/Core/src/main/java/org/terasology/core/logic/door/DoorSystem.java
modules/Core/src/main/java/org/terasology/logic/health/BlockDamageAuthoritySystem.java
modules/Core/src/main/java/org/terasology/logic/health/HealthAuthoritySystem.java

This solves hopefully all of the sound issues in multiplayer (fixes #715) and some issues with sound placement (#663).  There are two strategies to sound that are important to note:
1. Playing sounds on a common system (where the same code runs on remote client and authority)
- Use the PlaySoundEvent event that takes in the EntityRef of the owner.  Events that trigger playing a sound need need to specify the instigator entity that caused the sound so that when the authority broadcasts the sound to all players,  it will skip repeating the sound on the owning client.
- Accessing the audio system directly is generally a bad idea.
2. Playing sounds on the authority
- Use the PlaySoundEvent without an owner EntityRef.  That way it will broadcast to everyone including the client that caused the …

Fix sound issues when in multiplayer

---

engine/src/main/java/org/terasology/engine/modes/loadProcesses/JoinServer.java
engine/src/main/java/org/terasology/network/Server.java
engine/src/main/java/org/terasology/network/internal/ServerImpl.java

First, this fix check whether Game Name is present or not. If the game name is not present, then this fix look up for the Server hostname & address as log file name using existing SocketAddress.
The output forrmat log file name as follows:
Terasology-<hostname>-<IP>-<port>.log
Example:
Terasology-localhost-127.0.0.1-25777.log

Fix #2030 Add hostname & server address as log file name on server play

---

config/eclipse/.importorder

Fixes #2117.
_Note: since .importorder is a semantic extension, I've chosen not to name this file at all - looks clean and .gitignore-like. This may cause some awkward issues on Windows, though, so it's subject to change._
- In Eclipse, go to Window → Preferences → Java → Code Style → Organize Imports.
- Import the import order file, click Apply.
- **[Recommended]** Switch to Editor → Save Actions, check Perform the selected actions on save and Organize imports.

Add import statement order config file for Eclipse

---

engine/src/main/java/org/terasology/network/internal/NetworkSystemImpl.java

Fixes #1375 
The function named 'removeClient()' was being called twice when the admin kicked the user. This was because when admin kicked the user a method was called named as 'forceDisconnect' which called the 'removeClient' method, which leaded to the user being in a list named 'disconnectedClients'. Now when the user gets kicked successfully, the evil method here is called named 'channelDisconnect'. It again used to call 'removeClient' but there was no client and hence nullPointerException. So I modified the code accordingly.

Kick feature now working

---

engine-tests/src/test/resources/logback.xml
facades/PC/src/main/resources/logback.xml
facades/TeraEd/src/main/resources/logback.xml

A supplement to the fixes for MovingBlocks/TerasologyLauncher#349 and MovingBlocks/TerasologyLauncher#350, should be merged along with MovingBlocks/TerasologyLauncher#351
Whenever MovingBlocks/TerasologyLauncher#351 is merged, try modifying log levels in the launcher and then check out the game logs. This PR is what makes Logback actually accept the new levels in the game.

Add config option to override log level

---

engine/src/main/java/org/terasology/engine/subsystem/headless/assets/HeadlessSkeletalMesh.java
engine/src/main/java/org/terasology/rendering/assets/animation/MeshAnimation.java
engine/src/main/java/org/terasology/rendering/assets/animation/MeshAnimationData.java
engine/src/main/java/org/terasology/rendering/assets/animation/MeshAnimationImpl.java
engine/src/main/java/org/terasology/rendering/assets/skeletalmesh/SkeletalMesh.java
engine/src/main/java/org/terasology/rendering/assets/skeletalmesh/SkeletalMeshData.java
engine/src/main/java/org/terasology/rendering/assets/skeletalmesh/SkeletalMeshDataBuilder.java
engine/src/main/java/org/terasology/rendering/logic/SkeletonRenderer.java
engine/src/main/java/org/terasology/rendering/md5/MD5AnimationLoader.java
engine/src/main/java/org/terasology/rendering/opengl/OpenGLSkeletalMesh.java

Adds frustum culling to skeleton based meshes. 
This speeds up the game when there are a lot of skeleton meshes around that are currently not beeing looked at by the camera.
Test with newest version of the WildAnimals addon, which contains deers that have correct bounding boxes.

Faster skeleton mesh rendering via frustum culling

---

engine/src/main/java/org/terasology/rendering/nui/widgets/UIDropdownScrollable.java

Fixes #2185
Currently it just ignores the scroll value beyond a certain limit. So, no actual scroll happens after the vertical bar is scrolled a certain amount of pixels.
A better approach maybe to divide the net scroll amount of vertical bar according to the number of element (by linear weighing). This would allow actual scroll till the end of the bar.
If the second approach would be preferred, please let me know. I'll edit it.
.
This is my first PR to Terasology, so just submitted it in a bit of excitement, sorry if I missed some coding standard followed in this project.

Fix issue when menu is scrolled down.

---

modules/Core/src/main/java/org/terasology/rendering/nui/layers/ingame/inventory/InventoryGrid.java

Fixes #2212 - adds a catch block and warning-level log entry to `getPreferredContentSize()` & a precondition to `onDraw()` - logging here would be non-viable (think of the logspam!)
Try playing TTA depending on a version of WoodAndStone that doesn't have Terasology/WoodAndStone#43 merged in?
This should be a fairly straightforward fix either way.
These are the only methods that can cause a zero-division error within Core layouts.

Handle zero division in InventoryGrid

---

engine/src/main/java/org/terasology/input/cameraTarget/TargetSystem.java
engine/src/main/java/org/terasology/world/block/items/BlockItemSystem.java

Fixes #2154 
The target returned came from the entity associated with the block, which for all elements of a multi-block object would give a location in the same place. This modifies the target to set the LocationComponent to targetBlockPos
Reproduce: In Throughout The Ages break apart enough branches and dirt to make a crude axe hammer (craft with g) then chop some tree trunk blocks, place two adjacent, right click either top with the axe, tadaa you get a two block work station. 
Hover over the station, see that the selection grid appears in correct place for all blocks at all times.

Fix bug #2154

---

modules/Core/src/main/java/org/terasology/rendering/nui/layers/ingame/inventory/ItemIcon.java

Fixes bug #2213 
ItemIcon always returned (0,0) for its preferred size, which is what the craft bench relied upon to render it. I chose to return the size of the texture instead, I'm not sure if this is the best approach to fixing it, but it fixes the recipe display perfectly.
An alternative fix would be to edit CraftRecipeWidget to not rely on calculatePreferredSize, and provide its own size.
Obtain items for TTA crafting, eg destroy enough dirt to get stones. Press 'g' to open crafting window, you will see the result of the recipe displayed correctly.
ItemIcon is used all over the place, I am also unsure if it was set to return the 0 vector for a specific reason, or if it was a mistake.

Fix bug #2213, result of crafting recipe is displayed in crafting window

---

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/CreateGameScreen.java
engine/src/main/resources/assets/ui/menu/createGameScreen.ui

Fixes issue #2233
Adds a subtitle to the create game screen in singleplayer and multiplayer game.

Adds the Create Game screen subtitle

---

engine/src/main/java/org/terasology/logic/behavior/tree/Task.java

This pull request resolves issues relating to the behavior tree test failing.
run the unit test for logic/behavior.

resolved issue #2231

---

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/SelectModulesScreen.java

Fixed modules filter. Not installed modules don't disappear from the list anymore. Removed unnecessary update() call from onTextChange() listener.
Check modules filter. Modules don't disappear from the list anymore.

Fixed modules filter

---

modules/Core/src/main/java/org/terasology/logic/inventory/ItemCommands.java

Fixes issue #2174 
Using JoshariasSurvival, type into the console "giveItem axe". It will now list all items called "axe", instead of saying it couldn't find an item called "axe".
Type into the console "giveItem Stone" and it will still give you stone.
Type into the console "giveItem nothingWithThisNameExists" and it will tell you that no such item exists.
The wording on the details could be changed.

Fixes #2174 - adds a useful error message in case of giveItem with an ambiguous item

---

.gitignore
engine/src/main/java/org/terasology/engine/TerasologyEngine.java
engine/src/main/java/org/terasology/persistence/typeHandling/protobuf/ProtobufPersistedData.java
facades/PC/build.gradle
facades/PC/src/main/java/org/terasology/engine/Terasology.java

`.gitignore` - rearranged so ignored files stay ignored, added new Mac-specific ignores for things introduced in Mavericks, Yosemite, and El Capitan
`TerasologyEngine.java` - 1MB is `1048576` bytes, so we should just use that number instead.
`ProtobufPersistedData.java` - added a few things to (hopefully) aid in debugging
`facades/PC/build.gradle` - added "debug" task, same as "game" task but starts the JVM in debug mode (useful for IDEs)
It all passed in checkstyle.

Rearranged gitignore, minor fixes

---

engine/src/main/java/org/terasology/rendering/nui/itemRendering/StringTextIconRenderer.java

Fixes a bug in the StringTextIconRenderer as described in [a comment](https://github.com/MovingBlocks/Terasology/pull/2270#issuecomment-204645493) on #2270: icons overlap with text when text wrapping is disabled. (This was caused by the renderer not adjusting for icon width when the text being rendered doesn't need to be shortened - see [line 76 in the original file](https://github.com/MovingBlocks/Terasology/blob/98f37a55886b6431aeba85d04f4618adcc37a494/engine/src/main/java/org/terasology/rendering/nui/itemRendering/StringTextIconRenderer.java#L76))
Launch the game and go to _Settings → Player → Language_; test if any icons overlap with locale text.

Fix StringTextIconRenderer icon overlapping issue

---

modules/Core/src/main/java/org/terasology/rendering/nui/layers/ingame/inventory/InventoryGrid.java

Fixes another issue like #2212 after applying #2227 which makes the item icons bigger than the canvas.  In this divide by zero problem,  the canvas is smaller than the inventory item and so it rounds down horizontalCells to 0,  causing another divide by zero problem.  This will make it still draw the item even though it may not fit correctly.
After opening a wooden workbench (hit two side by side logs on the top) and getting some craftable items (and able to see the results thanks to #2227), it would crash at this point.

More avoiding dividing by zero in the inventory grid

---

engine/src/main/java/org/terasology/rendering/nui/widgets/UICheckbox.java
engine/src/main/java/org/terasology/rendering/nui/widgets/UIDropdown.java
engine/src/main/java/org/terasology/rendering/nui/widgets/UIDropdownScrollable.java
engine/src/main/resources/assets/ui/menu/videoMenuScreen.ui

Implementation for #2268. Adds a disabled state for UICheckbox, UIDropdown and UIDropdownScrollable - this should cover all of NUI's interactable widgets. _(UIButton can already be disabled via `"enabled": false`, while UIText can be set to readonly via `"readOnly": true`)_
Interact with the Volumetric Fog checkbox (as per #2246).

[OK to merge] Support for disabled UI elements

---

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/MigTestScreen.java
engine/src/main/resources/assets/ui/migTestScreen.ui

Implements a TODO item from #2274 as suggested in @Cervator's [comment](https://github.com/MovingBlocks/Terasology/pull/2274#issuecomment-206097263) on the issue:
- Adds a column containing disabled widgets for the relevant row (`"readOnly": true` for UIText and `"enabled": false` elsewhere). Currently widget disabling is implemented for UIButton, UIText, UIDropdown, UIDropdownScrollable and UICheckbox - making the assumption that `enabled` will eventually become an `AbstractWidget` property as per #2275.
- Removes invalid text properties that were throwing logger warnings, replaces them with more meaningful identifiers.
- Adds UIDropdownScrollable and fills some of the other widgets with sample data.
In the main menu open the console by pressing tilde, type in `showScreen migTestScreen`, …

Added disabled widgets to migTestScreen; fixed misc. issues

---

engine/src/main/java/org/terasology/rendering/nui/widgets/UIScrollbar.java

Short and simple fix for #2283. I originally wanted to couple this with more zero division fixes, but after some investigation (i.e. searching for '/' in widget code) it seems that these are actually the only lines of code in the UI* widget family that don't handle zero division properly.
Launch the game, type in `showScreen migTestScreen`, click on the `min`-sized UIScrollbar, check that it didn't throw a silent stacktrace.

UIScrollbar zero division hardening

---

engine/src/main/java/org/terasology/world/block/entity/BlockCommands.java

Fixes #2265
In the command system: `giveBlock pickaxe` results in a suggestion to use `giveItem`, and `giveBlock NothingWithThisNameExists` results in a message telling the player that no such block exists.
Do we want to move to a unified `give` that gives either blocks or items? At the moment, `giveBlock` and `giveItem` overlap a lot.

Fixes #2265

---

engine/src/main/java/org/terasology/logic/console/commands/CoreCommands.java
engine/src/main/java/org/terasology/logic/console/suggesters/ScreenSuggester.java

As title says, adds suggester for showScreen command. I couldn't resist to add this one. :)
Open console, write showScreen and hit TAB, it should be able show available assets for selection.

Add auto complete for "showScreen" command

---

engine/src/main/java/org/terasology/logic/characters/CharacterHeldItemAuthoritySystem.java
engine/src/main/java/org/terasology/logic/inventory/ItemCommonSystem.java
engine/src/main/java/org/terasology/rendering/logic/LightComponent.java
engine/src/main/java/org/terasology/rendering/opengl/GraphicState.java
engine/src/main/java/org/terasology/rendering/world/WorldRendererImpl.java
engine/src/main/resources/assets/shaders/lightGeometryPass_frag.glsl
engine/src/main/resources/org/terasology/include/globalFunctionsFragIncl.glsl

This fixes various parts of the lighting system.  Addressing issues with dropping multiple torches, oddness with specular light, and more usable attenuation values.  Screenshots to follow...
This does introduce something that needs addressing.  When a torch is held or dropped in the world,  it does not light itself.  This is probably an already existing issue present,  but made more obvious when I removed the light fading in and out when switching between torches and non torches.  Which brings me to something else that needs addressing,  items that are held need to be better shown in a multiplayer setting.  This will allow us to avoid putting lights on the character altogether.
Drop lots of torches.  Hold torches.  Watch the sun/moon effect on the world.

Reduce overbrightness in various parts of the system

---

engine/src/main/java/org/terasology/logic/players/MenuControlSystem.java
modules/Core/assets/skins/dropItemRegionDefault.skin
modules/Core/assets/ui/hud/dropItemRegion.ui
modules/Core/src/main/java/org/terasology/logic/inventory/CharacterInventorySystem.java
modules/Core/src/main/java/org/terasology/logic/inventory/events/DropItemRequest.java
modules/Core/src/main/java/org/terasology/rendering/nui/layers/hud/DropItemRegion.java
modules/Core/src/main/java/org/terasology/rendering/nui/layers/ingame/inventory/InventoryGrid.java

Fixing #2218 
.
I added an interaction region on all sides of the InventoryGrid, so the cells are put in the center of the screen (the offset is calculated by giving half of width left after drawing the cells).
There are 4 rectangular regions which need to be targetted. I have added all 4 with appropriate names.
I just tried to immitate the existing functionality of right click.. So the code is adapted version of [onUseItemButton](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/logic/players/LocalPlayerSystem.java#L348) from ```LocalPlayerSystem```
.
I Expected that if I drag an item out of the inventory cells (on the inventory screen) and drop it on empty area around the grid then it would get dropped on the terrain. I saw that on right click I …

Trying to add drag drop of items from inventory

---

modules/Core/src/main/java/org/terasology/rendering/nui/layers/hud/DropItemRegion.java

Fixes #2295 
Adds dropping of 1 item when user presses right click while holding a stack of item on the drop region around inventory grid.

Drop 1 item from inventory on right click in drop region.

---

engine/src/main/java/org/terasology/rendering/nui/widgets/UIImage.java

Currently, `UIImage` always uses white color to render. This PR adds tinting support, mainly for animations that will be added in a follow-up.

Add tinting support to UIImage

---

engine/src/main/java/org/terasology/world/viewer/layers/NominalFacetLayer.java
modules/Core/src/main/java/org/terasology/core/world/generator/facets/BiomeFacet.java
modules/Core/src/main/java/org/terasology/core/world/generator/rasterizers/SolidRasterizer.java
modules/Core/src/main/java/org/terasology/core/world/viewer/layers/CoreBiomeColors.java
modules/Core/src/main/java/org/terasology/core/world/viewer/layers/CoreBiomeFacetLayer.java

This allows modules to extend the biomes in external world generators and maintain compatibility with existing plugin world generation.  This was a problem with using JoshariasSurvival with ShatteredPlanes because the foragable food generation required Core's BiomeFacet.  
With this,  ShatteredPlanes can use the built in Facet mechanisms for biomes and add additional biomes of its own.
Core perlin world generation still generates flora according to biome.  The world preview still colors correctly to biome.

Make it possible to add new biomes and still be compatible with CoreBiomes

---

engine/src/main/java/org/terasology/rendering/logic/RegionOutlineComponent.java
engine/src/main/java/org/terasology/rendering/logic/RegionOutlineRenderer.java

A component (and a powering system) that allows modules to draw block region outlines.
The region looks like this:
(particle don't belong to it, but to gooey who choose to pop up right when I made the screenshot)
Get the debug branch from Terasology/GooeysQuests module and walk to the east side of a mountain. Gooey will show up and offer you to spawn a dungeon. When the dungeon spawns you get a debug item. When you select the debug item, the entrance region of the dungeon gets highlighted via this new region outline component. Activating  the item cause (right click) copies the blocks in the region as text to the clipboard.

Added component & system for drawing region outlines.

---

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/settings/PlayerSettingsScreen.java

A small follow-up for #2299 that uses the tinting capability of `UIImage` to dynamically change the color image in the player settings screen.

Use image tinting in player settings screen

---

engine/src/main/java/org/terasology/logic/inventory/ItemComponent.java
engine/src/main/java/org/terasology/logic/inventory/ItemPickupAuthoritySystem.java
engine/src/main/java/org/terasology/logic/inventory/PickupComponent.java
engine/src/main/resources/assets/prefabs/itemPickup.prefab
modules/Core/src/main/java/org/terasology/logic/inventory/CharacterInventorySystem.java

This PR adds item pickup time capabilities for the game. This has been discussed in PR #2289, and this is what I reduced it to.
I added _timeToPickUp_ to represent the time needed to pass from when the item was dropped and _pickUpTime_ as the time from when the counter starts.
I added the value changes in onDropItemRequest because I only wanted the **player's** item dropping to be affected by this change. Of course, any other drop item event listeners will be able to change the time needed to pick up the item by just getting the component, changing the two values, and saving.
I found this necessary because dropping items relatively below you or close enough to you would result in them being picked up by the character. This way, a player can throw items at his feed with no issues.
To test, …

Item pickup delay

---

modules/Core/src/main/java/org/terasology/logic/health/HealthAuthoritySystem.java

Nullify damage events while in god mode (fixes #652)
-Activate "Breathing" module
-Begin play (either new or saved)
-Use pickaxe on blocks, verify they can still be destroyed and picked up
-Find deep water, go swimming
-Verify you begin to lose health after being underwater for the standard period of time
-Surface, enter ghost mode ('F1' then type "ghost")
-Dive back in
-Verify that the oxygen meter goes down, but no health is lost.
I'm new to this project, and just assumed that god mode and ghosting were synonymous, since I couldn't find any references to "god mode" in the code. If I got this wrong, hey, sorry.

Nullify damage events while in god mode (fixes #652)

---

engine/src/main/java/org/terasology/rendering/assets/material/BaseMaterial.java
engine/src/main/java/org/terasology/rendering/logic/MeshRenderer.java
engine/src/main/java/org/terasology/rendering/opengl/PostProcessor.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersBase.java
engine/src/main/java/org/terasology/rendering/world/WorldRendererImpl.java

Applying a shader uniforms to not just "currentOnly" causes lots of openGL state changes because it has to enable all the other shaders individually,  set the value across the board,  then reload the original shader.  This starts to be a more prominent problem when each chunk does this multiple times in a frame.
With these changes,  I boosted my average FPS by 10+ and "mega" view distance became playable (over 20fps).
In measuring the amount of openGL calls,  I used gDEBugger and observed the difference in "OGL calls/frame".  The amount of OGL calls reduced by over 50%.
- Reduction of openGL calls by only using "currentOnly = true" when setting shader uniform values in world rendering.  (NUI rendering is another issue.  But it does not seem to affect FPS like world rendering)
- Reduction …

Reduce the amount of openGL noise in world rendering

---

engine/src/main/java/org/terasology/logic/console/suggesters/ScreenSuggester.java

My auto-complete PR(#2266) seems like broke proper initialisation of UIScreenLayer. An example for reproducing as mentioned in  #2329, when `migTestScreen` is loaded with auto completion, exiting the screen with `ESC` throws an Exception.  
My previous PR used `AssetManager`'s `getAvailableAssets()` method for suggesting available UIScreenLayer's for `showScreen()`. What I missed at that time, ~~`getAvailableAssets()`~~ `getAsset(...)` method tries to  initialise the assets and when `showScreen()` method is invoked with auto completion and proper initialisation steps are not considered.  A quick fix in this PR disposes these loaded assets, therefore screens are correctly loaded. 
For testing, loading `migTestScreen` with auto completion(writing `showScreen mig` and hitting `TAB` key) and …

Quick fix for #2329, disposes loaded assets for correct initialization

---

engine/src/main/java/org/terasology/logic/console/suggesters/ScreenSuggester.java

Currently, every screen that is suggested is loaded into memory and tested if the root widget implements `UIScreenLayer`. I removed the test to avoid unnecessary loading and to avoid creating duplicates. It will suggest other UIElements as well - I think that there are none though.
Fixes #2329, supersedes #2339

Do not load assets when suggesting screens

---

engine/src/main/java/org/terasology/entitySystem/prefab/internal/PrefabFormat.java
facades/PC/src/main/resources/logback.xml

Makes it a little easier to find misbehaving prefabs. Used it to fix up Signalling and clean up the now-outdated color definitions in Pathfinding. Adjusted default logging config to allow this one piece of debug logging, which does make the logs a bit chattier, but then I disallowed the pointless "given scan urls are empty. set urls in the configuration" log spam so it sort of balances out.
Couple examples now allowing easier connecting of deeper issues like deserialization problems with the exact prefab that caused it:
```
16:08:42.848 [main] DEBUG o.t.e.prefab.internal.PrefabFormat - Attempting to deserialize prefab PlantPack:Squash with inputs [/PlantPack/assets/prefabs/crop/Squash.prefab]
16:08:42.848 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component …
```

Minor logging tweaks.

---

engine/src/main/java/org/terasology/rendering/nui/widgets/UITreeView.java

A quick fix for an issue with #2338: when a `UITreeView` item is expanded/contracted with no item having been selected, a silent NPE is thrown. This doesn't cause any issues with the component (apart from the performance loss associated with throwing/logging exceptions?) but is still unintended.

Fix silent UITreeView error when no item is selected

---

engine/src/main/java/org/terasology/logic/characters/AffectJumpForceEvent.java
engine/src/main/java/org/terasology/logic/characters/KinematicCharacterMover.java

An event that allows modifying the character's jump speed based off some other factors.  This could be used for things like:
1. Training a jumping skill (this is what I personally plan on doing)
2. Wearing springy boots
3. Drinking a super jumping potion
This change should not affect current jumping behavior but allow extension.  After this is merged,  I have a jumping skill that will be added to ManualLaborEventualSkills.

Allow modification of jump speed using events

---

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/settings/PlayerSettingsScreen.java

Fixes  #2350 Sort entries in the language dropdown under player settings
Start Terasology. Go to settings -> player -> language. All languages should be sorted alphabetically instead of unordered.

languages sorted in player settings menu

---

engine/src/main/java/org/terasology/rendering/dag/BackdropNode.java
engine/src/main/java/org/terasology/rendering/dag/ShadowMapNode.java
engine/src/main/java/org/terasology/rendering/dag/SkyBandsNode.java
engine/src/main/java/org/terasology/rendering/dag/WorldReflectionNode.java
engine/src/main/java/org/terasology/rendering/opengl/GraphicState.java
engine/src/main/java/org/terasology/rendering/opengl/OpenGLUtils.java
engine/src/main/java/org/terasology/rendering/opengl/PostProcessor.java
engine/src/main/java/org/terasology/rendering/world/WorldRendererImpl.java

Two new nodes for DAG (Directed Acyclic Graph), wrapping tasks that are related with rendering Sky. 
Check if there are any weirdness related to rendering of Sky.

[RFR] Backdrop and Skybands Nodes for DAG

---

engine/src/main/java/org/terasology/engine/subsystem/lwjgl/LwjglGraphics.java

As title states PR fixes `IllegalStateException` whenever `LwjglGraphics.initDisplay()` called if `config.cfg` has rendering.debug = true. Without this fix, running Terasology throws  `IllegalStateException` in Mac OS X 10.11.4:
```java
...
03:36:34.926 [main] INFO  o.t.e.subsystem.lwjgl.LwjglGraphics - Starting initialization of LWJGL
03:36:34.927 [main] INFO  o.t.e.subsystem.lwjgl.LwjglGraphics - Initial initialization complete
03:36:36.019 [main] INFO  o.t.e.subsystem.lwjgl.LwjglGraphics - Initializing display (if last line in log then likely the game crashed from an issue with your video card
03:36:36.287 [main] WARN  o.t.e.subsystem.lwjgl.LwjglGraphics - Unable to create an OpenGL debug context. Maybe your graphics card does not support it.
java.lang.IllegalStateException: Function …
```

Fixes IllegalStateException whenever LwjglGraphics.initDisplay() called when rendering.debug = true

---

engine/src/main/java/org/terasology/rendering/nui/widgets/UITreeView.java
engine/src/main/resources/assets/skins/treeViewTestScreen.skin
engine/src/main/resources/assets/ui/nuiEditorScreen.ui
engine/src/main/resources/assets/ui/treeViewTestScreen.ui

Removes `UITreeView`'s native vertical scrollbar in favor of wrapping the element within a `ScrollableArea` to provide scrolling functionality. Wraps the existing `UITreeView` elements (in `nuiEditorScreen`/`treeViewTestScreen`) within a `ScrollableArea`.
Press F6 to activate the NUI editor, test the scrollbars with different asset files.

UITreeView scrollbar fixes

---

docs/Playing.md
engine/src/main/java/org/terasology/rendering/nui/editor/NUIEditorButton.java

Changes the hotkey to trigger the NUI editor to F10 (was F6) and adds info about it to `docs\Playing.md`.
Launch the game and press F10 to trigger the editor, then check Input Settings for binding details.
Nope!

NUI editor binding tweak

---

engine/src/main/java/org/terasology/rendering/dag/AmbientOcclusionPassesNode.java
engine/src/main/java/org/terasology/rendering/dag/OutlineNode.java
engine/src/main/java/org/terasology/rendering/dag/PrePostCompositeNode.java
engine/src/main/java/org/terasology/rendering/dag/SimpleBlendMaterialsNode.java
engine/src/main/java/org/terasology/rendering/opengl/GraphicState.java
engine/src/main/java/org/terasology/rendering/world/WorldRendererImpl.java

Four new nodes for DAG (Directed Acyclic Graph), wrapping tasks that are related with Pre-Post Composition.
* AmbientOcclusionPassesNode
* OutlineNode
* PrePostCompositeNode
* SimpleBlendMaterialsNode
Check if there are any weirdness related to rendering of transparent(with some degree, blended with background) objects, [Ambient Occlusion](https://en.wikipedia.org/wiki/Ambient_occlusion#/media/File:Show_how_3D_real_time_ambient_occlusion_works_2013-11-23_10-45.jpeg) and [outline](http://en.wikipedia.org/wiki/Sobel_operator) option.

[RFR] Add Pre-Post Composite Nodes

---

engine/src/main/java/org/terasology/engine/subsystem/lwjgl/DebugCallback.java

Reduce the log level for opengl notifications.
Reasoning: It used to log a line about buffer usage whenever a buffer got used to draw a line of a UI widget.
The logged message looked like this:
```
11:21:05.913 [main] INFO  OpenGL - [api] [other] Buffer detailed info:
Buffer object 212 (bound to GL_ARRAY_BUFFER_ARB,
usage hint is GL_STATIC_DRAW) will use VIDEO memory as the source for
buffer object operations.
```
Start the game, check the log file for the notifications above. May only occur on certain systems. I use a Geforce on a Linux system with Nvidia drivers.

Reduce the log level for opengl notifications.

---

engine/src/main/java/org/terasology/rendering/dag/DirectionalLightsNode.java

As title says, quick fix for the bug which was introduced in c301a69f4676f4a469c56ee126f0ff9966624b30. 
Probably fixes #2392.
Load the game and try to resize the window.
_Side note: Sorry for this tiny bug, human errors 😞  Hopefully not caused any fatalities, hoping it was just a little frustration to fellow gamers._

Quick fix for the visual artifact caused by DirectionalLightsNode

---

engine/src/main/java/org/terasology/logic/characters/CharacterMovementComponent.java
engine/src/main/java/org/terasology/logic/characters/KinematicCharacterMover.java

Fixes issue where if there are multiple entities with KinematicCharacterMovers in the world, a character could potentially jump infinitely.
Spawn into a world. Spawn Gooey from the Gooey's Quests modules. Attempt to multi-jump. If it fails, the test is successful.
Thanks to @Cervator for catching this issue.

Fix to infinite multijumping if there are multiple characters

---

engine/src/main/java/org/terasology/rendering/dag/AmbientOcclusionPassesNode.java
engine/src/main/java/org/terasology/rendering/dag/BackdropNode.java
engine/src/main/java/org/terasology/rendering/dag/BloomPassesNode.java
engine/src/main/java/org/terasology/rendering/dag/BlurPassesNode.java
engine/src/main/java/org/terasology/rendering/dag/ChunksAlphaRejectNode.java
engine/src/main/java/org/terasology/rendering/dag/ChunksOpaqueNode.java
engine/src/main/java/org/terasology/rendering/dag/ChunksRefractiveReflectiveNode.java
engine/src/main/java/org/terasology/rendering/dag/DirectionalLightsNode.java
engine/src/main/java/org/terasology/rendering/dag/DownSampleSceneAndUpdateExposureNode.java
engine/src/main/java/org/terasology/rendering/dag/FinalPostProcessingNode.java
engine/src/main/java/org/terasology/rendering/dag/FirstPersonViewNode.java
engine/src/main/java/org/terasology/rendering/dag/InitialPostProcessingNode.java
engine/src/main/java/org/terasology/rendering/dag/LightGeometryNode.java
engine/src/main/java/org/terasology/rendering/dag/LightShaftsNode.java
engine/src/main/java/org/terasology/rendering/dag/ObjectsOpaqueNode.java
engine/src/main/java/org/terasology/rendering/dag/OutlineNode.java
engine/src/main/java/org/terasology/rendering/dag/PrePostCompositeNode.java
engine/src/main/java/org/terasology/rendering/dag/ShadowMapNode.java
engine/src/main/java/org/terasology/rendering/dag/SimpleBlendMaterialsNode.java
engine/src/main/java/org/terasology/rendering/dag/SkyBandsNode.java
engine/src/main/java/org/terasology/rendering/dag/ToneMappedSceneNode.java
engine/src/main/java/org/terasology/rendering/dag/ToneMappingNode.java
engine/src/main/java/org/terasology/rendering/dag/WorldReflectionNode.java
engine/src/main/java/org/terasology/rendering/opengl/FrameBuffersManager.java
engine/src/main/java/org/terasology/rendering/opengl/OpenGLUtils.java
engine/src/main/java/org/terasology/rendering/opengl/PostProcessor.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersHdr.java
engine/src/main/java/org/terasology/rendering/world/WorldRendererImpl.java

Finally, the last nodes! 🎊 🎉 
Seven new nodes for DAG (Directed Acyclic Graph), wrapping tasks that are related with _Post-Processing_.
- BloomPassesNode
- BlurPassesNode
- DownSampleSceneAndUpdateExposureNode
- FinalPostProcessingNode
- InitialPostProcessingNode
- ToneMappedSceneNode
- LightShaftsNode
Check if there are any weirdness related to rendering of post-processing effects like bloom, blur, tone mapping (HDR), light shafts and so on.

[RFM] Post-Processing Nodes for DAG

---

engine/src/main/java/org/terasology/rendering/opengl/LwjglFrameBufferObject.java

Setting the background to full alpha for FBOs is not necessary. This avoids state changes is also less code. 
Can be tested with [MiniMap](https://github.com/Terasology/Minimap).

Support transparent FBOs

---

engine/src/main/java/org/terasology/engine/modes/loadProcesses/JoinServer.java
engine/src/main/java/org/terasology/network/internal/ClientConnectionHandler.java
engine/src/main/java/org/terasology/network/internal/NetworkSystemImpl.java

In #2230, @Cervator requested several things. This PR is meant to address that issue.
- I tested #1626 in many different ways on the local host and was unable to reproduce the error. I'm not sure if it was fixed since, or if it only affects WAN downloads.
- When I went into the relevant sources I found that some information about the module downloads (the version, name, and size) was being sent to the loading screen. Maybe somebody got to this before me?
- I did, however, add a similar statement to the log.
- I also added the count of how many modules remain to the output string that is sent to the loading screen while a module is being downloaded.
- Finally, and most significantly, I added a time out to the server info & module download process. If no packets are received from the server …

Handle situations where the server misbehaves better

---

engine-tests/src/main/java/org/terasology/TerasologyTestingEnvironment.java
engine-tests/src/test/java/org/terasology/logic/delay/ArbritaryDelayActionComponent.java
engine-tests/src/test/java/org/terasology/logic/delay/DelayedActionSystemTest.java
engine/src/main/java/org/terasology/logic/delay/DelayedActionSystem.java

Minor yet important alteration to how the delayedActionComponent and PeriodicActionComponent are checked in the addDelayedAction and addPeriodicAction methods. 
In short, even if the old earliest operation wakeup time of the "...OperationsSortedByTime" is not less than the new earliest operation wakeup time, the new action should still be added to delayedOperationsSortedByTime/periodicOperationsSortedByTime. This will allow the event to be fired off when it's duration expires.
Call addDelayedAction with various delay values, and see if the approraite events are sent out at the correct time.

Major change to DelayedActionSystem.

---

engine-tests/src/test/java/org/terasology/rendering/nui/widgets/treeView/GenericTreeTest.java
engine-tests/src/test/java/org/terasology/rendering/nui/widgets/treeView/JsonTreeConverterTest.java
engine/src/main/java/org/terasology/rendering/nui/contextMenu/ContextMenuBuilder.java
engine/src/main/java/org/terasology/rendering/nui/contextMenu/ContextMenuScreen.java
engine/src/main/java/org/terasology/rendering/nui/editor/NUIEditorScreen.java
engine/src/main/java/org/terasology/rendering/nui/editor/WidgetSelectionScreen.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/TreeViewTestScreen.java
engine/src/main/java/org/terasology/rendering/nui/widgets/UIList.java
engine/src/main/java/org/terasology/rendering/nui/widgets/UITextEntry.java
engine/src/main/java/org/terasology/rendering/nui/widgets/UITreeView.java
engine/src/main/java/org/terasology/rendering/nui/widgets/treeView/GenericTree.java
engine/src/main/java/org/terasology/rendering/nui/widgets/treeView/JsonTree.java
engine/src/main/java/org/terasology/rendering/nui/widgets/treeView/JsonTreeConverter.java
engine/src/main/java/org/terasology/rendering/nui/widgets/treeView/JsonTreeNode.java
engine/src/main/java/org/terasology/rendering/nui/widgets/treeView/JsonTreeValue.java
engine/src/main/java/org/terasology/rendering/nui/widgets/treeView/Tree.java
engine/src/main/java/org/terasology/rendering/nui/widgets/treeView/TreeKeyEventListener.java
engine/src/main/java/org/terasology/rendering/nui/widgets/treeView/TreeModel.java
engine/src/main/java/org/terasology/rendering/nui/widgets/treeView/TreeMouseClickListener.java
engine/src/main/java/org/terasology/rendering/nui/widgets/treeView/TreeViewState.java
engine/src/main/java/org/terasology/world/viewer/color/ColorModels.java
engine/src/main/resources/assets/skins/default.skin

An implementation for rzats/gsoc-nui-editor#6.
- An option is added to replace a `UITreeView`'s node with an arbitrary widget that will be rendered in place of the node.
- It is used within `NUIEditorScreen` to replace a selected node with an inline `UITextEntry` editor using custom `Formatter`/`Parser` overrides to convert a `JsonTreeNode` to a JSON string and vice versa.
Right-click on a NUI editor node, select "Edit", make some changes!

Initial inline editor implementation

---

engine/src/main/java/org/terasology/logic/characters/CharacterImpulseEvent.java
engine/src/main/java/org/terasology/logic/characters/CharacterStateEvent.java
engine/src/main/java/org/terasology/logic/characters/ServerCharacterPredictionSystem.java
engine/src/main/java/org/terasology/logic/debug/MovementDebugCommands.java

This PR adds a new `CharacterImpulseEvent` to change the player's movement. 
It allows to apply a forced movement, e.g., to push the player back or give a thrust forward. This does not require additional movement, in contrast to the boosted stats for running or jumping.
I'd like to have some feedback on this :) There are some outstanding positions I want to address before merging. 
I tried to give the player a "hard hit", throwing him backwards a bit (i.e., up a little and to the back). However, the only effect I could notice was the force backwards. Vertical velocity seems to be only in affect when jumping. Probably this is related to the `MovementMode`.

[RFM] Added CharacterImpulseEvent

---

engine/src/main/java/org/terasology/rendering/nui/itemRendering/ToStringTextRenderer.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/videoSettings/CameraSetting.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/videoSettings/DynamicShadows.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/videoSettings/Preset.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/videoSettings/ScreenshotSize.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/videoSettings/VideoSettingsScreen.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/videoSettings/WaterReflection.java
engine/src/main/java/org/terasology/rendering/world/viewDistance/ViewDistance.java
engine/src/main/resources/default.cfg

Fixes #2207. The presets menu now is translated according to the keys in menu_XX.lang.
I looked at this issue, and it appeared that the asignee had gotten busy and forgotten about it. I hope I'm not stepping on any toes.
Before:
Go to Settings->Player and switch your language to "Deutsch (German)". Note that the first two entries remain "Custom" and "Minimal."
After:
Do the same thing. Note that the first two entries change to "Benutzerdefiniert" und "Einfach."

Made the graphics presets respect translation keys (requires user reset of config.cfg)

---

engine/src/main/java/org/terasology/config/RenderingConfig.java
engine/src/main/java/org/terasology/config/RenderingDebugConfig.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/videoSettings/ScreenshotSize.java
engine/src/main/java/org/terasology/utilities/subscribables/AbstractGeneralSubscribable.java
engine/src/main/java/org/terasology/utilities/subscribables/AbstractSpecificSubscribable.java
engine/src/main/java/org/terasology/utilities/subscribables/AbstractSubscribable.java
engine/src/main/java/org/terasology/utilities/subscribables/GeneralSubscribable.java
engine/src/main/java/org/terasology/utilities/subscribables/SpecificSubscribable.java
engine/src/main/java/org/terasology/utilities/subscribables/Subscribable.java

- Added a number of "Subscribable" interfaces and abstract classes, allowing implementations to be monitored for general changes, specific changes or both.
- RenderingConfig and RenderingDebugConfig are now extending AbstractSubscribable. Should they extend AbstractSpecificSubscribable instead?
- Bonus Feature: added 4K UHD resolution among the possible Screenshot sizes.
- Eliminated 3 warnings related to private enum constructors - the "private" keyword is redundant in those circumstances.
**EDIT**: It should be noted that while individual parameters are, with this PR, monitorable, they are not yet monitored. This will come as @tdgunes work on the rendering engine proceeds.

[Merge it! Merge it!] Rendering and the RenderingDebug configs now "subscribable", on a per-property basis.

---

engine/src/main/java/org/terasology/rendering/logic/MeshRenderer.java

Solves #2412.
As stated in the linked issue, I was looking for a way to always render an entity's mesh, given that the entity is always relevant. Therefore, I changed the render check to include the relevance of the entity.
With this change, an entity that holds `MeshComponent` and `LocationComponent` with `alwaysRelevant` being `false` is handled like before, i.e., the mesh is only renderd when the chunk around it is loaded. 
Setting `alwaysRelevant` to `true` will cause the mesh to be rendered at the given location, regardless whether the chunk around is loaded or not. 
Pinging @immortius @flo @msteiger @Josharias @emanuele3d for quick review.

Check entity relevance for rendering

---

config/gradle/utility.gradle
engine/build.gradle
engine/src/main/java/org/terasology/engine/TerasologyEngine.java
engine/src/main/java/org/terasology/engine/TerasologyEngineBuilder.java
engine/src/main/java/org/terasology/entitySystem/prefab/internal/PojoPrefabManager.java
engine/src/main/java/org/terasology/logic/console/suggesters/ScreenSuggester.java
engine/src/main/java/org/terasology/rendering/animation/Rect2fAnimator.java
engine/src/main/java/org/terasology/rendering/animation/Rect2iAnimator.java
engine/src/main/java/org/terasology/rendering/animation/TimeModifiers.java
engine/src/main/java/org/terasology/rendering/logic/FloatingTextRenderer.java
engine/src/main/java/org/terasology/rendering/logic/RegionOutlineRenderer.java
engine/src/main/java/org/terasology/rendering/nui/layers/ingame/metrics/DebugMetricsSystem.java
engine/src/main/java/org/terasology/rendering/nui/layouts/CardLayout.java
engine/src/main/java/org/terasology/rendering/nui/widgets/browser/data/html/basic/DefaultHTMLDocumentBuilder.java
engine/src/main/java/org/terasology/rendering/nui/widgets/browser/data/html/basic/ParagraphBuilder.java
engine/src/main/java/org/terasology/rendering/nui/widgets/models/Tree.java
engine/src/main/java/org/terasology/rendering/nui/widgets/models/TreeModel.java
engine/src/main/java/org/terasology/rendering/world/WorldRendererImpl.java
engine/src/main/java/org/terasology/utilities/Assets.java
engine/src/main/java/org/terasology/world/block/internal/BlockManagerImpl.java
engine/src/main/java/org/terasology/world/block/loader/BlockFamilyDefinitionData.java
facades/PC/build.gradle
libs/subprojects.gradle

Okay I'm officially on vacation/sabbatical woohoo! First stage is *only* till mid-July, but hoping by then to have another couple months lined up :-)
Dug into the idea of having the CrashReporter embedded in a Terasology workspace as a library entry (same approach could be applied to other stuff like Gestalt) and got it working after a bit, sure has been a while but I missed it!
This was in part for @mtjvankuik to make it easier to make changes to the CR then immediately test them via Terasology. Reference: #1120 + https://github.com/MovingBlocks/CrashReporter/issues/29
Pinging @msteiger and @rzats for some review as well, especially for how this might handle in Eclipse rather than IntelliJ. I believe you can already link to the CR in a big Eclipse workspace, but it takes some setup, …

Move the CrashReporter to the PC facade and make it possible to embed it into a Terasology workspace

---

engine/src/main/java/org/terasology/rendering/dag/nodes/ShadowMapNode.java
engine/src/main/java/org/terasology/rendering/dag/nodes/WorldReflectionNode.java
engine/src/main/java/org/terasology/rendering/dag/stateChanges/BindFBO.java
engine/src/main/java/org/terasology/rendering/dag/stateChanges/SetViewportSizeOf.java
engine/src/main/java/org/terasology/rendering/dag/stateChanges/SetWireframe.java
engine/src/main/java/org/terasology/rendering/dag/tasks/SetViewportSizeOfTask.java
engine/src/main/java/org/terasology/rendering/world/WorldRendererImpl.java

As title mentions, adds a state change for [_All obvious State Changes implemented_](https://github.com/tdgunes/Terasology/issues/10)
Check the log for any difference with given one below and any weirdness on shadow mapping and reflections. (Testing window resizing would be great!)
```
19:15:32.747 [main] INFO  o.t.r.dag.RenderTaskListGenerator - -- Task List --
19:15:32.748 [main] INFO  o.t.r.dag.RenderTaskListGenerator - SetViewportSizeOfTask: sceneShadowMap(1024x1024)
19:15:32.748 [main] INFO  o.t.r.dag.RenderTaskListGenerator -           BindFBOTask: sceneShadowMap(26)
19:15:32.748 [main] INFO  o.t.r.dag.RenderTaskListGenerator - NodeTask: ShadowMapNode
19:15:32.748 [main] INFO  o.t.r.dag.RenderTaskListGenerator - SetViewportSizeOfTask: sceneReflected(576x360)
19:15:32.748 [main] INFO …
```

[RFR] Adds SetViewportSizeOf StateChange 

---

engine/src/main/java/org/terasology/config/RenderingDebugConfig.java
engine/src/main/java/org/terasology/rendering/dag/AbstractNode.java
engine/src/main/java/org/terasology/rendering/dag/Node.java
engine/src/main/java/org/terasology/rendering/dag/RenderTaskListGenerator.java
engine/src/main/java/org/terasology/rendering/dag/WireframeCapableNode.java
engine/src/main/java/org/terasology/rendering/dag/WireframeNode.java
engine/src/main/java/org/terasology/rendering/dag/nodes/BackdropNode.java
engine/src/main/java/org/terasology/rendering/dag/nodes/ChunksAlphaRejectNode.java
engine/src/main/java/org/terasology/rendering/dag/nodes/ChunksOpaqueNode.java
engine/src/main/java/org/terasology/rendering/dag/nodes/FirstPersonViewNode.java
engine/src/main/java/org/terasology/rendering/dag/nodes/ObjectsOpaqueNode.java
engine/src/main/java/org/terasology/rendering/dag/nodes/OverlaysNode.java
engine/src/main/java/org/terasology/rendering/dag/nodes/ShadowMapNode.java
engine/src/main/java/org/terasology/rendering/dag/nodes/SkyBandsNode.java
engine/src/main/java/org/terasology/rendering/dag/nodes/WorldReflectionNode.java
engine/src/main/java/org/terasology/rendering/dag/stateChanges/BindFBO.java
engine/src/main/java/org/terasology/rendering/dag/stateChanges/SetViewportSizeOf.java
engine/src/main/java/org/terasology/rendering/dag/stateChanges/SetWireframe.java
engine/src/main/java/org/terasology/rendering/dag/tasks/SetViewportSizeOfTask.java
engine/src/main/java/org/terasology/rendering/world/WorldRendererImpl.java

As title mentions, finalizes a Wireframe state change for [_All obvious State Changes implemented_](https://github.com/tdgunes/Terasology/issues/10)
By checking the log and observing wireframe debug mode. 
FYI:  _Debug mode is toggled by F3 key and wireframe with F9._
An example screenshot when wireframe is enabled:
Eliminations must be seen in the log:
This PR also includes setViewportSizeOf PR. Please just focus on last commit.

[RFR] Finalize SetWireframe StateChange

---

engine/src/main/java/org/terasology/rendering/nui/contextMenu/ContextMenuScreen.java
engine/src/main/java/org/terasology/rendering/nui/editor/NUIEditorContextMenuBuilder.java
engine/src/main/java/org/terasology/rendering/nui/editor/NUIEditorScreen.java
engine/src/main/java/org/terasology/rendering/nui/widgets/UITreeView.java
engine/src/main/java/org/terasology/rendering/nui/widgets/treeView/JsonTree.java
engine/src/main/java/org/terasology/rendering/nui/widgets/treeView/JsonTreeValue.java
engine/src/main/java/org/terasology/rendering/nui/widgets/treeView/TreeModel.java

Some additional minor fixes to the features introduced in #2415: 
- Boolean attributes now default to their inverse value when added.
- Fixed an issue with `NUIEditorItemRenderer` not properly displaying identical node values.
- Fixed an issue with `ContextMenuScreen` being drawn out of bounds for items below the screen.
Verify that the fixes work as intended and no other usability bugs remain.

[RFR] Misc. NUI editor fixes

---

engine/src/main/java/org/terasology/rendering/dag/StateChange.java
engine/src/main/java/org/terasology/rendering/dag/nodes/ShadowMapNode.java
engine/src/main/java/org/terasology/rendering/dag/nodes/SimpleBlendMaterialsNode.java
engine/src/main/java/org/terasology/rendering/dag/nodes/WorldReflectionNode.java
engine/src/main/java/org/terasology/rendering/dag/stateChanges/BindFBO.java
engine/src/main/java/org/terasology/rendering/dag/stateChanges/SetViewportSizeOf.java
engine/src/main/java/org/terasology/rendering/dag/stateChanges/SetWireframe.java
engine/src/main/java/org/terasology/rendering/dag/tasks/SetViewportSizeOfTask.java
engine/src/main/java/org/terasology/rendering/world/WorldRendererImpl.java

As title mentions, adds some necessary refactors according to given feedback on #2419 for [_All obvious State Changes implemented_](https://github.com/tdgunes/Terasology/issues/10)
Check any weirdness on rendering, especially during the startup.

[RFR] A Minor Refactor in StateChanges

---

engine/src/main/java/org/terasology/rendering/shader/ShaderParametersBase.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersBlock.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersChunk.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersCombine.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersDebug.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersDefault.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersHdr.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersLightGeometryPass.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersLightShaft.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersOcDistortion.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersPost.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersPrePost.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersSSAO.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersSky.java
engine/src/main/java/org/terasology/rendering/shader/ShaderParametersSobel.java

The code of ShaderParameter implementations will have to find its way into GLSLMaterial implementations or within the rendering engine's Node implementations. As the ShaderParameter implementations become empty, they will be removed.
This PR:
- provides no functional changes
- adds a large number of TODOs for future work
- in ShaderParametersChunk small code changes have been made to obtain the renderingConfig only once, add some empty lines and move a program.setFloat4 line to remove an otherwise unnecessary IF block.
I've ignored a large number of pre-existing CheckStyle warnings. We will deal with them as we move the ShaderParameter code into materials and nodes.

[RFR] Added TODOs for future work on ShaderParameter classes

---

modules/Core/assets/blocks/templates/leaf.block
modules/Core/assets/prefabs/damageTypes/shovelDamage.prefab
modules/Core/assets/prefabs/damageTypes/shovelTier2Damage.prefab
modules/Core/assets/prefabs/damageTypes/shovelTier3Damage.prefab

Changed the leaf block template to add two default categories ("wood" and "leaf") to it. Also altered the shovel damage prefabs so that shovels can now damage leaves. Thus, leaves can now be broken using fists, axes, or shovels.
Create a new world, and try destroying the leaves off of trees using unarmed combat, axes, and shovels.
@Cervator for finding this bug in the first place.

Added categories to leaf block template to make it breakable

---

docs/Playing.md
engine/src/main/java/org/terasology/config/Config.java
facades/PC/src/main/java/org/terasology/engine/Terasology.java

See [this post](http://forum.terasology.org/threads/multiplayer-server-management.1583/#post-13835) for a detailed description.
In short, it adds a run parameter `-overrideDefaultConfig=` to the PC facade.
The override config goes between the default config and the user config and gives the option to predefine settings for a headless server.
Create a file `override.cfg` with the following content:
```
{
"defaultModSelection": {
"modules": [
"MyModule"
],
"defaultGameplayModuleName": "MyModule"
},
"worldGeneration": {
"worldTitle": "World Title",
"defaultSeed": "custom seed for the server",
"defaultGenerator": "MyModule:MyWorldgen"
},
"moduleConfigs": {},
"network": {
"servers": [
{
"name": "localhost",
"address": "localhost",
"port": 25777,
"active": true
}
],
"upstreamBandwidth": 1024, …
```

Override config

---

engine/src/main/java/org/terasology/config/NUIEditorConfig.java
engine/src/main/java/org/terasology/rendering/nui/editor/layers/AbstractEditorScreen.java
engine/src/main/java/org/terasology/rendering/nui/editor/layers/NUIEditorScreen.java
engine/src/main/java/org/terasology/rendering/nui/editor/layers/NUIEditorSettingsScreen.java
engine/src/main/java/org/terasology/rendering/nui/editor/layers/NUISkinEditorScreen.java
engine/src/main/java/org/terasology/rendering/nui/editor/utils/NUIEditorNodeUtils.java
engine/src/main/resources/assets/i18n/menu.lang
engine/src/main/resources/assets/i18n/menu_cs.lang
engine/src/main/resources/assets/i18n/menu_de.lang
engine/src/main/resources/assets/i18n/menu_en.lang
engine/src/main/resources/assets/i18n/menu_es.lang
engine/src/main/resources/assets/i18n/menu_fr.lang
engine/src/main/resources/assets/i18n/menu_gl.lang
engine/src/main/resources/assets/i18n/menu_it.lang
engine/src/main/resources/assets/i18n/menu_ja.lang
engine/src/main/resources/assets/i18n/menu_pl.lang
engine/src/main/resources/assets/i18n/menu_pt.lang
engine/src/main/resources/assets/i18n/menu_ro.lang
engine/src/main/resources/assets/i18n/menu_ru.lang
engine/src/main/resources/assets/i18n/menu_sv.lang
engine/src/main/resources/assets/i18n/menu_uk.lang
engine/src/main/resources/assets/ui/editor/nuiEditorSettingsScreen.ui

Implements autosaving for the NUI editor, as per https://github.com/MovingBlocks/Terasology/pull/2438#issuecomment-241214770.
Open the NUI (skin/screen) editor, edit, Alt+F4 without saving changes, restart the game and open the same editor again.

NUI editor autosave

---

engine-tests/src/main/java/org/terasology/testUtil/WorldProviderCoreStub.java
engine/src/main/java/org/terasology/world/block/entity/placement/BlockPlacingSystem.java
engine/src/main/java/org/terasology/world/internal/AbstractWorldProviderDecorator.java
engine/src/main/java/org/terasology/world/internal/WorldProviderCore.java
engine/src/main/java/org/terasology/world/internal/WorldProviderCoreImpl.java

- added `setBlocks(Map<Vec3i, Block>)` to WorldProviderCore
- chunks are dirtied after all blocks are placed
- finally notifications for each changed block are send
- adjusted BlockPlacingSystem to take advantage of `setBlocks`
- - -
I tested this with structure templates (generating a PlaceBlocks event from the regions to fill) and the BlockBufferSystem of DynamicCities. I did not notice any crashes, and the overall time of placing blocks is reduced as each affected chunk is only re-calculated once after all blocks are set.
Does anybody see a problem in this implementation. Anything I forgot to take care of? I was wondering if the implemenation should make sure that the map is not too big (either restrict by API/contract or paritioning the blocksToPlace and run several iterations). Would …

[Review/Discussion] Set multiple blocks at once using WorldProvider

---

engine/src/main/java/org/terasology/world/internal/WorldProviderCoreImpl.java
modules/Core/assets/ui/ingame/benchmarkScreen.ui
modules/Core/src/main/java/org/terasology/core/debug/BenchmarkScreen.java

This pull request adds a screen that can be used to select and start a benchmark.
Currently the screen contains 2 benchmarks: 
1. A benchmark for the WorldProvider method setBlock 
2. A benchmark for the new WorldProvider method setBlocks (Recently added via #2453 )
Run the following command on the command line: `showScreen benchmarkScreen`
The window shows up. You can select a bench mark and start it. It will do 200 iterations and then stop automatically. The results can by selecting the text and then pressing ctrl+c.

Add a screen for doing benchmarks

---

engine-tests/src/test/java/org/terasology/rendering/nui/editor/ContextMenuUtilsTest.java
engine/src/main/java/org/terasology/rendering/nui/editor/layers/NUIEditorScreen.java
engine/src/main/java/org/terasology/rendering/nui/editor/layers/NUISkinEditorScreen.java
engine/src/main/java/org/terasology/rendering/nui/editor/utils/NUIEditorMenuTreeBuilder.java
engine/src/main/java/org/terasology/rendering/nui/editor/utils/NUIEditorNodeUtils.java

Two small NUI editor tweaks based on Slack feedback and personal usage.
- Attributes without a value are no longer automatically edited as they are added.
- A `layoutInfo` node can now be added to nodes located inside a layout.
- Create a new screen in the NUI editor. Try adding a few attributes to the `layoutInfo` node (e.g. `position-left`) and verify that they aren't automatically edited.
- Delete the `layoutInfo` node. Verify that it can be added again.

Do not edit attributes with no value; option to add layoutInfo

---

docs/Modules.md

Normally I just slip new modules straight into `develop` from time to time when we get them, but this batch is huge and a bit unusual so I thought I'd PR them for discussion. There are also some I'm not sure we should add yet.
These are the ones I think we should add for sure and I just tested all of them:
* Dialogs - involved with both unreleased L&S work and the new dynamic cities tutorial. Might not be perfect yet (I can only sporadically get the dialogs to work in the city tutorial) but it has been outside the lineup long enough - it actually went out of date vs. the engine and I didn't notice since it wasn't in my mega-workspace (107 modules and counting!). You okay with that @msteiger?
* MedievalCities - new by @skaldarnar and makes awesome cities!
* Potions - fixed up by …

Add a bunch of modules to the lineup + bump libraries

---

engine/src/main/java/org/terasology/rendering/world/ChunkMeshUpdateManager.java
engine/src/main/java/org/terasology/world/ChunkView.java
engine/src/main/java/org/terasology/world/chunks/CoreChunk.java
engine/src/main/java/org/terasology/world/chunks/internal/ChunkImpl.java
engine/src/main/java/org/terasology/world/chunks/localChunkProvider/LocalChunkProvider.java
engine/src/main/java/org/terasology/world/internal/ChunkViewCoreImpl.java
engine/src/main/java/org/terasology/world/internal/WorldProviderCoreImpl.java
engine/src/main/java/org/terasology/world/propagation/light/LightMerger.java

A performance optimization, archived by removing uncessary locking.
In my test this made the setBlocks method of WorldProvider more than twice
as fast.
The locking used to be done mainly by the main thread. Besides the main thread the light merging thread and the chunk mesh building thread were also locking. One reason why it probably got locked was the disposal of the chunk. When a chunk was no logner needed, it got made unusable which could have potentially be a problem for the background threads that were still using it. This patch makes the chunk remain readable even when the chunk is no longer needed. For the garbage collector it makes no difference and we can that way dispose chunks without having to let the main thread wait for background threads which were still reading the …

Improve performance by removing unnecessary locking.

---

engine/src/main/java/org/terasology/math/ChunkMath.java
engine/src/main/java/org/terasology/world/internal/ChunkViewCoreImpl.java
engine/src/main/java/org/terasology/world/internal/WorldProviderCoreImpl.java

Some low-hanging optimization fruit for anything that calls `getBlock` in a tight loop (pathfinders or anything that analyzes the map).
Call `getBlock` a lot and look at a profiler :)
The most obvious change is in allocations per second. I measured 2Ma/s before the patch, about 250Ka/s after. Also notice that GC stalls are much less frequent and that Eden heap space fills much less quickly :)
I wouldn't normally worry about object allocations but obviously the numbers are huge. After this change, `getBlock` can use CPU registers all the way until it indexes the massive data array behind it. Without it, we have to stop, find some space on the heap, create some object metadata, copy the values to far-away memory, recurse, unwrap the object (again going to far-away heap memory) and then …

remove temporary Vector3i allocations in getBlock

---

engine/src/main/java/org/terasology/persistence/typeHandling/mathTypes/BorderTypeHandler.java
engine/src/main/java/org/terasology/persistence/typeHandling/mathTypes/Rect2fTypeHandler.java
engine/src/main/java/org/terasology/persistence/typeHandling/mathTypes/Rect2iTypeHandler.java
engine/src/main/java/org/terasology/persistence/typeHandling/mathTypes/Region3iTypeHandler.java

* Fixes a remote client only NullPoinerException crash that happens when you clear a "wrong placement hint" of a structure template. The crash was caused by wrong deserialization of a `Region3i` field that got set to null.
* Fixes further potential crashes caused by the deserialization of `Rect2f`, `Rect2i` and `BorderTypeHandler` fields.
1. Start a server with the Gooey's Quests module enabled
2. Connect to the server as client
3. Get yourself a structure template with placement conditions. e.g. via the command `giveItem dungeonEntranceViaMountain`.
4. Try to place it at an invalid location (where the placement preview shows a red region)
5. You should see an error message dialog. Confirm the dialog
6. A red region should still be visible. Right click once to clear it. There should be no …

Fix null field deserialization crash + further possible crashes

---

config/eclipse/formatting.xml

I updated some values in the formatter to match the latest checkstyle in my changes.
This is the exported version of the formatter (line order got messed up a lot) from eclipse neon.
Not sure if this breaks older eclipse installations though :)

update eclipse formatter

---

docs/Credits.md
engine/src/main/resources/assets/textures/ui/icons/editor/LICENSE_NOTES
engine/src/main/resources/assets/textures/ui/treeView/LICENSE_NOTES

* A hint addition to the LICENSE file to make it clear that some assets are under a creative commons license. 
* A more specific explanation which files are under that creative commons license.
** Some of the files @rzats added were under that license, I listed those files more explicitly so that we later know what files exactly are under that license.
** Some of the icons were made by me, I added now explictly that those are also under the same create commons license like the other icons.
5"
@rzats please review the icon list if I got it correctly.

Make it more clear that there are assets are under a creative commons license

---

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/videoSettings/VideoSettingsScreen.java

Fix for #2489: The ESC key now does exactly what the "back" button does i.e recompiles shaders etc.
- Enter Setting -> Video, (either in-game or from outside)
- Hit ESC
- Check the logger
It should now show something like `VideoSettingsScreen - Video Settings: {"pixelFormat":24,"wind...`, which would earlier only arise after the back button was clicked.

Fixes #2489 - ESC now recompiles shaders while exiting video settings

---

config/gradle/ide.gradle
facades/PC/launchScripts/run_linux.sh
facades/PC/launchScripts/run_macosx.command
facades/PC/launchScriptsSrc/LauncherTeraEd.xml

This *mostly* addresses #2424.  The Windows launchers still need to be updated but I don't have a Windows machine to develop on.
Run any of the launch configs in IntelliJ, I had to re-run 'gradlew idea' for it to show the updated parameters in the configuration window.
The IntelliJ, OSX, Linux and TeraEd launchers were updated.  The Windows
binaries were not. Re-run 'gradlew idea' to have the updated configs applied in
IntelliJ.

Bumped -Xmx from 1024m to 1536m in launch configs

---

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/CreateGameScreen.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/SelectModulesScreen.java

Fixes #2342
- Open Singleplayer -> Create
- Check "Choose World Generator" list. (Should contain atleast "Builder Sample World")
- Go to Modules, enter "Filter" text as gibberish.
- Hit ESC or Back button
- Check "Choose World Generator" list.
- Filter text gibberish no longer impacts World Generator list. (Was earlier being generated from filtered module list. Now being generated from all modules list.)
- Note: Deactivating activated modules also works now. As compared to @kartikey0303's fix

Fixes #2342 Module Filters impacting WorldGen list

---

engine/src/main/java/org/terasology/engine/subsystem/lwjgl/LwjglGraphics.java
engine/src/main/java/org/terasology/rendering/backdrop/BackdropProvider.java
engine/src/main/java/org/terasology/rendering/backdrop/Skysphere.java
engine/src/main/java/org/terasology/rendering/dag/AbstractNode.java
engine/src/main/java/org/terasology/rendering/dag/ConditionDependentNode.java
engine/src/main/java/org/terasology/rendering/dag/Node.java
engine/src/main/java/org/terasology/rendering/dag/NodeFactory.java
engine/src/main/java/org/terasology/rendering/dag/nodes/BackdropNode.java
engine/src/main/java/org/terasology/rendering/dag/nodes/BackdropReflectionNode.java
engine/src/main/java/org/terasology/rendering/dag/nodes/BufferClearingNode.java
engine/src/main/java/org/terasology/rendering/dag/nodes/ShadowMapNode.java
engine/src/main/java/org/terasology/rendering/dag/nodes/WorldReflectionNode.java
engine/src/main/java/org/terasology/rendering/dag/tasks/DisableMaterialTask.java
engine/src/main/java/org/terasology/rendering/opengl/fbms/ShadowMapResolutionDependentFBOs.java
engine/src/main/java/org/terasology/rendering/world/WorldRendererImpl.java

**[EDIT] the latest commit fixes the bug and makes this PR, further feedback notwithstanding, ready for merge.**
* Refactored ShadowMapNode to fully take advantage of the new architecture
* Refactored WorldReflectionNode by extracting a new BackdropReflectionNode class from it, both taking advantage of the new architecture.
* [EDIT] Refactored BackdropNode to partially take advantage of the new architecture.
* Added and using a new BufferClearingNode class
* Added a new NodeFactory.createInstance(Class<T>, Object) method to allow passing initial data to the new Node.initialise(Object) method.
* [EDIT] <s>Changed FBOConfig class to hold information about the fbo manager to be associated with a given FBO.</s> - removed: will be reintroduced in a separate PR. 
* Start Terasology
* …

Rendering engine: refactored 2 nodes + new node type

---

engine/src/main/java/org/terasology/world/block/loader/AutoBlockProvider.java

Fixes #1988 
- Start a game
- Console command `giveBlock companion` (or any other auto block like dirt [BuilderSampleGameplay:Dirt] etc) should now give you the block! :smile:
- with ` forEach(tile -> result.add(tile.getUrn().getResourceName()));` the result was "**companion**". However when this was passed back to the giveBlock method inside `BlockCommands.java` (Refer: [this](https://github.com/MovingBlocks/Terasology/blob/3252f9ec05241ac370430abdf2118b771a6d590e/engine/src/main/java/org/terasology/world/block/entity/BlockCommands.java#L277)), the matchingUris set from `Set<ResourceUrn> matchingUris = Assets.resolveAssetUri(uri, BlockFamilyDefinition.class);` now contained "Companion:companion". As pointed out by @Waterpicker.
- with ` forEach(tile -> …

Fixed #1988 auto blocks in-game console

---

engine/src/main/java/org/terasology/world/block/entity/BlockCommands.java

Extended fix for #2518 
Try `bulkGiveBlock grass 10 sphere` with and without applying this patch
giveBlock now returns string instead of throwing a new exception. So if in a list of 10 blocks that contain "grass" in their name, one in the middle not having a sphere shape available will not prevent the player from getting the rest.
The red text on console looked good though :stuck_out_tongue:, won't get that any more.

giveBlock return instead of exception

---

engine/src/main/java/org/terasology/rendering/nui/widgets/UIList.java

Fixes #2508 
Start the game
Create a new game
Click Modules
Once the module list loads completely, scroll to the bottom.  There should no longer be excess space.
This was a regression introduced by 8c07c4e14.  The list items were rendering
without the correct margins but the margins were still being included when
calculating the size of the scrollable area, resulting in excess space at the
end of the list.

Fixes issue #2508, excess scrolling in module list

---

engine/src/main/java/org/terasology/physics/engine/PhysicsSystem.java
engine/src/main/java/org/terasology/physics/events/ImpactEvent.java

Contains:
This PR fixes #2139 by making any item that hits the ground (hard enough to register) send an event that is then caught, processed and gives the item a set speed upwards which prevents it from tunneling. 
By doing so, I've seen improvements in framerate when using the railgun and had the comical effect of some blocks bouncing around before they settle. 
This also puts the building blocks down for creating the StickySystem for #1443 and _could_ help with #1697
How to test:
Throw any item from any height onto any piece of land. They will most likely not go through them.
Possible improvements I need feedback on:

#2139 Added item impact events when hitting world

---

engine/src/main/java/org/terasology/config/BindsConfig.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/inputSettings/ChangeBindingPopup.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/inputSettings/ConfirmChangePopup.java
engine/src/main/resources/assets/ui/confirmChangePopup.ui

Added a fix for issue #2552 where if a key has already been mapped to another action, a popup is raised which asks the user to confirm the change. It opens a popup instead of flashing a red error message because I think that will look slightly out of style. 
To test - 
- Open the Input section in the Settings screen.
- Click on button to map.
- Choose a key that has already been assigned for another task. (Say S when you're rebinding W)
- Select OK to continue with the rebinding or cancel to go back and reconsider.

Added popup if a key has already been assigned to another action.

---

engine/src/main/java/org/terasology/rendering/nui/widgets/UIList.java
modules/Core/src/main/java/org/terasology/rendering/nui/layers/ingame/inventory/ItemIcon.java

Fixes #2452 
Load up the game with the potions module
Give yourself a double jump potion
Place the item in the lower-right inventory slot
Mouse over the item, the tooltip should not flicker or "vibrate" even when the mouse is on top of it
This scenario can occur when a tooltip is unable to render in the preferred
location due to the screen boundaries, for instance if an item with a really
long tooltip is placed in the lower-right most inventory slot.  Because UILists
define InteractionRegions around their contents by default and tooltips are
rendered last, they are seen as the new top-most interactive element on the
following game tick.  This causes an immediate reset of the tooltip timer due
to the top-most region changing, and the process repeats.  This has been fixed
by preventing …

Fixes issue #2452, tooltips flicker when forced under the mouse

---

engine/src/main/java/org/terasology/logic/characters/CharacterSystem.java
engine/src/main/java/org/terasology/logic/characters/events/OnItemUseEvent.java
engine/src/main/java/org/terasology/logic/inventory/ItemComponent.java
engine/src/main/java/org/terasology/logic/players/LocalPlayerSystem.java

- A fix to let items use just a single cooldowntime property on the ItemComponent.
- A improvement to the cooldown system that enforces validation on both the client and server side to see if an action is attempted while still cooling down.
As an implication of getting setting this data also on the server side,  this data will also be sent to other remote clients so that they can show other characters doing an action.
- Use an item
- Attack with a weapon
- Attack with bare hand
- Press and hold attack to ensure no machine gun-ing happens

Fixes for item use cooldowns

---

.gitignore
build.gradle
config/gradle/ide.gradle
templates/gradle.properties
templates/override.cfg

This is a tiny developer convenience PR.
- Contains an `override.cfg` file under `/templates` that'll get copied to the project root on `gradlew idea` - an easy way to get a tiny config file prepared for a server run
- The existing `gradle.properties` under `/templates` will now also get copied to the project root automatically, allowing convenient access to a bunch of Gradle config (turns on the Gradle Daemon and some other stuff by default - which is becoming default in Gradle 3 anyway)
- The headless server run config in IntelliJ will now use the `override.cfg` mentioned above by default (if it isn't present the game falls back on default config - no crash)
- There is a 3rd game client run config in IntelliJ so you can easily run _three_ separate game clients (and a headless server!) …

Utility: Include a template override.cfg for use by default in headless launched via IntelliJ

---

engine/src/main/java/org/terasology/rendering/dag/AbstractNode.java

Fixes #2608. See commit description for some more notes.
- run Terasology
- load a game
- F3 for debug mode
- F9 for wireframe mode
- exit Terasology while in wireframe mode
- restart Terasology
- reload a Game: wireframe should still be active and no crash should occur.
By the way, perhaps it would be nice to apply a "BugFix" label to this PR. Unless we want to assume that a PR with a "Bug" label is a bugfix rather than a PR willingly introducing a bug. :smile:

# Fixes issue 2608

---

engine/src/main/java/org/terasology/rendering/dag/nodes/DeferredPointLightsNode.java
engine/src/main/java/org/terasology/rendering/dag/nodes/DirectionalLightsNode.java
engine/src/main/java/org/terasology/rendering/dag/nodes/LightGeometryNode.java
engine/src/main/java/org/terasology/rendering/dag/nodes/OverlaysNode.java
engine/src/main/java/org/terasology/rendering/dag/stateChanges/DisableDepthTest.java
engine/src/main/java/org/terasology/rendering/dag/stateChanges/EnableBlending.java
engine/src/main/java/org/terasology/rendering/dag/stateChanges/EnableFaceCulling.java
engine/src/main/java/org/terasology/rendering/dag/stateChanges/EnableStencilTest.java
engine/src/main/java/org/terasology/rendering/dag/stateChanges/SetBlendFunction.java
engine/src/main/java/org/terasology/rendering/dag/stateChanges/SetStateParameter.java
engine/src/main/java/org/terasology/rendering/dag/tasks/SetBlendFunctionTask.java
engine/src/main/java/org/terasology/rendering/world/WorldRendererImpl.java

- refactors the LightGeometryNode into DeferredPointLightsNode, to move it to the new architecture
- refactors DirectionalLightNode for further work by isolating it from the DeferredPoingLightsNode.
- added some method/class-level javadocs
- fixes problem in OverlaysNode  - see first commit description
- updates WorldRendererImpl to account for the work done, i.e. the newly named node.
- Run Terasology, 
- start a saved game
- make sure there is nothing unusual with the image shown on screen.

Continuing work on nodes:  DeferredPointLightsNode and a few other things

---

README.markdown

When attempting to run the directions in the README, I found that gradlew is a script in the repo, not a command that I should expect to find on my system, so I'm adding ./ to the doc to describe how to run it.
Clone the repo and follow the instructions in the README.

docs update: gradlew requires ./ to run

---

engine/src/main/java/org/terasology/engine/subsystem/headless/renderer/HeadlessWorldRenderer.java
engine/src/main/java/org/terasology/rendering/dag/nodes/ApplyDeferredLightingNode.java
engine/src/main/java/org/terasology/rendering/dag/nodes/DeferredMainLightNode.java
engine/src/main/java/org/terasology/rendering/dag/nodes/DeferredPointLightsNode.java
engine/src/main/java/org/terasology/rendering/dag/stateChanges/SetInputTexture.java
engine/src/main/java/org/terasology/rendering/dag/tasks/SetInputTextureTask.java
engine/src/main/java/org/terasology/rendering/opengl/FBO.java
engine/src/main/java/org/terasology/rendering/world/WorldRenderer.java
engine/src/main/java/org/terasology/rendering/world/WorldRendererImpl.java

- existing DirectionalLightsNode has been split in DeferredMainLightNode and ApplyDeferredLightingNode. Both nodes now almost fully take advantage of the new architecture. [1]
- DeferredMainLightNode work done in commits 2 and 3 (eea3f7c and dc3d9cb).
- ApplyDeferredLightingNode work done in commits 4 and 5 (c377647 and 62affd8).
- Added classes SetInputTexture (StateChange) and SetInputTextureTask. [2]
- removed renderLightComponent method from WorldRenderer and WorldRendererImpl.
- start Terasology
- create or load a game
- verify rendering of the 3d scene continues to work as expected
[1] _Almost_ fully because there are a few things that are not yet in StateChanges but should, for example the binding of default FBOs
[2] StateChange subclass SetInputTexture is a good start as it makes …

More work on Lighting Nodes

---

config/eclipse/formatting.xml
engine-tests/src/test/java/org/terasology/world/EntityAwareWorldProviderTest.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/CreateGameScreen.java
engine/src/main/resources/assets/ui/menu/createGameScreen.ui
engine/src/main/resources/default.cfg

Small fixes for various issues mentioned in IRC and elsewhere:
- Set the Eclipse (IDEA-compatible) code formatter to indent with 4 spaces, which is what our indentation is, instead of 8.
- Ignored the known failing unit tests (see #2625 and #2629) for now so that they don't potentially confuse GCI students.
- Removed the save game path from the Create Game screen, as it would otherwise break the interface on resolutions lower than 1366x768:
- Set the Film Grain setting to false in the default config - it's been widely reported as an annoyance.
Fairly self-explanatory:
- IDEA should use 4-space indentation when set to the Terasology formatter.
- No unit tests should fail.
- The Create Game screen should work fine on 1366x768.
- A new game install should have film grain off by default.
No …

Engine fixes: code formatter, unit tests, create game screen, config

---

engine/src/main/java/org/terasology/engine/LoggingContext.java

Simple fix for #2592 - Appends engine version and build number to log directory if they exist, separated by "_".
Tested working with `versionInfo.properties` and Crash Reporter.

Added engine version and build number to log directories

---

engine/src/main/java/org/terasology/input/binds/movement/AutoMoveButton.java
engine/src/main/java/org/terasology/input/binds/movement/package-info.java
engine/src/main/java/org/terasology/logic/players/LocalPlayerSystem.java
engine/src/main/resources/assets/i18n/menu_en.lang

A PR to address #2557 . I have added a binding to enable auto run. 
Open up a game and press R (default binding - can be changed from the inputs menu). Any other action will stop the auto run state. 
More like questions before merging - 
- I have made impulse events fire up every 200 milliseconds. Will this have a negative impact on the performance? If I increase the deltas, the movement looks more jerky than how it does if I keep it at 200ms. 
- I would like some feedback though because using this method makes the movement looks slightly sluggish.

Added auto move feature

---

engine-tests/src/main/java/org/terasology/Environment.java
engine-tests/src/main/java/org/terasology/HeadlessEnvironment.java
engine/src/main/java/org/terasology/engine/modes/loadProcesses/InitialiseRemoteWorld.java
engine/src/main/java/org/terasology/engine/modes/loadProcesses/InitialiseWorld.java
engine/src/main/java/org/terasology/rendering/backdrop/Skysphere.java

Remove dependency on CoreRegistry from Skysphere by passing in the CelestialSystem directly. 
I also added it to the HeadlessEnvironment, with a mock to WorldProvider, and a static WorldTime reference, so unit testing the day/night cycle in the future becomes possible
* Run all the unit tests and verify nothing got broken by this change.
* Open up the game, and create a world
* Open up the game, and load a world

Remove dependency on CoreRegistry from Skysphere

---

engine/src/main/java/org/terasology/config/PlayerConfig.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/EnterUsernamePopup.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/JoinGameScreen.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/SelectGameScreen.java
engine/src/main/resources/assets/i18n/menu.lang
engine/src/main/resources/assets/i18n/menu_en.lang
engine/src/main/resources/assets/ui/enterUsernamePopup.ui

New players now always get assigned a generic username (Player#####) when they first run the game instead of the system username. Seems the code for this already existed so all I did was remove the part about the system username 🙂 
When accessing the Host Game or Join Game Screen for the first time, users will be prompted to choose a non-default username. They will only be prompted once.
- Delete your config.cfg before loading up Terasology
- You will be assigned a generic username when the game first starts (you can check this in Player Settings)
- You will be prompted to change your username when you first access either the Join Game or Host Game screen
- 'Ok' sets the username, 'Cancel' does nothing
- You will not be prompted anymore after the first time.
None

Prompt new users to pick username

---

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/JoinGameScreen.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/ServerListDownloader.java

Closes #2698 with a very simple one line fix 🙂 
Just an issue with the text being untranslated. It does seem a bit unintuitive that the translation is done in JoinGameScreen.java instead of ServerListDownloader.java but I went with this since the TranslationSystem object cannot be instantiated in ServerListDownloader.
Open the Join Game screen. Verify that the translated text is shown.

Fixed issue with untranslated text

---

modules/Core/src/main/java/org/terasology/rendering/nui/layers/ingame/inventory/InventoryScreen.java

Currently, the inventory is opened via [`InventoryUIClientSystem`](https://github.com/MovingBlocks/Terasology/blob/develop/modules/Core/src/main/java/org/terasology/logic/inventory/InventoryUIClientSystem.java#L46) in `onToggleInventory`. For seemingly no reason it is closed in [`InventoryScreen`](https://github.com/MovingBlocks/Terasology/blob/develop/modules/Core/src/main/java/org/terasology/rendering/nui/layers/ingame/inventory/InventoryScreen.java#L46) in `onBindEvent`.
The closing section in `InventoryScreen` appears to be redundant as when `onBindEvent` is removed the inventory opens and closes as normal. I am aware that I might simply be missing something which explains the logic behind this.
Also, removing `onBindEvent` also allows for other screens to be opened and closed …

Change how the inventory is opened and closed

---

engine/src/main/java/org/terasology/rendering/nui/internal/NUIManagerInternal.java

This fixes the issue mentioned in [JoshariasSurvival/#15](https://github.com/Terasology/JoshariasSurvival/issues/15) as well as [Books/#1](https://github.com/Terasology/Books/issues/1) related to how sometimes 2 `E` clicks are required to open an interaction screen if you close it with `Esc`. This is something that affects all interaction screens.
The problem seems to lie with how `popScreen` (called when `Esc` is pressed) is implemented in `NUIManager` as opposed to `closeScreen`. `popScreen` doesn't send a `ScreenLayerClosedEvent` to the client, leading to the some parts of the client still thinking that the interaction screen is open.
- Open a chest, then close it with `Esc`
- The next E should open the chest again.
A somewhat related issue would be how interaction screens overlay the …

Fix NUIManager issues

---

engine/src/main/java/org/terasology/logic/delay/PeriodicActionComponent.java
engine/src/main/java/org/terasology/logic/players/LocalPlayerSystem.java

Short follow up to #2557.
The current implementation will cancel the periodic action each time **any** periodic action is triggered.
The PeriodicActionComponent is not null safe on removal (note the null -> long autoboxing), which causes periodic NPEs.
Enable any module that triggers periodic action, like the portals module (place one portal block in the world, then watch the log).

Fix auto move cancel action when not triggered

---

engine/src/main/java/org/terasology/logic/characters/interactions/InteractionSystem.java
engine/src/main/java/org/terasology/rendering/nui/NUIManager.java
engine/src/main/java/org/terasology/rendering/nui/internal/NUIManagerInternal.java

As mentioned in #2703, this closes all screens with `isLowerLayerVisible` set to true before showing any interaction screens.
Open the inventory and then open a chest. The inventory screen should close before the chest screen appears.

Close all screens on E click

---

engine-tests/src/test/java/org/terasology/rendering/dag/SetName.java
engine/src/main/java/org/terasology/rendering/dag/stateChanges/BindFBO.java
engine/src/main/java/org/terasology/rendering/dag/stateChanges/DisableDepthMask.java
engine/src/main/java/org/terasology/rendering/dag/stateChanges/DisableDepthTest.java
engine/src/main/java/org/terasology/rendering/dag/stateChanges/EnableBlending.java
engine/src/main/java/org/terasology/rendering/dag/stateChanges/EnableFaceCulling.java
engine/src/main/java/org/terasology/rendering/dag/stateChanges/EnableMaterial.java
engine/src/main/java/org/terasology/rendering/dag/stateChanges/EnableStencilTest.java
engine/src/main/java/org/terasology/rendering/dag/stateChanges/SetBlendFunction.java
engine/src/main/java/org/terasology/rendering/dag/stateChanges/SetDepthFunction.java
engine/src/main/java/org/terasology/rendering/dag/stateChanges/SetInputTexture.java
engine/src/main/java/org/terasology/rendering/dag/stateChanges/SetInputTextureFromFBO.java
engine/src/main/java/org/terasology/rendering/dag/stateChanges/SetViewportToSizeOf.java
engine/src/main/java/org/terasology/rendering/dag/stateChanges/SetWireframe.java

Fixes #2706. Instead of the existing reference based comparison, all `StateChange.isDefaultInstance` implementations now make use of value based comparison by calling the `equals` method instead.
- Run the game, load a world.
- Check the logs for the render task list. Note the difference in number of generated tasks (114 from 123).
All implementations of the `isDefaultInstance` method used reference comparisons using the equality operator (`this == defaultInstance`). This is modified to call the overridden `equals` method instead (`this.equals(defaultInstance)`).

Value comparison instead of reference comparison in StateChange.isDefaultInstance

---

engine/src/main/java/org/terasology/world/block/entity/BlockCommands.java

Now the commands listBlocks, listItems, listFreeShapeBlocks and listShapes accept any number of string parameters that act as a filter to the output.
For example
`listItems core: engine:`
Will list all items beginning with "core:" or "engine:" effectively listing all items from the core and the engine modules.
Look at said commands with help, and try them.

Add startsWith filter to listing commands

---

engine/src/main/java/org/terasology/logic/players/PlayerFactory.java
engine/src/main/java/org/terasology/world/generation/facets/SurfaceDepthFacet.java
modules/Core/src/main/java/org/terasology/core/world/generator/rasterizers/SolidRasterizer.java

1. Added an optional surface depth facet that when added limits the default surface rasterizer from generating below the depth.
2. Made spawning point selection return a value even if no "good" spawn could be found, because it's better to at least spawn in the ground than crash the game.
Part of GCI task creating an Underworld.

Surface Depth Facet

---

engine/src/main/java/org/terasology/rendering/nui/itemRendering/StringTextIconRenderer.java

A change that makes it possible to use atlas icon URLs like `engine:items#whiteRecipe` with the `StringTextIconRenderer`. The latter can for example be used by a TreeView to render its icons.
Note that this change should not break anything since the TextureRegion is a interface implemented by the class Texture: Thus a StringTextIconRenderer sub class is still allowed to return a Texture and does not need to be adjusted.
No test needed, it should be enough that it compiles.

Make it possible to use more icon types for UI elements like tree views.

---

engine/src/main/java/org/terasology/logic/characters/CharacterHeldItemAuthoritySystem.java
engine/src/main/java/org/terasology/logic/players/FirstPersonClientSystem.java

Fixes #2605
This fixes 2605 by creating a new entity (client-side) for the wielded items.
This pull request creates a client side entity for first person view display instead of reusing the entity from the inventory. This makes reasoning easier and fixes the bug where the host held item spawns at (0, 0, 0) for the clients.
Create a listen server, join with a new client. Pick up an item as host and see how the client will not see the host wielded item at (0, 0, 0). Also dropping items and placing blocks should still work.

Fix #2605 Create new client side entity for wielded item

---

engine/src/main/java/org/terasology/logic/console/ui/ChatScreen.java
engine/src/main/java/org/terasology/logic/console/ui/MiniChatOverlay.java

This is a followup PR to #2667, closing #2376. It fixes the issue mentioned where part of the mini chat overlay would overrun the screen if the messages sent contain too many characters. 
The length of each message in the mini chat overlay is now limited to 250 characters, which the player can view in full by opening the active chat overlay (T by default). This also removes an extra newline in the active chat overlay.
Paste a string containing more than 250 characters into chat. It should be truncated and the last few characters replaced with a ellipsis.
Mini chat overlay:
Active chat overlay: 
None!

Fix issue where chat overlay would overrun screen

---

engine/build.gradle
engine/src/main/java/org/terasology/rendering/nui/layers/ingame/PauseMenu.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/MainMenuScreen.java
engine/src/main/resources/assets/i18n/menu.lang
engine/src/main/resources/assets/i18n/menu_en.lang
engine/src/main/resources/assets/ui/ingame/pauseMenu.ui
engine/src/main/resources/assets/ui/menu/mainMenuScreen.ui

Fixes #2577 
Load up a game
Press **Esc** to open the pause menu
There is a new button which brings up the crash reporter with the current game log

Add button to launch the Crash Reporter from the pause menu

---

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/settings/PlayerSettingsScreen.java

Fixes #2781 
- I've added Hindi #2733, Arabic #2769, Korean #2745, Farsi #2735, Chinese #2677 to the exclusion list.
- I've tested in Hindi and Chinese.
Before the change, Chinese appears in the list : 
After the change, Chinese disappeared :

Add an exclusion list for unready languages to the player settings

---

engine/src/main/java/org/terasology/rendering/dag/nodes/SimpleBlendMaterialsNode.java

Fixes #2800
Break some bushes: a small cloud of rapidly disappearing particles/leaves should appear where the bush used to be - this is the normal behavior. 
The Bug detailed in 2800 had the particle appear in the lower portion of the field of view of the player, in a frame of coordinates seemingly unrelated to the visible world.
This problem was due to the SimpleBlendMaterialsNode implicitly relying on other nodes to set the correct modelview and projection matrices. After the merging of PR #2794 nodes _must_ either add a StateChange to look through a specific camera or run their code assuming the projection and modelview matrices being identity matrices - opengl's default. 
As testing of #2794 didn't include semi-transparent objects, this problem was not noticed.

Fix for Issue 2800

---

engine/src/main/java/org/terasology/world/block/entity/BlockCommands.java

Makes the giveBlock command send multiple times, until quantity runs out. The command is limited to 99 blocks per stack, since that is the max stack size. Fixes #2607. 
Press (F1) to bring up the console. Use the giveBlock command by typing give <item> <quantity>. Pull up the inventory with (i) to see if none of the stack sizes are above 99 and if the correct number of blocks were given.
Sorry I had to reopen this again. I accidentally closed it when I force pushed. To answer @portokaliu 's question, unless I change stackCount in ItemComponent to an integer or create another component to contain the number of blocks to give, then I can't use InventoryAuthoritySystem to send blocks more than 127. If there's another way to do it, then please let me know. I apologize for the late response; …

Use multiple stacks to give blocks. This closes #2607

---

engine/src/main/java/org/terasology/logic/players/FirstPersonClientSystem.java

This is a sort of interesting one, tho the PR is just for documentation purposes and I'll re-open #2605 for a re-fix, then merge this in preparation for Alpha 7.
In short: @portokaliu in #2605 reported an issue where an entity went funny and ended up showing a mesh of what the host player is holding, rendered at 0, 0, 0 for client players. @Tropid found a fix for it via PR #2672 that filtered out some stuff preventing the entity quirk from rendering the bogus object. However, that in turn filtered *too much* causing held torches to not give up light and gifted goodie boxes in Core to not work.
We need to improve the fix in #2672 or find an alternative that doesn't cause undesired side effects. Maybe this is indicative of a networking strategy we can improve somehow? In the meantime this …

Revert #2672, fixing #2788 and part of #2804, but bringing back #2605

---

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/SelectGameScreen.java

Fixes disappearance of buttons that should come after clicking Singleplayer and Host Game buttons in main menu.
#2762 partially fixed already in pr 2772 and completely fixed after this
Fixes #2762 
1. Enable animated menus in settings > video
2. go back to main screen
3. click Singleplayer or Host Game button
4. click Back
5. click any among the Singleplayer or Host Game button

fixed singlePlayer and multiPlayer screen disappearance after enabling Animated Menus option

---

engine/src/main/resources/assets/skins/default.skin

Cleans up log output so it stops complaining about UIInputBindButton by removing UIInputBindButton from the default.skin file.
Fixing #2145
Fixes UIInputBindButton being redundant. Detailed in: #2145
Run the game and look at various log files for it complaining about UIInputBindButton

Remove UIInputBindButton from default.skin

---

engine/src/main/java/org/terasology/engine/subsystem/headless/renderer/HeadlessWorldRenderer.java
engine/src/main/java/org/terasology/engine/subsystem/headless/renderer/NullCamera.java

This pull request fixes the server build (the regression was likely caused by https://github.com/MovingBlocks/Terasology/pull/2803). It does not seem to affect the client noticeably (tested with a local client and server).
`./gradlew jar server` used to cause a build error, now it works.
Pinging @fabriond about this, since this fix is a bit hacky.

Fix headless server build

---

engine/src/main/java/org/terasology/input/InputSystem.java

Fixes #2554 and prevents controller input from being accepted when the game window isn't active.
Not actually sure how to run Checkstyle on the code, so unable to verify that currently...
Run game with out change using a controller, test that controller works for the game, make the window inactive and then try to input on the controller(it will still put in inputs).
With change these inputs on the inactive window are not accepted and function as a mouse or keyboard input would.
With the window active the game still functions normally and consumes all inputs.

Fix inactive controller inputs being consumed

---

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/CreateGameScreen.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/SelectGameScreen.java
engine/src/main/java/org/terasology/world/generation/BaseFacetedWorldGenerator.java

Fixes #2429 and partially fixes #2509
1. Click on Single Player > Create > Details
2. Wait for screen to show up
3. Then click on Back
4. Click on Details again
5. It shows null pointer exception and preview does not load
6. Can be tested by selecting any world generator or module(even stable ones will show this exception)
The 1st problem is not yet tackled but the reason for lag is the setting the environment which causes the assets to reload and when back button is pressed the environment is reset which also causes assets to reload and hence I think the lag
The 2nd problem in this issue is actually the above issue which is fixed
The 3rd problem is tackled in the commit for issue 2509 in which the game crashes or will be needed process killed.
1. Click on Single Player > Create > Details …

fixed #2429 Previewing a world breaks world preview for remainder of game session

---

engine/src/main/java/org/terasology/persistence/typeHandling/extensionTypes/PrefabTypeHandler.java

A fix for a crash that occurred when a field of type Prefab got synchronized over network with value `null`.
Not sure if this needs a test, but I had a crash after I placed a structure template on a server. The client would instantly crash upon joining.

Null prefab crash fix

---

engine/src/main/java/org/terasology/world/block/entity/BlockCommands.java
modules/Core/src/main/java/org/terasology/logic/inventory/ItemCommands.java

Adds the bulkGiveItem command (the same as bulkGiveBlock, but for items) mentioned in #2835.
It also moves the listItem command into ItemCommands, so it can be used in other commands relating to items.
Type the command "bulkGiveItem axe", and you will be given a copy of every item with "axe" in the name.
This complements #2841, but they are completely separate, and work individually or together.
As this command uses give in its implementation, using bulkGiveItem with a quantity only works if both patches are applied together.
Also, I changed uriStartsWithAnyString to be a static method because it is a useful utility function, but it might be better suited to be in a separate file, as it is used in both BlockCommands and ItemCommands.

Add bulkGiveItem command (from #2835)

---

engine/src/main/java/org/terasology/world/block/entity/BlockCommands.java
modules/Core/src/main/java/org/terasology/logic/inventory/ItemCommands.java

Fix most of #2835 (everything apart from the bulkGiveItem command), including the lag on large numbers of items introduced in #2678.
Run the command "give axe 1000", and observe that your inventory is filled with axes, and the command window reported the number of axes actually given.
Run the command "give dirt 10000000" and observe that the game no longer lags, but the command executes successfully, and reports the number of dirt blocks given.
This way of giving multiple items/blocks is a much more robust solution than the previous one, but it does it by giving them one at a time, rather than a stack at a time. I'm not sure if that's an issue, but it might be worthwhile to test giving a full inventory of items on a remote server, to make sure it's not too slow.
Also, the default number …

Fix quantity-based giving of items #2835

---

engine/src/main/java/org/terasology/input/internal/BindCommands.java

Dvorak command had left and right inverted. This simple fix swaps them back to be the correct way around.
Fix dvorak command (left and right were inverted)
Set keyboard to be a dvorak layout. Open up a game world, and run the dvorak command. The movement should have the same keys as a normal qwerty keyboard.

Fix dvorak command

---

engine/src/main/java/org/terasology/config/NetworkConfig.java
engine/src/main/java/org/terasology/engine/modes/StateIngame.java
engine/src/main/java/org/terasology/network/ServerInfoMessage.java
engine/src/main/java/org/terasology/network/internal/NetworkSystemImpl.java
engine/src/main/java/org/terasology/network/internal/ServerInfoMessageImpl.java
engine/src/main/java/org/terasology/protobuf/EntityData.java
engine/src/main/java/org/terasology/protobuf/NetData.java
engine/src/main/protobuf/NetMessage.proto

Implemented server MOTD (Message Of The Day) as suggested in #2855 (no html/markdown formatting for now).
Spin up a server (for example launch with `-headless -homedir=server-dir`) to create a configuration. Wait for the server to finish the initialization and start listening on network interfaces, then stop it. Now, open the `config.cfg` in the server's home directory (`server-dir` in the example), go in the `network` section and add a `serverMOTD` field, for example:
```
...
"serverPort": 25777,
"serverMOTD": "Hi, I'm the server's MOTD! (change it as you like)",
"masterServer": "meta.terasology.org"
...
```
Now start the server again, start a client and join the server (`localhost` if on the same machine). As soon as you get to the `StateInGame` state (the loading screen finishes) …

Implemented server MOTD (Message Of The Day)

---

engine/src/main/java/org/terasology/world/block/entity/BlockCommands.java
modules/Core/src/main/java/org/terasology/logic/inventory/ItemCommands.java

Apply change requested by @xrtariq2594 in  #2842 (making bulkGiveItem print a sarcastic message if you give it a quantity of zero or below).
It also changes bulkGiveBlock to do the same thing, so it only prints out one sarcastic message, rather than searching through the list of blocks and printing out one message for each of them.
And a minor change removing one unnecessary line.
Call the bulkGiveItem and bulkGiveBlock commands with a quantity of 0, and observe that you get a sarcastic message, and no blocks or items.

Make bulkGiveItem and bulkGiveBlock check for non-positive quantity

---

engine/src/main/java/org/terasology/rendering/dag/nodes/CopyImageToScreenNode.java
engine/src/main/java/org/terasology/rendering/dag/stateChanges/SetViewportToSizeOf.java
engine/src/main/java/org/terasology/rendering/opengl/fbms/DisplayResolutionDependentFBOs.java
engine/src/main/java/org/terasology/rendering/world/WorldRendererImpl.java

Contains fixes for the remaining resizing issues.
Existing Problem 1: When you start a game, exit to the main menu and start the game again, resizing will become corrupt and any resizing (maybe even no resizing) that you do will lead to problems.
Cause and Solution: The reason behind that is a static defaultInstance object of class SetViewportToSizeof, and this PR resets that object to null when disposing the RenderGraph.
Existing Problem 2: When playing with scale set to anything other than 100%, the game would not render to entire screen, and would draw only to a small part if scale < 100%, or outside bounds if scale > 100%.
Cause and Solution: This was caused because setViewportToSizeOf used an FBO to obtain the size, but since scale was not 100%, size of FBO was not same as size of …

Fixes all resizing issues

---

engine/src/main/java/org/terasology/logic/characters/KinematicCharacterMover.java
engine/src/main/java/org/terasology/physics/engine/SweepCallback.java
modules/Core/src/main/java/org/terasology/logic/health/HealthAuthoritySystem.java
modules/Core/src/main/java/org/terasology/logic/health/HealthComponent.java

###Contains
Fixes PR #2821 
Makes velocity of character = 0 when the character hits a ceiling. The gravity than does the rest.
Character takes damage if he/she hits the ceiling above allowable speed limit.
Made crashing speed generation more consistent and better than previously(Does not guarantee if player will take damage upon horizontal collision but is certainly better and consistent than the previous one)
###How to test
Run the game. Go under a low ceiling environment eg. under a tree.
Enable hjump.
Jump and die due to hitting on ground at a speed as if falling from a mountain.

Fixes Oddities surrounding maintaining momentum after hitting a ceiling

---

engine/src/main/java/org/terasology/rendering/dag/nodes/CopyImageToHMDNode.java

This PR prevents the creation of 2 unnecessary buffers for most casual players, the leftEye FBO and the rightEye FBO, which are used for HMD (Head Mounted Displays (VR)).
~~However, this PR is probably not complete, as we might want to consider re-working the ConditionDependentNodes. Currently, ConditionDependentNode::checkConditions() returns true if the state of Node was toggled, and false otherwise. Do we really need a return value, since we can just query it with Node.isEnabled() in the calling function (which returns the enabled state, which might be of more interest than toggleState, depending on the particular case)?~~
Pinging @indianajohn and @emanuele3d for review.

CopyImageToHMDNode Constructor Rework

---

engine/src/main/java/org/terasology/engine/TerasologyEngine.java
engine/src/main/java/org/terasology/engine/bootstrap/EnvironmentSwitchHandler.java
engine/src/main/java/org/terasology/engine/modes/GameState.java
engine/src/main/java/org/terasology/engine/modes/StateIngame.java
engine/src/main/java/org/terasology/engine/modes/StateLoading.java
engine/src/main/java/org/terasology/engine/modes/StateMainMenu.java
engine/src/main/java/org/terasology/engine/subsystem/headless/mode/StateHeadlessSetup.java

This PR removes a redundant call to the function `cheapAssetManagerUpdate` on shutdown, which causes a reload of assets during shutdown.
How to test: Run the game, do something (or don't) and ensure that you get no weirdness when quitting the game.
Pinging @immortius for review.

Fix reloading of assets on shutdown

---

engine/src/main/java/org/terasology/persistence/internal/SaveTransaction.java

Replaces the JDK internal ZipFileSystemProvider with the FileSystems public API. Since this classes will be hidden with Java 9 this change will be necessary.
Fixes #2354
Run the game and save a world.
Nothing.

Replace JDK internal ZipFileSystemProvider with FileSystems public API

---

engine/src/main/java/org/terasology/logic/behavior/BehaviorSystem.java

This is done for the new changes merged in https://github.com/Terasology/WildAnimals/ to work.
The additions to the WildAnimals module make changes to the entity's behavior component to switch behavior.
The current system uses events to trigger changes in the Behavior Tree. This means that if the deer is hit, the deer's `BehaviorComponent.tree` is extracted and it's value is changed from "Pathfinding:Stray" to "WildAnimals:Flee". The exact reverse happens when the deer reaches a safe distance from the player, i.e. `BehaviorComponent.tree` is changed from "WildAnimals:Flee" to "Pathfinding:Stray".
Whenever a change is made, the entity's (deer's) new entry is added to the `entityInterpreter` defined in the `BehaviorSystem`. (Using the `onBehaviorActivated` and `onBehaviorDeactivated` …

BehaviorSystem- changed Map to ConcurrentHashMap

---

engine/src/main/java/org/terasology/engine/NonNativeJVMDetector.java
engine/src/main/java/org/terasology/engine/TerasologyEngine.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/MainMenuScreen.java
engine/src/main/resources/assets/i18n/menu.lang
engine/src/main/resources/assets/i18n/menu_en.lang
engine/src/main/resources/assets/ui/menu/mainMenuScreen.ui

Idea for this patch is from issue #2905.
If the game is running in a 32-bit JVM on a 64-bit system, a warning is shown in the console and on the main menu screen.
This can help users which get limited performance due to running in a 32-bit JVM when they could install a 64-bit one (thus native for their CPU).
This is not uncommon especially on Windows, I remember seeing people playing other Java games on x86 JVMs despite being on a 64-bit CPU and OS.
On Windows, this is checked by simply verifying if the [PROCESSOR_ARCHITEW6432](https://blogs.msdn.microsoft.com/david.wang/2006/03/27/howto-detect-process-bitness/) is set.
On POSIX OSs, the JVM architecture is read from the "os.arch" property and the real system architecture by reading the output of "uname -m".
You need to be on a 64-bit CPU …

Show warning if running in 32-bit JVM on 64-bit system

---

engine/src/main/java/org/terasology/rendering/nui/widgets/UIText.java

Fix part of issue #2833 (Various isses with movement inputs persisting
through the chatbox) where the first letter typed into an empty chatbox was
causing the player to move.
This was caused by the event falling through to the normal event system,
because a path was not marked with eventHandled = true.
Note: there are still parts of #2833 that this doesn't fix, but might be related.
Fixes part of #2833
Open up a chatbox, making sure it is empty. Type a movement command (e.g. 'w'), and observe what happens.
Before the patch, the character typed would go into the chatbox, but the player would move, even though the chat box is open. After the patch, the character typed just goes into the chatbox, and doesn't make the player move.

Fix first letter in chatbox moving player

---

engine/src/main/java/org/terasology/rendering/logic/NearestSortingList.java

Possible fix for #2742.
Destroyed entities were not visible in the sorting thread, causing the lookup to fail.
Start with core gameplay and use the large railgun while walking forward/diagonal downwards and collect the destroyed blocks (should lag a lot, make sure to assign enough memory. ~2,5GB worked for me).
Without the PR, you should get the exception from https://github.com/MovingBlocks/Terasology/issues/2742#issuecomment-271735663 after some time.
With the PR, you should get a log message like `10:15:08.759 [Timer-1] WARN  o.t.r.logic.NearestSortingList - Entities destroyed during sorting process. Sorting is skipped this round.` at a similar time.
We should discuss if the `ComponentTable` has to be thread safe in the first place, before merging.
If the entire environment is expected …

Ignore out of bounds exception in NearestSortingList, Closes #2742

---

engine/src/main/java/org/terasology/audio/AudioEndListener.java
engine/src/main/java/org/terasology/audio/AudioManager.java
engine/src/main/java/org/terasology/audio/nullAudio/NullAudioManager.java
engine/src/main/java/org/terasology/audio/openAL/OpenALManager.java
engine/src/main/java/org/terasology/engine/modes/StateMainMenu.java
engine/src/main/java/org/terasology/logic/behavior/tree/PlayMusicNode.java
engine/src/main/java/org/terasology/logic/behavior/tree/PlaySoundNode.java

Contains snippets and changes from PRs #2846, #2545 and #2542 which are all inactive for more than a month. I would like to continue here and close the old PRs.
This fixes #2527. 
I was unable to reproduce #2364, so maybe @ratz or @Cervator can test this again?
Note that the change in the `AudioEndListener` will require a follow-up PR in the [MusicDirector](https://github.com/Terasology/MusicDirector) module.
If you want to keep the API untouched we could either introduce a new listener for the interrupt action on a music track or just omit the end listener entirely when music stops early.

Add loop functionality to AudioManager, loop menu theme

---

engine/src/main/java/org/terasology/config/BindsConfig.java

Fixes #2831 
There was a problem with checking if a bind input was bound and two inputs are both null, 
Could be solved a few different ways, but I figured the most plausible would be that no matter what null is never registered as bound to other inputs(even if it technically is).
Unbind 1 key, try unbinding a second(and a third and a fourth if you don't trust it) and it will now allow you to unbind these keys. 
Test in game that they are properly unbound and then rebind and see that they still work when rebound(the fix doesn't break the input binding system)
Double check that this is how we want to deal with unbinding keys and setting their input values to null.
There are a few different ways this could be done, this is just one of them.

Fix multi unbinding problem

---

engine-tests/build.gradle
engine-tests/src/test/java/org/terasology/logic/behavior/InterpreterTest.java
engine-tests/src/test/java/org/terasology/logic/behavior/ParallelTest.java
engine-tests/src/test/java/org/terasology/logic/behavior/SelectorTest.java
engine-tests/src/test/java/org/terasology/logic/behavior/SequenceTest.java
modules/Core/src/test/java/org/terasology/logic/inventory/InventoryAuthoritySystemTest.java

Updates the mockito dependency to the latest version which does not include hamcrest 1.1
See #2934 for details.
Also updated some tests, as mockito 2.x is more restrictive on type checks as 1.x, see https://github.com/mockito/mockito/wiki/What%27s-new-in-Mockito-2#incompatible-changes-with-110 for details.

update mockito-all to latest mockito-core, fixes #2934

---

modules/Core/src/main/java/org/terasology/logic/health/HealthAuthoritySystem.java
modules/Core/src/main/java/org/terasology/logic/health/HealthCommands.java

Adds a new `damagewithType` command which can take inputs `damageType` and `amount`.
Try with different damage types like - 
`damagewithType engine:physicalDamage 10`
`damagewithType AlterationEffects:poisonDamage 20`
with the appropriate modules enabled.

Added type damage command.

---

engine-tests/src/test/java/org/terasology/registry/InjectionHelperTest.java
engine/src/main/java/org/terasology/registry/InjectionHelper.java

Adds some learning tests how the constructor injection works and javadoc for the helper method which documents the behavior.
Also fixes a case for a nullpointer, the original system was unable to fallback to a constructor with less parameters, even though it did all the sorting logic and would try each one. It's easy to reproduce, just undo the `of()`->`ofNullable()` change in the `InjectionHelper` and re-run the tests.
I was thinking about using it to initialize component systems but this is more complicated as these may have dependencies between each other which is handled different by the current system so I am going to leave it with the tests for now.
Should be ready to merge the way it is.

Dependency injection tests

---

engine/src/main/java/org/terasology/i18n/TranslationRefreshSystem.java
engine/src/main/java/org/terasology/i18n/TranslationSystem.java

Adds i18n support for modules
Create a module `TestAndTryout` (or any other name, replace the translation key if so) with the following system:
```
@RegisterSystem
public class GreeterSystem extends BaseComponentSystem {
private static final Logger logger = LoggerFactory.getLogger(GreeterSystem.class);
@In
private TranslationSystem translationSystem;
@ReceiveEvent
public void onPlayerSpawn(OnPlayerSpawnedEvent event, EntityRef player) {
logger.info(translationSystem.translate("${TestAndTryout:greeter#greet}"));
}
}
```
add to the module `assets/i18n` (create folder):
greeter.lang
```
{
"greet": "greet"
}
```
greeter_en.lang
```
{
"greet": "Hello new player."
}
```
greeter_de.lang
```
{
"greet": "Hallo neuer Spieler."
}
```
- Without the PR the system will not load (system is not api)
- …

TranslationSystem API & reload i18n module assets

---

engine/src/main/java/org/terasology/logic/console/ui/ChatScreen.java
engine/src/main/java/org/terasology/logic/console/ui/ConsoleScreen.java
engine/src/main/java/org/terasology/rendering/nui/widgets/UIText.java

Fixes the problems addressed in #2834 
Inputting a string of empty spaces into either console or chat treats it as an empty message. (Does not send that message)
Inputting an empty message into console does nothing.
Inputting an empty message into chat closes the chat box.
Any messages are trimmed(white space before and after messages is removed)
Open up chat, try sending an empty message.
Open up chat, try sending a message with only spaces in it.
Open up console, try sending an empty message.
Open up console, try sending a message with only empty spaces in it.
Check that console and chat both trim the message before it is sent.
Nothing that I know of!

Empty space input for chat/console handling

---

engine/src/main/java/org/terasology/logic/debug/MovementDebugCommands.java

Contains a small fix for saving the gaze component when changing eye-height instead of reattaching the gazeEntity to the location only temporarily.

Fixed eye height movement debug command

---

engine/src/main/java/org/terasology/physics/events/CollideEvent.java

Required for CombatSystem module where this event is consumed if the other entity the weapon collided with was the player who fired it, so that no action is taken on the player.
For eg. arrows that player fire are spawned in the bounding box of the player and shouldn't hurt him.

changed CollideEvent to be consumable

---

engine/src/main/java/org/terasology/persistence/serializers/EntityDataJSONFormat.java

Added serializeSpecialFloatingPointValues to the Gson builder.
This solves the error which appears on using `dumpEntities` command in console:
```
An error occurred while executing command 'dumpEntities': NaN is not a valid double value as per JSON specification. To override this behavior, use GsonBuilder.serializeSpecialFloatingPointValues() method.
```

Fixes `dumpEntities` console command

---

engine/src/main/java/org/terasology/network/internal/AbstractClient.java

In the `AbstractClient` class, the private method `findClientEntityRef` is only called from `createEntity`, where we already have a handy reference to the `EntityManager`, so in my understanding there is no need to take it from the CoreRegistry.
Passing the reference as an argument also makes testing of the class and it's subclasses easier and cleaner (I needed to look at the `AbstractClient` class while writing tests for the `HeadlessClient` class I added in MovingBlocks/FacadeServer#2) since you don't have to set up a mocked context, add the entityManager to it, setting the CoreRegistry's context, etc.
Not much to test, all the automated unit tests pass and if you can try to use the game normally (e.g. join a local world or multiplayer server) and you can see that everything is as …

Small refactor in AbstractClient

---

engine/src/main/java/org/terasology/rendering/nui/widgets/UIText.java

For a UIText widget with `"multiline": true`, an `ENTER` key would now produce a newline (\n).

Multiline UIText, enter produces newline

---

engine/src/main/java/org/terasology/particles/ParticleData.java
engine/src/main/java/org/terasology/particles/ParticleDataMask.java
engine/src/main/java/org/terasology/particles/ParticleSystemManager.java

Adds API annotations to three classes in the particles system package. These classes are required for people to define and use custom particle affectors and generators in their modules.

added API annotations to classes in the particles sysem

---

modules/Core/assets/prefabs/door.prefab
modules/Core/src/main/java/org/terasology/core/logic/door/DoorComponent.java
modules/Core/src/main/java/org/terasology/core/logic/door/DoorSystem.java

This is linked to https://github.com/Terasology/AdventureAssets/pull/12
It basically allows the "Core" door placement mechanism to be extendable while creating different types of doors- password locked doors, pressure plate operated doors, level operated doors etc.
It links the doorRegion prefab as a parameter in the DoorComponent, which was earlier hardcoded in the DoorSystem.

Store DoorRegion prefab as component parameter

---

engine/src/main/java/org/terasology/logic/players/PlayerSystem.java
modules/Core/src/main/java/org/terasology/logic/health/HealthAuthoritySystem.java

This PR is linked to https://github.com/Terasology/AdventureAssets/pull/11
Separates the existing RespawnRequestEvent handler into two handlers with different priorities. The RespawnRequestEvent is sent to the client entity once the "Respawn" button is clicked on the Death Screen.
Basically, this is what happens now:
- The spawn location for a player is calculated using the worldGenerator information at the earliest step (`CRITICAL` priority).
- Any other system which wants to change the respawn location can then intercept the RespawnRequestEvent and make change to the entity's (client's) location component. (priority between `TRIVIAL` and `CRITICAL`, both exclusive)
- Finally, the RespawnRequestEvent is received by the PlayerSystem again. This time the respawnPlayer method is called and …

Separated spawnLocation calculation from respawnPlayer method

---

engine/src/main/java/org/terasology/rendering/logic/FloatingTextRenderer.java

This PR allows the FloatingTextRenderer to now split lines and separate them at "\n".
The FloatingTextComponent can now have the `text` parameter contain multiple "\n" separated lines.
The width for the mesh is calculated based on the longest length String after having broken the text. 
This is an example of how it looks:

FloatingTextRenderer accepts multiple \n separated lines

---

engine/src/main/java/org/terasology/rendering/dag/nodes/DeferredPointLightsNode.java

Fixes a bug introduced in an earlier ShaderParameter removal PR, which caused held objects to not produce any light.
Testing : Hold a torch and go to a dark place, and it should light things up.

Small fix for in-game torches not producing lights

---

engine/src/main/java/org/terasology/world/block/entity/BlockEntitySystem.java
modules/Core/assets/prefabs/particleEffects/defaultBlockParticles.prefab
modules/Core/src/main/java/org/terasology/logic/health/BlockDamageAuthoritySystem.java

- particles when damaging a block now have the block's texture (randomly selected from all sides)
- smoke effect is only shown when block is destroyed and drops debris

Fixes block particle effects

---

engine/src/main/java/org/terasology/physics/bullet/BulletPhysics.java

turns out that those changes triggered multiple CollideEvent for same entity and for same collisions. Found another way to achieve what i needed, so please do merge this to rollback the changes.

rollback the changes that were done to enable world collisions

---

engine-tests/src/test/java/org/terasology/entitySystem/BaseEntityRefTest.java
engine-tests/src/test/java/org/terasology/entitySystem/PojoEntityManagerTest.java
engine-tests/src/test/java/org/terasology/entitySystem/PojoEntityPoolTest.java
engine/src/main/java/org/terasology/entitySystem/entity/EntityBuilder.java
engine/src/main/java/org/terasology/entitySystem/entity/EntityManager.java
engine/src/main/java/org/terasology/entitySystem/entity/EntityPool.java
engine/src/main/java/org/terasology/entitySystem/entity/EntityRef.java
engine/src/main/java/org/terasology/entitySystem/entity/LowLevelEntityManager.java
engine/src/main/java/org/terasology/entitySystem/entity/SectorManager.java
engine/src/main/java/org/terasology/entitySystem/entity/internal/BaseEntityRef.java
engine/src/main/java/org/terasology/entitySystem/entity/internal/ComponentTable.java
engine/src/main/java/org/terasology/entitySystem/entity/internal/EngineEntityManager.java
engine/src/main/java/org/terasology/entitySystem/entity/internal/EngineEntityPool.java
engine/src/main/java/org/terasology/entitySystem/entity/internal/EngineSectorManager.java
engine/src/main/java/org/terasology/entitySystem/entity/internal/EntityInfoComponent.java
engine/src/main/java/org/terasology/entitySystem/entity/internal/EntityIterator.java
engine/src/main/java/org/terasology/entitySystem/entity/internal/EntityScope.java
engine/src/main/java/org/terasology/entitySystem/entity/internal/PojoEntityManager.java
engine/src/main/java/org/terasology/entitySystem/entity/internal/PojoEntityPool.java
engine/src/main/java/org/terasology/entitySystem/entity/internal/PojoSectorManager.java
engine/src/main/java/org/terasology/entitySystem/sectors/LoadedSectorUpdateEvent.java
engine/src/main/java/org/terasology/entitySystem/sectors/SectorSimulationComponent.java
engine/src/main/java/org/terasology/entitySystem/sectors/SectorSimulationEvent.java
engine/src/main/java/org/terasology/entitySystem/sectors/SectorSimulationSystem.java
engine/src/main/java/org/terasology/persistence/serializers/EntitySerializer.java
engine/src/main/java/org/terasology/persistence/typeHandling/extensionTypes/EntityRefTypeHandler.java
engine/src/main/java/org/terasology/protobuf/EntityData.java
engine/src/main/protobuf/EntityData.proto

This PR contains the work done so far on sectors/entity pools. There's nothing new in here that isn't in the following PRs:
#2975
https://github.com/Vizaxo/Terasology/pull/2
https://github.com/Vizaxo/Terasology/pull/3
https://github.com/Vizaxo/Terasology/pull/4
This PR just consolidates the work done so far, rebases it on top of the v2.0.0 branch (which is on par with develop, at the time of writing), and squashes the commits from 54 down to 8.
Also, any references to caches have been removed, so pool is used all the way through.
This adds entity pools, which split up the storage of entities into multiple pools, rather than storing them all together. It implements sectors on top of that, which are a new scope for entities to allow better simulation when no players are close to the entity. …

[WIP] Sectors/pools: v2.0.0 branch

---

engine/src/main/java/org/terasology/physics/bullet/BulletPhysics.java

Because the characters in the game use convex sweep on every input to check for collisions. The consuming of CollideEvent was useless in this case. Thats why the required changes have been introduced where a character ignores the collisions with a trigger that has Sensor collision group to avoid responding to invisible sensors.
Please note that if you require a Trigger for an entity that is not a Sensor and wants to collide with Characters than you are free to do so but do change the collisionGroup to something relevant in the TriggerComponent. The default collisionGroup is Sensor, so be sure to change it in that case.

prevents characters from colliding with sensors

---

engine/src/main/java/org/terasology/logic/characters/events/ActivationPredicted.java

Linked to https://github.com/Terasology/StructureTemplates/pull/18
This changes `ActivationPredicted` to a consumable event, allowing for activation to be blocked completely when needed.

Change ActivationPredicted to consumable event

---

engine/src/main/java/org/terasology/telemetry/metrics/SystemContextMetric.java

Quick Fix for #3021 
Fetches the context from `CoreRegistry.get()` (since `@In` wasn't working, maybe because it is not a registered system). Finds the `DisplayDevice` from the context and uses the built in method `isHeadless` to check if it is headless.

Checking isHeadless from DisplayDevice

---

engine/src/main/java/org/terasology/logic/characters/AliveCharacterComponent.java
engine/src/main/java/org/terasology/logic/characters/CharacterSoundSystem.java
engine/src/main/java/org/terasology/logic/characters/CharacterSystem.java
engine/src/main/java/org/terasology/logic/characters/events/PlayerDeathEvent.java
engine/src/main/java/org/terasology/logic/players/MenuControlSystem.java

The PlayerDeath event which is currently being sent to the client entity is now being sent to the character entity.

PlayerDeath event should be sent to character entity

---

engine/build.gradle

PR for documentation purposes only - already been testing and just forgot to add this in :-)
Reasoning: there's a small fix related to asset instances in this Gestalt release that helps support a feature in the new Scenario system

Dependency bump to Gestalt 5.1.3

---

engine/src/main/java/org/terasology/logic/players/PlayerSystem.java

If the last save happens when a player is dead (on the death screen) then the player entity is saved in the player store without the AliveCharacterComponent.
When a client rejoins, the player is spawned but without the AliveCharacterComponent. This PR ensures that all players that join a game have a AliveCharacterComponent.

Dead players alive-d on join

---

engine-tests/src/test/java/org/terasology/entitySystem/BaseEntityRefTest.java
engine-tests/src/test/java/org/terasology/entitySystem/PojoEntityManagerTest.java
engine-tests/src/test/java/org/terasology/entitySystem/PojoEntityPoolTest.java
engine-tests/src/test/java/org/terasology/persistence/EntitySerializerTest.java
engine/src/main/java/org/terasology/entitySystem/entity/EntityBuilder.java
engine/src/main/java/org/terasology/entitySystem/entity/EntityManager.java
engine/src/main/java/org/terasology/entitySystem/entity/EntityRef.java
engine/src/main/java/org/terasology/entitySystem/entity/internal/BaseEntityRef.java
engine/src/main/java/org/terasology/entitySystem/entity/internal/EngineEntityManager.java
engine/src/main/java/org/terasology/entitySystem/entity/internal/EntityInfoComponent.java
engine/src/main/java/org/terasology/entitySystem/entity/internal/EntityScope.java
engine/src/main/java/org/terasology/entitySystem/entity/internal/PojoEntityManager.java
engine/src/main/java/org/terasology/entitySystem/entity/internal/PojoEntityPool.java
engine/src/main/java/org/terasology/entitySystem/sectors/LoadedSectorUpdateEvent.java
engine/src/main/java/org/terasology/entitySystem/sectors/SectorRegionComponent.java
engine/src/main/java/org/terasology/entitySystem/sectors/SectorSimulationComponent.java
engine/src/main/java/org/terasology/entitySystem/sectors/SectorSimulationEvent.java
engine/src/main/java/org/terasology/entitySystem/sectors/SectorSimulationSystem.java
engine/src/main/java/org/terasology/entitySystem/sectors/SectorUtil.java
engine/src/main/java/org/terasology/math/ChunkMath.java
engine/src/main/java/org/terasology/persistence/serializers/EntitySerializer.java
engine/src/main/java/org/terasology/protobuf/EntityData.java
engine/src/main/protobuf/EntityData.proto

This removes the `alwaysRelevant` entity field, and makes the relevant methods look at the `alwaysRelevant` field on the entity's scope instead.
`GLOBAL` and `SECTOR` scope are `alwaysRelevant`, but `CHUNK` scope is not. The default scope is `CHUNK`, so the default for `alwaysRelevant` is still `false.`.
This also updates some entity-related tests, and fixes some problems found by them (now all of the entity creation code goes through the `EntityBuilder` (previously almost all of it did, but methods like `createEntityWithId()` didn't), so that the scope can be set properly without putting it in multiple places).
Load the [TutorialSectors](https://github.com/Terasology/TutorialSectors/tree/remove-alwaysrelevant) module on the `remove-alwaysrelevant` branch, and observe that the entity …

[v2.0.0] Convert alwaysRelevant to use entity scope instead

---

engine/src/main/java/org/terasology/entitySystem/entity/EntityManager.java
engine/src/main/java/org/terasology/entitySystem/entity/EntityRef.java
engine/src/main/java/org/terasology/entitySystem/entity/internal/BaseEntityRef.java
engine/src/main/java/org/terasology/entitySystem/entity/internal/PojoEntityManager.java
engine/src/main/java/org/terasology/entitySystem/sectors/LoadedSectorUpdateEvent.java
engine/src/main/java/org/terasology/entitySystem/sectors/SectorEntityLoad.java
engine/src/main/java/org/terasology/entitySystem/sectors/SectorEntityUnload.java
engine/src/main/java/org/terasology/entitySystem/sectors/SectorSimulationComponent.java
engine/src/main/java/org/terasology/entitySystem/sectors/SectorSimulationSystem.java
engine/src/main/java/org/terasology/entitySystem/sectors/SectorUtil.java

This splits SectorEntityComponent's maxDelta field into unloadedMaxDelta and loadedMaxDelta, which specify the maximum simulation delta for when all of the entity's watched chunks are unloaded, or when at least one is loaded, respectively.
This the simulation rate to be adjusted depending on whether or not the entity is loaded, so the unloaded simulation rate can be set as low as possible to maximise performance, while the loaded simulation rate can be higher to allow the player to observe the changes more frequently.
Load the [TutorialSectors](https://github.com/Terasology/TutorialSectors/tree/v2-branches/loaded-max-delta) module on the `v2-branches/loaded-max-delta` branch, and observe that the the entity simulates every second while the player is standing at (0, 0) (when a watched …

[v2.0.0] Allow sector entities to simulate at a different rate when loaded

---

engine/src/main/java/org/terasology/entitySystem/systems/BaseComponentSystem.java
engine/src/main/java/org/terasology/entitySystem/systems/ComponentSystem.java
engine/src/main/java/org/terasology/logic/players/FirstPersonClientSystem.java
engine/src/main/java/org/terasology/particles/rendering/SpriteParticleRenderer.java
engine/src/main/java/org/terasology/persistence/internal/ReadWriteStorageManager.java
engine/src/main/java/org/terasology/world/internal/EntityAwareWorldProvider.java

This should fix #2810 's fix
There shouldn't be a case for seeing other people's items (yet)
This fix adds `preAutoSave` and `postAutoSave` to the game so that items can be destroyed before they are saved by the system. The save method was just separated into 2 not so distinct ones.
This should prevent items from being despawned from your hand while playing as well (at least from the save PoV)
The problem was that the item held in your hand wasn't ever being destroyed, and was kept in the save as well. This created a floating mesh for the rest of eternity on the map.
The fix is that it's destroyed only during forced save and not auto.
I checked for the item remaining on the map in single player and multiplayer, and there doesn't seem to be any type of issue.

Item persisting on the map after saving fix

---

engine/src/main/java/org/terasology/engine/modes/loadProcesses/AwaitCharacterSpawn.java
engine/src/main/java/org/terasology/engine/modes/loadProcesses/AwaitedLocalCharacterSpawnEvent.java

@flo  for reference/review.
This is a PR that implements an event into the setup of a local player, when the local character entity is setup then it sends out this event. This allows for component systems that might rely on LocalPlayer to actually watch it for completion. It is only sent to the local client and will only trigger if a character entity is setup(won't trigger on a headless server or on someone joining a server, just the client's side)
Can test with any component system that would watch the event. An example that utilizes it is in the latest PR of the ScenarioModule. https://github.com/Terasology/Scenario/pull/36/commits/6bd6603e37c2a3bdab64c9c35ce23f6cfc904644
in 
https://github.com/ThompsonTyler/Scenario/blob/6bd6603e37c2a3bdab64c9c35ce23f6cfc904644/src/main/java/org/terasol …

LocalPlayerSetup Event

---

engine/src/main/java/org/terasology/rendering/nui/UILayout.java

Very minor PR to restore API compatibility after #3061. That broke EventualSkills and maybe other stuff.
This seems like a decent approach as it maintains API yet if somebody tries to use the method in question in a class that hasn't yet adjusted a clear error will occur. That pushes the problem out to module land where we know at the time of the API fix no error should occur as nothing uses the new method yet. But if somebody tries to develop using new stuff on top of unmodified module code they'll raise an exception
`throw new UnsupportedOperationException("Not implemented yet (default method)");`
Example: If after this PR somebody tries to use `removeAllWidgets` for the layout class in EventualSkills they'll hit an exception while testing their change. But after this is merged …

Adjustment for #3061- another default method to avoid API violation

---

engine/src/main/java/org/terasology/logic/console/commands/ClientCommands.java
engine/src/main/java/org/terasology/logic/players/PlayerSystem.java
engine/src/main/java/org/terasology/logic/players/SpawnLocationComponent.java
engine/src/main/java/org/terasology/logic/players/StaticSpawnLocationComponent.java

The PlayerSystem receives the RespawnRequestEvent and finds the location from the world generator.
This behavior has been modified such that it now checks for the existence of a SpawnLocationComponent attached to the ClientInfo Entity. If the component exists, the location is not found from the world generator and instead used directly.
The command that allows the player to set the spawn location is `setSpawnLocation`.
Use a world generator that dynamically finds the spawn location, for e.g.- PolyWorld (Island World)
1. Enable PolyWorld
2. `kill` yourself repeatedly by moving around. Notice that the spawn location changes every time.
3. Use the `setSpawnLocaiton` command to set a custom spawn location
4. Use `kill` command again and notice that the spawn location has now become static.

Added setSpawnLocation command

---

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/JoinGameScreen.java

Fixes the bug #3034. 
The code was missing a piece for the game screen to close if escape was pressed. This fixes the bug and allows the escape button to work for all the different screens/tabs at startup. This is my first pull request to this project, so if anything is wrong let me know. Thanks.

Fixed bug where ESC would not close Join Game Screen. Fixes #3034

---

engine/src/main/java/org/terasology/utilities/concurrency/Task.java
engine/src/main/java/org/terasology/utilities/concurrency/TaskMaster.java

A getter method for the ExecutorService used by TaskMaster
There are useful Guava utilities that can make use of ExecutorServices, for example the [SimpleTimeLimiter](https://google.github.io/guava/releases/22.0/api/docs/com/google/common/util/concurrent/SimpleTimeLimiter.html)
I make use of this in FlexiblePathfinding to [manage timeouts](https://github.com/kaen/FlexiblePathfinding/blob/master/src/main/java/org/terasology/flexiblepathfinding/JPSImpl.java#L66-L85) for pathfinding executions. This way I can use google time limiting logic instead of writing my own.
Currently, we can instantiate an ExecutorService directly ourselves, but we can't properly manage its lifecycle. Calling `executorService.shutdown` results in the following permissions error:
```
11:57:17.881 [Pathfinder-0] ERROR …
```

expose executor service in taskmaster

---

engine/src/main/java/org/terasology/config/MetricsUserPermissionConfig.java
engine/src/main/java/org/terasology/config/TelemetryConfig.java
engine/src/main/java/org/terasology/engine/subsystem/common/TelemetrySubSystem.java
engine/src/main/java/org/terasology/telemetry/Metrics.java
engine/src/main/java/org/terasology/telemetry/TelemetryCategory.java
engine/src/main/java/org/terasology/telemetry/TelemetryEmitter.java
engine/src/main/java/org/terasology/telemetry/TelemetryScreen.java
engine/src/main/java/org/terasology/telemetry/TelemetrySystem.java
engine/src/main/java/org/terasology/telemetry/TelemetryUtils.java
engine/src/main/java/org/terasology/telemetry/metrics/BlockDestroyedMetric.java
engine/src/main/java/org/terasology/telemetry/metrics/BlockPlacedMetric.java
engine/src/main/java/org/terasology/telemetry/metrics/GameConfigurationMetric.java
engine/src/main/java/org/terasology/telemetry/metrics/GamePlayMetric.java
engine/src/main/java/org/terasology/telemetry/metrics/Metric.java
engine/src/main/java/org/terasology/telemetry/metrics/ModulesMetric.java
engine/src/main/java/org/terasology/telemetry/metrics/MonsterKilledMetric.java
engine/src/main/java/org/terasology/telemetry/metrics/SystemContextMetric.java

Now the user can choose which field he wants to send in the `metrics menu`. 
- He can enable/disable a single field, e.g. the "language" field.
- He can enable/disable a whole metric e.g. "System Context", then all fields in that metric will be enabled/disabled.
- Click the check box "Send metrics to server" will enable/disable all fields.
- If all fields in the metric is disabled, that metric will be disabled automatically. If one field is enabled, that metric will be enabled automatically.
Make all the string default to `no_analysed` in ELK, we can finally do some pie graphs :)  The utility.terasology.org:5601 is updated. Here is an example proposed in #3024 
For the headless server, we need to edit in `terasology-server/config.cfg`:
- `"telemetryEnabled": true` to enable telemetry
- …

[telemetry] More user options

---

engine/src/main/java/org/terasology/world/block/entity/BlockEntitySystem.java

Fixes #3066 by adding a check to catch situations in which the particle prefab doesn't exist, such as when the Core module isn't enabled
Run BuilderSampleGameplay. Break a block. Should not get a `NullPointerException` and the block should disappear.
Admittedly I think behavior a while ago didn't even include a physics cube dropping - just the active block you place changes to the last you broke.
Nothing really. There are better fixes, such as grabbing the PrefabManager to see if the prefab exists before trying to use it, but at that point you might get tempted to try to fix it deeper. Should we cache the dust prefab in the system so we don't need to find it every time? Would that cause trouble if the player modifies the prefab on disk and wants a hot reload? Etc.
Ultimate fix would be …

Somewhat hacky fix for #3066 - validate the particle prefab being available

---

engine/src/main/java/org/terasology/logic/players/FirstPersonClientSystem.java

Fixes  #3067 by preventing the held item component deletion. The mesh is removed when held but otherwise it is untouched. This is a temporary fix while a better solution will be underway.
How to test:
Plonk down the starting chest, you'll see that it now has items inside. 
I've tested it thoroughly before judging it as an ok fix, but I might miss something, so a secondary test would be neat to have before merging :)

Prevent chests from losing items.

---

engine/src/main/java/org/terasology/config/facade/TelemetryConfiguration.java
engine/src/main/java/org/terasology/config/facade/TelemetryConfigurationImpl.java
engine/src/main/java/org/terasology/logic/health/EntityDestructionAuthoritySystem.java
engine/src/main/java/org/terasology/telemetry/GamePlayStatsComponent.java
engine/src/main/java/org/terasology/telemetry/TelemetrySystem.java
engine/src/main/java/org/terasology/telemetry/TelemetryUtils.java
engine/src/main/java/org/terasology/telemetry/metrics/BlockDestroyedMetric.java
engine/src/main/java/org/terasology/telemetry/metrics/BlockPlacedMetric.java
engine/src/main/java/org/terasology/telemetry/metrics/CreatureKilledMetric.java
engine/src/main/java/org/terasology/telemetry/metrics/GameConfigurationMetric.java
engine/src/main/java/org/terasology/telemetry/metrics/GamePlayMetric.java
engine/src/main/java/org/terasology/telemetry/metrics/Metric.java
engine/src/main/java/org/terasology/telemetry/metrics/ModulesMetric.java
engine/src/main/java/org/terasology/telemetry/metrics/SystemContextMetric.java
engine/src/main/resources/assets/i18n/menu.lang
engine/src/main/resources/assets/i18n/menu_en.lang

Follows-up to #3075, uncover timezone info in telemetry

uncover timezone and rename

---

engine/src/main/java/org/terasology/rendering/dag/nodes/InitialPostProcessingNode.java

Fixes issue #3092.
Testing: Start a new game with "vignette" option enabled, and go inside water.
Expected behaviour: water will be dark and murky ("tinted").

Fix underwater tint not working

---

engine/src/main/java/org/terasology/logic/console/commands/CoreCommands.java

Fixes #3094 
Open the console and type `help give` It will display `Required Permission Level - cheat`

Permission level displayed for a command on using help

---

engine/src/main/java/org/terasology/logic/health/EntityDestructionAuthoritySystem.java

Thanks for finding the bug！
Fix #3091 
When a Torch destroy because of the `supportRemovedDamage`， there is no instigator. Add a null pointer checker to instigator.
Break a block below a billboard plant, torch, or loose rock, there will be no NPE and the plant or torch or rock is destroyed as well.
By this way, the Torch destroyed because of `supportRemovedDamage` doesn't count as a block destroyed.

[Telemetry] block destroyed NPE fix

---

engine/src/main/java/org/terasology/rendering/nui/CoreScreenLayer.java

This closes #3101.  The new lifecycle method is called both when the
screen is first opened (as the existing `onOpened`), as well as when a
screen that's already open is made visible again (as `onShow`).
Unfortunately, I couldn't see any easy way to add automated tests for the UI system.  Since there aren't any existing tests for this system, either, and this is a very simple change, I figure this may be okay.  Anyway, I tested this manually by adding a temporary logger statement inside the method and clicking around the menu system.
Nothing I'm aware of.

Add `onScreenOpened` lifecycle method to `CoreScreenLayer`.

---

engine/src/main/java/org/terasology/logic/console/ConsoleSystem.java

Fixes #2990 
1. Start up 2 Terasology clients and connect to a server with client 1.
2. Connect to the server with client 2 and confirm that client 1 receives a popup notification.
3. Send a message from client 2 and confirm that client 1 receives a popup notification.
4. Open the chat window on client 1 (leave it open for the remaining steps).
5. Send a message from client 2 and confirm that client 1 sees the message, but does not receive a popup notification.
6. Disconnect client 2 from the server and confirm that client 1 sees the notification, but does not receive a popup notification.

Fix duplicate chat message notifications

---

engine/src/main/resources/assets/shaders/ssao_frag.glsl

As things stand, with the SSAO setting enabled, items have a black "halo" around them, caused due to a huge difference in depths of adjecent pixels. The traditional way to handle this is by using a "rangeCheck" function, that ignores pixels with a huge difference in depth. This was already implemented in Terasology, but the halo still persisted.
Slightly tweaks the parameters of rangeCheck, to better handle the difference check.
The SSAO effect in general should remain unchanged, and should still apply to hand-held items.
Because who doesn't like images? :D
Before | After

Slight SSAO Tweak

---

engine/src/main/java/org/terasology/engine/subsystem/DisplayDevice.java
engine/src/main/java/org/terasology/engine/subsystem/headless/device/HeadlessDisplayDevice.java
engine/src/main/java/org/terasology/engine/subsystem/lwjgl/LwjglDisplayDevice.java
engine/src/main/java/org/terasology/engine/subsystem/lwjgl/LwjglGraphics.java
engine/src/main/java/org/terasology/rendering/cameras/PerspectiveCamera.java
engine/src/main/java/org/terasology/rendering/dag/nodes/FinalPostProcessingNode.java
engine/src/main/java/org/terasology/rendering/opengl/FBO.java
engine/src/main/java/org/terasology/rendering/opengl/ScreenGrabber.java
engine/src/main/java/org/terasology/rendering/opengl/fbms/DisplayResolutionDependentFBOs.java
engine/src/main/java/org/terasology/rendering/world/WorldRendererImpl.java

Allows the DisplayDevice class to act as an observable system, that generates an event for resizing.
As things stand, certain systems in Rendering Land (like Cameras and DisplayResolutionDependentFBOManagers) should react to resizing events, but due to lack of the events, they either react late or they have to manually check `Display.isResized()`. For instance, in the screenshot attached, the world is rendered incorrectly (squashed) because perspectiveCamera does not immediately register the change.
With these events, it should also be possible to optimize certain parts of the code like not regenerating the projectionMatrix every frame, which currently happens.

Display events

---

engine/src/main/java/org/terasology/logic/players/MenuControlSystem.java

Solves #2939 by closing the overlay prior to pushing the death screen. 
Problem was happening because the ping/online players is an overlay and therefore is not actually in the screen stack and won't be closed when the death screen is pushed (death screen is set to not have lower screens visible).
I think functionally overlays and screens work as intended so no need to change their functionality, just this specific case, as overlays are "above" other elements and therefore should still show with screens displayed.
Go into game, hit tab to show online players then go into console and kill with online players screen open, screen should close and allow access to death screen.
Open/close online players to make sure that still functions. 
Kill with out player screen open to verify it still …

Close online player overlay before showing death screen

---

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/videoSettings/VideoSettingsScreen.java

So far, the video settings page contained an invalid variable reference for vrSupport, which caused an error to log every time you opened the video settings:
`[main] WARN  o.t.r.nui.databinding.BindHelper - Failed to resolve property oculusVrSupport of type class org.terasology.config.RenderingConfig - is the getter or setter missing?`
This PR fixes that reference.
Testing: Try opening the video settings page without the PR, and you should get the warning. With the PR, that warning should be gone.

Fixed "Failed to resolve property oculusVrSupport" message

---

engine/src/main/java/org/terasology/engine/module/ExternalApiWhitelist.java

Adds the `jdk.internal.reflect` to the API whitelist for modules to fix the compatibility issue with Java 9 as reported in #3106. I tested with OpenJDK 9 and appears to work correctly.
As you can see in the crash log reported by @Dariost in the issue, right before throwing the exception there is a line which says `02:40:14.218 [main] ERROR o.t.module.sandbox.ModuleClassLoader - Denied access to class (not allowed with this module's permissions): jdk.internal.reflect.ConstructorAccessorImpl`. So in my understanding there are modules which use code that relies on reflection, and the new JVM implementation uses additional internal classes for reflection and the custom filtering classloader denies access to said classes from sandboxed modules. So "unlocking" the mentioned package seems to …

Add jdk.internal.reflect to ExternalAPIWhitelist for Java 9 compatibility (fixes #3106)

---

engine/src/main/java/org/terasology/rendering/nui/widgets/UIImage.java

Closes #2872.
How to test: In any UI file using a non-stretching skin, add the `"ignoreAspectRatio": true` attribute to a UIImage, and change the width/height out of propotion and watch the image get stretched.
Sample: (Top is without ignoreAspectRatio, bottom is with ignoreAspectRatio)

Added new "ignoreAspectRatio" attribute to UIImage

---

engine-tests/src/test/java/org/terasology/entitySystem/PojoEventSystemTests.java
engine/src/main/java/org/terasology/entitySystem/event/internal/EventSystemImpl.java

`unregisterEventReceiver` did not unregister receivers that had no components associated with them (general vs specific receivers). Adds a clause for handling this case (and a test to prove it)
Run the test suite :3

fix for unregistering a "general" event receiver

---

engine/src/main/java/org/terasology/rendering/dag/nodes/RefractiveReflectiveBlocksNode.java

Originally, the static variables were declared after the instance variables, resulting in 14 Checkstyle violations. I moved the instance variables below the static variables to fix these issues.

RefractiveReflectiveBlocksNode.java Checkstyle Fix

---

engine/src/main/java/org/terasology/world/block/entity/neighbourUpdate/NeighbourBlockFamilyUpdateSystem.java

just realized a potential problem for the case when the player is holding onto an item that isn't a BlockItemComponent. Full block items do not have the BlockItemComponent component.

generalized event handler for  OnBlockItemPlaced

---

engine-tests/src/test/java/org/terasology/world/block/shape/BlockShapeTest.java

For pull request #3042 I implemented libgdx's bullet wrapper. I'm not sure about the shape collision boxes are the same between the variations of bullet. I plan to write a couple more test, but I wanted to make sure I'm not doing anything wrong in terms of this integration test and any suggestions would be good in terms of improving this.

added shape test

---

engine/src/main/java/org/terasology/rendering/logic/FloatingTextComponent.java
engine/src/main/java/org/terasology/rendering/logic/FloatingTextRenderer.java

Adds a `boolean` to the `FloatingTextComponent` called `isOccluded` that occludes the floating text if enabled. This patch simply enables/disables depth testing based on the value of `isOccluded`.
Place a `FloatingTextComponent` behind an obstacle with `isOccluded` set to `true`. The text will not be visible. It will, however, be visible behind an obstacle with `isOccluded` set to `true`.

Hide FloatingTextComponent behind objects

---

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/ServerListDownloader.java

Fixes #3069 
I am not sure if there is a way of testing this, I couldn't re-create the error myself. On changing just the `masterServer` in `config.cfg`, the downloader tries to download from `defaultAddress` which has been set to meta.terasology.org in `NetworkConfig.java` and successfully downloads it. However when I changed that as well, as proper message saying "Error Downloading Server List!" was displayed. However I understand that the error caused was due to the empty list returned by the server, so I have added a simple check for that.

Check if empty server list is obtained and display a proper message

---

engine/src/main/java/org/terasology/logic/players/DebugControlSystem.java
engine/src/main/java/org/terasology/rendering/world/viewDistance/ClientViewDistanceSystem.java

Fixes #3141 
(Discussed with @Cervator could not reach a conclusion on the right place for this to be moved)

Tidy up / refactor DebugControlSystem.

---

build.gradle

Brings in https://github.com/MovingBlocks/TeraConfig/releases/tag/v1.2.0 to the engine - two tiny tweaks for Checkstyle, including the fix for #3113
Does enable nagging over empty Javadoc so it'll add some new warnings.
Requires updating the metrics config files via `gradlew extractConfig` or it won't make a difference. On the plus side no IntelliJ restart needed, just hit the button that reloads Checkstyle rules!

Slight update to the code metrics / scanning stuff.

---

module.groovy

This enhances PR #3164 from @digitalripperynr some - contains a variety of code quality and clarity improvements I think would be a bit much to expect from a GCI task, since you can kinda keep moving and changing things around a while before settling on something that seems satisfactory ;-)
I used fairly granular commits to point out various good practices and to keep the changes easier to see.
One extra enhancement is favoring the user-supplied remote over the default Git clone target under the Terasology org. The module repo will now be cloned from the user-supplied remote *but* that will be named accordingly while `origin` gets added as well, pointing to the Terasology org version of the module.
Sample output (tweaked a little for clarity):
```
C:\Dev\Terasology\Git\Terasology>groovyw …
```

Refactor groovy module script - builds on #3164

---

engine/src/main/java/org/terasology/logic/inventory/ItemPickupAuthoritySystem.java

Resolves #3158.
Load a world with the the BasicCrafting module enabled. Instead of a NPE as detailed in #3158 being thrown, an appropriate warning for the absence of a block family for the specified prefab is logged.

Null check and warning log in ItemPickupAuthoritySystem if no block family for a block is present

---

engine/src/main/java/org/terasology/engine/bootstrap/EnvironmentSwitchHandler.java
engine/src/main/java/org/terasology/engine/modes/StateIngame.java

Fixes a compile error in specification-compliant Java compilers, of which javac is not one.

Fix typos and wildcard error in EnvironmentSwitchHandler

---

engine/src/main/java/org/terasology/world/chunks/CoreChunk.java
engine/src/main/java/org/terasology/world/chunks/internal/ChunkImpl.java

Added overload for setBiome() and getBiome() with BaseVector3i, like set/getBlock() and set/getLiquid() already had.

Added overloads for methods in ChunkImpl

---

engine/src/main/java/org/terasology/rendering/nui/widgets/UIRadialRing.java
engine/src/main/java/org/terasology/rendering/nui/widgets/UIRadialSection.java

Brings UIRadialRing to usable state. Previous version was throwing an exception related to binding, so I converted these binded properties to standard ones (temporary fix).
I've added also some functionality to UIRadialRing and UIRadialSection to create them and manipulate during the runtime. Previous version accepted only values from 
Just open the RadialRing example from TutorialNui. At least it works correctly now... :P

Added ability to manipulate UIRadialSections on the run (+quick bugfix)

---

engine-tests/src/test/java/org/terasology/engine/ComponentSystemManagerTest.java
engine/src/main/java/org/terasology/logic/console/commandSystem/MethodCommand.java

Fixes #2679 
As mentioned by @oniatus in that issue, download the Hunger module and remove `@Sender` annotation from `hungerCheck` command. Run the game as a host and you will see a log saying `Command hungerCheck contains a EntityRef without @Sender annotation, may cause a NullPointerException`. Already pinged oniatus for potential testing. 🙂

Add a logger when @Sender annotation is missing in EntityRef parameters

---

modules/Core/src/main/java/org/terasology/logic/actions/ExplosionAuthoritySystem.java

A modification of the ExplosionAuthoritySystem.
onDelayedExplosion event handler required the exploding entities to be a block. Now, with this modification, every entity which does have LocationComponent should be able to explode.
I have also made the DELAYED_EXPLOSION_ACTION_ID public to allow other systems use it, instead of statically defining it again in other places (Minesweeper module is the perfect example).

Allow non-block entities to explode

---

engine/src/main/java/org/terasology/rendering/nui/asset/UIDeltaFormat.java

Partially solution for the problems outlined in #3238.
Allows module creators to replace the skin for a particular UI screen by providing a delta file. Note that only support for skin has been added right now, and (if required) everything else will have to implemented separately.
(I'm considering you're developing Sample module, and want to replace the skin used in `toolbar.ui` (hud) with a custom skin (hudLarge))
- Checkout the PR
- Add the skin you want to replace an existing skin with (in my example, create `\modules\Sample\assets\skins\hudLarge.skin`)
- Add the delta for the UI skin you want to update (in my example, add a file `\modules\Sample\deltas\engine\ui\hud\toolbar.ui` with the following content: `{ "skin": "HUDLarge" }`)
- Run the game, and have the skin in `toolbar.ui` …

Added support for replacing skins through deltas

---

engine-tests/src/test/java/org/terasology/world/chunks/localChunkProvider/LocalChunkProviderTest.java
engine/src/main/java/org/terasology/world/chunks/internal/ReadyChunkInfo.java
engine/src/main/java/org/terasology/world/chunks/localChunkProvider/ChunkCache.java
engine/src/main/java/org/terasology/world/chunks/localChunkProvider/ChunkFinalizer.java
engine/src/main/java/org/terasology/world/chunks/localChunkProvider/ConcurrentMapChunkCache.java
engine/src/main/java/org/terasology/world/chunks/localChunkProvider/LightMergingChunkFinalizer.java
engine/src/main/java/org/terasology/world/chunks/localChunkProvider/LocalChunkProvider.java

This PR prepares an overhaul of the ChunkProviding system which is coupled to a different othere concepts like light merging, chunk loading and network transfer of chunks.
Changing any behavior of the system is out of scope of this PR and will be done in a follow up.
Therefore the goal here is just to put the system under test and do small refactorings to make the current API more expressive, even if it means to keep bugs or inintuitive concepts for the moment.

Remove light merging from LocalChunkProvider and refactor completeUpdate

---

engine/src/main/java/org/terasology/world/block/entity/BlockEntitySystem.java

Fixes #3196 and closes Terasology/Rails#32.
If `blockDamageModifierComponent` is null, uses `0` as the `impulsePower`.
Problem detailed in Terasology/Rails#32 does not occur anymore, needs confirmation.
@anuar2k

Add blockDamageModifierComponent null check

---

engine/src/main/java/org/terasology/engine/subsystem/config/BindsSubsystem.java
engine/src/main/java/org/terasology/input/InputSystem.java

More or less stole the fix @anuar2k put in #3219 (thanks! Even if it is just a restored method) but with a method in the old class that's flagged API that just calls the restored method in a new non-API place. So as far as the Dialogs module is concerned everything is back to normal and we're in API compliance again.
That is probably not ideal from a code perspective, since #2948 was doing some input binding overhaul activity, and this just puts one of the old methods back. I left TODOs in both places for future review and hopefully later on in some other input related effort we can sort it out. Maybe even in v2 since then we can break API in a valid fashion :D
Again may be interesting to @oniatus @msteiger @rzats @vampcat @ThompsonTyler @eviltak - but I'll merge this soonish just so work …

API fix for #3184 and minor code quality tweaks

---

engine/src/main/java/org/terasology/rendering/world/RenderableWorldImpl.java

Potential fix for #2590.
My current working hypothesis is:
Here is a method from RenderableWorldImpl:
```    @Override
public void onChunkLoaded(Vector3i chunkCoordinates) {
if (renderableRegion.encompasses(chunkCoordinates)) {
chunksInProximityOfCamera.add(chunkProvider.getChunk(chunkCoordinates));
Collections.sort(chunksInProximityOfCamera, new ChunkFrontToBackComparator());
}
}
```
We are directly adding the retrieved chunk to a list, which is then sorted. Now, java expects objects in the list to be non-null, which in turn leads to NPEs because `getChunk()` sometimes returns null.
Why does a chunk for which `onChunkLoaded` was called is null, I can't say. Maybe because the server sent a chunkLoaded request to a player, the player took some time to process the request during which …

Added null check

---

engine/src/main/java/org/terasology/utilities/subscribables/AbstractGeneralSubscribable.java
engine/src/main/java/org/terasology/utilities/subscribables/AbstractSpecificSubscribable.java
engine/src/main/java/org/terasology/utilities/subscribables/AbstractSubscribable.java
engine/src/main/java/org/terasology/world/block/BlockUri.java
engine/src/main/java/org/terasology/world/chunks/Chunk.java
engine/src/main/java/org/terasology/world/chunks/CoreChunk.java
engine/src/main/java/org/terasology/world/chunks/LitChunk.java
engine/src/main/java/org/terasology/world/generation/BaseFacetedWorldGenerator.java
engine/src/main/java/org/terasology/world/generator/WorldGenerator.java

Adds or edits a bunch of javadocs for a GCI task.
Since there are no code related changes, there is no testing required/possible.

Added some javadocs

---

.gitignore
engine/src/main/java/org/terasology/config/flexible/FlexibleConfigManagerImpl.java
engine/src/main/java/org/terasology/engine/paths/PathManager.java

Adds the `configs` folder to gitignore, and makes the path selection for the same more organized.
Potentially relevant to @emanuele3d @oniatus @eviltak

Rework path management to be more explicit

---

engine-tests/src/test/java/org/terasology/world/chunks/localChunkProvider/LocalChunkProviderTest.java
engine/src/main/java/org/terasology/rendering/world/RenderableWorldImpl.java
engine/src/main/java/org/terasology/world/chunks/RenderableChunk.java
engine/src/main/java/org/terasology/world/chunks/internal/ChunkImpl.java
engine/src/main/java/org/terasology/world/chunks/localChunkProvider/LocalChunkProvider.java
engine/src/main/java/org/terasology/world/chunks/remoteChunkProvider/RemoteChunkProvider.java

Improves the situation described in issue #1886.  In single player chunks become now visible when the nearby chunks got loaded and the chunk in the current location got light merged.
In multiplayer the amount of needed chunks before the first chunk becomes visible should be reduced from 7x7x7 to 5x5x5. It is an improvement but there is still room for further optimization.
Change the view distance to "Legally Bild (5x5x5)" and then start a single player game. Do this once with and without the changes of this PR. Without this PR only a single chunk is visible. With this PR 9 chunks are visible (3x3x3).

Show chunks faster and reduce amount of invisible chunks (Issue #1886).

---

engine/src/main/java/org/terasology/persistence/serializers/FieldSerializeCheck.java

For some reason there is a compiler warning at `NetworkEntitySerializer:206`, the line looks like this:
`deserializeOnto(entity, entityData, FieldSerializeCheck.NullCheck.<Component>newInstance());`
`FieldSerializeCheck` extends `DeserializeFieldCheck` and both define an inner class withe the same name.
The situation can be reproduced with the following situation:
```
public interface Super {
final class Something implements Super{
private static Something INSTANCE = new Something();
public static Something instance(){
return INSTANCE;
}
}
}
public interface Sub extends Super{
final class Something implements Sub{
private static Something INSTANCE = new Something();
public static Something instance(){
return INSTANCE;
}
}
}
```
Error: _Reference to 'Something' is ambiguous, both …

Fix ambiguous class definition in FieldSerializeCheck

---

engine/src/main/java/org/terasology/config/flexible/FlexibleConfigManagerImpl.java
engine/src/main/java/org/terasology/engine/paths/PathManager.java

Rolls back some of the changes made in #3252, because creating the directory in PathManager create the `configs` directory, but did not create the `configs/engine` (or `configs/moduleName`, in general case) directory.
Relevant to @emanuele3d and @Cervator.

Brought back ensureDirectoryExists() for FCs

---

engine/src/main/java/org/terasology/rendering/dag/RenderGraph.java
engine/src/main/java/org/terasology/rendering/world/WorldRendererImpl.java

Currently, with the fog setting on, during the night objects far away will appear illuminated instead of being pitch black.
Cause: There were two different causes. First, the `connect` method was not working properly. Second, an additional dependency of worldNodes had to be added to hazeIntermediateNode, so that haze did not contain objects/lighting.

Fixed weird light bugs with fog settings on

---

engine/src/main/java/org/terasology/rendering/dag/nodes/BloomBlurNode.java
engine/src/main/java/org/terasology/rendering/dag/nodes/BlurNode.java
engine/src/main/java/org/terasology/rendering/dag/nodes/DownSamplerForExposureNode.java
engine/src/main/java/org/terasology/rendering/dag/nodes/DownSamplerNode.java
engine/src/main/java/org/terasology/rendering/dag/nodes/HazeNode.java
engine/src/main/java/org/terasology/rendering/dag/nodes/LateBlurNode.java

This PR removes the setupConditions used by BlurNode and DownsamplerNode. This was probably required with the NodeFactory approach, but as things stand, it's very easy to move the contents of setupConditions to the constructor itself, which in turn makes the code cleaner and simpler.
This is an experimental move, and feedback would be appreciated.

Remove setupConditions

---

engine/src/main/java/org/terasology/logic/console/commands/CoreCommands.java
engine/src/main/java/org/terasology/rendering/world/WorldRendererImpl.java

As discussed in #3254, WR should not be a system, since that leads to 2 instances of this singleton class. This PR addresses the issue by removing the System status of the class, and instead registering the commands in it through `MethodCommand.registerAvailable`.
This PR contains a second smaller commit, that moves the `recompileShaders` command from CoreCommands to WorldRenderer.
As a side note, I still feel like WorldRenderer is becoming a monolith class, and we should consider moving commands to a different class. Any feedback on this idea would be great.

Converted WorldRenderer to a non-system class

---

.github/CONTRIBUTING.md

Fixed link for forum so that it no longer goes to incorrect page, and changed link for contributor-friendly issues to new label "Good first issue"
Previously, the links to the forum and "good first issue" for contributors did not work as intended. The forum link led to a "The requested page could not be found." error, and the contributor-friendly link to the label on Github is no longer relevant (outdated?) so I changed the link to the "Good First Issue" label.
You can test out the new links in the documentation 
`"please join us in our [forum](http://forum.terasology.org/forum/)"`
and 
```
"For finding easy to do issues to start with look at the [Contributor-friendly](https://github.com/MovingBlocks/Terasology/labels/Good%20First%20Issue) issues." 
respectively. 
```
N/A

Fixing broken links in Contributing.md

---

engine/src/main/java/org/terasology/rendering/nui/widgets/UIScrollbar.java

Scrollbars for ScrollableAreas in spaces large enough that they don't need to scroll are now fixed at 0, rather than flickering between the top and bottom when the scrollwheel is used.
Open the video config menu. Resize the window so that there is space left below the menu. Use the mouse scrollwheel.

Fix scrolling when there's already enough space.

---

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/SelectGameScreen.java

My attempt at fixing issue #3272 .
I added a select(0) method to the SelectGameScreen class. It now selects the first saved game(if it exists).
There's no need to verify if index 0 is valid, since index checking is already performed in the select() method.
1. Launch Terasology and create a saved world.
2. Go to the SelectGame screen from either 'Singleplayer' or 'Host Game' options in the main menu.
3. The first entry in the list is selected by default.

Fix for (beginner) issue #3272.

---

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/CreateGameScreen.java

Close #3159 
If a gameplay module in the "Create Game" screen has invalid dependencies, it will be displayed as red in the dropdown and the play button will be disabled (if it is selected).
Change the dependencies of an existing gameplay module such as JoshariasSurvival such that they are no longer valid (change the version, for instance) and try to use the template to create a new game.

"Create Game" Dependency Checking (#3159)

---

engine-tests/src/test/java/org/terasology/logic/console/ConsoleTest.java
engine/src/main/java/org/terasology/logic/console/Console.java
engine/src/main/java/org/terasology/logic/console/ConsoleImpl.java
engine/src/main/java/org/terasology/logic/console/Message.java
engine/src/main/java/org/terasology/logic/console/ui/ConsoleScreen.java
engine/src/main/java/org/terasology/logic/console/ui/NotificationOverlay.java
engine/src/main/java/org/terasology/rendering/world/WorldRendererImpl.java

Hi All,
I've added new method which we can use to solve an issue #3268. 
1. Open Console
2. Write "recompileShaders". So, at present we don't have new line between messages.
=> Recompiling shaders... done.
3. PROFIT :)
I'm not sure, will it be useful to add this functionality to ChatScreen widget. If so, let me know...

Add method for inline messages (Issue #3268)

---

engine-tests/src/test/java/org/terasology/particles/ParticlePoolTest.java

Alters the constructorTest() unit test to use JUnit 4's built in Exception testing framework. 
I made this change because I noticed that little try/catch block in the method, which included some code that could be considered "unreachable". 
It is a pretty small change, as this is my first Pull Request (just trying things out) 
To test, you could change the zero in the bottom ParticlePool to a '1' and run the test, which will cause it to fail. Then, change it back to '0' to make the test then pass.

Altered contructorTest() to use JUnit's built in Exception handling

---

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/MessagePopup.java

Add `@API` annotation to MessagePopup class for whitelisting, this enables the [ServerMOTD](https://github.com/Terasology/ServerMOTD) module  to work as expected.

Add @API annotation to MessagePopup class for whitelisting.

---

engine/src/main/java/org/terasology/rendering/dag/nodes/AlphaRejectBlocksNode.java
engine/src/main/java/org/terasology/rendering/dag/nodes/OpaqueBlocksNode.java
engine/src/main/java/org/terasology/rendering/dag/nodes/OpaqueObjectsNode.java
engine/src/main/java/org/terasology/rendering/dag/nodes/OverlaysNode.java
engine/src/main/java/org/terasology/rendering/dag/nodes/ShadowMapNode.java
engine/src/main/java/org/terasology/rendering/primitives/ChunkMesh.java

This pull request adds back face culling into nodes that can take advantage of it (#3044).
Back face culling can make rendering more efficient by not rendering triangles that are facing away from the camera. This is very useful for opaque models. The camera can't see through them, which means there's no point in rendering the away-facing triangles. As most of the blocks and objects are opaque, this change should speed up the rendering process.
- Added back face culling to OpaqueBlocksNode, OpaqueObjectsNode and ShadowMapNode.
- Wireframe mode disables back face culling in OpaqueBlocksNode and OpaqueObjectsNode.

Added back face culling to several nodes

---

engine/src/main/java/org/terasology/rendering/dag/nodes/PrePostCompositeNode.java
engine/src/main/resources/assets/shaders/prePostComposite_frag.glsl
engine/src/main/resources/assets/ui/menu/videoMenuScreen.ui
engine/src/main/resources/org/terasology/include/globalFunctionsFragIncl.glsl

I don't fully understand the intention behind volumetric fog or how it's meant to interact with haze, but the obvious issue is fixed and it now looks like fog.
Fix #2246. Re-enable menu item for volumetric fog. Add default setting for fog density and things. Remove volFogDensity, which looked like it was intended to make the fog never obscure things more than a certain amount, no matter how far away they are, as that seems to make it less useful for obscuring unloaded chunks.
The main part that resolves the original issue and the other issue this fix reveals is in globalFunctionsFragIncl.glsl .
Turn on volumetric fog and turn off inscattering/fog from the video menu. Look around a large open area in-game.
fogDensityAtViewer is fixed at 1, rather than being used.

Fix #2246 Volumetric Fog broken

---

config/groovy/util.groovy

Addresses condensed output format for long lists mentioned in #3279
Run: **groovyw module list**
Long lists are presented like below. Currently output format depends only on list size (threshold is hardcoded to 50). I think it would be a good idea to allow user override it and explicte specify which format he wants to use.
> --A: AdditionalFruits, AdditionalItemPipes, AdditionalRails, AdditionalVegetables, AdditionalWorlds, AdvancedBehaviors, Adventure, AdventureAssets, Alchemy, AlchemyPlantGenerator, AlterationEffects, Anatomy, AnotherWorld, AnotherWorldPlants
> --B: BasicCrafting, Behaviors, BlockDetector, BlockFamilyTutorial, BlockNetwork, BlockPicker, Books, BoomSticks, BoundlessWorlds, Breathing
> --C: CakeLie, Caves, ChangingBlocks, CheatsForAll, ChiselBlocks, ChrisVolume1OST, …

'groovyw * list' output condensed format

---

engine/src/main/java/org/terasology/engine/modes/loadProcesses/InitialiseWorldGenerator.java
engine/src/main/java/org/terasology/network/internal/NetworkSystemImpl.java
engine/src/main/java/org/terasology/rendering/cameras/Camera.java
engine/src/main/java/org/terasology/rendering/dag/nodes/WorldReflectionNode.java
engine/src/main/resources/assets/shaders/chunk_frag.glsl

The code for doing this all already exists, but was inactive, leading to surfaces below the water's surface being reflected above it. This was disabled in 296558, for unclear reasons, which makes me suspicious there's something I'm missing, but the result does seem to look better.
Activate global water reflections. View a water surface from a reasonably high angle, with well-lit surfaces beneath the water. Before this commit, they're reflected and obscure the correct reflections. After, they are omitted.
Before:
After:
~~In Builder-sample mode, this causes nothing below sea-level to render.~~

Re-activate removal of underwater surfaces from reflections.

---

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/selectModulesScreen/SelectModulesScreen.java

Small fix for the Issue #3050. 
The issue was that _getExplicitlySelectedModules_() method use _sortedModules_, and _filterText()_ method do the same. In this case, when we call _refreshSelection()_ it works with "filtered/searched" modules which might be are not explicitly selected. 
1. Create new game
2. Activate **JoshariasSurvival** module.
3. Search "help". You should get list from 3 items (In Game Help, In Game Help API, and WorkstationInGameHelp)
4. Activate and deactivate "In Game Help API". 
5. Check that search result is still yellow and presented.

Fix for filtered modules in SelectModulesScreen [Issue #3050]

---

engine/src/main/java/org/terasology/logic/characters/KinematicCharacterMover.java

When walking off a cliff, the player can press spacebar to jump mid-air. This shouldn't happen when their `numberOfJumpsMax` is set to 1 (one ground jump, no air jumps).
To fix this behavior, `numberOfJumpsLeft` is decreased when player's `isGrounded()` state is changed from grounded to not grounded.
As a side effect, this fixes the problem mentioned in PR #3269 (issue #3267), where the player was able to jump in water when he fell or walked into it.
Mid-air bug:
1. Build a tower 4-6 blocks high.
2. Walk off the top.
3. While falling, try to jump.
Water bug:
1. Walk or fall into water (without jumping).
2. While in water, try to jump.

Fix jumping in water and in mid-air

---

engine/src/main/java/org/terasology/rendering/nui/layers/ingame/PauseMenu.java

I'm not sure will it be useful, but from my perspective it could be useful. 
Well, to avoid mixing of layers I removed OnlinePlayers overlay when we open PauseMenu.
Also I think debug overlay is fine as is. Don't it?
1. Load/create game
2. Pressing TAB 
3. And press Esc together

Close online players overlay when pause menu opened

---

engine/src/main/java/org/terasology/logic/players/MenuControlSystem.java

Fixes #3139 .
Pressing Escape in the game pauses the world time.
Maybe the getPlayerCount() method could be a separate file, so that other developers may use it too.
The player count may be updated whenever a player joins/leaves so that the engine doesn't iterate over all clients every time the escape menu is pressed.
Maybe raise a new issue for this?

Fixes #3139-Pause on menu

---

engine/src/main/java/org/terasology/rendering/nui/layouts/relative/RelativeLayout.java

Fix #2755, stack overflow error caused by infinite recursion between the methods getRegion() and getTargetRegion(). If one element in the NUI editor is set to be below another element, and the second element is set to be above the first, then the getRegion() and getTargetRegion() repeatedly call each other when trying to resolve the location of the elements. This results in a stack overflow.
The fix is a simple try/catch checking for a StackOverflowError exception in the getRegion() method when calling the getTargetRegion() method. The exception only fires when the game would otherwise crash, so the performance impact is minimal.
The NUI editor seems to be a bit buggy, so it is best to test this issue by manually adding elements.
1. Open NUI editor
2. Select new screen and make sure it is …

fix issue #2755

---

engine/src/main/java/org/terasology/rendering/nui/layers/ingame/PauseMenu.java

On toggling the pause menu, if the player chooses to click on the `Back` button to return to the game, it results in the time still being paused (Only pressing `Escape` to return would unpause the time correctly). So, this fix unpauses the time state when the button is clicked.
- Create a game, and toggle pause menu (Pressing Esc)
- Click on the `Back` button to return to the game.
Nothing as of now.

Fixed : Time remains paused even when the back button is clicked in the pause menu.

---

engine/src/main/java/org/terasology/rendering/dag/nodes/AlphaRejectBlocksNode.java
engine/src/main/java/org/terasology/rendering/dag/nodes/OpaqueBlocksNode.java
engine/src/main/java/org/terasology/rendering/dag/nodes/RefractiveReflectiveBlocksNode.java
engine/src/main/java/org/terasology/rendering/dag/nodes/WorldReflectionNode.java
engine/src/main/java/org/terasology/world/block/tiles/WorldAtlasImpl.java
engine/src/main/resources/assets/shaders/chunk_frag.glsl

This PR:
1. Corrects the formulae used in the shaders to calculate parallax and normal maps.
1. Restricts parallax maps to not fetch colours from beyond the current texture.
1. Alters the default setting for parallax maps to improve their appearance.
1. Enables the use of parallax mapping without normal mapping.
Parts 2 and 3 resolve #2418, and part 4 deals with some of the confusingness of the settings discussed in that issue.
The branch 4Denthusiast/Terasology:parallax uses a more realistic version but looks worse due to parallax mapping being unable to extend the block's rendering beyond its original size. This branch is a compromise which makes the block appear flatter at shallow angles.
Activate parallax mapping in the video menu. Activating extra lighting as well should no longer be …

Fix parallax and normal mapping

---

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/SelectGameScreen.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/TwoButtonPopup.java
engine/src/main/resources/assets/i18n/menu.lang
engine/src/main/resources/assets/i18n/menu_en.lang
engine/src/main/resources/assets/i18n/menu_ru.lang
engine/src/main/resources/assets/ui/menu/twoButtonPopup.ui

I'd like to add additional confirmation popup before remove saved game to prevent accidental deletion.
1. Open SelectGame menu
2. Select saved game
3. Push Delete button

Add confirmation popup for button Delete on SelectGame screen

---

engine/src/main/java/org/terasology/world/block/Block.java
engine/src/main/java/org/terasology/world/block/family/AttachedToSurfaceFamily.java
engine/src/main/java/org/terasology/world/block/family/MultiConnectFamily.java
engine/src/main/java/org/terasology/world/block/internal/BlockBuilder.java

This is a small tweak where I exchange direction for rotation. For SegmentedPaths and MarcineScModule there is a separate interface that gets added to identify the new sides based on the rotation. This should remove some of this duplicate code by exchanging direction of the block for rotation. The side itself can be assumed to be pointing forward in the world and rotated accordingly.

changed Direction to rotation

---

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/WaitPopup.java

Currently, if something goes wrong during module loading, the module loading dialog goes away without explanation.
This change displays an error message informing the user that something went wrong, possibly with enough information to debug.
Fixes #3333

Show error if module loading fails.

---

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/selectModulesScreen/SelectModulesScreen.java
engine/src/main/resources/assets/i18n/menu.lang
engine/src/main/resources/assets/i18n/menu_en.lang
engine/src/main/resources/assets/ui/menu/selectModsScreen.ui

Fix for #3354, adds a label for the new module categories and a reset filters button that clears out all checked filters. 
Load up game, open up module select menu, and try selecting / resetting advanced filters.
* Translations needed for the new button and title

Adding Reset Filters button and module categories title (fix for #3354)

---

engine/src/main/java/org/terasology/engine/paths/PathManager.java

Once upon a time for some reason I forgot we determined the working directory when the engine starts based on where the `PathManager` class literally sat, including inside a jar file in some cases. This works fine for the game but in some cases when working in a standalone workspace (like module builds in Jenkins) that would mean the game's working directory became a jar file in the local system's Gradle cache - not ideal. Maybe before `Paths.get("")` was a thing we couldn't get a good dir with plain `File` ?
That broke the use of any sort of environment-based module unit tests in Jenkins and apparently also the ServerFacade which works somewhat similar at build time. The fix in this PR still seems to let the game work out of the correct dir, both from source, as a binary, starting as a …

PathManager fix - better identify working directory on launch

---

engine/src/main/java/org/terasology/world/BlockEntityRegistry.java
engine/src/main/java/org/terasology/world/internal/EntityAwareWorldProvider.java

This PR adds a method to `BlockEntityRegistry` that sets the entity at a given location. I've added it to this class because it already keeps track of entities linked with positions in the world.
This is something I wish to use for the multiblock style towers in my Tower Defense GSOC project but I can also see applications for it in modules like Simple Farming.
I also wish to note that this doesn't break the API as it only adds a method

Add method to set entity at location

---

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/CreateGameScreen.java
engine/src/main/resources/assets/ui/menu/createGameScreen.ui

The `id` of the game name `UIText` was `worldName` for some reason. Maybe it was used for worlds before or something. I've changed that to `gameName`. Just a little something I discovered while dealing with the create game flow.
Run the game. You can even do a search for `worldName` with the `Match Case` option ticked in IntelliJ. There should be 0 results.

Weird id of game name in CreateGameScreen

---

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/CreateGameScreen.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/MainMenuScreen.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/NewGameScreen.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/SelectGameScreen.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/StartPlayingScreen.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/UniverseSetupScreen.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/UniverseWrapper.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/WorldPreGenerationScreen.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/WorldSetupScreen.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/selectModulesScreen/AdvancedGameSetupScreen.java
engine/src/main/java/org/terasology/rendering/world/World.java
engine/src/main/java/org/terasology/rendering/world/WorldSetupWrapper.java
engine/src/main/resources/assets/ui/startPlayingScreen.ui
engine/src/main/resources/assets/ui/worldPreGenerationScreen.ui
engine/src/main/resources/assets/ui/worldSetupScreen.ui

The backend of the [new create game flow](https://goo.gl/hizreb). The player can now select different world generators and add a number of worlds to the game. Each world has a unique seed and the seed you see on the `AdvanceGameSetupScreen` is for the Universe. Each world is previewable individually on the `WorldPreGenerationScreen`. You have the option to configure and change the properties of your world in both `UniverseSetupScreen` and `WorldPreGenerationScreen`. There is a configure button which leads you to the `WorldSetupScreen`  where properties can be edited and the changes are successfully previewed in the `WorldPreGenerationScreen`.
A video of what's done: https://www.youtube.com/watch?v=qhKGQjEONmA

New create game flow backend | Part 2

---

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/CreateGameScreen.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/NewGameScreen.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/StartPlayingScreen.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/UniverseSetupScreen.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/UniverseWrapper.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/WorldPreGenerationScreen.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/WorldSetupScreen.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/selectModulesScreen/AdvancedGameSetupScreen.java
engine/src/main/java/org/terasology/rendering/world/WorldSetupWrapper.java

Nothing new to review in this PR compared to #3383 I've only addressed the review by vampcat. Will be pushing the last few things needed for the create game flow here.
Could use some help in the above-mentioned issues. :)

New create game flow backend | Final steps

---

engine/src/main/java/org/terasology/network/ServerPingSystem.java
engine/src/main/java/org/terasology/rendering/nui/layers/ingame/OnlinePlayersOverlay.java

Fixes #3318 
For some reason in function `determinePlayerAndPing` `allClients` would not contain all of the clients sometimes. I did not figure out why was that, but instead I used client entities directly from `pingMap`. It didn't contain client local to the server, but I just put it into the map with 5ms ping.
- Start two game clients
- Have one host and the other join
- Hold down TAB and observe both names listed

Fix to online players overlay not displayig all of the players

---

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/GameDetailsScreen.java
engine/src/main/resources/assets/ui/menu/selectModsScreen.ui

Fix NPE for DetailsGameScreen after releasing V2. 
After release we don't have an old version of some modules in our classpath. In this case all your saved game with the old core version can't be showed correctly on this screen.
See Core, BuilderSampleGameplay, CoreSampleGameplay.
1. Open DetailsGameScreen for any save with old core version.
2. See log for appropriate message.
3. Check that they aren't in list of modules.

Fix NPE after releasing v2 Core

---

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/NewGameScreen.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/SelectGameScreen.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/WorldPreGenerationScreen.java
engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/WorldSetupScreen.java
engine/src/main/java/org/terasology/rendering/nui/widgets/UISlider.java
engine/src/main/resources/assets/i18n/menu.lang
engine/src/main/resources/assets/i18n/menu_en.lang
engine/src/main/resources/assets/ui/menu/selectGameScreen.ui
engine/src/main/resources/assets/ui/newGameScreen.ui
engine/src/main/resources/assets/ui/worldPreGenerationScreen.ui
engine/src/main/resources/assets/ui/worldSetupScreen.ui

Disabled the time progression slider and world shape drop down. Changed the UI of the `WorldSetupScreen` and removed the Message Popup which appeared by clicking "Re-Roll".

New create game flow, final touches
