MovingBlocks/Terasology

- engine/src/main/java/org/terasology/world/sun/package-info.java
> Make o.t.world.sun available for modules

- engine/src/main/java/org/terasology/rendering/opengl/DefaultRenderingProcess.java
Removed .toString from screenshot dateformat
> Removed .toString from screenshot dateformat

- engine/src/main/java/org/terasology/logic/characters/CharacterSoundSystem.java
I honestly find the sound quite annoying after walking around for a while.
> Make landing sound volume depend on the velocity

- engine/src/main/java/org/terasology/rendering/nui/layers/ingame/inventory/InventoryGrid.java
- engine/src/main/resources/assets/ui/ingame/containerScreen.ui
- engine/src/main/resources/assets/ui/ingame/inventoryScreen.ui
* More efficient update routine
* Abstracted repeated getNumSlots
* Improved layout of inventory and containers.
> Inventory and Container Tweaks

- engine/src/main/java/org/terasology/rendering/nui/layers/ingame/inventory/InventoryGrid.java
Apologies, I forgot to update cells.remove() when I rewrote the code to be more style-conformant.
> cell remove fix

- engine/src/main/java/org/terasology/logic/console/ConsoleImpl.java
- engine/src/main/java/org/terasology/logic/permission/PermissionCommands.java
Minimal fix set for multiplayer commands:
* Fixes the sending of command results to calling players
* Adds the missing ```@Sender``` annotation to the usePermissionKey command
> Fix for #1482 - Multiplayer commands

- engine/src/main/java/org/terasology/network/internal/NetworkSystemImpl.java
This PR adds some more logging when hosting a server. All network interfaces that listen for incoming conns. are enumerated and their hostname (where available) and IP adress are logged.
This helps identifying the right hostname. An example can be found here:
http://jenkins.terasology.org/job/TerasologyHeadlessServer/7/console
> Add more logging info when hosting a server

- engine/src/main/java/org/terasology/entitySystem/metadata/EventMetadata.java
- engine/src/main/java/org/terasology/network/internal/NetClient.java
- engine/src/main/java/org/terasology/network/internal/ServerImpl.java
- engine/src/main/java/org/terasology/persistence/serializers/EventSerializer.java
- engine/src/main/java/org/terasology/persistence/typeHandling/SerializationException.java
- engine/src/main/java/org/terasology/physics/events/ChangeVelocityEvent.java
- engine/src/main/java/org/terasology/reflection/metadata/ClassMetadata.java
- engine/src/main/java/org/terasology/rendering/nui/ScreenLayerClosedEvent.java
Improved error handling around network events.
Added reporting of network events lacking default constructors.
Prevent crashes relating deserializing events without default constructors.
> Fix for #1516

- engine/src/main/java/org/terasology/monitoring/impl/PerformanceMonitorImpl.java
Added a small documentation snippet to the PerformanceMonitorImpl class, as discussed in PR #1494.
> Small documentation addition to PerformanceMonitorImpl

- engine/src/main/java/org/terasology/logic/characters/KinematicCharacterMover.java
- engine/src/main/java/org/terasology/logic/characters/MovementMode.java
This PR introduces a new movement mode DIVING and slightly tunes the movement behavior for swimming. 
* the player does not sink down under water
* the player only sinks very slowly when swimming (might be subject to change later)
> Swimming fix

- engine/src/main/java/org/terasology/rendering/logic/SkeletonRenderer.java
This PR fixes rare index out of bound exceptions during animation playback.
I also refacted the code a bit to make it more readable.
> Fix an index out of bound exception during animation playback.

- engine/src/main/java/org/terasology/logic/console/commandSystem/AbstractCommand.java
The comparison of processed parameters with command parameters now skips the sender.
fixes #1541
> Fix for console suggestion throwing IOOBE

- engine/src/main/java/org/terasology/config/SystemConfig.java
- engine/src/main/java/org/terasology/monitoring/chunk/ChunkMeshInfo.java
- engine/src/main/java/org/terasology/monitoring/chunk/ChunkMonitor.java
- engine/src/main/java/org/terasology/monitoring/chunk/ChunkMonitorEvent.java
- engine/src/main/java/org/terasology/rendering/world/ChunkMeshUpdateManager.java
- engine/src/main/java/org/terasology/rendering/world/RenderableWorldImpl.java
- engine/src/main/java/org/terasology/rendering/world/WorldRendererLwjgl.java
- engine/src/main/java/org/terasology/world/chunks/RenderableChunk.java
- engine/src/main/java/org/terasology/world/chunks/internal/ChunkImpl.java
Removed the notion of VerticalChunkMeshSegments from SystemConfig. 
Everything else is a consequence, including chunks no longer having submeshes and related methods.
> Removed the notion of VerticalChunkMeshSegments from SystemConfig and everywhere else.

- engine-tests/build.gradle
- modules/Core/build.gradle
Tested on Jenkins - runs without test failure (as before)
http://jenkins.terasology.org/job/TerasologyTemp/10/
I'd really love to have the PR builder plugin for Jenkins working so I'd not have to do it manually each time I upgrade dependency versions :wink:
> Update junit to 4.12 and mockito to 1.10.19

- engine/src/main/java/org/terasology/config/PlayerConfig.java
- engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/CieCamColors.java
This also removes the unused CieCAM color samples.
> Auto-generate default player name and color

- engine/src/main/java/org/terasology/rendering/logic/MeshRenderer.java
Fix for invisible translucent mesh bug as reported by @skaldarnar 
There are still some rendering issues related the interaction of translucent mesh and depth blur.
> Brought alpha-blended mesh rendering in line with opaque mesh rendering.

- engine/src/main/java/org/terasology/utilities/random/Random.java
I use this in a weather module and it is general enough to deserve it's own function in Random.
> Adds a nextGuassian function with mean and stdDev parameters

- engine/src/main/java/org/terasology/network/NetworkSystem.java
- engine/src/main/java/org/terasology/network/internal/AbstractClient.java
- engine/src/main/java/org/terasology/network/internal/LocalClient.java
- engine/src/main/java/org/terasology/network/internal/NetClient.java
- engine/src/main/java/org/terasology/network/internal/NetworkSystemImpl.java
- engine/src/main/java/org/terasology/network/internal/ServerConnectionHandler.java
Reasoning: Commands reference players by name.
Please note: This pull request does not change the handling of duplicate player ids.
> Enforce unique player names.

- engine/src/main/java/org/terasology/network/internal/AbstractClient.java
Unique player names are still enforced. If the user picks a name
that is used, he will get the wish name + a small number.
Reasoning for letting all players rename as they want:
They can create new profiles anyway. Cleanup up old profiles
isn't fun, so the goal should be to encourage players to keep
their profiles.
> User player name & color settings even when a known player joins.

- engine/src/main/java/org/terasology/rendering/opengl/FBO.java
- engine/src/main/java/org/terasology/rendering/opengl/LwjglRenderingProcess.java
- engine/src/main/java/org/terasology/rendering/opengl/PBO.java
- engine/src/main/java/org/terasology/rendering/shader/ShaderParametersCombine.java
- engine/src/main/java/org/terasology/rendering/shader/ShaderParametersLightGeometryPass.java
- engine/src/main/java/org/terasology/rendering/shader/ShaderParametersLightShaft.java
- engine/src/main/java/org/terasology/rendering/shader/ShaderParametersPost.java
- engine/src/main/java/org/terasology/rendering/shader/ShaderParametersSSAO.java
- engine/src/main/java/org/terasology/rendering/shader/ShaderParametersSobel.java
Resubmitting 2 out of 3 commits from PR #1640. 
The third commit was attempting to address a bigger issue that should be dealt with separately, as pointed out by @msteiger.
> Moving fbo+pbo out of lwjgl rendering process (redux)

- engine/src/main/java/org/terasology/config/NetworkConfig.java
As mentioned / suggested by @Cervator
> Use localhost as default server entry for new config files

- engine/src/main/java/org/terasology/input/binds/general/OnlinePlayersButton.java
- engine/src/main/java/org/terasology/logic/chat/ChatMessageEvent.java
- engine/src/main/java/org/terasology/logic/console/commands/ServerCommands.java
- engine/src/main/java/org/terasology/logic/notifications/NotificationMessageEvent.java
- engine/src/main/java/org/terasology/logic/players/MenuControlSystem.java
- engine/src/main/java/org/terasology/logic/players/PlayerUtil.java
- engine/src/main/java/org/terasology/rendering/nui/layers/ingame/OnlinePlayersOverlay.java
- engine/src/main/resources/assets/prefabs/player/client.prefab
- engine/src/main/resources/assets/skins/onlinePlayersOverlay.skin
- engine/src/main/resources/assets/ui/onlinePlayersOverlay.ui
This pull request makes it possible to display a list of all online players by holding [TAB].
@immortius  this pull request makes client entities be synchronized to all players. Is anything speaking against that?
> Online player list

- engine-tests/src/main/java/org/terasology/DisplayEnvironment.java
- engine-tests/src/main/java/org/terasology/HeadlessEnvironment.java
- engine-tests/src/test/java/org/terasology/entitySystem/PojoEntityManagerTest.java
- engine-tests/src/test/java/org/terasology/entitySystem/PojoPrefabManagerTest.java
- engine-tests/src/test/java/org/terasology/entitySystem/PrefabTest.java
- engine-tests/src/test/java/org/terasology/persistence/EntitySerializerTest.java
- engine-tests/src/test/java/org/terasology/persistence/internal/StorageManagerTest.java
- engine-tests/src/test/java/org/terasology/world/EntityAwareWorldProviderTest.java
- engine/src/main/java/org/terasology/asset/AssetManager.java
- engine/src/main/java/org/terasology/asset/AssetManagerImpl.java
- engine/src/main/java/org/terasology/engine/TerasologyEngine.java
Extract an interface out of AssetManager.
No functional changes.
> Extract interface from AssetManager

- engine/src/main/java/org/terasology/world/block/entity/BlockCommands.java
Reasoning: The command is not worth fixing for multiplayer as it is
useless. Blocks can be placed via right click. The bad thing about the
command is that it appears to be working but in multiplayer too, but
the blocks exist only on client side only.
Interesting for the future might be a command for placing multiple
blocks at once at a certain location but as it is the command is
useless.
> Remove the placeBlock command as it does not work in multiplayer.

- build.gradle
- config/gradle/common.gradle
- engine-tests/src/test/java/org/terasology/utilities/WhiteNoiseTest.java
- engine/build.gradle
- engine/src/main/java/org/terasology/input/binds/general/OnlinePlayersButton.java
- engine/src/main/java/org/terasology/logic/players/PlayerUtil.java
- engine/src/main/java/org/terasology/rendering/nui/layers/ingame/OnlinePlayersOverlay.java
* Set JDK version to 1.8
* Fixed residual javadoc errors
* Updated to gestalt 2.3.0-RC1 and latest versions of javassist and reflectasm
> Switched to Java 8

- engine/src/main/java/org/terasology/rendering/primitives/BlockMeshGenerator.java
- engine/src/main/java/org/terasology/rendering/primitives/BlockMeshGeneratorSingleShape.java
- engine/src/main/java/org/terasology/rendering/primitives/BlockMeshGenerator_SingleShape.java
- engine/src/main/java/org/terasology/rendering/primitives/ChunkTessellator.java
- engine/src/main/java/org/terasology/world/block/Block.java
A single step change, the minimum required to have customized block rendering by mod/block.  Later PR's will enhance this but as it is this is fully functional.
> Block rendering update

- engine/src/main/java/org/terasology/logic/characters/events/ActivationRequest.java
> Fix NullPointerException on instigator access on server.

- engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/AddServerPopup.java
- engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/JoinGameScreen.java
- engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/ServerListDownloader.java
This also adds a few usability tweaks.
Fixes #1687
> Sync lifetime of ServerInfoService with join game screen

- build.gradle
- engine/src/main/java/org/terasology/engine/modes/StateIngame.java
- engine/src/main/java/org/terasology/engine/modes/loadProcesses/JoinServer.java
- engine/src/main/java/org/terasology/engine/modes/loadProcesses/RegisterMods.java
- engine/src/main/java/org/terasology/engine/module/ModuleManagerImpl.java
Fixes an issue where the asset system may be asked to reload assets from a closed environment.
> Fix for ordering environment close<->asset system environment switch

- engine/build.gradle
> Updated to gestalt 4.0.3, fixing an issue with compiling under Eclipse

- engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/SelectModulesScreen.java
- engine/src/main/resources/assets/ui/menu/selectModsScreen.ui
> Remove 'Enable All' modules button

- engine/src/main/java/org/terasology/world/block/loader/BlockFamilyDefinitionFormat.java
Fixes incorrect inheritance of freeform block family factory by child block family definitions
> Addressing #1790

- build.gradle
- engine/build.gradle
- modules/Core/build.gradle
- modules/CoreSampleGameplay/build.gradle
Fix for #1777
* Updated gradle build to use reflections-0.9.9 and the new dom4j dependency
* Tweaks to engine cacheReflections because it randomly started thinking it was always up-to-date on me.
* Core and CoreSampleGamePlay also updated to use the new reflections, this will need to be pushed out to other modules and possibly improved in structure.
> Fix for #1777

- engine/src/main/java/org/terasology/world/block/tiles/BlockTile.java
- engine/src/main/java/org/terasology/world/block/tiles/NullWorldAtlas.java
- engine/src/main/java/org/terasology/world/block/tiles/WorldAtlas.java
- engine/src/main/java/org/terasology/world/block/tiles/WorldAtlasImpl.java
- engine/src/main/java/org/terasology/world/block/tiles/WorldAtlasSystem.java
Implemented auto reloading of the world atlas texture after a block tile is reloaded.
> World Atlas auto-reloading

- templates/module.txt
- Include snapshot in the version to come in line with the recent changes to the build system.
- Correct isServerSideOnly to be serverSideOnly as per the StandardModuleExtension enum.
> Update the template module.txt 

- engine/src/main/java/org/terasology/engine/ComponentSystemManager.java
- engine/src/main/java/org/terasology/engine/GameEngine.java
- engine/src/main/java/org/terasology/engine/TerasologyEngine.java
- engine/src/main/java/org/terasology/engine/modes/StateIngame.java
- engine/src/main/java/org/terasology/engine/subsystem/DisplayDevice.java
- engine/src/main/java/org/terasology/engine/subsystem/headless/device/HeadlessDisplayDevice.java
- engine/src/main/java/org/terasology/engine/subsystem/lwjgl/LwjglDisplayDevice.java
- engine/src/main/java/org/terasology/engine/subsystem/lwjgl/LwjglGraphics.java
- engine/src/main/java/org/terasology/input/InputSystem.java
- engine/src/main/java/org/terasology/rendering/nui/internal/NUIManagerInternal.java
Moved focus and mouse capture related methods out of engine and into DisplayDevice and InputSystem
> Moved more methods out of GameEngine

- engine-tests/src/test/java/org/terasology/persistence/ComponentSerializerTest.java
- engine/src/main/java/org/terasology/persistence/typeHandling/Serializer.java
A side effect of being more lenient of nulls on components.
> Allow the deserializer to set null to fields on components

- engine/build.gradle
Switched to gestalt 4.1.1 with fix for watcher threading.
> Fix for #1837

- engine/src/main/java/org/terasology/logic/players/LocalPlayerSystem.java
- engine/src/main/java/org/terasology/logic/spawner/AbstractSpawner.java
This currently affects non-trivial spawning code only (e.g. PolyWorld).
> Fix some minor issues around player spawning code

- engine/src/main/java/org/terasology/world/viewer/picker/CirclePickerClosest.java
Adds a constructor without radius function to `CirclePickerClosest`.
> Minor improvements of CirclePickerClosest

- engine/src/main/java/org/terasology/entitySystem/entity/internal/PojoEntityManager.java
- engine/src/main/java/org/terasology/logic/console/ui/UICommandEntry.java
- engine/src/main/java/org/terasology/rendering/nui/internal/NUIManagerInternal.java
* Fixes missing key event consumption resulting in the player moving about while typing in the console
* Also reorders add component event order to reduce errors caused by removing a component during its add event.
> Fix for Console input

- engine/src/main/java/org/terasology/rendering/nui/asset/UIFormat.java
- engine/src/main/resources/assets/ui/menu/selectModsScreen.ui
Logs a warning if unknown json entries are encountered during deserialization of `.ui` files.
> Warn on unrecognized fields in UIFormat

- engine/src/main/java/org/terasology/engine/subsystem/headless/assets/HeadlessTexture.java
- engine/src/main/java/org/terasology/rendering/assets/texture/Texture.java
- engine/src/main/java/org/terasology/rendering/assets/texture/subtexture/Subtexture.java
- engine/src/main/java/org/terasology/rendering/opengl/OpenGLTexture.java
Correctly subscribed subtextures to dispose when their origin texture is disposed.
> Fix for #1855

- engine/src/main/java/org/terasology/logic/nameTags/NameTagClientSystem.java
- engine/src/main/java/org/terasology/logic/nameTags/NameTagComponent.java
- engine/src/main/java/org/terasology/rendering/logic/FloatingTextComponent.java
- engine/src/main/java/org/terasology/rendering/logic/FloatingTextRenderer.java
> Support text scale in NameTag and FloatingText

- engine/src/main/java/org/terasology/world/generation/WorldBuilder.java
I believe that this was intended to be outside the loop in the first place already.
Ping @immortius for a quick review.
> Fix redundant entries in facet provider chain

- engine-tests/src/main/java/org/terasology/entitySystem/stubs/ListOfObjectComponent.java
- engine-tests/src/main/resources/assets/prefabs/withListContainer.prefab
- engine-tests/src/test/java/org/terasology/entitySystem/PrefabTest.java
- engine/src/main/java/org/terasology/persistence/serializers/EntityDataJSONFormat.java
> Fix serialization bug with lists in components

- engine/src/main/java/org/terasology/persistence/GenericObject.java
- engine/src/main/java/org/terasology/persistence/typeHandling/TypeSerializationLibrary.java
- engine/src/main/java/org/terasology/persistence/typeHandling/coreTypes/GenericObjectHandler.java
Simple and straightforward.
Completes #1945 together with #1947.
> Add GenericObject for delayed conversion

- engine/src/main/java/org/terasology/rendering/nui/UILayout.java
- engine/src/main/java/org/terasology/rendering/nui/layouts/CardLayout.java
- engine/src/main/java/org/terasology/rendering/nui/layouts/ColumnLayout.java
- engine/src/main/java/org/terasology/rendering/nui/layouts/FlowLayout.java
- engine/src/main/java/org/terasology/rendering/nui/layouts/MultiRowLayout.java
- engine/src/main/java/org/terasology/rendering/nui/layouts/RowLayout.java
- engine/src/main/java/org/terasology/rendering/nui/layouts/ScrollableArea.java
- engine/src/main/java/org/terasology/rendering/nui/layouts/ZoomableLayout.java
- engine/src/main/java/org/terasology/rendering/nui/layouts/relative/RelativeLayout.java
Complements the `void addWidget(UIWidget element, T hint);` method.
Requires a small tweak in MasterOfOreon/PickOneLayout.
> Add UILayout.removeWidget()

- engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/ModuleListDownloader.java
Reasoning:
Waiting for the list to load is annoying.
> Module list loading speedup

- engine/src/main/java/org/terasology/logic/behavior/BehaviorComponent.java
- engine/src/main/java/org/terasology/logic/behavior/BehaviorNodeComponent.java
- engine/src/main/java/org/terasology/logic/behavior/asset/BehaviorTree.java
- engine/src/main/java/org/terasology/logic/behavior/tree/SetAnimationNode.java
Also adds a `null` check to avoid unnecessary NPEs.
> Make Behavior assets available for modules

- engine/src/main/java/org/terasology/config/NetworkConfig.java
- engine/src/main/java/org/terasology/config/ServerInfo.java
- engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/AddServerPopup.java
- engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/JoinGameScreen.java
> Fix various issues in JoinGameScreen

- modules/Core/src/main/java/org/terasology/core/world/generator/facetProviders/DefaultFloraProvider.java
- modules/Core/src/main/java/org/terasology/core/world/generator/facetProviders/DefaultTreeProvider.java
- modules/Core/src/main/java/org/terasology/core/world/generator/facetProviders/PerlinHumidityProvider.java
Realized through a method
protected List<Predicate<Vector3i>> getFilters(GeneratingRegion region)
> Support custom filters in Tree and FloraProvider

- engine/src/main/java/org/terasology/math/Region3i.java
Required/Used by latest Cities develop branch.
> Use BaseVector in Region3i where possible without API break

- engine/src/main/java/org/terasology/logic/ai/HierarchicalAISystem.java
- engine/src/main/java/org/terasology/logic/characters/CharacterMovementSystemUtility.java
- engine/src/main/java/org/terasology/logic/health/HealthSystem.java
- modules/Core/src/main/java/org/terasology/core/world/generator/ClimateSimulator.java
- modules/Core/src/main/java/org/terasology/core/world/generator/ClimateSimulatorData.java
- modules/Core/src/main/java/org/terasology/core/world/generator/trees/RecursiveTreeGeneratorLSystem.java
- modules/Core/src/main/java/org/terasology/core/world/generator/trees/TreeGeneratorLSystem.java
These commits are a series of refactors aimed to improve code readability and maintainability without affecting code functionality. The JDeoderant code smell detection tool was used and the suggested refactors were implemented. The refactors are of a project for a Software Architecture and Design course with the goal of applying class concepts on open source software.
> Long method and God class code smell refactors

- engine/src/main/java/org/terasology/engine/modes/loadProcesses/CacheBlocks.java
- engine/src/main/java/org/terasology/logic/inventory/ItemPickupSystem.java
- engine/src/main/java/org/terasology/physics/HitResult.java
- engine/src/main/java/org/terasology/rendering/nui/layers/ingame/inventory/ItemCell.java
- engine/src/main/java/org/terasology/rendering/nui/layers/ingame/inventory/TransferItemCursor.java
- engine/src/main/java/org/terasology/rendering/primitives/BlockMeshGeneratorSingleShape.java
- engine/src/main/java/org/terasology/world/block/Block.java
- engine/src/main/java/org/terasology/world/block/internal/BlockBuilder.java
- modules/Core/src/main/java/org/terasology/core/logic/door/DoorSystem.java
I deleted some uses of deprecated methods
> Remove use of deprecated methods

- engine/src/main/java/org/terasology/logic/console/commands/CoreCommands.java
- engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/MainMenuScreen.java
- engine/src/main/resources/assets/ui/menu/mainMenuScreen.ui
- engine/src/main/resources/assets/ui/migTestScreen.ui
> Remove MIG layout test menu

- engine/src/main/java/org/terasology/config/InputConfig.java
Get a new config instance in order to have defaults in default.cfg.
Fix a part of #2064.
> Fix mouse sensitivity set to 0 when resetting input config.

- engine/src/main/java/org/terasology/config/InputConfig.java
- engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/inputSettings/InputSettingsScreen.java
> fix missing label in secondary input mapping description.

- engine/src/main/java/org/terasology/config/BindsConfig.java
- engine/src/main/java/org/terasology/input/DefaultBindings.java
- engine/src/main/java/org/terasology/input/binds/general/ConsoleButton.java
- engine/src/main/resources/default.cfg
Fixes #1511.
Now the config is sourced in code and not in default.cfg for the first startup.
Resolves conflicts between annotations and default config file.
> Allows to use multiple @DefaultBinding.

- engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/videoSettings/EnvironmentEffectsBinding.java
See http://jenkins.terasology.org/job/Terasology/1596/findbugsResult/type.-936980778/.
I don't know if it have an impact but it's easily repaired.
> Fix checking twice the same conditional in EnvironmentEffectsBinding.

- engine/src/main/java/org/terasology/engine/LoggingContext.java
- engine/src/main/java/org/terasology/logic/console/Console.java
- engine/src/main/java/org/terasology/logic/console/Message.java
- engine/src/main/java/org/terasology/logic/console/commands/CoreCommands.java
- engine/src/main/java/org/terasology/logic/console/commands/ServerCommands.java
- engine/src/main/java/org/terasology/logic/console/ui/ChatScreen.java
- engine/src/main/java/org/terasology/logic/console/ui/ConsoleScreen.java
- engine/src/main/java/org/terasology/persistence/internal/SaveTransaction.java
- engine/src/main/java/org/terasology/world/block/entity/BlockCommands.java
Removed 4 TODOs and refactor some code.
> Changes to Java 8 allowed structures to cleanup code.

- engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/inputSettings/InputSettingsScreen.java
- engine/src/main/resources/assets/skins/mainmenu.skin
- engine/src/main/resources/assets/ui/menu/videoMenuScreen.ui
Just a few tweaks to the video settings UI file, so it looks consistent with the input settings menu.
Before:
After:
> Improve video settings screen layout

- engine-tests/src/test/java/org/terasology/documentation/BindingScraper.java
- engine/src/main/java/org/terasology/logic/behavior/nui/package-info.java
This also registers the behavior editor button to a new category.
> Respect InputCategory entry for input bindings

- engine/src/main/java/org/terasology/entitySystem/entity/internal/BaseEntityRef.java
> Allow EntityRef.toFullDescription() to run in modules.

- README.markdown
- build.gradle
- config/gradle/artifactory.gradle
- config/gradle/common.gradle
- config/gradle/utility.gradle
- engine-tests/src/main/resources/module.txt
- engine/src/main/resources/engine-module.txt
- facades/PC/launchScripts/run_linux.sh
- facades/PC/launchScripts/run_macosx.command
- facades/PC/src/main/java/org/terasology/engine/Terasology.java
- modules/Core/build.gradle
- modules/Core/module.txt
- modules/CoreSampleGameplay/build.gradle
- modules/CoreSampleGameplay/module.txt
- templates/facades.gradle
- templates/version.txt
Tweaking at some Gradle and version info. Help text too. And pre-alpha -> Alpha!
Making PR just for Jenkins test and doc, merging shortly then doing a bunch of module version tweaks on top.
> Initial v1.0.0 release candidate prep

- NOTICE
> We're in 2016 (Happy new year !).

- engine/src/main/java/org/terasology/input/ControllerId.java
Transform ControllerId (interface of constants) into a "static" class.
Fix a checkstyle issue.
> Refactor ControllerInput to cleanup code.

- engine/src/main/java/org/terasology/input/lwjgl/JInputControllerDevice.java
> Add null check to avoid crashes when controller buttons not registered.

- engine/src/main/resources/assets/skins/mainmenu.skin
- engine/src/main/resources/assets/ui/menu/videoMenuScreen.ui
Some minor adjustments to the margins of subheadings to get some spacing to the left border:
> Adjust margins for subheadings

- engine/src/main/resources/assets/prefabs/player/player.prefab
> Adjust the character's gaze so that it does not peek into blocks above

- code_of_conduct.md
See #1975.
I set the report adress to cervator@gmail.com, we can change it later.
~~I also use a little antispam trick.~~
> Add Open Code of Conduct to the repo.

- engine/src/main/resources/assets/ui/menu/changeBindingPopup.ui
> Switch "Cancel" and "Ok" buttons on the Input Settings popup.

- engine-tests/src/test/java/org/terasology/documentation/ApiScraper.java
- engine/src/main/java/org/terasology/engine/module/ExternalApiWhitelist.java
- engine/src/main/java/org/terasology/engine/module/ModuleManagerImpl.java
> Refactor external whitelist to add it to ApiScraper

- engine/src/main/java/org/terasology/persistence/internal/SaveTransactionHelper.java
This patch tries to fix #2160:
Instead of crashing it should log now the following line:
``` The save job could not cleanup a temporarly created directory, it will retry once in one second```
> Try to fix #2160 by adding a delayed retry.

- engine/src/main/java/org/terasology/rendering/nui/widgets/UIDropdownScrollable.java
Similar to PR #2180, but without the long list of previous commits. Fixes #2179.
> Fixed showing of unnecessary scrollbar - follow-up from PR #2180

- engine/src/main/java/org/terasology/logic/characters/KinematicCharacterMover.java
- engine/src/main/java/org/terasology/logic/players/LocalPlayerSystem.java
A minor change to allow the use of the jump key and crouch keys to allow climbing up and down ladders respectively. Fixes #1345.
> Allow climbing ladders with jump/crouch keys.

- modules/Core/src/main/java/org/terasology/rendering/nui/layers/ingame/inventory/InventoryGrid.java
Proper fix of #2212 . Replaces catch added by #2215 logic that avoid the division through 0.
See  #2215
> Avoid catching of ArithmeticExceptions, by avoiding division through 0.

- engine/src/main/java/org/terasology/logic/console/ui/UICommandEntry.java
- engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/SelectModulesScreen.java
- engine/src/main/java/org/terasology/rendering/nui/widgets/TextChangeEventListener.java
- engine/src/main/java/org/terasology/rendering/nui/widgets/UIText.java
- engine/src/main/resources/assets/i18n/menu_en.lang
- engine/src/main/resources/assets/skins/mainmenu.skin
- engine/src/main/resources/assets/ui/menu/createGameScreen.ui
- engine/src/main/resources/assets/ui/menu/selectModsScreen.ui
> Warn modules

- engine/src/main/java/org/terasology/logic/characters/CharacterStateEvent.java
- engine/src/main/java/org/terasology/logic/characters/CharacterTeleportEvent.java
- engine/src/main/java/org/terasology/logic/characters/ServerCharacterPredictionSystem.java
- engine/src/main/java/org/terasology/logic/debug/MovementDebugCommands.java
- engine/src/main/java/org/terasology/logic/players/PlayerSystem.java
Make teleport command work in multiplayer.
API wise, character teleports can now be simply triggered on the server side by sending a CharacterTeleportEvent to the entity. So implementing a portal should be much simpler now.
Use the teleport command as remote client.
Can be merged after #1619 so that @HashCode55  does not have to do the merging.
@HashCode55: I started trying it out (because I was curious) before I read your reply and when I read it I was almost done. I hope you don't mind that I created this pull request.
> Make teleport command work in multiplayer.

- engine/src/main/resources/assets/i18n/menu_en.lang
- engine/src/main/resources/assets/ui/menu/createGameScreen.ui
- engine/src/main/resources/assets/ui/menu/selectModsScreen.ui
Just adds a label for filter in select modules screen next to modules search box.
.
.
Got some free time so added it.
> Added a label for filter.

- engine/src/main/java/org/terasology/logic/behavior/BehaviorSystem.java
- engine/src/main/java/org/terasology/logic/behavior/nui/BehaviorEditor.java
- engine/src/main/java/org/terasology/logic/behavior/nui/BehaviorEditorScreen.java
- engine/src/main/java/org/terasology/logic/behavior/tree/Actor.java
- engine/src/main/java/org/terasology/logic/behavior/tree/Interpreter.java
- engine/src/main/java/org/terasology/logic/behavior/tree/PlaySoundNode.java
- engine/src/main/java/org/terasology/logic/behavior/tree/SetAnimationNode.java
- engine/src/main/java/org/terasology/logic/behavior/tree/Status.java
- engine/src/main/java/org/terasology/logic/behavior/tree/Task.java
First changes for #2070
- some renamings and refactoring
- fixed a bug where the palette removed to many entries on collapse
- improved string representation of entities
Worked with L&S but probably not finished. Any ideas for junit-tests?
Small use-case: spawn some L&S creatures, open the behavior editor and try to create and attach a tree with some simple logic to one of them.
I used a repeat node with a squence: set target to local player - find path - move along path, to make a creature follow the player.
I suggest to use it as a base for the upcoming gsoc.
Note that the change breaks the API of the Actor class which is used in Pathfinding
> Behavior system cleanup and refactoring

- engine/src/main/java/org/terasology/rendering/opengl/GLSLMaterial.java
This resolves issue #966. This chunk of code just rebinds all the uniforms due to the fact that some uniforms may not update continuously at run-time. The shader is recompiled at this stage but, this ends up unbinding all the values bound to the last instance of the shader. This resolves the problem by just re-binds all the necessary uniforms. This problem may also exist on GLSL shader, but that issue has not shown up yet!
run the game and change the settings.
> fix to resolve problems with entities appearing as either white or black

- engine/src/main/java/org/terasology/rendering/opengl/PostProcessor.java
- engine/src/main/java/org/terasology/rendering/shader/ShaderParametersHdr.java
- engine/src/main/java/org/terasology/rendering/shader/ShaderParametersSky.java
- engine/src/main/java/org/terasology/rendering/world/WorldRenderer.java
- engine/src/main/resources/assets/shaders/hdr_frag.glsl
- engine/src/main/resources/assets/shaders/highp_frag.glsl
- engine/src/main/resources/assets/shaders/lightGeometryPass_frag.glsl
- engine/src/main/resources/org/terasology/include/globalDefinesIncl.glsl
- engine/src/main/resources/org/terasology/include/globalFunctionsFragIncl.glsl
ref:   #899 , #667 , #2113
Fixes some issues related to lights rendering near white values. There are still problems related to light rays still over saturating the image, but this should fix a lot of the major issues related to overblown lights. Torches that are close together will also tend to over saturate the image.
> fix problems related to light values blowing up

- engine/src/main/java/org/terasology/engine/modes/StateIngame.java
- engine/src/main/java/org/terasology/engine/modes/loadProcesses/AwaitCharacterSpawn.java
- engine/src/main/java/org/terasology/engine/modes/loadProcesses/CreateRemoteWorldEntity.java
- engine/src/main/java/org/terasology/engine/modes/loadProcesses/CreateWorldEntity.java
- engine/src/main/java/org/terasology/engine/subsystem/headless/renderer/HeadlessWorldRenderer.java
- engine/src/main/java/org/terasology/logic/particles/BlockParticleEmitterSystem.java
- engine/src/main/java/org/terasology/logic/players/PlayerSystem.java
- engine/src/main/java/org/terasology/rendering/cameras/OculusStereoCamera.java
- engine/src/main/java/org/terasology/rendering/logic/MeshRenderer.java
- engine/src/main/java/org/terasology/rendering/logic/SkeletonRenderer.java
- engine/src/main/java/org/terasology/rendering/opengl/PostProcessor.java
- engine/src/main/java/org/terasology/rendering/shader/ShaderParametersBase.java
- engine/src/main/java/org/terasology/rendering/shader/ShaderParametersPrePost.java
- engine/src/main/java/org/terasology/rendering/world/RenderableWorldImpl.java
- engine/src/main/java/org/terasology/rendering/world/WorldRenderer.java
- engine/src/main/java/org/terasology/rendering/world/WorldRendererImpl.java
- engine/src/main/java/org/terasology/rendering/world/viewDistance/ClientViewDistanceSystem.java
* WorldRenderer interface: trimmed and fully documented
* WorldRendederImpl class: some refactoring, added javadocs for class and main public methods
* minor changes to most other files are a consequence of the interface changes
Next mini-goal:
* documenting of RenderableWorld/RenderableWorldImpl
> Added javadocs, todos, refactored WorldRenderer/WorldRendererImpl

- engine/src/main/java/org/terasology/world/sun/BasicCelestialModel.java
Fixes #2276
Use a test module that listens for OnMidnightEvents. It should now get events.
None
> Fixes #2276 - fix midnight events

- engine/src/main/java/org/terasology/world/generation/WorldBuilder.java
Fixes #2260
Filters in https://github.com/Terasology/ShatteredPlanes finally working now!
> Fixed @Updates annotation to actually create the borders when requested

- engine/build.gradle
> Bump library versions

- engine/src/main/java/org/terasology/world/block/entity/BlockCommands.java
replaceBlock command is finished and tested to work in game. I also fixed some checkStyle issues on other commands.
> replaceBlocks Command is done!

- engine/src/main/java/org/terasology/rendering/nui/internal/NUIManagerInternal.java
Fix for dialogs not working
1. Open Terasology
2. Try to download a module
The download button will do nothing. Same with other actions that show certain dialogs.
> Fix non working dialogs

- engine/src/main/java/org/terasology/world/block/internal/BlockManagerImpl.java
Cache the Air block so that looking up air by ```BlockUri``` is reduced. This is important during chunk generation when changing from unknown to a block because the unknown block is given back as Air.  Each time air is given back, it has to then do a lookup of the air block by ```BlockUri``` which eventually is looked up based on ResourceUrn hash code which is expensive when you do it for every single block in the known world. 
Load a world, see how long it takes for all the chunk generation to cease.  This is different than having all chunks visible,  you must keep an eye on the chunk threads in the debug menu.  In my case I hooked up Yourkit profiler so that I could measure more accurately.
For my test I used the Builders World with a seed of "0" with Ultra view distance in a single …
> Reduce chunk generation time by ~50%

- engine/src/main/java/org/terasology/logic/characters/AffectMultiJumpEvent.java
- engine/src/main/java/org/terasology/logic/characters/CharacterMovementComponent.java
- engine/src/main/java/org/terasology/logic/characters/KinematicCharacterMover.java
This PR adds basic multijumping functionality to the base engine .
In the CharacterMovementComponent class, change the numberOfJumpsMax value to something greater than 1. Load up the game and see if you jump that same number of times.
> Allow multijumping capabilities and modification of multijumping using events

- engine/src/main/java/org/terasology/logic/characters/CharacterMovementComponent.java
- engine/src/main/java/org/terasology/logic/characters/KinematicCharacterMover.java
Fixes #2359 
Use the DoubleJumpPotion added following [this commit](https://github.com/Terasology/Alchemy/commit/9aacb0eb174173975b2e34a8501a40a617682f15) on the Alchemy module.
No conflicts.
Thanks for catching this @Cervator.
> Fixes #2359.

- engine/src/main/java/org/terasology/engine/subsystem/headless/renderer/HeadlessWorldRenderer.java
- engine/src/main/java/org/terasology/rendering/dag/BackdropNode.java
- engine/src/main/java/org/terasology/rendering/dag/ChunksAlphaRejectNode.java
- engine/src/main/java/org/terasology/rendering/dag/ChunksOpaqueNode.java
- engine/src/main/java/org/terasology/rendering/dag/ChunksRefractiveReflectiveNode.java
- engine/src/main/java/org/terasology/rendering/dag/DirectionalLightsNode.java
- engine/src/main/java/org/terasology/rendering/dag/FirstPersonViewNode.java
- engine/src/main/java/org/terasology/rendering/dag/LightGeometryNode.java
- engine/src/main/java/org/terasology/rendering/dag/Node.java
- engine/src/main/java/org/terasology/rendering/dag/ObjectsOpaqueNode.java
- engine/src/main/java/org/terasology/rendering/dag/OverlaysNode.java
- engine/src/main/java/org/terasology/rendering/dag/ShadowMapNode.java
- engine/src/main/java/org/terasology/rendering/dag/SkyBandsNode.java
- engine/src/main/java/org/terasology/rendering/dag/WorldReflectionNode.java
- engine/src/main/java/org/terasology/rendering/opengl/GraphicState.java
- engine/src/main/java/org/terasology/rendering/opengl/OpenGLUtils.java
- engine/src/main/java/org/terasology/rendering/opengl/PostProcessor.java
- engine/src/main/java/org/terasology/rendering/world/WorldRenderer.java
- engine/src/main/java/org/terasology/rendering/world/WorldRendererImpl.java
Eight new nodes for DAG (Directed Acyclic Graph), wrapping tasks that are related with rendering world.
- _ChunksAlphaRejectNode_
- _ChunksOpaqueNode_
- _ChunksRefractiveReflectiveNode_
- _DirectionalLightsNode_
- _FirstPersonViewNode_
- _LightGeometryNode_
- _ObjectsOpaqueNode_
- _OverlaysNode_
Check if there are any weirdness related to rendering of world. (chunks and other in-game entities)
> [RFR] Render World Nodes for DAG

- engine/build.gradle
Tiny tweak in Gestalt requested by @emanuele3d
> Update dependency on Gestalt to 5.1.1

- engine/src/main/java/org/terasology/world/internal/WorldProviderCore.java
Makes the setBlocks addition added by #2453 not break the Pathfinding module.
Build this PR with Pathfinding module. There should be no compile error.
> Add a default implementation for setBlocks.

- engine/src/main/java/org/terasology/rendering/nui/internal/CanvasImpl.java
Open the behaviour tree editor and select one of the nodes in the default behaviour tree. Drag it in a circle around the other and check that the line is properly drawn at all angles.
No outstanding issues!
> Fix an issue with drawLine() connecting wrong edges of a rectangle

- engine/src/main/java/org/terasology/entitySystem/entity/internal/PojoEntityManager.java
A memory leak fix, that is especially noticable in the setBlock benchmark available via the `showScreen benchmarkScreen` command.
The `EntitySetDeltaRecorder` class records changes to persistent entities
in order to forward them later on to the background saving thread.
It got informed about changes to temporary block entities, but did not
get informed about the silent destruction of those entities when the
entities were no longer needed to represent the block.
This patch marks the entity manager inform the `EntitySetDeltaRecorder`
indirectly about the destruction of the temporary block entities,
so that it knows that the entities do no longer need to be stored.
1. Run in game (with 2GB memory)
2. run the command `showScreen benchmarkScreen`
3. Use the dialog to start the …
> Fix a memory leak by properly clearing recorded data about temporary block entities

- engine/src/main/java/org/terasology/logic/delay/DelayedActionSystem.java
Fixes item 2 of issue #2473.
Use systems that utilize the delay system. See if they still function as expected.
> Added null checks to reduce NPEs.

- engine-tests/src/test/java/org/terasology/rendering/dag/RenderTaskListGeneratorTest.java
- engine-tests/src/test/java/org/terasology/rendering/dag/SetName.java
- engine-tests/src/test/java/org/terasology/rendering/dag/SetNameTask.java
- engine/src/main/java/org/terasology/rendering/dag/AbstractNode.java
- engine/src/main/java/org/terasology/rendering/dag/Node.java
- engine/src/main/java/org/terasology/rendering/dag/NodeTask.java
- engine/src/main/java/org/terasology/rendering/dag/RenderTaskListGenerator.java
- engine/src/main/java/org/terasology/rendering/dag/stateChanges/BindFBO.java
- engine/src/main/java/org/terasology/rendering/dag/stateChanges/DisableDepthMask.java
- engine/src/main/java/org/terasology/rendering/dag/stateChanges/DisableDepthTest.java
- engine/src/main/java/org/terasology/rendering/dag/stateChanges/EnableBlending.java
- engine/src/main/java/org/terasology/rendering/dag/stateChanges/EnableFaceCulling.java
- engine/src/main/java/org/terasology/rendering/dag/stateChanges/EnableMaterial.java
- engine/src/main/java/org/terasology/rendering/dag/stateChanges/EnableStencilTest.java
- engine/src/main/java/org/terasology/rendering/dag/stateChanges/SetFacesToCull.java
- engine/src/main/java/org/terasology/rendering/dag/stateChanges/SetStateParameter.java
- engine/src/main/java/org/terasology/rendering/dag/stateChanges/SetViewportToSizeOf.java
- engine/src/main/java/org/terasology/rendering/dag/stateChanges/SetWireframe.java
- engine/src/main/java/org/terasology/rendering/dag/tasks/BindFBOTask.java
- engine/src/main/java/org/terasology/rendering/dag/tasks/DisableMaterialTask.java
- engine/src/main/java/org/terasology/rendering/dag/tasks/DisableStateParameterTask.java
- engine/src/main/java/org/terasology/rendering/dag/tasks/EnableMaterialTask.java
- engine/src/main/java/org/terasology/rendering/dag/tasks/EnableStateParameterTask.java
- engine/src/main/java/org/terasology/rendering/dag/tasks/MarkerTask.java
- engine/src/main/java/org/terasology/rendering/dag/tasks/SetDepthMaskTask.java
- engine/src/main/java/org/terasology/rendering/dag/tasks/SetFacesToCullTask.java
- engine/src/main/java/org/terasology/rendering/dag/tasks/SetViewportToSizeOfTask.java
- engine/src/main/java/org/terasology/rendering/dag/tasks/SetWireframeTask.java
@tdgunes: you might want to have a look at this one.
@indianajohn: it might be interesting for you too, to increase your knowledge of the system.
* Considerably refactored the RenderTaskListGenerator class, responsible for taking the nodes in the render graph (currently just a list) and generating the list of tasks that are executed every frame to generate the image shown on screen. Also added some javadocs.
* Changed toString() methods in a number of classes to generate a better logger output, with aligned text fields separated by colons.
* Added some statistics printout at the end of the tasklist generation process.
* Load up a game and then check the logger output for two lists: the Intermediate Renderer List first and the Renderer Task List next. The first lists all potential opengl …
> Render Task List Generator refactor / Improved Logger Output

- engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/SelectModulesScreen.java
Fix for #2321 
- Create a new module using "gradlew createModuleMyTestModule"
- Create a new single player game
- Go to Modules menu
- Find MyTestModule and check Update button
> Fixes #2321 Update disabled for modules not on meta-server

- engine/src/main/java/org/terasology/world/block/entity/BlockCommands.java
Fixes #2518
- Open Console
- type `bulkGiveBlock cake` to get all cake blocks :smile: 
- type `bulkGiveBlock core` to get a larger list and see what happens when inventory gets full.
> Fix for #2518

- engine/src/main/java/org/terasology/world/block/entity/BlockCommands.java
Extension to #2518 
Test with `bulkGiveBlock cake 99 stair`
> Added quantity and shape for bulkGiveBlock

- engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/CreateGameScreen.java
Fixes #2526 
- Create two new games (Game 1 and Game 2).
- Create new game menu (name should be Game 3).
- Delete the first two games.
- Create new game menu (name should be Game 1).
> Updates gameName on each reopening of menu

- engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/savedGames/GameProvider.java
Fix for NPE at loading save games
Manage to kill the game when saving is in progress.
Open the game. There should be a NPE [here](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/savedGames/GameProvider.java#L69)
> Fix for NPE at loading save games

- engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/CreateGameScreen.java
- engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/SelectGameScreen.java
- engine/src/main/resources/assets/i18n/menu.lang
- engine/src/main/resources/assets/i18n/menu_en.lang
- engine/src/main/resources/assets/ui/menu/createGameScreen.ui
- engine/src/main/resources/assets/ui/menu/selectGameScreen.ui
Fix for #2566 
1.Open Game
2. Go to Create/Load World screens
3.The Save Game Path is displayed
> Display savegame path

- engine/src/main/java/org/terasology/logic/console/commands/ServerCommands.java
- engine/src/main/java/org/terasology/logic/debug/MovementDebugCommands.java
- engine/src/main/java/org/terasology/logic/permission/PermissionCommands.java
Added the IgnoreCase condition in player equal tag. I tested it on my computer, locally. More work maybe required. I think i earlier deleted my branch on which i was working on, so the issue closed automatically.
> added ignoreCase in givepermission command, more work maybe required

- engine/src/main/java/org/terasology/engine/subsystem/headless/renderer/HeadlessWorldRenderer.java
- engine/src/main/java/org/terasology/rendering/dag/nodes/AlphaRejectBlocksNode.java
- engine/src/main/java/org/terasology/rendering/dag/nodes/ChunksAlphaRejectNode.java
- engine/src/main/java/org/terasology/rendering/dag/nodes/ChunksOpaqueNode.java
- engine/src/main/java/org/terasology/rendering/dag/nodes/ChunksRefractiveReflectiveNode.java
- engine/src/main/java/org/terasology/rendering/dag/nodes/LightGeometryNode.java
- engine/src/main/java/org/terasology/rendering/dag/nodes/ObjectsOpaqueNode.java
- engine/src/main/java/org/terasology/rendering/dag/nodes/OpaqueBlocksNode.java
- engine/src/main/java/org/terasology/rendering/dag/nodes/OpaqueObjectsNode.java
- engine/src/main/java/org/terasology/rendering/dag/nodes/OverlaysNode.java
- engine/src/main/java/org/terasology/rendering/dag/nodes/RefractiveReflectiveBlocksNode.java
- engine/src/main/java/org/terasology/rendering/dag/nodes/ShadowMapNode.java
- engine/src/main/java/org/terasology/rendering/dag/nodes/WorldReflectionNode.java
- engine/src/main/java/org/terasology/rendering/primitives/ChunkMesh.java
- engine/src/main/java/org/terasology/rendering/shader/ShaderParametersCombine.java
- engine/src/main/java/org/terasology/rendering/shader/ShaderParametersDebug.java
- engine/src/main/java/org/terasology/rendering/world/WorldRenderer.java
- engine/src/main/java/org/terasology/rendering/world/WorldRendererImpl.java
Refactoring of a number of nodes, primarily to migrate them to the new rendering architecture.
Startup a game and check that landscape, water surfaces, shadows, objects and plants render as usual in all circumstances. 
See individual comments for further info on specific bits of code.
> More work on render nodes

- engine/src/main/java/org/terasology/rendering/dag/nodes/BackdropNode.java
Attempt to fix #2591 
Follow the instructions in #2591  on how to reproduce the problem and verify it no longer occurs.
> # Attempt to fix issue 2591

- docs/Modules.md
3 small changes made to the syntax of `Modules.md`
> Minor syntax update

- docs/Conduct.md
Moves from our current code of conduct to the contributor covenant
> Switched to the contributor convenant

- engine/src/main/java/org/terasology/logic/console/commands/CoreCommands.java
Added ping command , only works on windows
> Ping Command

- engine/src/main/java/org/terasology/logic/console/commands/CoreCommands.java
Please test before merging, I'm on my laptop right now :turtle:
> Cleanup of ping command.

- engine/src/main/java/org/terasology/logic/console/ui/ConsoleScreen.java
- engine/src/main/java/org/terasology/world/block/entity/BlockCommands.java
- modules/Core/src/main/java/org/terasology/logic/inventory/ItemCommands.java
Implemented #2293 
giveBlock and giveItem commands are now just give. (+ better return messages)
Ex.)
```
give <Block or item name> (amount) (block shape)
```
Playing.md has not been adjusted for this.
Possible next steps:
- inventoryManager.giveItem doesn't support item quantity to give
- Uses prefab.getName() for items, should use a display name maybe?
> Unified giveItem + giveBlock to give

- engine-tests/src/test/java/org/terasology/rendering/dag/RenderTaskListGeneratorTest.java
- engine/src/main/java/org/terasology/rendering/ShaderManagerLwjgl.java
- engine/src/main/java/org/terasology/rendering/assets/shader/ParamType.java
- engine/src/main/java/org/terasology/rendering/assets/shader/ShaderProgramFeature.java
- engine/src/main/java/org/terasology/rendering/backdrop/Skysphere.java
- engine/src/main/java/org/terasology/rendering/dag/nodes/AlphaRejectBlocksNode.java
- engine/src/main/java/org/terasology/rendering/dag/nodes/BackdropNode.java
- engine/src/main/java/org/terasology/rendering/dag/nodes/BackdropReflectionNode.java
- engine/src/main/java/org/terasology/rendering/dag/nodes/ShadowMapNode.java
- engine/src/main/java/org/terasology/rendering/nui/layers/ingame/metrics/DebugOverlay.java
- engine/src/main/java/org/terasology/rendering/opengl/FBO.java
- engine/src/main/java/org/terasology/rendering/opengl/GLSLMaterial.java
- engine/src/main/java/org/terasology/rendering/opengl/GLSLShader.java
- engine/src/main/java/org/terasology/rendering/opengl/OpenGLUtils.java
- engine/src/main/java/org/terasology/rendering/shader/ShaderParametersOcDistortion.java
- engine/src/main/java/org/terasology/rendering/world/RenderableWorldImpl.java
- engine/src/main/java/org/terasology/rendering/world/viewDistance/ViewDistance.java
- engine/src/main/java/org/terasology/world/propagation/light/LightMerger.java
Fixes for a number of warnings given by Jenkins during the build process.
Jenkins' output can be found at the end of each PR, under the Details link. The issues this PR has been addressing are just a small portion of the total, but have been found in [**this**](http://jenkins.terasology.org/job/TerasologyPRs/1093/analysisResult/) specific build output.
- start Terasology
- load a game
- everything should work normally
- Given the breadth of the changes, even though many are small and probably inconsequential, we need to check if this PR gives any problem to known modules. I.e. a number of changes regard unused methods and fields. Perhaps modules were using them? This would need verifying in a workspace including all the modules. But who, who could have such a megaworkspace?
- I've used …
> Addressed a number of issues flagged by Jenkins

- engine/src/main/java/org/terasology/config/RenderingConfig.java
- engine/src/main/java/org/terasology/rendering/world/viewDistance/ViewDistance.java
This was a task for the Google Code In. The changes in RenderingConfig.java were neccesary because viewDistance would be null on a first time startup.
> Added dimensions to the view distance setting

- engine/src/main/java/org/terasology/rendering/openvrprovider/OpenVRProvider.java
- engine/src/main/java/org/terasology/rendering/openvrprovider/OpenVRState.java
- engine/src/main/java/org/terasology/rendering/openvrprovider/OpenVRUtil.java
Fixes check style violations, clearing some warnings from the OpenVR package.
Open up your IDE and see that the warnings are mostly gone. I've left a couple of methods public and unused methods/variables, because I plan to use them in the future.
> Addressed warnings.

- modules/Core/assets/prefabs/crossbow.prefab
- modules/Core/src/main/java/org/terasology/logic/actions/ArrowAction.java
- modules/Core/src/main/java/org/terasology/logic/actions/ArrowActionComponent.java
I added the crossbow. I will create a pull request with the crafting recipe in the WoodAndStone module. Not all tests passed, but that was already the case I believe.
> Added the crossbow from the GCI task

- engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/CreditsScreen.java
- engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/MainMenuScreen.java
- engine/src/main/java/org/terasology/rendering/nui/widgets/UIScrollingText.java
- engine/src/main/resources/Credits.txt
- engine/src/main/resources/assets/i18n/menu.lang
- engine/src/main/resources/assets/i18n/menu_en.lang
- engine/src/main/resources/assets/ui/menu/creditsScreen.ui
- engine/src/main/resources/assets/ui/menu/mainMenuScreen.ui
Fixes #2578:
- Contains a new UIScrollingText NUI widget which scrolls through lines of text with methods to start, stop, reset scrolling, set scrolling speed and toggle auto reset for the scrolling.  
- Also contains a new credits screen accessible from the main menu that makes use of UIScrollingText
Open the Credits screen from the main menu.
Need some opinions on the font size, scrolling speed, and overall structure of the credits. 
~~As for support for fancy text with UIScrollingText, seems that I would have to make use of drawTextRaw but I'm unsure of how to obtain a new Font object different from the current style.~~
Also, the credits are currently loaded as a very long string in CreditsScreen.java - seems like it would be better to read it from an external file, but where would I …
> Added UIScrollingText widget and credits screen

- engine-tests/src/test/java/org/terasology/rendering/nui/layouts/CardLayoutTest.java
- engine-tests/src/test/java/org/terasology/rendering/nui/layouts/ColumnLayoutTest.java
- engine-tests/src/test/java/org/terasology/rendering/nui/layouts/RowLayoutTest.java
3 tests for RowLayout that test the 3 main scenarios: 
- when all the widgets have relative widths specified
- when no widgets have relative widths specified
- when some widgets have relative widths specified
Run RowLayoutTest.java. All tests should pass!
I've made sure to comment on most parts of the code so that it's easier to understand. Do take a look and see if the tests are ok since this is my first time writing unit tests.
P.S. Unit testing isn't as bad as everyone says 😄 Gives you a good understanding of the class.
> Added tests for RowLayout and CardLayout

- engine-tests/src/test/java/org/terasology/rendering/nui/layouts/ZoomableLayoutTest.java
Had to draw it on paper to figure this one out 🙂 
3 tests for ZoomableLayout:
- Default scaling for screen and world
- Zooming out
- Zooming in and repositioning
Run ZoomableLayoutTest.java. All tests should pass.
None
> Added ZoomableLayoutTest

- engine-tests/src/main/java/org/terasology/TerasologyTestingEnvironment.java
- engine-tests/src/test/java/org/terasology/logic/console/ConsoleTest.java
- engine/src/main/java/org/terasology/logic/console/Console.java
- engine/src/main/java/org/terasology/logic/console/ConsoleImpl.java
- engine/src/main/java/org/terasology/logic/console/commands/CoreCommands.java
Add "clear" command to console. Unit test included.
> add clear command for console

- engine/src/main/java/org/terasology/logic/console/commands/CoreCommands.java
The help command now returns commands in alphabetical order
> help returns commands in alphabetical order

- engine/src/main/java/org/terasology/logic/console/ui/ChatScreen.java
- engine/src/main/java/org/terasology/logic/console/ui/MiniChatOverlay.java
- engine/src/main/resources/assets/ui/minichatOverlay.ui
Simple fix for #2376 
- Chat overlay now shows up to last 6 messages
- Sending a message now closes the chat window and opens the chat overlay instead of remaining focused on the text field
- Tweaked base time values of chat overlay so it lasts longer before fading out
Open up a game and type something in chat. Here's an image of the updated chat overlay:
Some ideas I had but not really sure if they should be put in the game:
- Settings for max no. of lines to be shown on overlay
- Similar to other games, where the chat history is separate from the text box and pressing the chat button just makes the text field visible and turns the chat history scrollable (my concern with this is that it might take up too much space since the new messages appear at the bottom but we could change this …
> Chat UI tweaks

- engine/src/main/java/org/terasology/engine/modes/loadProcesses/AwaitCharacterSpawn.java
- engine/src/main/java/org/terasology/engine/subsystem/lwjgl/LwjglGraphics.java
- engine/src/main/java/org/terasology/input/binds/movement/AutoMoveButton.java
- engine/src/main/java/org/terasology/logic/characters/GazeAuthoritySystem.java
- engine/src/main/java/org/terasology/logic/console/ui/ConsoleScreen.java
- engine/src/main/java/org/terasology/logic/console/ui/MiniChatOverlay.java
- engine/src/main/java/org/terasology/logic/players/LocalPlayerSystem.java
- engine/src/main/java/org/terasology/logic/players/PlayerSystem.java
- engine/src/main/java/org/terasology/physics/bullet/BulletPhysics.java
- engine/src/main/java/org/terasology/rendering/dag/nodes/CopyImageToHMDNode.java
- engine/src/main/java/org/terasology/rendering/dag/nodes/CopyImageToScreenNode.java
- engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/CreateGameScreen.java
- engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/videoSettings/DisplayModeSetting.java
- engine/src/main/java/org/terasology/rendering/opengl/LwjglFrameBufferObject.java
- engine/src/main/java/org/terasology/world/block/entity/BlockCommands.java
- engine/src/main/java/org/terasology/world/internal/EntityAwareWorldProvider.java
- modules/Core/src/main/java/org/terasology/core/debug/BenchmarkScreen.java
- modules/Core/src/main/java/org/terasology/logic/actions/ArrowAction.java
- modules/Core/src/main/java/org/terasology/logic/actions/ArrowActionComponent.java
- modules/Core/src/main/java/org/terasology/logic/inventory/CharacterInventorySystem.java
- modules/CoreSampleGameplay/src/main/java/org/terasology/coresamplegameplay/PlayerStartingInventorySystem.java
Fixed CheckStyle issues logged by IntelliJ checkstyle plugin
Run the IntelliJ CheckStyle plugin.
> Fixed Checkstyle Issues

- engine/src/main/java/org/terasology/rendering/nui/widgets/UIText.java
Add Javadoc documentation to the UIText widget class.
> Add documentation to UIText widget.

- engine/src/main/java/org/terasology/rendering/nui/widgets/ActivateEventListener.java
- engine/src/main/java/org/terasology/rendering/nui/widgets/CursorUpdateEventListener.java
- engine/src/main/java/org/terasology/rendering/nui/widgets/ItemActivateEventListener.java
- engine/src/main/java/org/terasology/rendering/nui/widgets/ItemSelectEventListener.java
- engine/src/main/java/org/terasology/rendering/nui/widgets/TextChangeEventListener.java
Add Listeners Interface Documentation
> Listeners Interface Documentation

- engine/src/main/java/org/terasology/entitySystem/entity/internal/PojoEntityManager.java
- engine/src/main/java/org/terasology/monitoring/gui/PerformanceMonitorPanel.java
- engine/src/main/java/org/terasology/rendering/nui/asset/UIFormat.java
- engine/src/main/java/org/terasology/rendering/nui/widgets/UIText.java
Fixed 21 checkstyle issues in 4 files:
- 12 issues to do with variable declaration order in UIText.java
- 4 issues to do with redundant modifiers in ThreadMonitorPanel.java
- 3 redundant modifiers in PojoEntityManager.java
- 2 redundant modifiers in UIFormat.java
> Fix 21 checkstyle issues.

- engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/SelectModulesScreen.java
The UI now checks for dependencies while selecting the color to use to display gameplay modules.
> Minor UI tweak in module list for gameplay modules.

- engine/src/main/java/org/terasology/engine/TerasologyConstants.java
- engine/src/main/java/org/terasology/engine/paths/PathManager.java
- engine/src/main/java/org/terasology/entitySystem/systems/RenderSystem.java
- engine/src/main/java/org/terasology/input/events/InputEvent.java
- engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/SelectModulesScreen.java
Added javadocs for RenderSystem, PathManager, InputEvent, and TerasologyConstants. 
No particular target issue, just roamed around the engine and found some undocumented important classes.
> InputEvent, PathManager, RenderSystem javadocs

- engine/src/main/java/org/terasology/math/AABB.java
- engine/src/main/java/org/terasology/math/Region3i.java
- engine/src/main/java/org/terasology/world/block/Block.java
- engine/src/main/java/org/terasology/world/block/BlockComponent.java
> AABB,Block and BlockComponent javadoc

- engine/src/main/java/org/terasology/rendering/nui/layouts/CardLayout.java
- engine/src/main/java/org/terasology/rendering/nui/layouts/RowLayout.java
- engine/src/main/java/org/terasology/rendering/nui/widgets/UIButton.java
- engine/src/main/java/org/terasology/rendering/nui/widgets/UIScrollingText.java
Just went ahead and added javadocs to some of the classes I was more familiar with.
Let me know if there are any problems with the documentation! 🙂
> CardLayout, RowLayout, UIButton, UIScrollingText javadocs

- engine/src/main/resources/assets/ui/behaviorEditorScreen.ui
- engine/src/main/resources/assets/ui/enterTextPopup.ui
- engine/src/main/resources/assets/ui/waitPopup.ui
> Internationalizing Strings

- engine/src/main/java/org/terasology/rendering/dag/RenderTaskListGenerator.java
- engine/src/main/java/org/terasology/rendering/dag/stateChanges/SetViewportToSizeOf.java
> Use dimensions instead to compare SetViewportSizeOf instances

- engine/src/main/java/org/terasology/audio/AudioEndListener.java
- engine/src/main/java/org/terasology/audio/AudioManager.java
- engine/src/main/java/org/terasology/audio/Sound.java
- engine/src/main/java/org/terasology/audio/StaticSoundData.java
- engine/src/main/java/org/terasology/audio/StreamingSound.java
- engine/src/main/java/org/terasology/audio/events/AbstractPlaySoundEvent.java
- engine/src/main/java/org/terasology/audio/events/PlaySoundEvent.java
- engine/src/main/java/org/terasology/audio/events/PlaySoundForOwnerEvent.java
- engine/src/main/java/org/terasology/audio/nullAudio/NullAudioManager.java
- engine/src/main/java/org/terasology/audio/nullAudio/NullSound.java
- engine/src/main/java/org/terasology/audio/nullAudio/NullStreamingSound.java
- engine/src/main/java/org/terasology/audio/openAL/BaseSoundPool.java
- engine/src/main/java/org/terasology/audio/openAL/OpenALManager.java
- engine/src/main/java/org/terasology/audio/openAL/SoundPool.java
- engine/src/main/java/org/terasology/audio/openAL/SoundSource.java
- engine/src/main/java/org/terasology/audio/system/AudioSystem.java
Javadoc for the audio code in the main engine. (PlaySoundEvent, AudioManager etc etc)
Confirm that there are no functional changes and that the javadoc is accurate
Ensure that the javadoc is accurate and follows Terasology standards
> Added javadoc to the audio system and related files.

- engine/src/main/java/org/terasology/rendering/nui/widgets/treeView/Tree.java
- engine/src/main/java/org/terasology/rendering/nui/widgets/treeView/TreeModel.java
Makes some TreeView model classes accessible by modules by adding a @API annotation to them.
There are probably more tree view classes that need that annotation but for my local code to work I need those :).
Minimalistic change, no gameplay test necessary.
> Make some TreeView classes accessible by modules.

- engine-tests/src/main/java/org/terasology/HeadlessEnvironment.java
- engine-tests/src/test/java/org/terasology/entitySystem/metadata/internal/MetadataBuilderTest.java
- engine-tests/src/test/java/org/terasology/logic/console/ConsoleTest.java
- engine-tests/src/test/java/org/terasology/logic/delay/ArbritaryDelayActionComponent.java
- engine-tests/src/test/java/org/terasology/logic/delay/DelayedActionSystemTest.java
- engine-tests/src/test/java/org/terasology/persistence/typeHandling/coreTypes/EnumTypeHandlerSerializerTest.java
- engine-tests/src/test/java/org/terasology/rendering/nui/layouts/CardLayoutTest.java
- engine-tests/src/test/java/org/terasology/rendering/nui/widgets/treeView/GenericTreeTest.java
- engine-tests/src/test/java/org/terasology/world/propagation/BetweenChunkPropagationTest.java
- modules/Core/src/main/java/org/terasology/core/logic/blockDropGrammar/BlockDropGrammarSystem.java
- modules/Core/src/main/java/org/terasology/core/world/CoreBiome.java
- modules/Core/src/main/java/org/terasology/logic/actions/ArrowAction.java
- modules/Core/src/main/java/org/terasology/logic/health/BlockDamageRenderer.java
Fixed ~30 checkstyle issues for GCI.
> Checkstyle GCI

- engine/src/main/java/org/terasology/world/generation/Border3D.java
Adds some Javadocs.
Just go and check if the javadoc isn't too detailed, or too broad.
Thanks to Cervator,oniatus and Josharias for helping me with fixing my workspace. It was a pain. Thanks.
> Added javadocs

- .gitignore
- engine/src/main/java/org/terasology/rendering/nui/editor/utils/NUIEditorMenuTreeBuilder.java
Fixes for a few minor NUI editor issues, specifically #2763 and #2764 - read these for a nice detailed description. Also adds an autosave file created by the editor to `.gitignore`, since we never want to include it in git.
Attempt to reproduce the bugs from #2763 and #2764, then verify that you can't reproduce them because they've been fixed!
No outstanding issues! /cc @flo
> Fix NUI editor issues

- engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/CreditsScreen.java
Fixed Credits Screen with "animated menus" enabled. Partially fixes #2762.
Partially fixes #2762, other two (single/multi) may be harder to fix.
Enable animated menus, go to credits and back.
> Fixed CreditsScreen

- engine/src/main/java/org/terasology/rendering/nui/widgets/UITabBox.java
- engine/src/main/resources/assets/skins/default.skin
Add a UI Tab as per issue #2695.
An example on it's use can be seen [here](https://github.com/Terasology/TutorialNui/pull/2)
> Add UITabBox

- engine/src/main/java/org/terasology/logic/notifications/NotificationMessageEvent.java
This adds @API to NotificationMessageEvent, making it usable to external modules.
> Added @API to NotificationMessageEvent

- engine/src/main/java/org/terasology/logic/chat/ChatMessageEvent.java
- engine/src/main/java/org/terasology/logic/chat/ChatSystem.java
I found today that using command "say" and "whisper" only sends the first word of one sentence. 
A tiny fix to make it send a whole sentence.
- `say()` and `whisper()` receive `String[]` as message
- A small method `join()` transfers `String[]` to `String` with a space between every word
- Please press in console `say Hello Terasology!` or `whisper playName Heya good morning :-)`
> Modify "say" and "whisper" so that it sends a whole sentence

- engine/src/main/java/org/terasology/engine/subsystem/headless/renderer/HeadlessWorldRenderer.java
- engine/src/main/java/org/terasology/rendering/cameras/Camera.java
- engine/src/main/java/org/terasology/rendering/cameras/OpenVRStereoCamera.java
- engine/src/main/java/org/terasology/rendering/cameras/PerspectiveCamera.java
- engine/src/main/java/org/terasology/rendering/cameras/SubmersibleCamera.java
- engine/src/main/java/org/terasology/rendering/shader/ShaderParametersBase.java
- engine/src/main/java/org/terasology/rendering/world/WorldRenderer.java
- engine/src/main/java/org/terasology/rendering/world/WorldRendererImpl.java
Moves isHeadUnderWater function from WorldRenderer.java to Camera.java (function name changed to isCameraUnderWater) and other minor changes made accordingly.
(This change was in the to-do comment right over the isHeadUnderWater function in the WorldRenderer class)
This change isn't supposed to make a change in-game, but to make the code more readable so, to test it, just compare the functionality of the underwater camera with and without the change.
> Head underwater check function moved (following to-do comment in-code)

- engine/src/main/java/org/terasology/logic/chat/ChatSystem.java
A nicer solution for transform String[] to String with separator in between : `Arrays.stream(words).collect(joining(sep));`
Thanks for advice @skaldarnar 
Please see #2805
> Improvement for say command

- engine/src/main/java/org/terasology/physics/bullet/BulletPhysics.java
- engine/src/main/java/org/terasology/physics/engine/PhysicsSystem.java
- engine/src/main/java/org/terasology/physics/events/CollideEvent.java
I exposed a bit more for the collision event. At the moment this is fairly temporary but hopefully something else can be worked out in regards to how physics works in the game. This is just the collision point from each object, how much they penetrate each other and the normal vector in regards to the two collision points.
> exposed more to the collision event

- engine/src/main/java/org/terasology/rendering/nui/widgets/UIRadialRing.java
- engine/src/main/java/org/terasology/rendering/nui/widgets/UIRadialSection.java
This really should have been removed earlier.
Also change the sections to use bindings following discussion with rzats and immortius
> Remove testing line from Radial UI

- engine/src/main/java/org/terasology/rendering/dag/RenderTaskListGenerator.java
- engine/src/main/java/org/terasology/rendering/dag/nodes/ApplyDeferredLightingNode.java
- engine/src/main/java/org/terasology/rendering/dag/nodes/BackdropNode.java
- engine/src/main/java/org/terasology/rendering/dag/nodes/DeferredMainLightNode.java
- engine/src/main/java/org/terasology/rendering/dag/nodes/DeferredPointLightsNode.java
- engine/src/main/java/org/terasology/rendering/dag/stateChanges/SetFboWriteMask.java
- engine/src/main/java/org/terasology/rendering/dag/stateChanges/SetInputTextureFromFBO.java
- engine/src/main/java/org/terasology/rendering/dag/stateChanges/SetRenderBufferMask.java
This PR
- Adds a new SetRenderBufferMask StateChange
- Moves MarkerTask to end of file, so it's no longer the first class in file.
> New SetRenderBufferMask StateChange

- engine/src/main/java/org/terasology/input/cameraTarget/TargetSystem.java
- engine/src/main/java/org/terasology/logic/characters/CharacterSystem.java
Fixed attack event for CharacterSystem.
> fixed attack event for issue #2887

- engine/src/main/java/org/terasology/rendering/nui/Canvas.java
Just a small PR fixing two typos in Canvas class.
What's the "correct way" to submit typo fixes? Do idependent PRs work, considering the fact that I'm not doing anything else in this part of the code?
> Fixed two small typos in Canvas

- engine-tests/src/test/java/org/terasology/network/TestNetwork.java
- engine-tests/src/test/java/org/terasology/network/internal/NetworkOwnershipTest.java
- engine/src/main/java/org/terasology/engine/TerasologyEngine.java
- engine/src/main/java/org/terasology/engine/modes/GameState.java
- engine/src/main/java/org/terasology/engine/modes/StateLoading.java
- engine/src/main/java/org/terasology/engine/modes/StateMainMenu.java
- engine/src/main/java/org/terasology/engine/subsystem/headless/mode/StateHeadlessSetup.java
- engine/src/main/java/org/terasology/network/NetworkSystem.java
- engine/src/main/java/org/terasology/network/internal/NetworkSystemImpl.java
Interface changes to support ModuleTestingEnvironment (creation and manipulation of TerasologyEngines)
see https://github.com/kaen/ModuleTestingEnvironment
Engine should work exactly as it did before :)
> alter some interfaces to support GameEngine testability

- engine/src/main/java/org/terasology/logic/characters/CharacterSystem.java
I don't know why the previous code does not work.
This is just a quick fix for the Blocker #2913.
Also, I really wanted to test the WildAnimals:deer in tomorrow's multiplayer play test :stuck_out_tongue:
> Fixes the blocker #2913

- engine/src/main/java/org/terasology/logic/characters/KinematicCharacterMover.java
- engine/src/main/java/org/terasology/logic/characters/events/OnEnterBiomeEvent.java
- engine/src/main/java/org/terasology/logic/characters/events/OnEnterBlockEvent.java
Adds a `onEnterBiomeEvent` that gets sent whenever the player enters a new biome.
Note: The `updateMode` method has moved because of an auto code clean up.
Add this line
`logger.info("newBiome: " + newBiome);`
inside the  [if block](https://github.com/MovingBlocks/Terasology/pull/2954/files#diff-e81079f2b9fefe8630619776b065c2aaR175) where the event is sent. 
Run the game. 
Walk around a little.
You'd see logs whenever an onEnterBiomeEvent is sent as and when the player enters a new biome.
> Added onEnterBiome event

- engine/src/main/java/org/terasology/utilities/CamelCaseMatcher.java
> remove brackets from console query

- engine/src/main/java/org/terasology/logic/characters/AliveCharacterComponent.java
- engine/src/main/java/org/terasology/logic/characters/CharacterMovementComponent.java
- engine/src/main/java/org/terasology/logic/characters/CharacterSoundSystem.java
- engine/src/main/java/org/terasology/logic/characters/CharacterSystem.java
- engine/src/main/java/org/terasology/logic/characters/ClientCharacterPredictionSystem.java
- engine/src/main/java/org/terasology/logic/characters/ServerCharacterPredictionSystem.java
- engine/src/main/java/org/terasology/logic/characters/events/PlayerDeathEvent.java
- engine/src/main/java/org/terasology/logic/players/LocalPlayerSystem.java
- engine/src/main/java/org/terasology/logic/players/MenuControlSystem.java
- engine/src/main/java/org/terasology/logic/players/PlayerCharacterComponent.java
- engine/src/main/java/org/terasology/logic/players/PlayerFactory.java
- engine/src/main/java/org/terasology/logic/players/PlayerSystem.java
- engine/src/main/java/org/terasology/logic/players/event/OnPlayerRespawnedEvent.java
- engine/src/main/resources/assets/prefabs/player/player.prefab
- modules/Core/src/main/java/org/terasology/logic/health/HealthAuthoritySystem.java
- modules/Core/src/main/java/org/terasology/logic/inventory/CharacterInventorySystem.java
An approach to not destroy the player entity completely upon death. This is done so as to allow for components attached to the player entity to persist after respawn.
Added death handling for character entities, that takes care of not destroying the player entity by consuming the BeforeDestroyEvent. The CharacterSystem captures the BeforeDestroy event and sends out a DeathEvent for all character entities regardless. There is just an additional check to consume the BeforeDestroy event (so as to save the DoDestroy from happening) in the case that the character entity is a Player (i.e. has a PlayerCharacterComponent). In that case, it also sends out a PlayerDeathEvent.
This adds the **OnPlayerRespawnedEvent, PlayerDeathEvent, AliveCharacterComponent, PlayerCharacterComponent**.
A character …
> Do not destroy player entity completely on death

- engine/src/main/java/org/terasology/rendering/nui/contextMenu/ContextMenuUtils.java
- engine/src/main/java/org/terasology/rendering/nui/contextMenu/MenuTree.java
- engine/src/main/java/org/terasology/rendering/nui/widgets/treeView/TreeMouseClickListener.java
Adds API annotations to the required ContextMenu Classes in order for the context menu of NUI to be used with modules.
Create a module that uses the contextMenu from NUI and test it out.
Current version of Scenario module uses it with PR https://github.com/Terasology/Scenario/pull/13
> ContextMenu API Annotations

- engine/src/main/java/org/terasology/logic/players/PlayerSystem.java
Fixes the bug of a player entity being destroyed after death.
https://github.com/MovingBlocks/Terasology/pull/2958/ made the change to preserve the player entity even after death. 
Basically, the BeforeDestroyEvent for a player entity is consumed if it has the AliveCharacterComponent, the AliveCharacterComponent is stripped off and the DeathScreen is created ([here](https://github.com/MovingBlocks/Terasology/blob/c18b201a4d5ad678e6f1346b5e8727cc3367e7db/engine/src/main/java/org/terasology/logic/characters/CharacterSystem.java#L89-L89)). 
Once the player loses its AliveCharacterComponent, it is susceptible to destruction should it get damaged again (since the HealthAuthoritySystem would trigger a DestroyEvent again).
Since most damage inflictors like attacking skeletons were made to attack …
> Prevents player entity from being destroyed after death onDamage

- engine/src/main/java/org/terasology/physics/StandardCollisionGroup.java
- engine/src/main/java/org/terasology/physics/bullet/BulletPhysics.java
- engine/src/main/java/org/terasology/physics/components/TriggerComponent.java
- engine/src/main/java/org/terasology/physics/engine/PhysicsLiquidWrapper.java
- engine/src/main/java/org/terasology/physics/engine/PhysicsSystem.java
- engine/src/main/java/org/terasology/physics/engine/PhysicsWorldWrapper.java
changes in physics to enable trigger collisions with the world and to make triggers have their own collision groups. It also makes slight changes in PhysicsLiquidWrapper and PhysicsWorldWrapper so that the latest TeraBullet module can recompile with the engine.
Will need to merge https://github.com/MovingBlocks/TeraBullet/pull/2 before merging this.
NOTE: After merging this pr you will need to recompile the engine module with latest TeraBullet module.
> changes in physics to enable trigger collisions with the world and to make triggers have their own collision groups

- engine/src/main/java/org/terasology/physics/bullet/BulletPhysics.java
- engine/src/main/java/org/terasology/physics/components/TriggerComponent.java
- engine/src/main/java/org/terasology/physics/events/CollideEvent.java
Makes the variables of the TriggerComponent to be synched between server and client.
> made the TriggerComponent to be compatible on a network

- modules/Core/src/main/java/org/terasology/core/logic/door/CloseDoorEvent.java
- modules/Core/src/main/java/org/terasology/core/logic/door/DoorPlacedEvent.java
- modules/Core/src/main/java/org/terasology/core/logic/door/DoorSystem.java
- modules/Core/src/main/java/org/terasology/core/logic/door/OpenDoorEvent.java
- modules/Core/src/main/java/org/terasology/core/logic/door/package-info.java
New door related events that make the door inside Core module easily extendable and multiplayer ready.
> Added door related events

- engine/src/main/java/org/terasology/logic/players/FirstPersonClientSystem.java
Fixes #2605
This commit clones the picked up entity and creates a client-only entity for displaying the selected item. It does so by cloning the entity and removing the NetworkComponent and RigidBodyComponent. By creating the new entity no other systems like inventory and pickup systems should be affected.
Notes:
1) Item is only visible for the client wearing it (as far as I know it was not visible beforehand also).
2) In the previous commit nearly all components but some rendering-related ones where removed (whitelist). This also incorrectly removed the component responsible for emitting the light from a torch. So in this commit only the NetworkComponent and RigidBodyComponent are removed from the cloned entity (blacklist). This may lead to other problems.
3) Other clients still won't …
> Use client-side entity for held item, fixes #2605

- engine/src/main/java/org/terasology/logic/behavior/BehaviorSystem.java
- engine/src/main/java/org/terasology/logic/behavior/actions/SleepAction.java
- engine/src/main/java/org/terasology/logic/behavior/actions/conditions/ConditionAction.java
- engine/src/main/java/org/terasology/logic/behavior/core/ActionNode.java
- engine/src/main/java/org/terasology/logic/behavior/core/DecoratorNode.java
Tweaks to ConditionNode and a few others, accompanies today's changes to WildAnimals and Behaviors
> Behavior - minor changes

- engine/src/main/java/org/terasology/rendering/nui/UILayout.java
- engine/src/main/java/org/terasology/rendering/nui/layouts/CardLayout.java
- engine/src/main/java/org/terasology/rendering/nui/layouts/ColumnLayout.java
- engine/src/main/java/org/terasology/rendering/nui/layouts/FlowLayout.java
- engine/src/main/java/org/terasology/rendering/nui/layouts/MultiRowLayout.java
- engine/src/main/java/org/terasology/rendering/nui/layouts/RowLayout.java
- engine/src/main/java/org/terasology/rendering/nui/layouts/ScrollableArea.java
- engine/src/main/java/org/terasology/rendering/nui/layouts/ZoomableLayout.java
- engine/src/main/java/org/terasology/rendering/nui/layouts/miglayout/MigLayout.java
- engine/src/main/java/org/terasology/rendering/nui/layouts/relative/RelativeLayout.java
Simply adds a method called `removeAllWidgets` that allows clearing all the Widgets that are stored inside a layout.
> Added removeAllWidgets method

- engine-tests/src/test/java/org/terasology/engine/ComponentSystemManagerTest.java
- engine/src/main/java/org/terasology/engine/ComponentSystemManager.java
Fixes #3087 
See https://github.com/MovingBlocks/Terasology/issues/3087#issuecomment-326409756 for a detailed explanation.
->100% TDD 😎 *wohoo*
> Clear ComponentSystem subscribers on shutdown - fixes #3087

- module.groovy
- templates/build.gradle
Port the 'new module' Gradle interface to Groovy.
Ref: https://github.com/MovingBlocks/Terasology/issues/3099
> Implement new module interface in groovy

- module.groovy
> Add update and update-all functionalities to modules.groovy

- engine/src/main/java/org/terasology/logic/players/DebugControlSystem.java
This is a fix for issue #3055. 
The fix may be tested using the following steps:
1. Enter a world in Terasology.
2. Increase the view distance by pressing the appropriate key binding (by default the "home" key).
3. A message should pop up in the chat window stating that the view distance has been increased.
4. Continue to increase the view distance until it reaches the "Mega" setting.
5. A warning message should pop up in the chat window regarding possible performance issues.
6. Increase the viewing distance to the "Extreme" setting.
7. Another warning message regarding possible performance issues should appear.
8. Decrease the view distance by pressing the appropriate key binding (by default the "end" key).
9. If all tests pass, the change should be safe to merge.
> Fix for issue #3055.

- facades/PC/launchScripts/run_linux.sh
- facades/PC/launchScripts/run_macosx.command
> Enhance game executable scripts to pass forward command line arguments

- engine/src/main/java/org/terasology/rendering/nui/layouts/ScrollableArea.java
/me steals tiny change from @jellysnake needed for BasicCrafting
> Allow modifying the preferred size via code rather than just a .ui file.

- engine/src/main/java/org/terasology/rendering/world/WorldRendererImpl.java
- 19 checkstyle error fixes
- several warning fixes
in class engine/src/main/java/org/terasology/rendering/world/WorldRendererImpl.java
> Fixes checkstyle issues in WorldRendererLmpl

- engine-tests/src/test/java/org/terasology/world/block/shape/BlockShapeTest.java
- engine/src/dev/java/org/terasology/benchmark/entitySystem/EntityCreateBenchmark.java
- engine/src/main/java/org/terasology/engine/modes/loadProcesses/CacheBlocks.java
- engine/src/main/java/org/terasology/engine/modes/loadProcesses/CacheTextures.java
- engine/src/main/java/org/terasology/engine/modes/loadProcesses/InitialiseBlockTypeEntities.java
- engine/src/main/java/org/terasology/engine/modes/loadProcesses/InitialiseCommandSystem.java
- engine/src/main/java/org/terasology/engine/modes/loadProcesses/JoinServer.java
- engine/src/main/java/org/terasology/engine/modes/loadProcesses/LoadEntities.java
- engine/src/main/java/org/terasology/engine/modes/loadProcesses/LoadPrefabs.java
- engine/src/main/java/org/terasology/engine/modes/loadProcesses/PostBeginSystems.java
- engine/src/main/java/org/terasology/rendering/cameras/PerspectiveCamera.java
- engine/src/main/java/org/terasology/rendering/dag/nodes/RefractiveReflectiveBlocksNode.java
- engine/src/main/java/org/terasology/rendering/nui/widgets/UIImage.java
- engine/src/main/java/org/terasology/rendering/nui/widgets/UIText.java
- engine/src/main/java/org/terasology/rendering/opengl/fbms/DisplayResolutionDependentFBOs.java
Fixes checkstyle issues. This PR removes 9 empty Javadoc blocks, fixes 2 ExplicitInitializationCheck errors, 22 UnusedImports, and 2 DeclarationOrderChecks (18 warnings).
> Fix Checkstyle Issues - Updated

- engine/src/main/java/org/terasology/world/block/family/MultiConnectFamily.java
I tried reworking how multiconnect family works. I removed all the specific elements and made the implementation more general. One concern is that this creates a bit more boilerplate code when defining a new family. The gist below shows how this may look with the rework. 
https://gist.github.com/pollend/f5f9870303e4e3f68d1c5debcc8a8184
> Multiconnect family rework

- engine/src/main/java/org/terasology/rendering/nui/UIWidget.java
- modules/Core/src/main/java/org/terasology/rendering/nui/layers/ingame/inventory/InventoryGrid.java
Several comments (actually more normal comments than javadoc) useful for somebody who would like to display the inventory of some entity. I had a problem with understanding how a InventoryGrid works so I've thought these comments would be useful for somebody who has never worked with inventories.
> Some tip comments on InventoryGrid.java

- engine-tests/src/main/java/org/terasology/entitySystem/stubs/ListOfEnumsComponent.java
- engine-tests/src/main/resources/assets/prefabs/withListEnumContainer.prefab
- engine-tests/src/test/java/org/terasology/entitySystem/PrefabTest.java
- engine/src/main/java/org/terasology/persistence/typeHandling/coreTypes/EnumTypeHandler.java
I added a test case for a list of enums and also resolved an issue where a component that uses a list of enums deserializes to an empty list. I was trying to use a list of Sides with Rails and the set/list always deserializes to an empty list.
> fixed enum list handler

- engine/src/main/java/org/terasology/engine/module/ModuleDownloadListGenerator.java
A local source module will take precedence over a remote module with the same (snaphot) version. 
If the remote module has a higher version number than local source module it will still be downloaded.
> I tested it, it's safe!
_famous last words_
> adds check for local source module to module downloader

- docs/Playing.md
adds a line of documentation for the [R] key to the Playing.md user guide like page
> Add documention for [R] key to Playing.md

- engine/src/main/java/org/terasology/world/block/family/AbstractBlockFamily.java
- engine/src/main/java/org/terasology/world/block/family/BlockFamily.java
- engine/src/main/java/org/terasology/world/block/family/BlockSections.java
- engine/src/main/java/org/terasology/world/block/family/FreeFormSupported.java
- engine/src/main/java/org/terasology/world/block/family/MultiSection.java
- engine/src/main/java/org/terasology/world/block/family/MultiSections.java
- engine/src/main/java/org/terasology/world/block/family/RegisterBlockFamily.java
Minor fixes to the newBlockFamilies' javadocs as an extra for Block Families Task no. 3.
> Minor fixes to new block families' docs (merge to newBlockFamilies branch)

- engine/src/main/java/org/terasology/logic/console/commands/CoreCommands.java
Hi, I have added the following codes:
- command for prepare 10 Bowling pins
- command for dropping many blocks
- to activate bulk dropper type `bulkDrop (your_block_name) (drop_amount)`
- to activate bowling pin type `bowlingPrep (your_block_name)`
> Bouncy Objects

- config/groovy/functions.groovy
- facade.groovy
- lib.groovy
- meta.groovy
This system makes the current groovyw script system much more modular and improves the reusability of functions.
All the functions are stored in a 'functions.groovy' script in the 'configs/groovy/' directory and the base scripts are located in the root directory. 
There is only one problem with this approach. The base scripts are entirely same except for the initialization code in the start.
I wonder if we could make a 'commands.groovy' script in the configs folder and the base scripts would just initialize the type of command and pass on the arguments to the commands script. 
That would make the system even more modular.
Suggestions Please !!!
> Redesigned Groovyw Setup

- engine/src/main/java/org/terasology/identity/storageServiceClient/ServiceApiRequest.java
The identity storage service client now correctly follows HTTP redirects (301/302). Particularly useful if the server forces HTTP requests to move to HTTPS through 301/302 redirects, like the official server (http://utility.terasology.org) is now doing thanks to @qwc.
Try to use the identity storage service on the official server (http://utility.terasology.org), by clicking (from the main menu) Settings > Player > Login. On the current master/develop branches, it will only work if you enter the HTTPS URL (https://utility.terasology.org); the login will fail if you put the plain HTTP URL (http://utility.terasology.org), because it redirects to the HTTPS one but the client does not follow this redirect.
On this branch, both the HTTP and HTTPS URLs work (HTTP can be a bit slower due to the …
> Automatically follow HTTP/HTTPS redirects for identity storage service

- engine-tests/src/test/java/org/terasology/logic/console/ConsoleTest.java
- engine/src/main/java/org/terasology/logic/console/ConsoleImpl.java
There're small changes after code review for recently merged PR #3278 ( Issue #3268 )
> Fix javaDoc for Issue #3268

- engine/src/main/java/org/terasology/logic/console/Console.java
It's my second try (and I hope is the last one!) to fix javaDocs for the PR #3278 ( Issue #3268 ).
PLEASE DO NOT MERGE IT ! 
before @emanuele3d will have opportunity to take a look and approve it.
> Fix javaDoc (try #2)

- config/groovy/common.groovy
It adresses the problem with GithHub API pagination described in https://github.com/MovingBlocks/Terasology/issues/3279
Run: **groovyw module list**
Currently it returns 183 items. Before the change 100 items were returned.
> paginate large item hits via GitHub API

- engine/src/main/java/org/terasology/logic/characters/KinematicCharacterMover.java
Fixes [#3267](https://github.com/MovingBlocks/Terasology/issues/3267)
Jump into the water and check that you're not able to jump, neither diving underwater nor swimming above the surface
> Bug Character can jump once under water fixed

- engine-tests/src/test/java/org/terasology/rendering/md5/MD5PatternsTests.java
- engine/src/main/java/org/terasology/rendering/md5/MD5AnimationLoader.java
- engine/src/main/java/org/terasology/rendering/md5/MD5Patterns.java
- engine/src/main/java/org/terasology/rendering/md5/MD5SkeletonLoader.java
Based off of #3240 
I created a class, MD5Patterns, to hold the patterns that were in both the 
MD5AnimationLoader and MD5SkeletonLoader classes. Also,
I updated the float pattern from @kartikey0303's suggestion. 
In addition, I added unit tests for all of the patterns in the 
new class that was created. 
Run the new unit test class, along with all of the unit tests.
> Md5 patterns and unit tests

- README.markdown
Link to the discord and link to IntelliJ download site. Not in reference to a specific issue I just noticed that there weren't links and it would be convenient if they were there.
see that the links work
> Added links to discord and to intellij download in readme

- engine-tests/src/test/java/org/terasology/math/DirectionTests.java
Adds unit tests for the two of the methods inside of the Direction enum class.
Run the tests yourself, along with the entire suite if you like : )
If you have suggestions as far as anything goes let me know! I am also open
to suggestions when it comes to adding more tests to this class.
> Direction class unit tests

- engine/src/main/java/org/terasology/engine/TerasologyEngine.java
- engine/src/main/java/org/terasology/engine/module/ModuleManagerImpl.java
- engine/src/main/java/org/terasology/particles/rendering/SpriteParticleRenderer.java
Adds a hook so that facades can add classpaths to the engine module.
> Support facade classpaths

- config/gradle/ide.gradle
- fileTemplates/System.java
* Adds a fix for `@In` not correctly marking a variable as assigned if the variable was private
* Changes the year in the copyright to always be the current year
* Adds a file template for creating a System.
> IntelliJ Tweaks and Fixes

- engine/src/main/java/org/terasology/network/internal/AbstractClient.java
- engine/src/main/java/org/terasology/network/internal/ClientConnectionHandler.java
- engine/src/main/java/org/terasology/network/internal/ClientHandshakeHandler.java
- engine/src/main/java/org/terasology/network/internal/JoinStatusImpl.java
- engine/src/main/java/org/terasology/network/internal/LocalClient.java
- engine/src/main/java/org/terasology/network/internal/NetClient.java
Signed-off-by: engiValk <adamkenyon554@gmail.com>
Adding Javadoc to all the network code to make use and readability easier.
Do not merge until all docs are done. This is just one file for now.
> Network code documentation

- engine/src/main/java/org/terasology/world/block/family/AbstractBlockFamily.java
- engine/src/main/java/org/terasology/world/block/family/FreeformFamily.java
I just reworded the block name to avoid confusion and also added a bit more logging information that helped diagnoses the issue.
old:
Registered BlockFamily[core:brick:engine:stair]
new:
Registered BlockFamily[freeform,core:brick:engine:stair]
> fixed rotation issue with freeform family and added more detailed logging information for BlockFamily

- engine/src/main/java/org/terasology/math/AABB.java
- engine/src/main/java/org/terasology/math/Border.java
- engine/src/main/java/org/terasology/math/Diamond3iIterator.java
- engine/src/main/java/org/terasology/math/Direction.java
- engine/src/main/java/org/terasology/math/Pitch.java
- engine/src/main/java/org/terasology/math/Roll.java
- engine/src/main/java/org/terasology/math/Rotation.java
- engine/src/main/java/org/terasology/math/Side.java
- engine/src/main/java/org/terasology/math/SideBitFlag.java
- engine/src/main/java/org/terasology/math/Yaw.java
Cleanup work in org.terasology.math. Primarily marks fields which are effectively final as "final", but also performs more advanced cleanup/optimizations in Rotation.
If the game turns on, it's probably fine.
> cleanup work in org.terasology.math

- engine/src/main/java/org/terasology/engine/module/ExternalApiWhitelist.java
Additions to the API whitelist for consideration.
Review the classes for being sandbox-friendly, I guess?
> Expand API whitelist with ZIP and more IO-related classes

- engine/src/main/java/org/terasology/world/block/items/BlockItemSystem.java
- engine/src/main/java/org/terasology/world/block/items/OnBlockItemPlaced.java
Added a new constructor in `OnBlockItemPlaced` to have a third argument for event instigator, and corresponding changes made in `BlockItemSystem`.
> New constructor in `OnBlockItemPlaced` to have a third argument for event instigator

- engine/src/main/java/org/terasology/rendering/nui/widgets/UISlider.java
Fixes the issue due to the new listeners on UISliders. :)
> Fix the issue with ALL UISliders

- engine/src/main/java/org/terasology/rendering/nui/layouts/ScrollableArea.java
This PR refactors the Scrollable Area widget to be more readable and structured better.
In addition to this the PR adds methods to enable horizontal or vertical scrollbars from the code.
Also adds javadoc for all methods.
> Scrollable area refactor

- engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/advancedGameSetupScreen/AdvancedGameSetupScreen.java
- engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/gameDetailsScreen/GameDetailsScreen.java
- engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/moduleDetailsScreen/ModuleDetailsScreen.java
- engine/src/main/resources/assets/ui/menu/advancedGameSetupScreen.ui
- engine/src/main/resources/assets/ui/menu/moduleDetailsScreen.ui
Small refactoring and I've added possibility to open ModuleDetails screen from AdvancedGameSetup screen.
1. Open AdvancedGameSetup screen
2. Try to open ModuleDetails screen
Nothing.
> Tweak advanced game setup screen + small improvements

- engine-tests/src/main/java/org/terasology/TerasologyTestingEnvironment.java
- engine-tests/src/test/java/org/terasology/persistence/internal/StorageManagerTest.java
- engine-tests/src/test/java/org/terasology/recording/EventSystemReplayImplTest.java
- engine/src/main/java/org/terasology/engine/bootstrap/EntitySystemSetupUtil.java
- engine/src/main/java/org/terasology/recording/RecordAndReplaySerializer.java
- engine/src/main/java/org/terasology/recording/RecordedEventSerializer.java
Support to be able to record BindButtonEvents that are in modules.
Run `WoodCutReplayTest` in the TestReplayModule
> Updating Record and Replay to make it possible to record other module's BindButtonEvents

- engine/src/main/java/org/terasology/config/Config.java
- engine/src/main/java/org/terasology/config/RootConfig.java
- engine/src/main/java/org/terasology/config/UniverseConfig.java
- engine/src/main/java/org/terasology/game/GameManifest.java
- engine/src/main/java/org/terasology/persistence/internal/ReadWriteStorageManager.java
- engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/GameManifestProvider.java
- engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/NewGameScreen.java
- engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/StartPlayingScreen.java
- engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/UniverseWrapper.java
Fixes the issue the GameName being null and the one with spawning world. 
I'll push the config stuff to this PR itself, no need to merge this one yet.
> Game Name + Spawning World Issue + UniverseConfig [WIP]

- engine/src/main/java/org/terasology/recording/CharacterStateEventPositionMap.java
- engine/src/main/java/org/terasology/recording/DirectionAndOriginPosRecorder.java
- engine/src/main/java/org/terasology/recording/EventCatcher.java
- engine/src/main/java/org/terasology/recording/EventCopier.java
- engine/src/main/java/org/terasology/recording/RecordAndReplayCurrentStatus.java
- engine/src/main/java/org/terasology/recording/RecordAndReplayStatus.java
- engine/src/main/java/org/terasology/recording/RecordAndReplayUtils.java
- engine/src/main/java/org/terasology/recording/RecordedEvent.java
- engine/src/main/java/org/terasology/recording/RecordedEventStore.java
JavaDoc improvements for the Record and Replay classes
> Improvements to the Record and Replay classes' JavaDoc

- engine/src/main/java/org/terasology/engine/modes/loadProcesses/AwaitCharacterSpawn.java
- engine/src/main/java/org/terasology/engine/modes/loadProcesses/CacheBlocks.java
- engine/src/main/java/org/terasology/engine/modes/loadProcesses/CacheTextures.java
- engine/src/main/java/org/terasology/engine/modes/loadProcesses/EnsureSaveGameConsistency.java
- engine/src/main/java/org/terasology/engine/modes/loadProcesses/InitialiseRecordAndReplay.java
- engine/src/main/java/org/terasology/engine/modes/loadProcesses/JoinServer.java
- engine/src/main/java/org/terasology/engine/modes/loadProcesses/LoadPrefabs.java
- engine/src/main/java/org/terasology/engine/modes/loadProcesses/PostBeginSystems.java
- engine/src/main/java/org/terasology/engine/modes/loadProcesses/PreBeginSystems.java
- engine/src/main/java/org/terasology/engine/modes/loadProcesses/PrepareWorld.java
- engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/loadingScreen/LoadingScreen.java
- engine/src/main/resources/assets/i18n/menu.lang
- engine/src/main/resources/assets/i18n/menu_en.lang
- engine/src/main/resources/assets/i18n/menu_pt.lang
Hi guys, that's my first pull request for Terasology. Therefore, I need some feedback so I can make sure I'm doing it correctly. 
Basically, I changed a lot of LoadProcess's `getMessage` methods to return the string according to i18n, then I changed the LoadingScreen `updateStatus` method to translate these strings. 
Here is how it was done:
```java
@Override
public String getMessage() {
return "${engine:menu#loading-prefabs}";
}
```
```java
public void updateStatus(String message, float v) {
if (messageLabel != null) {
messageLabel.setText(translationSystem.translate(message));
}
...
}
```
Now we can have the load screen status translated to any language.
This work is in progress, because the code still has a bunch of English hard-coded strings.
> Translate load screen status messages

- engine/src/main/java/org/terasology/math/AABB.java
Adds documentation to the undocumented methods in the `AABB` class, and performs some refactoring.
- `createMinMax`
- `createCenterExtent`
- `createEmpty`
- `createEncompassing` (vertices variant)
- `getCenter`
- `getMin`
- `getMax`
- `transform` (both variants)
- `getFirstHitPlane`
- `intersectRectangle`
- `minX`, `Y`, `Z`
- `maxX`, `Y`, `Z`
- `AABB.getFirstHitPlane`
> AABB improvements

- README.markdown
Makes it look more impressive B)
> Remove 'latest' qualifier from downloads count

- README.markdown
- engine/src/main/java/org/terasology/world/block/entity/BlockCommands.java
Playing with a new integration for PRs
> Try out LGTM

- engine/src/main/java/org/terasology/monitoring/chunk/ChunkMonitorEntry.java
- engine/src/main/java/org/terasology/monitoring/gui/ChunkMonitorDisplay.java
- engine/src/main/java/org/terasology/rendering/collada/ColladaLoader.java
- engine/src/main/java/org/terasology/rendering/nui/widgets/UIButtonWebBrowser.java
Fixes the following list of issues from #3510:
- Command line is built with string concatenation
- Container contents are never accessed
- Container contents are never initialized
Most of the affected classes are not under unit test, but I have run all unit tests locally to verify I didn't break anything and manually tested the affected parts by running the game.
> Fixes for some of #3510

- engine/src/main/java/org/terasology/recording/RecordAndReplayCurrentStatus.java
Javadoc update to reflect the changes made on #3506
> RecordAndReplayCurrentStatus' javadoc update to reflect the UI changes made on #3506

- engine/src/main/java/org/terasology/rendering/dag/stateChanges/BindFbo.java
- engine/src/main/java/org/terasology/rendering/dag/stateChanges/DisableDepthWriting.java
- engine/src/main/java/org/terasology/rendering/dag/stateChanges/EnableMaterial.java
- engine/src/main/java/org/terasology/rendering/dag/stateChanges/LookThroughDefault.java
- engine/src/main/java/org/terasology/rendering/dag/stateChanges/SwapGBuffers.java
Fixes the LGTM hashCode error in #3510.
> Fixes the LGTM error "Inconsistent equals and hashCode"

- engine/src/main/java/org/terasology/input/lwjgl/JInputControllerDevice.java
Fixes the "Type mismatch on container modification" from #3510.
The input code was fairly tightly coupled so I had trouble unit testing this approach. As an alternative, I have [attached a snippet in this Gist](https://gist.github.com/mwvdev/a2c868c2679c345f220c1155213de289) to verify that this fix works. The snippet also shows that the LGTM error is unlikely to be a false positive.
> Fixed the LGTM error "Type mismatch on container modification"

- engine/src/main/java/org/terasology/engine/module/ModuleManagerImpl.java
- engine/src/main/java/org/terasology/identity/storageServiceClient/ServiceApiRequest.java
- engine/src/main/java/org/terasology/recording/RecordAndReplaySerializer.java
- engine/src/main/java/org/terasology/recording/RecordedEventSerializer.java
- engine/src/main/java/org/terasology/rendering/assets/material/MaterialFormat.java
- engine/src/main/java/org/terasology/rendering/opengl/GLSLShader.java
Fixes the "Potential input resource leak" warnings from #3510.
I've only tested this manually by trying to run the affected code.
> Fixed the LGTM warnings "Potential input resource leak"

- engine/src/main/java/org/terasology/persistence/internal/GamePreviewImageProvider.java
- engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/FilePickerPopup.java
- engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/savedGames/GameProvider.java
Fix for deleted saves error #3547 
The return line used a stream which remained open and caused the folder to be inaccessible, giving an error in the delete process.
I've put the stream in a try with resources construct which closed the stream right after using it.
Make a new save, then try to delete it.
> Fixed deleted saves error.

- engine/src/main/java/org/terasology/rendering/collada/ColladaLoader.java
Fixed some LGTM errors in ColladaLoader
> Fixed LGTM Issue - Dereferenced variable may be null - GCI

- engine/src/main/java/org/terasology/engine/internal/TimeBase.java
- engine/src/main/java/org/terasology/logic/players/LocalPlayerSystem.java
- engine/src/main/java/org/terasology/math/MatrixUtils.java
- engine/src/main/java/org/terasology/persistence/internal/ReadWriteStorageManager.java
- engine/src/main/java/org/terasology/rendering/cameras/FrustumPlane.java
- engine/src/main/java/org/terasology/rendering/dag/nodes/ShadowMapNode.java
- engine/src/main/java/org/terasology/rendering/nui/internal/Line.java
- engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/settings/PlayerSettingsScreen.java
- engine/src/main/java/org/terasology/rendering/nui/layouts/ColumnLayout.java
- engine/src/main/java/org/terasology/rendering/nui/layouts/MultiRowLayout.java
- engine/src/main/java/org/terasology/rendering/nui/widgets/UIRadialRing.java
- engine/src/main/java/org/terasology/rendering/world/WorldRendererImpl.java
- engine/src/main/java/org/terasology/utilities/procedural/HeightmapFileReader.java
- engine/src/main/java/org/terasology/utilities/procedural/Voronoi.java
- engine/src/main/java/org/terasology/world/time/WorldTimeEvent.java
GCI Task: Fix a group of LGTM warnings - MovingBlocks
Fixes LGTM warnings "Result of multiplication cast to wider type" #3510 | 15 files, 18 alerts
https://lgtm.com/projects/g/MovingBlocks/Terasology/alerts/?mode=tree&severity=warning&ruleFocus=7900075
> Fix LGTM warnings "Result of multiplication cast to wider type" - GCI

- engine/src/main/java/org/terasology/persistence/serializers/ProtobufSerializer.java
Adds Documentation to ProtobufSerialization
Ensure there are no build problems. 
N/A
> Added ProtobufSerialization Documentation

- engine/src/main/java/org/terasology/persistence/serializers/GsonSerializer.java
Added Documentation to GsonSerializer. Used same methodology as in #3562 
Ensure accurate descriptions in documentation. Make sure there are no issues with merging.
N/A
> Added Documentation to GsonSerializer.java

- engine/src/main/java/org/terasology/audio/AudioEndListener.java
- engine/src/main/java/org/terasology/engine/subsystem/config/BindsManager.java
- engine/src/main/java/org/terasology/logic/characters/CharacterSystem.java
- engine/src/main/java/org/terasology/logic/characters/KinematicCharacterMover.java
- engine/src/main/java/org/terasology/logic/location/DistanceComparator.java
- engine/src/main/java/org/terasology/math/Region3i.java
- engine/src/main/java/org/terasology/rendering/RenderHelper.java
- engine/src/main/java/org/terasology/rendering/cameras/Camera.java
- engine/src/main/java/org/terasology/rendering/cameras/PerspectiveCamera.java
- engine/src/main/java/org/terasology/rendering/nui/internal/Line.java
- engine/src/main/java/org/terasology/rendering/nui/layouts/ColumnLayout.java
- engine/src/main/java/org/terasology/rendering/nui/layouts/MultiRowLayout.java
- engine/src/main/java/org/terasology/rendering/opengl/FBO.java
- engine/src/main/java/org/terasology/rendering/world/viewDistance/ClientViewDistanceSystem.java
- engine/src/main/java/org/terasology/utilities/procedural/BrownianNoise.java
- engine/src/main/java/org/terasology/utilities/procedural/BrownianNoise2D.java
- engine/src/main/java/org/terasology/utilities/procedural/BrownianNoise3D.java
Fixes some of the LGTM alerts mentioned in #3510
Run the unit tests that are covering the affected files.
> Fix LGTM Alerts

- engine-tests/src/test/java/org/terasology/rendering/FontUnderlineTest.java
…ineTest.java
Added 4 unit tests for the FontUnderline class
Added 4 unit tests for the FontUnderline class under rendering for the isValid() and markUnderlined() methods.
Run them :)
> Add unit tests to the FontUnderline class

- engine/src/main/java/org/terasology/rendering/nui/widgets/UIImage.java
Issue #3584. In UIImage boolean atribute wasn't used right and I adjusted ScaleMode
> SlideImagesPreviewScaleFixed

- README.markdown
Adds a badge for discord chat to the readme. This includes a link to the discord server when clicked.
> Add discord to the readme

- engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/UniverseSetupScreen.java
- engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/WorldPreGenerationScreen.java
- engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/WorldSetupScreen.java
- engine/src/main/java/org/terasology/rendering/world/WorldSetupWrapper.java
- engine/src/main/resources/assets/ui/worldSetupScreen.ui
Now world can have custom name
create a new advance game 
- click on configure button after adding world.
- change name and click on done.
- click on continue and world pregeneration screen will appear
- click on configure button and here also you can change name 
- after changing name go back to universe setup screen and you can see changes has been reflected back
> changes for custom world name

- engine/src/main/java/org/terasology/engine/module/ModuleInputStream.java
- engine/src/main/java/org/terasology/engine/module/ModuleOutputStream.java
- engine/src/main/java/org/terasology/engine/module/SandboxFileManager.java
- engine/src/main/java/org/terasology/engine/module/SandboxManager.java
- engine/src/main/java/org/terasology/engine/paths/PathManager.java
I'm following the "safe" file space approach to solve this issue (closes #3366). I've changed the `PathManager` to create a new sub-directory ( `<user home>/Terasology/sandbox`) in the game data directory. I've also created the `SandboxFileManager` which wraps common file operations so they're only allowed to happen within that sub-directory. The `SandboxFileManager` is marked with the `@API` annotation so that it could be accessed by any module.
1. Using any module like `BuilderSampleGameplay`, you could implement `postSave()` method in the system class, like this:
```java
@Override
public void postBegin() {
SandboxFileManager sandboxFileManager = new SandboxFileManager();
byte[] someBytes = new byte[2];
someBytes[0] = 'h';
someBytes[1] = 'i';
Consumer<OutputStream> consumer = …
```
> Allow modules limited API access to files

- engine/src/main/java/org/terasology/i18n/assets/TranslationFormat.java
Fixes #3629 
Allow UI text to be specified in an array
Change string to array of strings in some of the *.lang files (menu_en.lang for example).
Launch the game, if there is no stack traces in log and corresponding string shows ok - it works.
> Issue #3629

- engine-tests/src/test/java/org/terasology/i18n/TranslationFormatTests.java
Here is a multi-line test for PR #3698 and issue #3629
> Feature multi line test

- config/groovy/module.groovy
- docs/Modules.md
- engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/moduleDetailsScreen/ModuleDetailsScreen.java
Short and simple, just ran into it by coincidence trying to update all the modules, that script didn't like BiomesAPI being present without being its own Git repo.
Making PR to doc, to see if somebody wants some easy merge practice, and in case somebody else manages to spot anything else I missed.
> Plug in a few missing BiomesAPI spots

- config/groovy/common.groovy
`groovyw` command for modules fails for engine modules (and `.settings` folder generated by some IDEs or editors). This PR catches the `RepositoryNotFoundException` to fail gracefully.
> fix groovy module commands for engine modules

- engine/src/main/java/org/terasology/logic/behavior/GroupMindComponent.java
- engine/src/main/java/org/terasology/logic/behavior/GroupTagComponent.java
New group components. This relates directly with PR #3717 and with [WildAnimalsMadness PR #1](https://github.com/Terasology/WildAnimalsMadness/pull/1).
The new Group components were created as part of the WildAnimalsMadness module. After testing the different grouping scenarios they are ready to me moved into the behavior package as originally intended.
- New component: `GroupTag`
- New component: `GroupMind`
> Added group components to the behavior package

- engine-tests/src/test/java/org/terasology/rendering/cameras/PerspectiveCameraTest.java
- engine/src/main/java/org/terasology/engine/subsystem/DisplayDevice.java
- engine/src/main/java/org/terasology/engine/subsystem/headless/device/HeadlessDisplayDevice.java
- engine/src/main/java/org/terasology/engine/subsystem/lwjgl/LwjglDisplayDevice.java
- engine/src/main/java/org/terasology/rendering/cameras/PerspectiveCamera.java
This PR add's a basic test for perspective camera and verifies the view and projection matrix. I also reworked display devices to return the display height and width.  
This also helps me verify my JOML port when I rework the camera. #3706
> added camera test

- README.markdown
I feel like the punctuation of the read me would be better with some added . and a few , that I added. 
I am not a master at grammar or anything but I feel like that this would be "more correct"
If you think the changes are not good it is ok, I wanted to try to be helpful.
For line 22: "We encourage contributions from anybody and try to keep a warm and friendly community and maintain a [code of conduct](https://github.com/MovingBlocks/Terasology/blob/develop/docs/CODE_OF_CONDUCT.md)" I did not add a . because it would make it look weird.
Adds better punctuation. 
Please read it to decide if you agree.
> Better punctuation

- engine/src/main/java/org/terasology/math/Rotation.java
- engine/src/main/java/org/terasology/particles/ParticlePool.java
- engine/src/main/java/org/terasology/rendering/primitives/BlockMeshGeneratorSingleShape.java
- engine/src/main/java/org/terasology/rendering/primitives/ChunkTessellator.java
- engine/src/main/java/org/terasology/rendering/world/WorldRendererImpl.java
#3798 
Sir/Madam I have solved checkstyle issues in Terasology project.
The files that are changes are - 
1: engine/src/main/java/org/terasology/math/Rotation.java
2: engine/src/main/java/org/terasology/particles/ParticlePool.java
3: engine/src/main/java/org/terasology/rendering/primitives/BlockMeshGeneratorSingleShape.java
4: engine/src/main/java/org/terasology/rendering/primitives/ChunkTessellator.java
5: engine/src/main/java/org/terasology/rendering/world/WorldRendererImpl.java
> Checkstyleissuessolved

- engine/src/main/java/org/terasology/engine/module/ModuleInstaller.java
- engine/src/main/java/org/terasology/utilities/download/MultiFileDownloader.java
Fixes issue #3801. Switched URL to a URI for better mapping. Also, added some javadoc documentation for the Class.  Changed the usage of MultiFileDownloader in ModuleInstaller.java to match with the current changes. Also changed getDownloadUrls() method to map URIs instead of URLs as well.
In order to test this try to install new modules.
> Switched URL to a URI for better mapping.

- engine/src/main/java/org/terasology/math/Direction.java
- engine/src/main/java/org/terasology/math/Side.java
Fixes some Checkstyle errors in `math`
> resolved checkstyle errors

- engine/src/main/java/org/terasology/engine/module/ExternalApiWhitelist.java
Exposes JOML as a package to Modules
impot JOML, JomlUtil in any module and replace any vector/matrix with JOML counterpart and convert it to TeraMath conterpart with JomlUtil.from()
> Expose JOML as a package to modules

- engine/src/main/java/org/terasology/engine/modes/loadProcesses/PrepareWorld.java
Fixes the loading bar issue where the bar crosses its limits
Start the game and the loading bar will not overshoot
> fixed loading bar issue

- engine-tests/src/test/java/org/terasology/entitySystem/PojoEntityManagerTest.java
- engine/src/main/java/org/terasology/audio/formats/OggStreamingSoundData.java
> Logger and unused variable

- engine-tests/src/test/java/org/terasology/entitySystem/PojoEntityManagerTest.java
- engine-tests/src/test/java/org/terasology/entitySystem/PojoEventSystemTests.java
- engine/src/main/java/org/terasology/logic/console/commands/WorldCommands.java
- engine/src/main/java/org/terasology/rendering/assets/texture/NoiseTextureProducer.java
- engine/src/main/java/org/terasology/rendering/nui/SortOrderSystem.java
- engine/src/main/java/org/terasology/world/block/items/BlockItemSystem.java
Just deleting some unused variables.
> Removed unused variables

- engine-tests/src/test/java/org/terasology/documentation/ApiScraper.java
- engine/src/main/java/org/terasology/audio/system/AudioSystem.java
- engine/src/main/java/org/terasology/entitySystem/sectors/SectorUtil.java
- engine/src/main/java/org/terasology/logic/characters/CharacterMovementSystemUtility.java
- engine/src/main/java/org/terasology/logic/characters/events/ActivationPredicted.java
- engine/src/main/java/org/terasology/logic/common/ActivateEvent.java
- engine/src/main/java/org/terasology/logic/players/LocalPlayer.java
- engine/src/main/java/org/terasology/logic/players/LocalPlayerSystem.java
- engine/src/main/java/org/terasology/logic/players/PlayerSystem.java
- engine/src/main/java/org/terasology/network/internal/NetClient.java
- engine/src/main/java/org/terasology/persistence/internal/AbstractStorageManager.java
- engine/src/main/java/org/terasology/persistence/internal/PlayerStoreInternal.java
- engine/src/main/java/org/terasology/physics/bullet/BulletPhysics.java
- engine/src/main/java/org/terasology/physics/bullet/EntityMotionState.java
- engine/src/main/java/org/terasology/rendering/logic/FloatingTextRenderer.java
- engine/src/main/java/org/terasology/rendering/logic/MeshRenderer.java
- engine/src/main/java/org/terasology/world/chunks/internal/ChunkRelevanceRegion.java
- modules/Core/src/main/java/org/terasology/logic/actions/ExplosionAuthoritySystem.java
Contains
The game crashes when any player on the server tries to respawn when multiple players are present in the server.
How to test
- Start a local server and two clients using run configurations .
- Join the server from both the clients.
- Die and respawn any player.(This causes the game to crash in the version before fix)
> Multipayer Respawn Crash Bug Fix

- .gitattributes
- modules/CoreSampleGameplay/src/main/java/org/terasology/coresamplegameplay/PlayerStartingInventorySystem.java
- companion no longer lies in CoreBlocks but in Core
- add .dll and .pdb to .gitattributes
> fix: companion module reference

- engine/src/main/java/org/terasology/rendering/assets/font/Font.java
- engine/src/main/java/org/terasology/rendering/assets/font/FontImpl.java
- engine/src/main/java/org/terasology/rendering/nui/itemRendering/StringTextIconRenderer.java
- engine/src/main/java/org/terasology/rendering/nui/itemRendering/StringTextRenderer.java
- engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/inputSettings/UIInputBind.java
- engine/src/main/java/org/terasology/rendering/nui/widgets/TooltipLineRenderer.java
- engine/src/main/java/org/terasology/rendering/nui/widgets/UIButton.java
- engine/src/main/java/org/terasology/rendering/nui/widgets/UILabel.java
- engine/src/main/java/org/terasology/rendering/nui/widgets/UIScrollingText.java
- engine/src/main/java/org/terasology/rendering/nui/widgets/UIText.java
This is another bite sized PR that just changed Vector2i for font.
> converted terasology vector2i to joml vector2i for font

- engine/src/main/java/org/terasology/logic/players/FirstPersonHeldItemMountPointComponent.java
This resolve a serialization issue found with #3877. 
Use the dumpEntities command to get a text file with all active entities written to my workspace for troubleshooting.
> removed vrProvider from FirstPersonHeldItemMountPointComponent for #3877

- .gitpod.yml
- gitpod.dockerfile
Files required to run Terasology using Gitpod
- Create an account on Gitpod (easier with Github credentials)
- Create a new workspace using this PR link: https://github.com/MovingBlocks/Terasology/pull/<PR number>
- After the workspace is created and the init scripts are executed you should see Terasology's initial screen shown in the VNC machine panel
Related discussion: https://community.gitpod.io/t/lwjgl-openal/1105
> Added Gitpod files

- engine/src/main/java/org/terasology/logic/chat/ChatMessageEvent.java
- engine/src/main/resources/assets/prefabs/floatingCube.prefab
- engine/src/main/resources/assets/prefabs/player/player.prefab
doc: Add notes about event target and sender entity to ChatMessageEvent
fix: Remove components from prefabs that are no longer in engine
- MinionMove is in Behaviors
- Breather is in Breathing
>  chore: Add JavaDoc and fix some prefabs

- engine/src/main/java/org/terasology/persistence/typeHandling/coreTypes/factories/ObjectFieldMapTypeHandlerFactory.java
- engine/src/main/java/org/terasology/reflection/reflect/ConstructorLibrary.java
Due to the way permissions are checked by both gestalt and Java, `SecurityExceptions` are raised when a module declared `TypeHandler`/`TypeHandlerFactory` calls code that accesses members of a type using reflection call. This problem was illuminated by Terasology/QuestExamples#11, where `TaskGraphTypeHandler` in the `Tasks` module would request the creation of the `TypeHandler` for the runtime task type. The creation process (via `ObjectFieldMapTypeHandlerFactory`) involves retrieving all the declared fields and constructors of a type with reflection, something that modules are not allowed to do.
Offending code in `ObjectFieldMapTypeHandlerFactory` and `ConstructorLibrary` that uses reflection to retrieve declared members of a type is wrapped in a `AccessController.doPrivileged` call so …
> fix: Use appropriate privileges to access members of types with reflection during serialization

- engine-tests/src/test/java/org/terasology/particles/updating/ParticleUpdaterImplTest.java
- engine/src/main/java/org/terasology/particles/ParticleSystemManager.java
- engine/src/main/java/org/terasology/particles/ParticleSystemManagerImpl.java
- engine/src/main/java/org/terasology/particles/functions/RegisterParticleSystemFunction.java
- engine/src/main/java/org/terasology/particles/functions/affectors/AccelerationAffectorFunction.java
- engine/src/main/java/org/terasology/particles/functions/affectors/AffectorFunction.java
- engine/src/main/java/org/terasology/particles/functions/affectors/VelocityAffectorFunction.java
- engine/src/main/java/org/terasology/particles/functions/generators/ColorRangeGeneratorFunction.java
- engine/src/main/java/org/terasology/particles/functions/generators/EnergyRangeGeneratorFunction.java
- engine/src/main/java/org/terasology/particles/functions/generators/GeneratorFunction.java
- engine/src/main/java/org/terasology/particles/functions/generators/PositionRangeGeneratorFunction.java
- engine/src/main/java/org/terasology/particles/functions/generators/ScaleRangeGeneratorFunction.java
- engine/src/main/java/org/terasology/particles/functions/generators/TextureOffsetGeneratorFunction.java
- engine/src/main/java/org/terasology/particles/functions/generators/VelocityRangeGeneratorFunction.java
- engine/src/main/java/org/terasology/particles/updating/ParticleUpdater.java
- engine/src/main/java/org/terasology/particles/updating/ParticleUpdaterImpl.java
This commit is a continuation from #3230. I removed Facade.groovy, resolved compile issues, conflicts and implemented tweaks from @eviltak.
> feat: Particle System Gen./Aff. Registration

- engine/src/main/java/org/terasology/world/WorldProvider.java
- engine/src/main/java/org/terasology/world/internal/WorldProviderCore.java
Modified Javadocs for setExtraData methods. This is a part of #3904 which was split into this PR and https://github.com/Terasology/BiomesAPI/pull/2 after #3942 was merged.
> modified javadocs

- Jenkinsfile
I'm more or less blindly editing files in the hope they play together in some way at the end 🤷
Related to https://github.com/MovingBlocks/ModuleJteConfig/commit/2de63dadf0abd343ccc4e66c71eb8ba58d2f1ed9
Related to #3942
> fix: add 'templates/build.gradle' to build artifacts

- engine-tests/src/test/java/org/terasology/world/propagation/BulkLightPropagationTest.java
- engine-tests/src/test/java/org/terasology/world/propagation/BulkSunlightPropagationTest.java
- engine/src/main/java/org/terasology/world/internal/WorldProviderCoreImpl.java
- engine/src/main/java/org/terasology/world/propagation/BlockChange.java
- engine/src/main/java/org/terasology/world/propagation/StandardBatchPropagator.java
- engine/src/main/java/org/terasology/world/propagation/SunlightRegenBatchPropagator.java
This PR migrates `BlockChange` to JOML and adjusts its usage throughout the engine.
> feat(JOML): Migrate BlockChange

- engine/src/main/java/org/terasology/math/Side.java
added some missing javadocs and added migrated JOML methods.
> feat(JOML) Migrate Side

- .idea/codeStyles/Project.xml
> build(idea): Import classes instead of fully qualified names

- engine/src/main/java/org/terasology/rendering/logic/RegionOutlineRenderer.java
- engine/src/main/java/org/terasology/rendering/logic/SkeletonRenderer.java
ref: https://github.com/Terasology/CoreRendering/issues/11
ref: https://github.com/MovingBlocks/Terasology/pull/3950
verified with gooeyquest.
> fix invisible skeletalmesh

- engine/src/main/java/org/terasology/rendering/primitives/Tessellator.java
- engine/src/main/java/org/terasology/world/block/internal/BlockBuilder.java
- engine/src/main/java/org/terasology/world/block/shapes/BlockMeshPart.java
- engine/src/main/java/org/terasology/world/block/shapes/JsonBlockShapeLoader.java
I ported over the JsonBlockShapeLoader to json. The next part is trying to port overt the Tesselator. 
this logic is used to load in blocks so just loading in a world should be enough to verify the functionality.
> feat(JOML): Migrate BlockMeshLoader

- engine-tests/src/test/java/org/terasology/rendering/nui/internal/LineTest.java
- engine-tests/src/test/java/org/terasology/rendering/nui/layouts/CardLayoutTest.java
- engine-tests/src/test/java/org/terasology/rendering/nui/layouts/ColumnLayoutTest.java
- engine-tests/src/test/java/org/terasology/rendering/nui/layouts/RowLayoutTest.java
- engine-tests/src/test/java/org/terasology/rendering/nui/layouts/ZoomableLayoutTest.java
- engine/src/main/java/org/terasology/input/device/MouseDevice.java
- engine/src/main/java/org/terasology/input/device/nulldevices/NullMouseDevice.java
- engine/src/main/java/org/terasology/input/lwjgl/LwjglMouseDevice.java
- engine/src/main/java/org/terasology/reflection/copy/legacy/Quat4fCopyStrategy.java
- engine/src/main/java/org/terasology/reflection/copy/legacy/Vector2fCopyStrategy.java
- engine/src/main/java/org/terasology/reflection/copy/legacy/Vector2iCopyStrategy.java
- engine/src/main/java/org/terasology/reflection/copy/legacy/Vector3fCopyStrategy.java
- engine/src/main/java/org/terasology/reflection/copy/legacy/Vector3iCopyStrategy.java
- engine/src/main/java/org/terasology/reflection/copy/legacy/Vector4fCopyStrategy.java
- engine/src/main/java/org/terasology/rendering/nui/internal/NUIManagerInternal.java
- engine/src/main/java/org/terasology/rendering/nui/widgets/browser/data/basic/FlowParagraphRenderable.java
- engine/src/main/java/org/terasology/rendering/nui/widgets/browser/data/basic/flow/ContainerRenderSpace.java
- engine/src/main/java/org/terasology/rendering/nui/widgets/browser/data/basic/flow/FlowRenderable.java
- engine/src/main/java/org/terasology/rendering/nui/widgets/browser/data/basic/flow/ImageFlowRenderable.java
- engine/src/main/java/org/terasology/rendering/nui/widgets/browser/data/basic/flow/TextFlowRenderable.java
- engine/src/main/java/org/terasology/rendering/nui/widgets/browser/data/html/basic/MultiBlockParagraphRenderable.java
- engine/src/main/java/org/terasology/rendering/nui/widgets/browser/data/html/basic/list/ListParagraphRenderable.java
- engine/src/main/java/org/terasology/rendering/nui/widgets/browser/data/html/basic/list/OrderedListDecorator.java
- engine/src/main/java/org/terasology/rendering/nui/widgets/browser/data/html/basic/list/UnorderedListDecorator.java
- engine/src/main/java/org/terasology/rendering/nui/widgets/browser/ui/BrowserWidget.java
- engine/src/main/java/org/terasology/rendering/nui/widgets/browser/ui/ContainerFlowContainerRenderSpace.java
- engine/src/main/java/org/terasology/rendering/nui/widgets/browser/ui/DocumentRenderer.java
- engine/src/main/java/org/terasology/rendering/nui/widgets/browser/ui/ParagraphRenderable.java
This pull request depends on and should be integrated into #4017.
The code from that branch previously crashed due a type conflict in `MouseDevice` between the extracted NUI's version of `org.terasology.input` and the built-in (original) version, as NUI now uses `Vector2i` from JOML instead of TeraMath (incompatible method definitions).
I also made some fixes to prevent a crash in `NUIManagerInternal` due to it querying key bindings that don't exist yet (often when the game is started for the first time).
In addition, a serialisation bug relating to the removal of TeraMath serialisers from the codebase has been fixed, by re-adding the serialisers previously removed (as they are no longer in `nui-reflect`). This fixes the camera behaving incorrectly when a world is loaded for the first …
> feat/nui-extraction branch: Make the game playable again

- engine/src/main/java/org/terasology/engine/module/ModuleManagerImpl.java
Fixes loading modules from classpath to resolve https://github.com/Terasology/ModuleTestingEnvironment/issues/12
Detailed in the accompanying MTE PR: https://github.com/Terasology/ModuleTestingEnvironment/pull/16
I'm not sure why this limited to URLClassLoader previously. My guess is because ClassLoader has these methods `protected` where URLClassLoader has them public. I couldn't find any case where the system classloader is changed from the default. To my knowledge this can only typically be done via a system property, and that property didn't have any hits in the codebase either.
My only concern is that I don't know the implications of always loading modules from the classpath when they're provided. Still, it seems semantically correct that any time we explicitly put modules in the …
> always try loading classpath jars as modules

- engine/src/main/java/org/terasology/rendering/assets/material/BaseMaterial.java
- engine/src/main/java/org/terasology/rendering/cameras/PerspectiveCamera.java
ref: https://github.com/Terasology/CoreRendering/pull/17
> feat(JOML): Migrate transpose Camera#getInverseProjectionMatrix()

- engine/src/main/java/org/terasology/rendering/RenderHelper.java
- engine/src/main/java/org/terasology/rendering/cameras/SubmersibleCamera.java
this is just a migration for the submersible camera. pretty simple change with all the other changes in the core engine.
> feat(JOML): migrate submersibleCamera

- engine/src/main/java/org/terasology/engine/TerasologyEngine.java
A small typo fix for a comment in the TerasologyEngine class.
Not applicable
> small typo fix

- engine/src/main/java/org/terasology/logic/behavior/Interpreter.java
> check nulls in Interpreter#toString() (fixes #4074)

- engine/src/main/java/org/terasology/entitySystem/event/BeforeAfterEvent.java
Adds AbstractBeforeAfterEvent : Immutable event to notify a change in a certain value.
This is a generic event and more specific events implementing this event should be fired and reacted to.
> feat: Add BeforeAfterEvent

- engine/src/main/java/org/terasology/engine/TerasologyEngine.java
- facades/PC/src/main/java/org/terasology/engine/Terasology.java
This PR fixes #4092
For now, run the load latest configuration.
My code might not be named or commented in the best way. It could also be benficial to create tests for this specific load configuration.
> fixed the load latest configuration

- engine/src/main/java/org/terasology/rendering/logic/RegionOutlineRenderer.java
This is pretty simple to verify. this can be verified in StructuredTemplates with the wall replacement tool. where the highlighted green region is displayed from the RegionOutlineRenderer.
> feat(JOML): Migrate RegionOutlineRenderer

- engine/src/main/java/org/terasology/logic/characters/GazeAuthoritySystem.java
- engine/src/main/java/org/terasology/logic/characters/GazeMountPointComponent.java
- engine/src/main/java/org/terasology/logic/debug/MovementDebugCommands.java
This is a small and fairly trivial change. Just verify that this component isn't used in a module component else those would need to migrated over.
> feat(JOML): migrate GazeMountPointComponent

- engine/src/main/java/org/terasology/logic/behavior/actions/conditions/ConditionAction.java
to test try run LightAndShadow and the game should crash with a stackoverflow. problem with decoding class objects gson shouldn't be touching. problem when gson evaluates the classpath and gets stuck in a recursive loop. 
```
java.lang.StackOverflowError: null
at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383)
at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383)
at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383)
at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383)
at …
```
> Mark injected fields as transient in ConditionAction

- engine/build.gradle
- engine/src/main/java/org/terasology/engine/subsystem/headless/renderer/HeadlessCanvasRenderer.java
- engine/src/main/java/org/terasology/rendering/assets/font/FontMeshBuilder.java
- engine/src/main/java/org/terasology/rendering/assets/mesh/MeshBuilder.java
- engine/src/main/java/org/terasology/rendering/nui/internal/LineRenderer.java
- engine/src/main/java/org/terasology/rendering/nui/internal/LwjglCanvasRenderer.java
The changes in TeraNui need to be updated in Terasology.
issue: https://github.com/MovingBlocks/TeraNUI/pull/19
> feat migrate nui canvas for Colorc

- engine/src/main/java/org/terasology/math/Side.java
This is a straightforward migration of inDirection. It will take a a bit of time before the replacements methods get updated.
> feat(JOML): migrate Side#inDirection(Vector3f)

- engine/src/main/java/org/terasology/utilities/random/Random.java
I migrated random along with updating comments and reformatting code.
> feat(JOML): migrate random

- engine/src/main/java/org/terasology/logic/players/LocalPlayer.java
- engine/src/main/java/org/terasology/math/Direction.java
I just added replacement methods in LocalPlayer and we should remove the other methods at a later point.
> feat(JOML): migrate LocalPlayer and correct Direction

- engine/src/main/java/org/terasology/logic/actions/PlaySoundAction.java
- engine/src/main/java/org/terasology/logic/actions/SpawnPrefabAction.java
- engine/src/main/java/org/terasology/logic/characters/CharacterSystem.java
- engine/src/main/java/org/terasology/logic/characters/events/ActivationPredicted.java
- engine/src/main/java/org/terasology/logic/characters/events/ActivationRequest.java
- engine/src/main/java/org/terasology/logic/common/ActivateEvent.java
- engine/src/main/java/org/terasology/logic/players/LocalPlayer.java
- engine/src/main/java/org/terasology/math/ChunkMath.java
- engine/src/main/java/org/terasology/recording/DirectionAndOriginPosRecorder.java
- engine/src/main/java/org/terasology/world/block/items/BlockItemSystem.java
this migrates ActivateEvent/ActivationRequest/ActivationPrediction along with changes to get the game to run.
> feat(JOML): migrate action event

- docs/Modules.md
Reorganization and updating of docs/modules.md
Cross referenced list in the omega properties with module lineup in docs/modules.md.
Updated module list.
Added Other Module subsection.
Added Tutorials section.
I don't have much experience with git or documentation so criticism / thoughts welcome.
Refs #4040
> docs: update module lineup list

- engine/src/main/java/org/terasology/logic/behavior/core/ActionNode.java
> fix: action construction exception log

- engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/inputSettings/InputSettingsScreen.java
- previously if any of the `getBinds()` calls returned a non-null but empty list, the game would crash due to an out-of-bounds error
> fix(nui): `InputSettings:onClose` out-of-bounds crash

- build.gradle
> build: add extract natives for jinput

- engine/src/main/java/org/terasology/rendering/opengl/fbms/DisplayResolutionDependentFbo.java
Fix for quad screenshot.
1. start Terasology
2. create or load game
3. take screenshot
4. check screenshot. It's resolution should be equal your window resolution.
> fix(screenshot): fix quad screenshots

- engine/src/main/java/org/terasology/input/BindableButton.java
- engine/src/main/java/org/terasology/input/InputSystem.java
- engine/src/main/java/org/terasology/input/cameraTarget/CameraTargetSystem.java
- engine/src/main/java/org/terasology/input/internal/BindableButtonImpl.java
- engine/src/main/java/org/terasology/math/JomlUtil.java
this is a migration of the target system since JOMLUtil is not needed any more in this case.
> feat(JOML): migrate target system

- engine/src/main/java/org/terasology/physics/Physics.java
- engine/src/main/java/org/terasology/physics/bullet/BulletPhysics.java
- engine/src/main/java/org/terasology/world/block/items/BlockItemSystem.java
here is some work on migrating aabb for physics along with some effort to migrate BlockItemSystem.
> feat(JOML): migrate BlockItemSystem and Physics#scanArea

- engine/src/main/java/org/terasology/world/chunks/pipeline/ChunkProcessingPipeline.java
Fixes #4240
1. Run game
2. create/load world
3. Exit from TS.
4. Game process should finished.
> Fix not killed process.

- engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/GameManifestProvider.java
- engine/src/main/java/org/terasology/world/time/WorldTime.java
- thus the night won't seem that long and the player has more time to prepare for it
> feat: start first game day at sunrise

- engine/src/main/java/org/terasology/logic/console/commands/CoreCommands.java
- engine/src/main/java/org/terasology/logic/inventory/events/DropItemEvent.java
straightforward migration of CoreCommands. this is the rest of the termath methods for this class so hopefully we don't need to touch this anymore in terms of JOML.
commands affected:
- spawnPrefab
- spawnBlock
- bulkDrop
- bowlingPrep
> feat(JOML): migrate core commands

- engine/src/main/java/org/terasology/entitySystem/entity/internal/PojoEntityManager.java
Possibly a fix for #4135 
**Problem:** The `PojoEntityManager` handles the life cycle of components added to and removed from entities. It notifies two kinds of subscribers about these changes, (1) registered systems receive `OnAddedComponent`/`OnActivatedComponent` or `OnChangedComponent`, and (2) internal systems (such as the delta recorder) are directly notified. 
The error of #4135 appears if the component that was just added is directly removed in reaction to any of the life cycle events mentioned in (1).
**Solution:** I assume that the internal systems that get directly notified won't change the state of the entity but are read-only system (e.g., for storing the state, or recording the delta info). Therefore, I think it is safe to notify those before sending events via the event …
> fix: reverse order of notification in PojoEntityManager

- engine/src/main/java/org/terasology/entitySystem/MutableComponentContainer.java
Handle cases where the transformation/upsert function returns `null`. This was previously not well defined, now we state what the behavior is in the Javadoc and change the implementation to handle these cases gracefully.
**Update Component** I encountered a case where I wanted to update a component, and possibly remove it in the end if some condition is met. I thought returning null in this case might be a good way to indicate that this component should be removed from the container.
**Upsert Component** Analog to the update case, returning a null value from the upsert function indicates that no component should be added to the container.
This is used already in https://github.com/Terasology/Notifications/tree/develop (if this PR get's rejected I'll adapt the module code).
> feat(MutableComponentContainer): Handle 'null' values in [update|upsert]Component

- Jenkinsfile
Updates instructions for Jenkins to include pruning of attached artifacts off older jobs, only keeping one set for non-special branches while the special branches retain up to 10 sets (at present `master` and `develop` are considered special). Also cleans up a tiny bit.
CI system testing only, no functional code changes to validate.
* http://jenkins.terasology.io/teraorg/job/Nanoware/job/Terasology/job/discardOldBuildArtifacts/ is a non-special branch so only one job should have artifacts attached - ✔️ 
* http://jenkins.terasology.io/teraorg/job/Nanoware/job/Terasology/job/master/ is a special branch (and had this change pushed as well), so it gets up to 10 jobs with artifacts. Don't mind that the build fails, that's irrelevant - key is that builds 3 and 4 have artifacts attached - ✔️ …
> chore: make older engine builds in Jenkins prune their attached artifacts + minor quality tweaks

- engine/src/main/java/org/terasology/logic/characters/CharacterSystem.java
- engine/src/main/java/org/terasology/logic/characters/CharacterTeleportEvent.java
- engine/src/main/java/org/terasology/logic/characters/ServerCharacterPredictionSystem.java
- engine/src/main/java/org/terasology/logic/debug/MovementDebugCommands.java
- engine/src/main/java/org/terasology/logic/players/PlayerSystem.java
> feat(JOML): migrate CharacterTeleportEvent

- engine/src/main/java/org/terasology/logic/console/commands/ClientCommands.java
- engine/src/main/java/org/terasology/logic/players/PlayerSystem.java
- engine/src/main/java/org/terasology/logic/players/StaticSpawnLocationComponent.java
- engine/src/main/java/org/terasology/logic/spawner/AbstractSpawner.java
- engine/src/main/java/org/terasology/logic/spawner/FixedSpawner.java
- engine/src/main/java/org/terasology/logic/spawner/Spawner.java
- engine/src/main/java/org/terasology/world/generator/WorldGenerator.java
> feat(JOML): migrate player spawn component and logic

- engine/src/main/java/org/terasology/logic/location/LocationComponent.java
- engine/src/main/java/org/terasology/rendering/logic/SkeletonRenderer.java
This is a migration of just the skeleton renderer. hopefully we can get to migrating the other code for GLTF. The two key modules to test this would be: 
- Light And Shadow
- Wild Animals
- Gooey Quest
- Metal Renegades
make sure the animations work correctly and scaling is correct.
> feat(JOML): migrate SkeletonRenderer

- engine/src/main/resources/assets/shaders/lightGeometryPass_frag.glsl
- engine/src/main/resources/org/terasology/include/globalFunctionsFragIncl.glsl
during mid day the lighting seems to get heavily over-saturated to the point where a lot of the scene is heavily washed out. 
current:
modified:
> fix: tweak lighting for over exposure problem

- engine/src/main/java/org/terasology/rendering/nui/widgets/browser/data/html/HTMLDocument.java
> feat(nui): allow batch-adding multiple paragraphs to HTMLDocument

- README.markdown
> doc: add system requirements to README

- engine/src/main/java/org/terasology/rendering/nui/CoreScreenLayer.java
- engine/src/main/java/org/terasology/rendering/nui/animation/DeferredMenuAnimationSystem.java
- engine/src/main/java/org/terasology/rendering/nui/animation/MenuAnimationSystem.java
- engine/src/main/java/org/terasology/rendering/nui/animation/MenuAnimationSystemStub.java
- engine/src/main/java/org/terasology/rendering/nui/animation/SwipeMenuAnimationSystem.java
here is a migration of some animation logic for rectanglei. from what I can tell the only screen that uses this is the debug dropdown terminal in the game. so this should be pretty simple to verify and test.
> feat(JOML): migrate to Rectanglei nui.animation

- engine/src/main/java/org/terasology/particles/updating/ParticleUpdaterImpl.java
here is a migration of the ParicleUpdateImpl. the usage is entirely internal so we don't need to update any other logic.
> feat(JOML): migrate ParicleUpdateImpl

- engine/src/main/java/org/terasology/logic/characters/CharacterSystem.java
straightforward migration of CharacterSystem.
> feat(JOML): migrate CharacterSystem

- engine/src/main/java/org/terasology/world/block/entity/BlockEntitySystem.java
This is a pretty straightforward migration of the BlockEntitySystem.
> feat(JOML): migrate BlockEntitySystem

- engine/src/main/java/org/terasology/rendering/logic/FloatingTextRenderer.java
pretty straightforward migration of FloatingTextRenderer. I added some additional debugging to help if the location is not defined correctly for a text component.
> feat(JOML): migrate FloatingTextRenderer

- engine/src/main/java/org/terasology/physics/bullet/BulletPhysics.java
Here is the migration of the LocationComponent logic in BulletPhysics. I'm wondering about all these finite checks if we should both with it. I'm wondering if it would be better to add a Precondition to LocationComponent to check for this and drop all these finite checks littering the engine.
> feat(JOML): migrate BulletPhysics

- engine-tests/src/test/java/org/terasology/world/chunks/localChunkProvider/LocalChunkProviderTest.java
Update LocalChunkProviderTest for #4368.
(I haven't actually run the test locally, because just using the PR auto-test thingy seemed more convenient, so I'll have to see how it goes.)
> Fix LocalChunkProviderTest

- engine/src/main/java/org/terasology/rendering/nui/layers/ingame/metrics/DebugOverlay.java
migrate DebugOverlay. There are only a couple instances throughout the codebase but LocationComponent is pretty close to just dropping all the termath methods.
> feat(JOML): migrate DebugOverlay

- engine/src/main/java/org/terasology/logic/players/PlayerSystem.java
- engine/src/main/java/org/terasology/world/generator/WorldGenerator.java
> feat(JOML): migrate WorldGenerator#getSpawnPosition

- engine/src/main/java/org/terasology/world/viewer/picker/CirclePicker.java
- engine/src/main/java/org/terasology/world/viewer/picker/CirclePickerAll.java
- engine/src/main/java/org/terasology/world/viewer/picker/CirclePickerClosest.java
- engine/src/main/java/org/terasology/world/viewer/picker/package-info.java
> feat(JOML): deprecate TeraMath methods for `world.viewer.picker.*`

- engine/src/main/java/org/terasology/world/generation/Border3D.java
- engine/src/main/java/org/terasology/world/zones/Zone.java
- engine/src/main/java/org/terasology/world/zones/ZonePlugin.java
> feat(JOML): migrate `world.zones.*`

- engine-tests/src/main/java/org/terasology/MapWorldProvider.java
- engine-tests/src/main/java/org/terasology/testUtil/WorldProviderCoreStub.java
- engine/src/main/java/org/terasology/engine/subsystem/headless/renderer/HeadlessWorldRenderer.java
- engine/src/main/java/org/terasology/rendering/world/ChunkMeshUpdateManager.java
- engine/src/main/java/org/terasology/rendering/world/RenderableWorldImpl.java
- engine/src/main/java/org/terasology/world/internal/AbstractWorldProviderDecorator.java
- engine/src/main/java/org/terasology/world/internal/WorldProviderCore.java
- engine/src/main/java/org/terasology/world/internal/WorldProviderCoreImpl.java
> feat(JOML): migrate ChunkProvider#getLocalView

- engine/src/main/java/org/terasology/world/propagation/BatchPropagator.java
- engine/src/main/java/org/terasology/world/propagation/StandardBatchPropagator.java
- engine/src/main/java/org/terasology/world/propagation/SunlightRegenBatchPropagator.java
This keeps the existing APIs available but deprecates them. There should be no module changes required.
I recommend to have a look at the individual commits to review this migration. 
I'd like to highlight the changes in 3de1db4 (refactoring) and 4dec17d (performance optimization).
If you prefer, I can split this into more PRs.
---
Follow-up to #4384
> feat(JOML): add JOML API for BatchPropagator (partial migration)

- engine/src/main/java/org/terasology/world/block/BlockRegion.java
I removed some of the conditions to speed up the iterator for block regions.
> perf(optimize): optimize iterator for block region 

- engine-tests/src/test/java/org/terasology/persistence/internal/StorageManagerTest.java
- engine-tests/src/test/java/org/terasology/world/propagation/BetweenChunkPropagationTest.java
- engine/src/main/java/org/terasology/world/chunks/ChunkProvider.java
- engine/src/main/java/org/terasology/world/chunks/localChunkProvider/LocalChunkProvider.java
- engine/src/main/java/org/terasology/world/chunks/remoteChunkProvider/RemoteChunkProvider.java
looks like I didn't add this to ChunkProvider even though the other objects the inherit this use getChunk(Vector3ic).
> feat(JOML): migrate ChunkProvider#getChunk(Vector3ic)

- .gitignore
- build.gradle
Fixup of #4401
I had hoped this would also help with SpotBugs going crazy, but nope...
> build(jmh): git-ignore generated code

- engine-tests/src/test/java/org/terasology/persistence/internal/StorageManagerTest.java
- engine-tests/src/test/java/org/terasology/world/ChunkTest.java
- engine/src/main/java/org/terasology/engine/subsystem/headless/assets/HeadlessMesh.java
- engine/src/main/java/org/terasology/logic/players/LocalPlayerSystem.java
- engine/src/main/java/org/terasology/persistence/internal/AbstractStorageManager.java
- engine/src/main/java/org/terasology/rendering/AABBRenderer.java
- engine/src/main/java/org/terasology/rendering/BlockOverlayRenderer.java
- engine/src/main/java/org/terasology/rendering/assets/mesh/Mesh.java
- engine/src/main/java/org/terasology/rendering/cameras/Camera.java
- engine/src/main/java/org/terasology/rendering/cameras/ViewFrustum.java
- engine/src/main/java/org/terasology/rendering/logic/MeshRenderer.java
- engine/src/main/java/org/terasology/rendering/nui/internal/LwjglCanvasRenderer.java
- engine/src/main/java/org/terasology/rendering/opengl/OpenGLMesh.java
- engine/src/main/java/org/terasology/world/chunks/RenderableChunk.java
- engine/src/main/java/org/terasology/world/chunks/internal/ChunkImpl.java
> feat(JOML): migrate Mesh AABBf

- engine/src/main/java/org/terasology/engine/subsystem/headless/assets/HeadlessMaterial.java
- engine/src/main/java/org/terasology/rendering/assets/material/BaseMaterial.java
- engine/src/main/java/org/terasology/rendering/assets/material/Material.java
- engine/src/main/java/org/terasology/rendering/opengl/GLSLMaterial.java
there are no more references for any of these methods so we can safely remove them from the engine.
> feat(JOML): remove use of termath methods from Material

- engine/src/main/java/org/terasology/world/block/entity/placement/BlockPlacingSystem.java
- engine/src/main/java/org/terasology/world/block/entity/placement/PlaceBlocks.java
- engine/src/main/java/org/terasology/world/block/structure/AttachSupportRequired.java
- engine/src/main/java/org/terasology/world/block/structure/BlockDefSupportRequired.java
- engine/src/main/java/org/terasology/world/block/structure/BlockStructuralSupport.java
- engine/src/main/java/org/terasology/world/block/structure/BlockStructuralSupportSystem.java
- engine/src/main/java/org/terasology/world/block/structure/SideBlockSupportRequired.java
- engine/src/main/java/org/terasology/world/internal/AbstractWorldProviderDecorator.java
- engine/src/main/java/org/terasology/world/internal/EntityAwareWorldProvider.java
- engine/src/main/java/org/terasology/world/internal/WorldProviderCore.java
- engine/src/main/java/org/terasology/world/internal/WorldProviderCoreImpl.java
> feat(JOML): migrate setBlock(Map)

- engine/src/main/java/org/terasology/engine/subsystem/headless/assets/HeadlessTexture.java
- engine/src/main/java/org/terasology/rendering/assets/texture/Texture.java
- engine/src/main/java/org/terasology/rendering/opengl/OpenGLMesh.java
- engine/src/main/java/org/terasology/rendering/opengl/OpenGLTexture.java
Requires https://github.com/MovingBlocks/joml-ext/pull/17
> feat(JOML): migrate Texture

- engine/src/main/java/org/terasology/world/block/family/MultiConnectFamily.java
- engine/src/main/java/org/terasology/world/block/family/UpdatesWithNeighboursFamily.java
This enables a bunch of module clean-ups.
> feat(block/family): add default forwarding to JOML API

- engine-tests/src/test/java/org/terasology/logic/location/LocationComponentTest.java
- engine/src/main/java/org/terasology/logic/ai/SimpleAISystem.java
- engine/src/main/java/org/terasology/logic/characters/CharacterSoundSystem.java
- engine/src/main/java/org/terasology/logic/location/LocationChangedEvent.java
- engine/src/main/java/org/terasology/logic/location/LocationChangedSystem.java
- engine/src/main/java/org/terasology/logic/location/LocationComponent.java
- engine/src/main/java/org/terasology/logic/players/CameraClientSystem.java
> feat(JOML): migrate rest of `LocationComponent`

- engine/src/main/java/org/terasology/rendering/primitives/ChunkMesh.java
updated constants and replaced with JOML types.
> feat(JOML): cleanup chunk mesh

- engine/src/main/java/org/terasology/network/internal/NetClient.java
- engine/src/main/java/org/terasology/network/internal/ServerImpl.java
- engine/src/main/java/org/terasology/network/serialization/NetEntityRefTypeHandler.java
- engine/src/main/java/org/terasology/world/block/BlockComponent.java
- engine/src/main/java/org/terasology/world/block/entity/BlockCommands.java
- engine/src/main/java/org/terasology/world/block/entity/neighbourUpdate/NeighbourBlockFamilyUpdateSystem.java
- engine/src/main/java/org/terasology/world/block/structure/SideBlockSupportRequired.java
- engine/src/main/java/org/terasology/world/internal/EntityAwareWorldProvider.java
Dependant module PRs are linked back to this PR. To test it out, checkout the branch `joml/migrate-BlockComponent` on all those modules.
```sh
git checkout joml/migrate-BlockComponent
for m in ItemRendering Explosives Furnishings ItemPipes AdditionalItemPipes Rails Signalling AdditionalRails AdventureAssets AlterationEffects ClimateConditions GrowingFlora MultiBlock Behaviors Fences ComputerMonitors Machines ManualLabor Exoplanet FunnyBlocks KComputers MasterOfOreon Sample Scenario WoodAndStone SimpleFarming; do
git -C $(pwd)/modules/$m fetch;
git -C $(pwd)/modules/$m checkout joml/migrate-BlockComponent;
done
```
Resolves #4430
> feat(JOML)!: migrate `BlockComponent`

- engine/src/main/java/org/terasology/rendering/nui/CoreScreenLayer.java
- engine/src/main/java/org/terasology/rendering/nui/layers/hud/HUDScreenLayer.java
The linked module PR make use of the new JOML API.
```
for m in Compass GooeyDefence Minimap Tasks; do
git -C (pwd)/modules/$m fetch
git -C (pwd)/modules/$m checkout joml/migrate-hud
done
```
> feat(JOML)!: add JOML API for HUDScreenLayer

- engine/src/main/java/org/terasology/network/internal/LocalClient.java
- engine/src/main/java/org/terasology/network/internal/NetMessageUtil.java
- engine/src/main/java/org/terasology/network/serialization/NetEntityRefTypeHandler.java
- chore(network): remove unused import from LocalClient
- chore(network)!: remove unused method from NetMessageUtil
- refactor(network): migrate NetEntityRefTypeHandler to JOML
> refactor(JOML)!: migrate `network` fully to JOML

- engine/src/main/java/org/terasology/math/Direction.java
migrate direction.
PR
- https://github.com/Terasology/Inferno/pull/21
> feat(JOML): migrate direction

- engine/src/main/java/org/terasology/input/InputSystem.java
- engine/src/main/java/org/terasology/input/cameraTarget/PlayerTargetSystem.java
- engine/src/main/java/org/terasology/input/cameraTarget/TargetSystem.java
- engine/src/main/java/org/terasology/logic/characters/CharacterSoundSystem.java
- engine/src/main/java/org/terasology/logic/characters/ServerCharacterPredictionSystem.java
- engine/src/main/java/org/terasology/logic/players/CameraClientSystem.java
- engine/src/main/java/org/terasology/persistence/internal/ReadWriteStorageManager.java
- engine/src/main/java/org/terasology/persistence/internal/SaveTransactionBuilder.java
- engine/src/main/java/org/terasology/physics/engine/PhysicsSystem.java
- engine/src/main/java/org/terasology/physics/events/ImpactEvent.java
- engine/src/main/java/org/terasology/rendering/assets/texture/subtexture/Subtexture.java
- engine/src/main/java/org/terasology/rendering/cameras/ViewFrustum.java
- engine/src/main/java/org/terasology/rendering/nui/contextMenu/ContextMenuScreen.java
- engine/src/main/java/org/terasology/rendering/nui/layers/hud/HUDScreenLayer.java
- engine/src/main/java/org/terasology/rendering/nui/widgets/browser/data/basic/flow/TextFlowRenderable.java
- engine/src/main/java/org/terasology/world/block/shapes/BlockShapeImpl.java
- engine/src/main/java/org/terasology/world/internal/ChunkViewCoreImpl.java
I have other PR that address the few dependencies left and this can all be removed in one go after all that.
> feat(JOML): remove usage of JOMLUtil and migrate remaining code

- engine/src/main/java/org/terasology/particles/rendering/SpriteParticleRenderer.java
minor performance changes. GL.createCapabilities() calls over into some native logic. this should help a little bit.
> perf(GL): move opengl33 off of draw loop

- buildSrc/src/main/kotlin/terasology-module.gradle.kts
- engine-tests/build.gradle
- engine-tests/src/test/java/org/terasology/persistence/typeHandling/mathTypes/AABBTypeHandlerTest.java
- engine-tests/src/test/java/org/terasology/persistence/typeHandling/mathTypes/BlockAreaTypeHandlerTest.java
- engine-tests/src/test/java/org/terasology/persistence/typeHandling/mathTypes/BlockRegionTypeHandlerTest.java
- engine-tests/src/test/java/org/terasology/persistence/typeHandling/mathTypes/MathTypeAssert.java
- engine-tests/src/test/java/org/terasology/reflection/TypeRegistryTest.java
and mockito 3.7.7.
I expect this is low-risk.
> test: upgrade to JUnit 5.7.1

- engine/src/main/java/org/terasology/rendering/nui/layers/ingame/DeathScreen.java
remove usage of CoreRegistry from DeathScreen.
> refactor(nui): remove CoreRegistry from DeathScreen

- engine/src/main/java/org/terasology/logic/behavior/BehaviorSystem.java
- engine/src/main/java/org/terasology/logic/behavior/CollectiveBehaviorSystem.java
- engine/src/main/java/org/terasology/logic/nameTags/PlayerNameTagSystem.java
Some minor code cleanup based on the boy scout rule to leave the code in a better state than before :nerd_face: Mainly reduced log spam with some additional changes to not catch runtime exceptions.
> chore(behavior,logic): minor code cleanup

- engine/src/main/java/org/terasology/rendering/opengl/FBO.java
looks like this is why the screen dimensions are wrong. kind of strange the that the finalbuffer is getting modified though?
> bugfix: correct Dimensions#multiplySelfBy

- engine-tests/src/test/java/org/terasology/world/block/BlocksTest.java
- engine/src/main/java/org/terasology/world/block/Blocks.java
> feat(block): Add 'Blocks' utility class to convert world to block coordinates

- buildSrc/src/main/kotlin/org/terasology/gradology/constants.kt
- buildSrc/src/main/kotlin/org/terasology/gradology/module_build.kt
- buildSrc/src/main/kotlin/org/terasology/gradology/module_deps.kt
- buildSrc/src/main/kotlin/terasology-module.gradle.kts
Not quite a strict mechanical refactoring, but close. No changes to build logic expected here.
> build: factor out methods making gradle dependencies from gestalt metadata

- engine/src/main/java/org/terasology/world/block/entity/BlockEntitySystem.java
- engine/src/main/java/org/terasology/world/block/items/BlockItemSystem.java
remove some usage of getPosition(dest). shouldn't be anything dramatic but it should help.
> chore: remove usage of getPosition(dest)

- engine-tests/build.gradle
- engine/build.gradle
* joml-ext v0.1.0
* nui v1.4.0
Close #4414
> build: use joml-ext v0.1.0 and nui v1.4.0

- subsystems/TypeHandlerLibrary/src/main/java/org/terasology/reflection/reflect/ConstructorLibrary.java
Fixes #4550.
Usage of `AccessController.doPrivilaged` was before #4244.
Reason for remove this is unknown.
Fixes AccesControlException, when AssetsManager try to loads data for classes in another modules via TypeHandlerLibrary.
1. Run Terasology
2. Create `MetalRenegates` gameplay.
3. Should loads.
> fix(ConstructorLibrary): prevent AccessControlException by using `AccessController.doPrivilaged`

- engine-tests/src/main/java/org/terasology/Environment.java
> test: initialize Bullet for [Headless]Environment

- engine/src/main/java/org/terasology/engine/core/module/ModuleManager.java
- subsystems/DiscordRPC/src/main/resources/org/terasology/subsystem/discordrpc/engine-module.txt
this fixes one problem but I'm having other registration problems with NUIManagerInternal.
> feature: migrate gestalt v7 discord subsystem

- README.markdown
(_edit by @skaldarnar_)
This PR improves the language of the player section in the README.
> doc: Update README

- engine/src/main/java/org/terasology/engine/telemetry/Metrics.java
Closes https://github.com/MovingBlocks/Terasology/issues/4655
> chore(telemetry): drop module scanning from telemetry.Metrics

- engine/src/main/java/org/terasology/engine/particles/rendering/SpriteParticleRenderer.java
From what I can tell this display list is not called within SpriteParticleRenderer so It should be safe to drop this from the class. The only instance I see using this renderer is in Health  when breaking a block.
> chore: remove unused displaylist in SpriteParticleRenderer

- engine/src/main/java/org/terasology/engine/telemetry/TelemetryScreen.java
> chore(telemetry): drop module scanning from telemetry.TelemetryScreen

- engine/src/main/java/org/terasology/engine/rendering/nui/editor/layers/AbstractEditorScreen.java
> chore: add doc and todo on module presence as source check

- engine-tests/src/main/java/org/terasology/unittest/stubs/StubSubsystem.java
- engine-tests/src/test/java/org/terasology/engine/core/module/ModuleManagerTest.java
adds some test cases to ModuleManagerTest
> test(ModuleManager): new tests for existing behavior

- engine/src/main/resources/org/terasology/engine/assets/shaders/sobel_frag.glsl
- engine/src/main/resources/org/terasology/engine/assets/shaders/sobel_vert.glsl
- engine/src/main/resources/org/terasology/engine/assets/shaders/toneMapping_frag.glsl
- engine/src/main/resources/org/terasology/engine/assets/shaders/toneMapping_vert.glsl
even though https://www.khronos.org/opengl/wiki_opengl/index.php/Core_Language_(GLSL)#Version states the exact opposite
> fix: version directives need to come before comments

- engine/src/main/java/org/terasology/engine/entitySystem/event/internal/EventSystemImpl.java
We currently swallow all exceptions thrown during event handling in `EventSystemImpl#invoke` and just log the error.
Not catching the error will hand it further up, leading to a game crash eventually (which is probably the better option given that we're talking about arbitrary exceptions here).
There might be specific exceptions we can handle in this place, and we can add those back in if we learn about them. For now, I believe crashing the game here and collecting the reason would be more beneficial (btw, how is log metric collection going?).
We can make use of this by introducing custom exceptions to `CrashHardException` or `CrashSoftException` which can hold additional information, e.g,. whether to dump the entity state, or an error message to display to users/in the log.
> feat?: Don't swallow exceptions in EventSystem#invoke

- README.markdown
Updates a broken link in README.
> fix: broken wiki link in README

- engine/src/main/resources/org/terasology/engine/assets/shaders/lightGeometryPass_frag.glsl
when trying to disable shadows, lightgeometrypass will fail to compile.
> fix: lightgeometrypass to allow shadows to be disabled

- engine/src/main/java/org/terasology/engine/core/bootstrap/EntitySystemSetupUtil.java
- engine/src/main/java/org/terasology/engine/core/bootstrap/EnvironmentSwitchHandler.java
IntelliJ noticed this was duplicate code. One of the implementations is on a utility class in the same package, so that seems appropriate for the other class to use.
> refactor(bootstrap): remove duplicate registerComponents method

- engine/src/main/java/org/terasology/engine/utilities/procedural/BrownianNoise.java
PR: https://github.com/Terasology/AnotherWorld/pull/27
> feat: expose scale for BrownianNoise

- Jenkinsfile
> fix(ci): backslash-escape multi-line shell command

- engine/src/main/java/org/terasology/engine/core/modes/loadProcesses/InitialiseRemoteWorld.java
this removes an unnecessary cast for the Skysphere.
> chore: remove unecessary cast

- engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/IndexResource.java
- engine/src/main/java/org/terasology/engine/rendering/nui/editor/layers/AbstractEditorScreen.java
- engine/src/main/java/org/terasology/engine/rendering/nui/internal/LineRenderer.java
- engine/src/main/java/org/terasology/engine/rendering/nui/internal/LwjglCanvasRenderer.java
- engine/src/main/java/org/terasology/engine/rendering/opengl/OpenGLMesh.java
looks like we're still using some deprecated opengl calls. this resolve the asset editor when you hit F11. This introduces two changes, one resolves the line rendering logic and the other just attempts to get the editor working correctly. Not sure about the second change though. 
- hit F11
- open an editor option in the drop down
- test with a couple different nui layouts.
> fix: resolve problems with gui editor

- engine/src/main/java/org/terasology/engine/logic/players/LocalPlayerSystem.java
- engine/src/main/java/org/terasology/engine/logic/players/SetDirectionEvent.java
- engine/src/main/java/org/terasology/engine/logic/players/UpdateDirectionEvent.java
This PR allows players to face a particular direction by making use of an UpdateDirectionEvent.
> feat: add `SetDirection` event to set player orientation

- gradle/gooeycli/src/main/groovy/org/terasology/cli/commands/module/GetCommand.groovy
- gradle/gooeycli/src/main/groovy/org/terasology/cli/util/Constants.groovy
- gradle/gooeycli/src/main/groovy/org/terasology/cli/util/ModuleIndex.groovy
* reimplement algorithm. gather dependencies before git cloning.
* parallel getting at x1.5-x4 faster then sequence getting
Use `time ./gw module init omega` (at Linux)
or use stopwatch for windows.
> feat: Add parallel module get

- engine-tests/src/test/java/org/terasology/engine/persistence/serializers/TypeSerializerTest.java
- engine-tests/src/test/java/org/terasology/engine/world/EntityAwareWorldProviderTest.java
- engine-tests/src/test/java/org/terasology/math/Diamond3iIteratorTest.java
- engine/src/main/java/org/terasology/engine/audio/openAL/OpenALManager.java
- engine/src/main/java/org/terasology/engine/logic/behavior/nui/BehaviorEditor.java
- engine/src/main/java/org/terasology/engine/logic/characters/CharacterSystem.java
- engine/src/main/java/org/terasology/engine/logic/inventory/ItemPickupAuthoritySystem.java
- engine/src/main/java/org/terasology/engine/logic/players/FirstPersonHeldItemMountPointComponent.java
- engine/src/main/java/org/terasology/engine/network/internal/NetClient.java
- engine/src/main/java/org/terasology/engine/network/internal/NetMessageUtil.java
- engine/src/main/java/org/terasology/engine/persistence/typeHandling/TypeHandlerLibraryImpl.java
- engine/src/main/java/org/terasology/engine/physics/engine/PhysicsSystem.java
- engine/src/main/java/org/terasology/engine/rendering/nui/contextMenu/ContextMenuScreen.java
- engine/src/main/java/org/terasology/engine/rendering/opengl/OpenGLSkeletalMesh.java
- engine/src/main/java/org/terasology/engine/rendering/world/ChunkMeshUpdateManager.java
- engine/src/main/java/org/terasology/engine/rendering/world/RenderableWorldImpl.java
- engine/src/main/java/org/terasology/engine/world/block/items/BlockItemSystem.java
- engine/src/main/java/org/terasology/engine/world/chunks/Chunk.java
- engine/src/main/java/org/terasology/engine/world/chunks/Chunks.java
- engine/src/main/java/org/terasology/engine/world/chunks/internal/ChunkImpl.java
- engine/src/main/java/org/terasology/engine/world/chunks/internal/ChunkRelevanceRegion.java
- engine/src/main/java/org/terasology/engine/world/viewer/picker/CirclePickerAll.java
- engine/src/main/java/org/terasology/engine/world/viewer/picker/CirclePickerClosest.java
here is some minor cleanup that finishes up the migration from termath. There are some extra qualified org.joml in the code that should help a little bit with cleaning up the existing code.
> chore: cleanup extra qualification for org.joml from termath migration

- engine/src/main/java/org/terasology/engine/core/PathManager.java
If this breaks anything, let's document that use case better next time.
This PR does help when trying to run certain gradle tasks for modules, related to https://youtrack.jetbrains.com/issue/IDEA-277315
The thing this has the potential to break is finding the path to the native libraries. Try starting the game (or other tests linked to code in the native libraries) and make sure it doesn't crash with a library-not-found error.
> chore(PathManager): remove some "probably isn't needed anymore" code

- engine/src/main/java/org/terasology/engine/logic/behavior/core/ActionNode.java
This PR changes the logger level for animation-action link on behaviors, solving the MTE log flood problem described by Niru on Discord/ai
> chore: reduce logger level for animation-action link on behaviors

- engine/src/main/java/org/terasology/engine/rendering/world/selection/BlockSelectionRenderer.java
I added a small offset so the surface is not z-fighting and I made some mistakes with the UV. try breaking a block and seeing if the block breaking animation looks correct.
- z-fighting
- squashed textures because of the wrong UV's
> bugfix: resolve BlockSelectionRenderer

- .github/SECURITY.md
A security policy with instructions on how to report a security vulnerability in Terasology.
Fixes #4983
> chore: add security policy

- engine/src/main/resources/org/terasology/engine/assets/prefabs/player/player.prefab
> chore: remove no longer existing CharacterMovement fields from prefabs
