MovingBlocks/Terasology

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/WorldPreGenerationScreen.java, engine/src/main/java/org/terasology/rendering/nui/widgets/UISlider.java, engine/src/main/java/org/terasology/rendering/nui/widgets/UISliderOnChangeTriggeredListener.java
Moved the interface to a separate file and changed the name to `UISliderOnChangeTriggeredListener`
=> Change listener name and new interface file

modules/Core/assets/blocks/Torch.block
Fixes #3390 
I corrected the blocks section attribute name of the torch from `top` -> `topBottom` as defined in its family AttachedToSurfaceFamily [here](https://github.com/MovingBlocks/Terasology/blob/d0c852d53788e92fc82a56fe0ef4b5347b85e148/engine/src/main/java/org/terasology/world/block/family/AttachedToSurfaceFamily.java#L37) .
- Start the game with GooeysQuests
- Ask Gooey for a quest.
- If you got the DwarfHalls quest, check if they are constructed correctly.
=> Correct block attribute top -> topBottom

engine-tests/src/test/java/org/terasology/rendering/dag/RenderTaskListGeneratorTest.java, engine/src/main/java/org/terasology/rendering/dag/RenderTaskListGenerator.java
Currently the `RenderTaskListGenerator` class outputs the entire `INTERMEDIATE RENDERER LIST` which is really long. I've moved to to debug rather than info which makes the log easier to search through and use as this list can get very long
=> Make render logging a little quieter

engine/src/main/java/org/terasology/persistence/typeHandling/TypeSerializationLibrary.java, engine/src/main/java/org/terasology/persistence/typeHandling/coreTypes/ByteArrayTypeHandler.java
A persistence handler for byte[] objects, used by KComputers to proxy Kallisti synchronization packets.
Already tested in KComputers, seems to [work fine](https://img.asie.pl/wUAV).
Nothing! I might write a generic persistence handler for array objects later, but one is not necessary yet.
=> add byte array persistence type handler

engine/src/main/java/org/terasology/logic/players/ThirdPersonRemoteClientSystem.java
#3379
Edited ingame commands for remote held item translation rotation and mountpoint scale (the 3rd one is probaly useless though, might as well get rid of it). These commands, introduced by #3337 stopped working after #3379 changed the code to suit the refactored logic. 
Changes: shortened, made it work. Redundant checks for _relatesToLocalPlayer(remotePlayer)_ removed as only real remote player entities should have _RemotePersonHeldItemMountPointComponent_ already (this check is performed when adding those). Unnecessary call to _ensureClientSideEntityOnHeldItemMountPoint()_ deleted.
Start multiplayer game with 2 players minimum. Aim your screen at the other player/s. Fire up your console ("~") and use one of the commands:
*setRemotePlayersHeldItemMountPointTranslations \<Float x\> …
=> Fix remotely held items @commands broken by #3379, brought by #3337

gradle/wrapper/gradle-wrapper.properties
Relates to #3407 - at least on MacOS you can run the game seemingly OK with Java 10, but without this PR you couldn't *build* the game on Java 10 due to a trivial version parsing change in how Gradle detects the Java version.
Still would be good with more research to see if there are any other obvious issues with 9 or 10, this just allows you to use Gradle again.
I recall having noted several potential issues in upgrading Gradle beyond 3.3 or so. So it might not be ideal to merge this yet - especially as I believe one relates to how Gradle outputs when running in CI (the logging changes and can end up deducing the wrong mode to run in)
Anyway, anybody else able to test out this simple change on Win + Linux? Try out a few Gradle commands (like `gradlew idea`, check, jar, clean, etc) and …
=> Upgrade to Gradle 4.7 for Java 10 compatibility (version parsing issue)

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/gameDetailsScreen/GameDetailsScreen.java
Small fix for GameDetails screen. Actually, only adds fully qualified name for biomes.
Open details of any saved game (better with PolyWorld module enabled). Check that we have full names on Worlds & Biomes tab now.
Should be something like this...
=> Add fully qualified name (module:name) for biomes

engine/src/main/resources/assets/ui/menu/gameDetailsScreen.ui
Before:
Now:
Open details of any saved game. And check that box looks better :) 
Nope.
=> Small fix of margin on game details screen

engine/src/main/java/org/terasology/rendering/nui/widgets/UIButton.java, engine/src/main/java/org/terasology/rendering/nui/widgets/UITabBox.java
Currently, we could highlight button only when we are pressing mouse down. It's fine, but we also need to have a way how to highlight some "active" buttons, e.g. active tab in UITabBox widget.
Original issue #3384 .
1. Open GameDetailsScreen. 
2. Check that tabs and tab buttons work correctly. As well as only one active button was highlighted.
Nothing.
=> Highlight active tab buttons

engine/src/main/resources/assets/ui/hud/toolbar.ui, modules/Core/assets/ui/hud/inventoryHud.ui
When you have started new game you may find in log next warnings. So, I've fixed them. 
For UICrosshair, inventoryDefault skin already has background "engine:gui#crosshair". So we can safely remove them.
For UIIconBar, I'm not sure what "emptyIcon" means in HUD context. We still have "engine:icons#burstBubble" in atlas, but I believe it hasn't worked since 2015 or never.
```
20:00:22.620 [main] WARN  o.t.rendering.nui.asset.UIFormat - Field 'emptyIcon' not recognized for interface org.terasology.rendering.nui.UIWidget in {"type":"UIIconBar","id":"breathBar","icon":"engine:icons#bubble","family":"breathBar","emptyIcon":"engine:icons#burstBubble","halfIconMode":"shrink","spacing":2,"maxIcons":10,"layoutInfo":{"use-content-width":true,"use-content-height":true,"position-left":{"target":"CENTE …
```
=> Remove old useless attributes from ui files

engine-tests/src/main/java/org/terasology/HeadlessEnvironment.java, engine/src/main/java/org/terasology/engine/TerasologyEngine.java, engine/src/main/java/org/terasology/engine/bootstrap/EnvironmentSwitchHandler.java, engine/src/main/java/org/terasology/engine/modes/loadProcesses/RegisterBlocks.java, engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/UniverseSetupScreen.java, engine/src/main/java/org/terasology/world/block/family/BlockFamilyLibrary.java, engine/src/main/java/org/terasology/world/block/loader/BlockFamilyDefinition.java, engine/src/main/java/org/terasology/world/block/loader/BlockFamilyDefinitionFormat.java
I replaced BlockFamilyRegistry with a block family library type. The idea behind this change is to allow a block family to be mapped to the module vs just the name. This is more specific and should avoid problems in the future where a family is named the same in two separate modules. There are currently some block families that follow the module:family type. This can be tested with some of the blocks under the additional rails module where some of the special rail blocks use the family type from the base rails module.
=> Blockfamily library handler

engine-tests/src/main/java/org/terasology/TerasologyTestingEnvironment.java, engine-tests/src/test/java/org/terasology/input/InputSystemTests.java, engine-tests/src/test/java/org/terasology/persistence/internal/StorageManagerTest.java, engine-tests/src/test/java/org/terasology/recording/EventSystemReplayImplTest.java, engine/src/main/java/org/terasology/engine/TerasologyEngine.java, engine/src/main/java/org/terasology/engine/bootstrap/EntitySystemSetupUtil.java, engine/src/main/java/org/terasology/engine/modes/StateMainMenu.java, engine/src/main/java/org/terasology/engine/modes/loadProcesses/InitialiseRemoteWorld.java, engine/src/main/java/org/terasology/engine/modes/loadProcesses/InitialiseWorld.java, engine/src/main/java/org/terasology/engine/subsystem/headless/mode/StateHeadlessSetup.java, engine/src/main/java/org/terasology/input/events/KeyDownEvent.java, engine/src/main/java/org/terasology/input/events/KeyRepeatEvent.java, engine/src/main/java/org/terasology/input/events/KeyUpEvent.java, engine/src/main/java/org/terasology/input/events/MouseAxisEvent.java, engine/src/main/java/org/terasology/logic/characters/CharacterSystem.java, engine/src/main/java/org/terasology/logic/players/LocalPlayer.java, engine/src/main/java/org/terasology/recording/DirectionAndOriginPosRecorder.java, engine/src/main/java/org/terasology/recording/DirectionAndOriginPosRecorderList.java, engine/src/main/java/org/terasology/recording/EventCatcher.java, engine/src/main/java/org/terasology/recording/EventCopier.java, engine/src/main/java/org/terasology/recording/RecordAndReplaySerializer.java, engine/src/main/java/org/terasology/recording/RecordedEventSerializer.java
Fixes the issue in which holding left click during a recording was causing replays to not reproduce block destruction correctly.
Record a game in which you destroy blocks by holding left click and then watch its replay to check that everything was destroyed correctly.
=> Record & Replay - Fix issue of holding left click

engine-tests/src/test/java/org/terasology/persistence/typeHandling/gson/GsonTypeHandlerAdapterTest.java, engine-tests/src/test/java/org/terasology/persistence/typeHandling/gson/GsonTypeSerializationLibraryAdapterFactoryTest.java, engine/src/main/java/org/terasology/persistence/typeHandling/gson/GsonFactory.java, engine/src/main/java/org/terasology/persistence/typeHandling/gson/GsonMapExclusionStrategy.java, engine/src/main/java/org/terasology/persistence/typeHandling/gson/GsonTypeHandlerAdapter.java, engine/src/main/java/org/terasology/persistence/typeHandling/gson/GsonTypeHandlerAdapterFactory.java, engine/src/main/java/org/terasology/persistence/typeHandling/gson/GsonTypeSerializationLibraryAdapterFactory.java, engine/src/main/java/org/terasology/persistence/typeHandling/gson/GsonUtility.java, engine/src/main/java/org/terasology/persistence/typeHandling/gson/LegacyGsonTypeHandlerAdapter.java, engine/src/main/java/org/terasology/persistence/typeHandling/gson/TypeHandlerEntry.java, engine/src/main/java/org/terasology/rendering/nui/asset/UIFormat.java, engine/src/main/java/org/terasology/rendering/nui/skin/UISkinFormat.java, engine/src/main/java/org/terasology/utilities/ReflectionUtil.java
Terasology uses a custom serialization system loosely based on the Gson 1.x architecture. To specify custom serialization for specific types, Terasology requires the use of implementations of `TypeHandler<T>` -- a Terasology-specific interface. As such, serialization handlers for Terasology-introduced types like `Vector3i` and `Color` implement `TypeHandler` and are only compatible with the Terasology serialization system.
To help use existing `TypeHandlers` for serializing Terasology types to JSON via Gson, the `JsonTypeHandlerAdapter` class, a legacy Gson 1.x serialization adapter, was created. `JsonTypeHandlerAdapter` can be used to register Gson type adapters for each type manually; however, this approach is suboptimal for reasons stated below.
Since manually registering a …
=> Gson TypeAdapters and Factories for TypeHandlers

engine-tests/src/test/java/org/terasology/persistence/typeHandling/gson/GsonTypeHandlerAdapterTest.java, engine-tests/src/test/java/org/terasology/persistence/typeHandling/gson/GsonTypeSerializationLibraryAdapterFactoryTest.java, engine-tests/src/test/java/org/terasology/persistence/typeHandling/gson/PolymorphicTypeAdapterFactoryTest.java, engine/src/main/java/org/terasology/persistence/typeHandling/gson/GsonBuilderFactory.java, engine/src/main/java/org/terasology/persistence/typeHandling/gson/PolymorphicTypeAdapterFactory.java
Gson by default does not allow serialization of polymorphic references (e.g. base type references to a sub-type instance). This PR introduces the `PolymorphicTypeAdapterFactory`, which serializes type metadata for types deriving from the given base type.
- Add `PolymorphicTypeAdapterFactory`
- Rename `GsonFactory` to `GsonBuilderFactory`
- Create a `GsonBuilder` from a factory method in `GsonBuilderFactory`.
- Register instances of `PolymorphicTypeAdapterFactory` in the `GsonBuilder` for each base type you wish to support (e.g. `gsonBuilder.registerTypeAdapterFactory(PolymorphicTypeAdapterFactory.of(Event.class))`)
- Serialize base type references of sub-type instances (like `Event event = new AttackEvent()`) with ease
=> Polymorphic Gson

engine/src/main/java/org/terasology/logic/characters/ServerCharacterPredictionSystem.java
Changes "getDelta()" to "getDeltaMs()" in the ServerCharacterPredictionSystem since it is more appropriate and this could be causing weird behavior.
It is not known if this will really help anything, but after discussing about this in the #architecture channel in the Slack, we arrived at the conclusion that the `getDelta()` method was not appropriate for what it was being used.
=> Switched "getDelta()" to "getDeltaMs()" in the ServerCharacterPredictionSystem.

engine/src/main/java/org/terasology/persistence/typeHandling/gson/LegacyGsonTypeHandlerAdapter.java, engine/src/main/java/org/terasology/rendering/nui/asset/UIFormat.java, engine/src/main/java/org/terasology/rendering/nui/skin/UISkinFormat.java
Deprecates `LegacyGsonTypeHandlerAdapter` and removes its usages.
The following usage(s) in `UIFormat`
https://github.com/MovingBlocks/Terasology/blob/5d17468a400f9335ec36fff4beeee348848adcf8/engine/src/main/java/org/terasology/rendering/nui/asset/UIFormat.java#L108-L110
are replaced with a single `GsonTypeSerializationLibraryAdapterFactory`.
The usage in `UISkinFormat`
https://github.com/MovingBlocks/Terasology/blob/5d17468a400f9335ec36fff4beeee348848adcf8/engine/src/main/java/org/terasology/rendering/nui/skin/UISkinFormat.java#L69
is replaced with a `GsonTypeHandlerAdapterFactory` with a `ColorTypeHandler`.
`TypeSerializationLibrary` logs a few errors when the UI is loaded, but these errors are irrelevant and everything functions as expected (needs confirmation). This error logging will …
=> Deprecate LegacyGsonTypeHandlerAdapter

engine/src/main/java/org/terasology/rendering/nui/widgets/UIList.java, engine/src/main/resources/assets/ui/menu/selectGameScreen.ui
IMHO, it might be useful. At present, you can't switch list items by up and down keys, you can use mouse only. 
1. Open any screen with UIList widget (e.g. SelectGameScreen). 
2. Select any item from list (focus should be on UIList), and check that **Up**, **Down** and **Enter** keys work properly.
Nothing.
=> Up-Down-Enter keys support for UIList widget

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/advancedGameSetupScreen/AdvancedGameSetupScreen.java
I've spotted out that sometimes I can't find all existing modules on AdvancedGameSetup screen. After investigation, I understood that in this case I can see only "remote" and "filtered" modules from previous session. 
1. Open AdvancedGameSetup screen.
2. Filter "libraries"
3. Exit game. 
4. Open AdvancedGameSetup screen.
5. Uncheck libraries.
6. Check that available only "libraries", even when you selected "local".
Nothing.
=> [Defect] Not always all modules are available for filtering

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/SelectGameScreen.java, engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/SelectionScreen.java, engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/gameDetailsScreen/GameDetailsScreen.java, engine/src/main/java/org/terasology/rendering/nui/widgets/UIImageSlideshow.java, engine/src/main/resources/assets/skins/default.skin, engine/src/main/resources/assets/skins/framed_image.skin, engine/src/main/resources/assets/ui/menu/gameDetailsScreen.ui, engine/src/main/resources/assets/ui/menu/selectGameScreen.ui
I redid slideshow widget, now images can be switched manually or by time period, or even both methods.
_GameDetailsScreen.java_
```
public void setPreviews(final List<UIImage> textures) {
if (textures != null && !textures.isEmpty()) {
previewSlideshow.clean();
textures.forEach(previewSlideshow::addImage);
// ADD RANDOM IMAGES
previewSlideshow.addImage(Assets.getTexture("engine:defaultPreview").get());
previewSlideshow.addImage(Assets.getTexture("engine:default").get());
previewSlideshow.addImage(Assets.getTexture("engine:char").get());
previewSlideshow.addImage(Assets.getTexture("engine:openbook").get());
}
}
```
Nothing.
=> Improvements for UIImageSlideshow widget

engine/src/main/java/org/terasology/rendering/nui/widgets/UIImageSlideshow.java
@Naman-sopho found an issue with last updates of UIImageSlider (https://pastebin.com/HaFumrrh)
When user doesn't have saved games it produces IndexOutOfBound exception.
I added additional check to avoid it.
1. Remove all saved games.
2. Open the game and check that game works properly.
Nothing.
=> Hot fix for UIImageSlideshow

engine-tests/src/main/java/org/terasology/TerasologyTestingEnvironment.java, engine-tests/src/test/java/org/terasology/persistence/internal/StorageManagerTest.java, engine-tests/src/test/java/org/terasology/recording/EventSystemReplayImplTest.java, engine/src/main/java/org/terasology/engine/GameThread.java, engine/src/main/java/org/terasology/engine/bootstrap/EntitySystemSetupUtil.java, engine/src/main/java/org/terasology/engine/modes/StateLoading.java, engine/src/main/java/org/terasology/engine/modes/loadProcesses/InitialiseRecordAndReplay.java, engine/src/main/java/org/terasology/engine/subsystem/headless/HeadlessGraphics.java, engine/src/main/java/org/terasology/engine/subsystem/headless/renderer/HeadlessWorldRenderer.java, engine/src/main/java/org/terasology/recording/EventSystemReplayImpl.java, engine/src/main/java/org/terasology/recording/RecordAndReplaySerializer.java, engine/src/main/java/org/terasology/recording/RecordedEvent.java, engine/src/main/java/org/terasology/recording/RecordedEventSerializer.java, engine/src/main/java/org/terasology/rendering/world/WorldRendererImpl.java
Refactor that removed the Record and Replay initialization from the WorldRendererImpl and put it in a new LoadProcess. This also made it possible to run a replay in a headless client.
Replay a recording and everything should work the same way as before.
=> Creation of a LoadProcess for Record and Replay

engine-tests/src/test/java/org/terasology/math/RotationTest.java, engine-tests/src/test/java/org/terasology/math/SideTest.java, engine/src/main/java/org/terasology/math/Side.java, engine/src/main/java/org/terasology/rendering/primitives/BlockMeshGeneratorSingleShape.java, engine/src/main/java/org/terasology/world/block/entity/neighbourUpdate/NeighbourBlockFamilyUpdateSystem.java, engine/src/main/java/org/terasology/world/block/family/AttachedToSurfaceFamily.java, engine/src/main/java/org/terasology/world/block/internal/BlockBuilder.java, engine/src/main/java/org/terasology/world/block/shapes/BlockShapeImpl.java, engine/src/main/java/org/terasology/world/block/structure/AttachSupportRequired.java, engine/src/main/java/org/terasology/world/block/structure/BlockStructuralSupportSystem.java, engine/src/main/java/org/terasology/world/chunks/localChunkProvider/LocalChunkProvider.java, engine/src/main/java/org/terasology/world/propagation/StandardBatchPropagator.java, engine/src/main/java/org/terasology/world/propagation/light/LightMerger.java
Reduction of memory allocations while playing the game. As result this will lead to fewer garbage collections.  
Found this while recording a view minutes of gameply with Java Mission Control.
Run the game with the debug information displayed and compare the memory information.  
Alternatively check the allocations with some profiler.
Maybe replace all occurences of Sides.values() in the codebase with a static variable?
=> Reduce memory allocations

config/gradle/ide.gradle
Follow up of PR #3469 
Provides a new run configuration with enabled Java FlightRecorder. The provided configuration will only work until Java 9 (didn't worked on Java 10+ for me).
Run Terasology with the new configuration. After closing the program a new file called `terasology.jfr` should be in the project root directory.
Maybe the wiki entry @Cervator mentioned in the original PR. But I think the run configuration should be enough to start with. An entry for the analysis of the recording is IMHO out of scope.
=> Add new run configuration for Java FlightRecorder

engine/src/main/java/org/terasology/rendering/primitives/ChunkMesh.java, engine/src/main/java/org/terasology/rendering/primitives/ChunkVertexFlag.java
Since #3476 renders most of #3309 obsolete, this is the remaining parts, revealing the bits of API necessary for a custom implementation of BlockMeshGenerator, such as FlowingLiquids uses for making meshes for liquid blocks.
Although this is not currently necessary due to the module access restrictions being disabled, it still seems desirable to have this marked as API as it's actually used in a module (and harmless).
The things revealed do relate to some rather ad-hoc internals of rendering which may be changed at some point, but if that's a problem, it indicates that changes need to be made elsewhere so that access to these isn't necessary.
Reveals ChunkVertexFlag and ChunkMesh.RenderType as API
=> Add rendering enums as API

engine/src/main/resources/assets/shaders/chunk_vert.glsl
Change the offset for animated water from being vertical in view-space to being vertical in world-space. Resolves #2450.
It still doesn't look good, but it does look better.
Turn on animated water in video settings. Look at it from various angles.
=> Make water-waves actually vertical

engine-tests/src/test/java/org/terasology/math/Region3iTest.java, engine/src/main/java/org/terasology/math/Region3i.java, engine/src/main/java/org/terasology/rendering/world/RenderableWorldImpl.java, engine/src/main/java/org/terasology/world/block/regions/BlockRegionComponent.java, engine/src/main/java/org/terasology/world/chunks/internal/ChunkRelevanceRegion.java
- Fixes #3486
- Adds `Region3i.empty()`
- Deprecates `Region3i.EMPTY`
- Removes all references to `Region3i.EMPTY`
- Run Region3i tests.
=> Deprecate Region3i.EMPTY

engine/src/main/java/org/terasology/config/SystemConfig.java, engine/src/main/java/org/terasology/engine/module/ModuleManagerImpl.java, facades/PC/src/main/java/org/terasology/engine/Terasology.java
Fixed formatting.
_Cerv edit_ : pasting in description from #3493 to close that one and merge this one:
Added permissive security flags fixes #3444
Description:
New permissive security flag, to test run the game and enter a world, when the permissive security ("-permissiveSecurity") flag is on security messages similar to this: "[main] ERROR o.t.m.s.WarnOnlyProviderFactory - Non-permitted permission..." will appear in the console.
=> Permissive security flags with fixed formatting. Fixes #3444

engine/src/main/java/org/terasology/world/block/family/FreeformFamily.java, engine/src/main/java/org/terasology/world/block/family/MultiConnectFamily.java
this is a quick hot-fix that fixes the block building in structured templates. A freeformfamily is now considered a side-defined family. this can be verified by building a structured template shape with stairs and verifying that the stairs are in the right direction.
=> hotfix that fixes the rotation issue with structured templates

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/videoSettings/ScreenshotSize.java, engine/src/main/resources/assets/skins/graypopup.skin, engine/src/main/resources/assets/skins/settingsmenu.skin, engine/src/main/resources/assets/ui/enterTextPopup.ui, engine/src/main/resources/assets/ui/menu/addServerPopup.ui, engine/src/main/resources/assets/ui/menu/audioMenuScreen.ui, engine/src/main/resources/assets/ui/menu/inputSettingsScreen.ui, engine/src/main/resources/assets/ui/menu/playerMenuScreen.ui, engine/src/main/resources/assets/ui/menu/videoMenuScreen.ui, engine/src/main/resources/default.cfg, modules/Core/assets/skins/inventoryDefault.skin
Fixes #2927
Screens:
- engine:videoMenuScreen,
- engine:inputSettingsScreen,
- in-game inventory/backpack screen,
now have transparent background and centered titles.
- engine:addServerPopup now has strict gray background.
Also,
- screenshot size options are now sorted from smallest to biggest
- default screenshot format is png
- removed “:” at the end of “experimental” title in Player-Settings screen
The changes can be seen on affected screens directly in-game.
=> Made UI screen styles consistent

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/advancedGameSetupScreen/CheckboxAssociationEnum.java
This commit contains the changes made in the CheckboxAssociationEnum class to allow checkboxes to be generated dynamically based on the the `StandardModuleExtension` instead of hardcoding them.
Fixed #3355
=> Checkboxes are now generated dynamically

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/advancedGameSetupScreen/AdvancedGameSetupScreen.java
Fixes #3507 by disabling "Module details" button on "Advanced Game Setup" screen until a valid module is selected.
=> Fix module details NPE

engine-tests/src/test/java/org/terasology/rendering/nui/widgets/browser/data/basic/HTMLLikeParserParameterizedTest.java, engine-tests/src/test/java/org/terasology/rendering/nui/widgets/browser/data/basic/HTMLLikeParserTest.java, engine/src/main/java/org/terasology/rendering/nui/widgets/browser/data/basic/HTMLLikeParser.java
Fixes the LGTM array out of bounds error in #3510. When starting to work on this issue, I noticed that the method didn't work as intended so this has been fixed as part of this issue.
Run the unit tests added as part of this PR. Verify that LGTM no longer flags this method as having errors (I was unable to test this locally since LGTM doesn't seem to support analyzing forks).
I've tried keeping the fix as close to the original code as possible. In order to maintain the behavior of throwing an exception if an unsupported entity is encountered, I chose to add the length guard at each individual entity, since adding the check near `if (c == '&') {` would change this behavior. It would also need to check entities of length 3 and 4.
=> Fixes the LGTM array out of bounds error

engine/src/main/resources/assets/ui/menu/advancedGameSetupScreen.ui, engine/src/main/resources/assets/ui/menu/audioMenuScreen.ui, engine/src/main/resources/assets/ui/menu/devToolsMenuScreen.ui, engine/src/main/resources/assets/ui/menu/inputSettingsScreen.ui, engine/src/main/resources/assets/ui/menu/joinGameScreen.ui, engine/src/main/resources/assets/ui/menu/newGameScreen.ui, engine/src/main/resources/assets/ui/menu/playerMenuScreen.ui, engine/src/main/resources/assets/ui/menu/previewWorldScreen.ui, engine/src/main/resources/assets/ui/menu/settingsMenuScreen.ui, engine/src/main/resources/assets/ui/menu/startPlayingScreen.ui, engine/src/main/resources/assets/ui/menu/universeSetupScreen.ui, engine/src/main/resources/assets/ui/menu/videoMenuScreen.ui, engine/src/main/resources/assets/ui/menu/worldPreGenerationScreen.ui, engine/src/main/resources/assets/ui/telemetryScreen.ui, engine/src/main/resources/assets/ui/worldSetupScreen.ui
Removes "Terasology" logo from various UI screens except from `mainMenuScreen` and `creditsScreen`, resolves #3509. 
Go through each affected screen and check if "Terasology" logo is removed and the screen looks visually pleasing (UI elements are not out of view bounds). Alternatively `NUI Screen Editor` can be used to check each screen instead of navigating through the UI.
=> Remove "Terasology" logo image from unnecessary UI screens

engine/src/main/java/org/terasology/config/Config.java, engine/src/main/java/org/terasology/logic/behavior/core/DecoratorNode.java, engine/src/main/java/org/terasology/logic/delay/DelayedActionSystem.java, engine/src/main/java/org/terasology/network/internal/ServerImpl.java, engine/src/main/java/org/terasology/rendering/nui/editor/utils/NUIEditorMenuTreeBuilder.java, engine/src/main/java/org/terasology/telemetry/Metrics.java, engine/src/main/java/org/terasology/world/block/internal/BlockManagerImpl.java
Fixes the following LGTM errors and warnings from #3510:
- Missing format argument
- Unused format argument
Note that the logging statements previously would log less information than expected, since the unmatched argument would simply be omitted from the formatted log statement.
Either reproducing the conditions that cause the logging to occur, or instead forcing the condition to occur by attaching a debugger and manually changing the state to force the logging code path.
=> Fixes LGTM logger errors and warnings

engine/src/main/java/org/terasology/rendering/nui/layouts/ColumnLayout.java
Fixes #3508.
It turned out when availableSize.y (org/terasology/rendering/nui/layouts/ColumnLayout.java:232) become negative or zero it causes incorrect row height calculation as Canvas size become (0, 0) and preferable Label height becomes significantly higher as it expects Label text to be split to as many lines as possible for 0 widths. 
Fix looks a bit hacky and I believe there is a better solution, but I hope this PR will at least help in a further investigation.
See test case from #3508.
=> #3508 avoid zero and negative available size in ColumnLayout

engine-tests/src/test/java/org/terasology/rendering/nui/ColorTest.java, engine/src/main/java/org/terasology/logic/console/commandSystem/CommandParameter.java, engine/src/main/java/org/terasology/rendering/nui/Color.java
Fixes the "Useless comparison test" warnings from #3510.
Run the unit test changed as part of this PR to verify that the Color changes work. The preconditions were not working due to using the boolean OR operator rather than boolean AND operator.
Note that the fix for CommandParameter is relevant since the precondition in the private constructor ensures that the `name` variable is never `null` or length `0`.
=> Fixed the LGTM warnings "Useless comparison test"

engine-tests/src/test/java/org/terasology/persistence/internal/StorageManagerTest.java, engine-tests/src/test/java/org/terasology/recording/EventSystemReplayImplTest.java, engine/src/main/java/org/terasology/persistence/typeHandling/coreTypes/CharacterTypeHandler.java, engine/src/main/java/org/terasology/recording/RecordAndReplaySerializer.java, engine/src/main/java/org/terasology/recording/RecordedEventSerializer.java
With `CollectionTypeHandler`, the way `RecordedEvents` are serialized are now greatly improved, making the whole serialization more general, without having to write code for each and every type of event supported by R&R. By the way, before in `RecordedEventSerializer` we had **523** lines and now only **112** including javadocs. :smile: 
- Create a record.
- Replay the record.
Closes #3466.
=> Overhauled R&R serialization

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/NewGameScreen.java
I found that when I create a game in the singleplayer. And put for example `Terasology World` in the game name textbox. Then the game should put that name But sadly the game generates a name for the game instead of using my given name. So, I made a small change to fix this issue.
- Open the game
- Go to singleplayer
- Click on `Create` ( If you don't have any game it will show you the create screen )
- Fill any name from your mind
- Click on `Play`
- Click `Esc`
- Go back to the game menu. You will find the game with the given name that you wanted it to be.
=> Player can't create a game with special name from the player

engine/src/main/java/org/terasology/world/biomes/Biome.java, engine/src/main/java/org/terasology/world/biomes/BiomeChangeEvent.java, engine/src/main/java/org/terasology/world/biomes/PlayerBiomeChangeTrackerSystem.java
`Biome` interface currently contains methods not actually useful for lots of use cases. This PR aims to deprecate them.
Just check nothing breaks
=> Deprecating methods in Biome API

engine/src/main/java/org/terasology/config/RenderingConfig.java, engine/src/main/java/org/terasology/engine/subsystem/lwjgl/LwjglInput.java, engine/src/main/java/org/terasology/engine/subsystem/openvr/OpenVRInput.java, engine/src/main/java/org/terasology/input/lwjgl/LwjglMouseDevice.java, engine/src/main/java/org/terasology/rendering/nui/internal/CanvasImpl.java, engine/src/main/java/org/terasology/rendering/nui/internal/LwjglCanvasRenderer.java, engine/src/main/java/org/terasology/rendering/nui/internal/NUIManagerInternal.java, engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/videoSettings/VideoSettingsScreen.java, engine/src/main/resources/assets/i18n/menu.lang, engine/src/main/resources/assets/i18n/menu_en.lang, engine/src/main/resources/assets/ui/menu/videoMenuScreen.ui
Implements rudimentary UI scaling (#1223). Feedback is welcome!
- Adds `uiScaling` property to `RenderingConfig` and the video settings UI
- Modifies NUI to reduce the size of it's canvas, and the GL backend to use `glScalef()` to scale the canvas rendering up/down as necessary.
- Modifies the GL mouse input as appropriate
Load it up, go to the Video Settings UI and modify the new "UI Scale" option.
=> UI Scaling

engine-tests/src/test/java/org/terasology/rendering/FontColorTest.java
This pull request adds a new test suite under the engine-tests called FontColorTest. I mainly added tests for the isValid() method and the input it is required to take.
Run my unit tests in the FontColorTest suite. (org.terasology.rendering)
=> Font color tests

engine/src/main/java/org/terasology/rendering/nui/layouts/ColumnLayout.java, engine/src/main/java/org/terasology/rendering/nui/layouts/MultiRowLayout.java
Fixes integer casts of normalized float multiplication in `ColumnLayout.java` and `MultiRowLayout.java`.
This solves spacing errors that were present in the settings menus (video settings, audio settings etc.), fixing item four in #3577.
MultiRowLayout is not currently used in the game, but I change the cast to fit with the columnlayout cast.
- Open the three settings menus (video, audio, input) and confirm that the spacing between the various elements is normal.
=> Fix Columnlayout and MultiRowLayout spacing issues by fixing integer casts

engine/src/main/java/org/terasology/engine/subsystem/headless/mode/StateHeadlessSetup.java
Fixes a bug where the FacadeServer fails to save the `worlds` object in `manifest.json`, which causes this error on start.
The Headless client doesn't have this error though, so it might be something else, but this is just a quick fix.
There are still errors in FacadeServer when you connect to it which go away if you disable world saving.
```
21:21:09.124 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.NullPointerException: null
at org.terasology.engine.modes.loadProcesses.InitialiseWorld.step(InitialiseWorld.java:100)
at org.terasology.engine.modes.StateLoading.update(StateLoading.java:243)
at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:458)
at …
```
=> Fixed world saving error when running with ServerFacade

engine/src/main/java/org/terasology/rendering/nui/widgets/UIDropdown.java, engine/src/main/java/org/terasology/rendering/nui/widgets/UIDropdownScrollable.java
Fixes #3587.
Go to the display mode dropdown (inside the video settings menu) and click it with the mouse. The dropdown will now function as expected.
=> Fixes the display mode dropdown

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/SelectionScreen.java, engine/src/main/java/org/terasology/rendering/nui/widgets/UIImage.java
The previous fix to #3584 changes the scaling mode for every UIImage, with potentially unpredictable results. The most prominent of these results is that the main title is cropped instead of scaled to size.
This PR replaces #3595 with a backwards-compatible fix instead, avoiding this issue and presumably others.
- Ensure title is not cropped
- Ensure previews fill their UI box on the game select, replay select, and record screens
=> Revert #3595, re-fix #3584, thereby fixing main title cropping

.gitignore, engine/src/main/java/org/terasology/rendering/nui/layers/ingame/ExtraMenuScreen.java, engine/src/main/resources/assets/ui/ingame/extraMenuScreen.ui, engine/src/main/resources/assets/ui/ingame/pauseMenu.ui
As stated in Issue #3608 I have added an **Extras** button  in **InGame Menu** which includes following buttons in it **"Metrics Menu "**, **"Issue Reporter"**, **"Developer Tools"** along with **"Back"** Button 
to solve above issue I created **2** new files
1-**ExtraMenuScreen.java**
2-**extraMenuScreen.ui**
Create a new game or load any previous games and then press **esc** .
**InGame Menu** screen will appear then click on button by the name of **EXTRAS**.
then after clicking a new screen will appear which will includes **"Metrics Menu "**, **"Issue Reporter"**, **"Developer Tools"** and  **"Back"** Button.
=> new button by the name of "EXTRAS'' has been added in InGame Menu

engine/src/main/java/org/terasology/logic/players/MenuControlSystem.java, engine/src/main/java/org/terasology/rendering/nui/animation/SwipeMenuAnimationSystem.java
#3553 
In MenuControlSystem if networkMode is off the time is paused, so any animation cannot happen over time.
Even if the time is paused we let the menu system pass in an estimated delta time(in SwipeAnimationSystem in case animDelta is 0 it is set it to 0.035f).
=> Issue #3553 solved. Can't go back after enabling Animated Menus

engine/src/main/java/org/terasology/rendering/nui/layers/ingame/PauseMenu.java, engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/NameRecordingScreen.java, engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/NewGameScreen.java, engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/RecordScreen.java, engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/ReplayScreen.java, engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/SelectGameScreen.java, engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/StartPlayingScreen.java, engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/UniverseSetupScreen.java, engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/WorldPreGenerationScreen.java, engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/WorldSetupScreen.java, engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/gameDetailsScreen/GameDetailsScreen.java, engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/inputSettings/ChangeBindingPopup.java, engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/inputSettings/InputSettingsScreen.java, engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/moduleDetailsScreen/ModuleDetailsScreen.java, engine/src/main/java/org/terasology/telemetry/TelemetryScreen.java
Fixes three problems relating to animated menus in the main menu. Related to #3553 and #3614.
Three main issues are resolved:
- Animations in the advanced game setup menus have been added.
- Fixed incomplete animations between selection screens, advanced game setup, and various other locations (by adding `isLowerLayerVisible()` statements where they were needed).
- Fixed clipping animations between some menus (by adding `super.onOpened()/onClosed()` where they were needed).
- All main menu animations should now run without error or need to use the escape key.
=> Various animation/UI system fixes

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/gameDetailsScreen/GameDetailsScreen.java
Fixes #3583 by showing the world name in worlds&biomes and in description box of world when game is quick start 
- Click on Single Player and quick start a game
- Start Playing a game and exit to main menu
- Again Click on Single player and then Click on your last Played game
- Click on details then Click on World&Biomes you will be able to see the name of world
- Click on the name of world you will be able to see the name in Module description
=> world name appear when quick start game

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/GameManifestProvider.java, engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/WorldPreGenerationScreen.java
Fixes #3610, making the worlds generate randomly again.
1) Use the reproduction steps from the issue to verify the bug exists for your workspace.
2) Use this branch and repeat the steps given in the issue. The generation should now be random. 
Create a world with the same world-generator twice and compare the result. (It should be a different world).
=> Make world generation random again

engine/src/main/java/org/terasology/rendering/nui/layers/ingame/DevToolsMenuScreen.java, engine/src/main/java/org/terasology/rendering/nui/layers/ingame/ExtraMenuScreen.java, engine/src/main/java/org/terasology/rendering/nui/layers/ingame/PauseMenu.java
Adds animations and extends fixes from #3615 to the in-game menus.
- Animated menus should now work for all in-game menus (with the exception of developer tool buttons).
=> Add/Repair UI animations for in-game menus

engine/src/main/java/org/terasology/engine/subsystem/common/ConfigurationSubsystem.java
Window size and position are saved to config.cfg
Fixes #3625 
- Start the game
- Resize or move the window
- Restart the game, size and position should be saved
=> Save window position and size on shutdown

engine/src/main/java/org/terasology/rendering/nui/widgets/UIButton.java, engine/src/main/java/org/terasology/rendering/nui/widgets/UISlider.java
Fixes the first problem mentioned in #3577 
Sliders can now be activated with Tab and used with the arrow keys.
This also fixes the activation persistence problem of sliders, i.e, holding down a slider and scrolling prevented the slider from deactivating.
- Go to a menu with sliders (eg. Audio Settings)
- Navigate to a slider using Tab or Shift+Tab
- Increase its value using RIGHT/UP key, or decrease using LEFT/DOWN key
=> Extend tabbing to UISlider

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/UniverseSetupScreen.java, engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/WorldSetupScreen.java
Added checks for similar world names. If a similarly named world is found, a popup is shown.
1. Create game -> Advanced Setup -> Universe Setup
2. Add a couple of worlds
3. Rename first to, say, "blocksEverywhere" (by selecting world and going into Configure menu)
4. Try to rename second world to the same name.
=> World name similarity checks

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/moduleDetailsScreen/ModuleDetailsScreen.java
Fixes #3464. Game no longer crashes when viewing Module details with missing dependencies.
1. Repeat the steps given in #3464 to reproduce the issue
2. Go to a details page of the module with missing dependency. (eg. Gooey defense with Flexible pathfinding not installed)
=> Added null checks when dependency is not found

engine/src/main/java/org/terasology/config/SystemConfig.java, engine/src/main/java/org/terasology/engine/modes/GameState.java, engine/src/main/java/org/terasology/engine/modes/StateLoading.java, engine/src/main/java/org/terasology/engine/modes/loadProcesses/LoadingChunkEventSystem.java, engine/src/main/resources/default.cfg
@Cervator Cleaned up git a bit as requested. Follow-up of previous PR which I will close: https://github.com/MovingBlocks/Terasology/pull/3642, solving https://github.com/MovingBlocks/Terasology/issues/2753.
I have added Javadoc to the new LoadingChunkEventSystem, and have moved the timeout time to system config. I told the user to check the log for more info if the failure occurs.
As stated before:
Player should spawn without issues when everything goes as expected. If an error is introduced in the chunk generation process, the player will fail to spawn, and the game will time out back to the main menu.
To introduce an error in the chunk generation process:
Add `int num = 4 / (4 - 4);` at the start of the `generateChunk` method in BuilderWorldRasterizer: …
=> Graceful spawn fail on chunk load timeout: git cleaned up

engine/src/main/java/org/terasology/rendering/nui/widgets/UIDropdownScrollable.java, engine/src/main/java/org/terasology/rendering/nui/widgets/UIScrollbar.java
Fixes #3668 
Open a menu that contains a scrollable dropdown(example: video settings/fullscreen resolution, NUI editor, single player/gameplay templates). The scrollbar works as desired now
=> Add scrollbar region as interacting region to fix #3668

config/groovy/common.groovy, config/groovy/util.groovy, groovyw.bat
This PR adds wildcard support to the `groovyw <item> get <object>` e.g. `groovyw <item> get *`.
Testing this PR could take some considerable time and effort to check all of the use-cases are correct, so these changes should only apply if wildcards (`*` or `?`) are detected in the input argument (see [Line 61 of util.groovy](https://github.com/BenjaminAmos/Terasology/blob/715d2450d077613a3fc3c6e5ee4ca26f3a9e9b7c/config/groovy/util.groovy#L61)). As such, I will list the series of tests that I have tried so far:
- Command: `groovyw module get *`
- Expected result: All the available modules under the @Terasology organisation should be obtained.
- Command: `groovyw module get ?????Blocks`
- Expected result: The [FunnyBlocks](https://github.com/Terasology/FunnyBlocks) module should be obtained. …
=> Added wildcard support to groovyw <item> get

config/groovy/common.groovy
Adds a try catch to the update item call.
This allows the exception to be caught, and the item to be skipped.
Break a module's git in some way so that `groovyw module update-all` doesn't work
Then verify that the module is skipped and the rest of the command works fine.
=> Add try-catch to updateItem

engine/src/main/java/org/terasology/rendering/dag/nodes/LightShaftsNode.java
Quick tweak for sun shafts being present during night, which looks really bad.
This PR presents a quick solution remapping light shafts' source position to the moon with lowered exposure during night. An overlap instead of a switch would be nicer, or perhaps to just shorten the interval for moonshafts, start with sun a little bit more under the horizon.
- Turn on light shafts in the video settings
- Open console '~', write setWorldTime [time], where time is any float in *days*. 
0,1,2 -> midnights;  0.5,1.5,2.5 - noons;   
- Verify that with the beginning of night the shafts start to appear from the moon and stop appearing from the sun under the horizon. And vice-versa
[ ] - Nothing yet
=> LightShafts calculated from the Moon during night time and with half exposure.

engine/src/main/java/org/terasology/logic/characters/VisualCharacterSystem.java
Fixes #3685
Add this command to `VisualCharacterSystem.java`:
```java
@Command(shortDescription = "print all characters and visual entities present currently")
public String printVisualEntities() {
StringBuilder message = new StringBuilder();
for (EntityRef character: entityManager.getEntitiesWith(PlayerCharacterComponent.class)) {
if (character.hasComponent(VisualCharacterComponent.class)) {
EntityRef visualCharacter = character.getComponent(VisualCharacterComponent.class).visualCharacter;
message.append(character.toFullDescription());
message.append("\n");
message.append(visualCharacter.toFullDescription());
message.append("\n");
}
}
return message.toString();
}
```
Now, start 3-4 instances of game, host a Core Gameplay mode game on one of them, and join using others. Once, everyone has …
=> Fix for Incorrect VisualCharacter entity

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/AddServerPopup.java
This fix applies `.trim()` to the text to ignore trailing whitespaces.
The 'port' value in the `AddServerPopup` can end up invalid due to
whitespaces, such as newline characters (`\n`). This will disable the _OK_ button and the user cannot add a new server.
=> Fixes invalid values for 'port' in AddServerPopup

engine/src/main/java/org/terasology/rendering/nui/widgets/UIText.java
Fixes #3688
Start from a clean game with no save games. Try reproducing #3688, in both the ways stated over there. The new game should load properly now.
=> Fix getText() function in UIText

engine-tests/src/test/java/org/terasology/logic/characters/VisualCharacterSystemTest.java, engine/src/main/java/org/terasology/logic/permission/PermissionManager.java
Fixes the currently failing `testSendingOfCreateVisualCharacterEvent` in `VisualCharacterSystemTest`.  
Also, whitelists the PermissionManager class for it to be used by modules.
Run `testSendingOfCreateVisualCharacterEvent` in `VisualCharacterSystemTest`
=> VisualCharacterSystemTest Fix and Whitelist PermissionManager

engine/src/main/java/org/terasology/rendering/nui/widgets/UIDropdown.java, engine/src/main/java/org/terasology/rendering/nui/widgets/UIDropdownScrollable.java
When I checked #3668 I saw that keys didn't work in dropdown menus at all. After that I found out, that TabbingManager.focusedWidget mention in UIDropdown and UIDropdownScrollable classes creates NullPointerException.
PR fixes: 
-highlight of menu options with mouse or keyboard when widget is open
-change options with keyboard when widget is closed
-"enter" key event added (it chooses highlighted option)
Open video settings or language settings and check out a dropdown widgets. "Up", "Down", "Left", "Right" and "Enter" keys should work. Options should be highlighted when cursor is over it AND when cursor is somewhere else.
=> Minor changes in dropdown menus

engine/src/main/java/org/terasology/rendering/primitives/BlockMeshGeneratorSingleShape.java
Improved performance by the following changes:
- Reduced looping over all block sides from 3 to 1 loop
- Only load values when they will be used later
On my Surface Pro 3 with an i5 and high rendering settings the FPS increased at world loading from ~10 to ~13. Also the world loading feels faster.
Run the game.
Nothing from my side.
=> Improve performance of BlockMeshGeneratorSingleShape#generateChunkMesh

engine/src/main/java/org/terasology/logic/players/LocalPlayerSystem.java, engine/src/main/java/org/terasology/rendering/logic/RegionOutlineRenderer.java, engine/src/main/java/org/terasology/rendering/logic/SkeletonRenderer.java
This PR fixes #3665. It is a very simple fix, since there are only 3 places where a method call leads to a call to `glLineWidth`. All of these calls have been modified to have a line width of only 1. This should prevent any warnings from OpenGL.
Also, it seems like Eclipse automatically replaced all of the tabs with spaces (which shouldn't be an issue since most of the project uses spaces instead anyway), and reordered the imports. I don't think these should be major issues though.
=> Fixed OpenGL line width warning

engine/src/main/java/org/terasology/engine/subsystem/headless/mode/StateHeadlessSetup.java
Fixes #3673
Logs warning in `StateHeadlessServer` when module is not found in module registry.
Add a non-existing module (e.g. TestMissingModule) to the `override.cfg` file and then start the headless server (make sure you have no saved games otherwise it will load the config from the first one). In the logs you should see the message "ModuleRegistry has no latest version for module <module>".
Note: I noticed that the modules from `override.cfg` are loaded first, and then `config.cfg`. This tripped me up while testing. First you'll have to delete any entry in `config.cfg` for this
```
"defaultModSelection": {
"modules": []
```
otherwise what you specify in `override.cfg` will be completely ignored.
=> Log warning when module specified in override.cfg not found

engine/src/main/java/org/terasology/logic/selection/LocalPlayerBlockSelectionByItemSystem.java, engine/src/main/java/org/terasology/logic/selection/MovableSelectionEndEvent.java, engine/src/main/java/org/terasology/logic/selection/MovableSelectionStartEvent.java, engine/src/main/java/org/terasology/world/selection/BlockSelectionComponent.java
Implementation for a new feature which enables the player to select a suitable position for a selected region after specifying its size.
There is no change in the block selection logic so any modules depending on old logic should work fine. In order to use the new feature, the `MovableSelectionStartEvent` must be sent which binds the camera position with the region and the player can select the final position of the region by clicking the left mouse button.
Refer to the PR [MasterOfOreon#50](https://github.com/Terasology/MasterOfOreon/pull/50) for a working example and steps to test.
=> Implement movable selection feature

engine/src/main/java/org/terasology/input/binds/inventory/UseItemButton.java, engine/src/main/java/org/terasology/input/binds/inventory/package-info.java
there are _two_ packages named `org.terasology.input.binds.inventory`: one in the engine, one in the Inventory module. The engine one is `@API`, but the Inventory one is not. When the APIScanner looks for API annotated types, Reflections _sometimes_ thinks it's returning the engine package but actually returns the Inventory package. APIScanner is unable to find the annotation on the Inventory package,  causing an NPE.
This is fixed by removing the API annotation from the package and moving it to the only class in the package, `UseItemButton`.
Resolves Terasology/ModuleTestingEnvironment#9.
=> Fix APIScanner NPE when running MTE tests

engine/src/main/java/org/terasology/utilities/procedural/PerlinNoise.java, modules/Core/src/main/java/org/terasology/core/world/generator/facetProviders/SimplexBaseSurfaceProvider.java, modules/Core/src/main/java/org/terasology/core/world/generator/facetProviders/SimplexHillsAndMountainsProvider.java, modules/Core/src/main/java/org/terasology/core/world/generator/facetProviders/SimplexHumidityProvider.java, modules/Core/src/main/java/org/terasology/core/world/generator/facetProviders/SimplexOceanProvider.java, modules/Core/src/main/java/org/terasology/core/world/generator/facetProviders/SimplexRiverProvider.java, modules/Core/src/main/java/org/terasology/core/world/generator/facetProviders/SimplexSurfaceTemperatureProvider.java, modules/Core/src/main/java/org/terasology/core/world/generator/worldGenerators/FlatWorldGenerator.java, modules/Core/src/main/java/org/terasology/core/world/generator/worldGenerators/HeightMapWorldGenerator.java, modules/Core/src/main/java/org/terasology/core/world/generator/worldGenerators/SimplexFacetedWorldGenerator.java, modules/CoreSampleGameplay/module.txt
Converted Core Perlin world generator to instead use Simplex noise. 
Deprecated Perlin noise in favor of Simplex noise, which is a newer algorithm from Ken Perlin with fewer directional artifacts, lower computational overhead for higher dimensions.
=> Deprecated Perlin noise over Simplex

engine/build.gradle, engine/src/main/java/org/terasology/logic/behavior/asset/Group.java, engine/src/main/java/org/terasology/logic/behavior/asset/GroupBuilder.java, engine/src/main/java/org/terasology/logic/behavior/asset/GroupData.java, engine/src/main/java/org/terasology/logic/behavior/asset/GroupFactory.java, engine/src/main/java/org/terasology/logic/behavior/asset/GroupFormat.java
- New asset: Group
- Updates the build with gestalt version 5.1.4 (required by asset structure)
- The new Group asset allows group configurations to be loaded from JSON files (assets/groups/.group). 
- Gestalt 5.1.4 contains a fix to a bug that would sometimes prevent an asset file to be loaded. This error appears as an `java.security.AccessControlException` exception ("access denied"), with the stack trace leading to `org.terasology.assets.format.AssetDataFile.openStream(AssetDataFile.java:99)` .
- New asset structure: `Group`, `GroupBuilder`, GroupData`, GroupFactory`, and `GroupFormat`. The new implementation is hermetic and shouldn't affect any of the existing classes.
- Updates both `gestalt-module` and `gestalt-asset-core`  to version 5.1.4 in `build.gradle`
- Make sure to …
=> New asset: Group

engine/src/main/java/org/terasology/logic/selection/LocalPlayerBlockSelectionByItemSystem.java
Fix for two NPEs thrown by the `LocalPlayerBlockSelectionByItemSystem`:
- When the cam target had no `LocationComponent`, for eg: when the player is looking up at the sky
- When `onLeftMouseButtonDown` event was not triggered after a selection had been made, in which case the `blockSelectionComponentEntity` would be null
=> Fix NPEs related to movable selections

engine-tests/src/test/java/org/terasology/config/flexible/internal/SettingImplTest.java, engine/src/main/java/org/terasology/config/flexible/Setting.java, engine/src/main/java/org/terasology/config/flexible/internal/FlexibleConfigImpl.java, engine/src/main/java/org/terasology/config/flexible/internal/SettingImpl.java
The value type is stored as a `TypeInfo` which stores information like generic parameters. The `FlexibleConfig` API remains unchanged for now -- the `FlexibleConfig.newSetting` method still takes a `Class` parameter.
=> Use TypeInfo to store value type in Setting

engine/src/main/java/org/terasology/engine/module/ExternalApiWhitelist.java
These are useful for audio buffers. While it's still necessary to
copy to a `ByteBuffer` when passing it on to Terasology, this
helps a lot during synthesis and effect processing.
Additionally, these are analogous to `ByteBuffer` and `IntBuffer`. So
it seems reasonable to have these too. (And in a future PR,
maybe `DoubleBuffer`, `LongBuffer` and `CharBuffer`?)
=> Add ShortBuffer and FloatBuffer to API whitelist

engine/src/main/java/org/terasology/logic/inventory/ItemPickupAuthoritySystem.java, engine/src/main/java/org/terasology/physics/bullet/shapes/BulletBoxShape.java, engine/src/main/java/org/terasology/physics/bullet/shapes/BulletConvexHullShape.java, engine/src/main/java/org/terasology/physics/bullet/shapes/BulletSphereShape.java, engine/src/main/java/org/terasology/physics/shapes/BoxShape.java, engine/src/main/java/org/terasology/physics/shapes/ConvexHullShape.java, engine/src/main/java/org/terasology/physics/shapes/SphereShape.java
#3199 introduced a wrapper over collision shapes to remove engine and module dependencies on the physics engine. However, the introduced wrappers are merely functional and have inconsistent and incomplete public APIs. This PR formalizes the `CollisionShape` API and establish a consistent set of methods in the relevant interfaces.
=> CollisionShape API formalization

engine/src/main/java/org/terasology/logic/console/ui/CyclingTabCompletionEngine.java
Emulates the autocomplete behaviour of `zsh` to further increase efficiency.
Open the console and type `sScr` - should complete to `showScreen ` (note the space at the end), which allows you to type in the screen uri without having to manually enter a space.
=> Add space after completing text in Console

engine/src/main/java/org/terasology/engine/module/ModuleManagerImpl.java
A possible tiny improvement to how classpath entries are processed for modules specifically on Windows. While chasing mysteries for https://github.com/Terasology/DynamicCities/pull/40 I discovered that in a brand new mini-workspace with _just_ DynamicCities added I got a weird error about loading jar files instead of the original issue I posted to that DC PR.
The problem was specific to Strings referring to jar files starting with something like `/C:/...` which did not gracefully turn into `Path` objects. Chances are that I haven't hit that in my mega-workspace as I have _every_ relevant module in source form so I never end up loading modules from jars, let alone specifically while running MTE tests - and it may be specific to MTE tests somehow? Unsure.
After applying this fix I could run …
=> Small Improvement for handling Paths on Windows for module classloading

engine/src/main/java/org/terasology/reflection/TypeRegistry.java
Fix #3745 
Removing this line fixes a crash for certain users with no obvious repercussions.
From my very limited research, I think that all the line did was tell reflections to run on multiple threads which, although nice, is not worth causing crashes for some users. It also might not at all be what it's doing so I'll create an issue to investigate this.
=> Fix crash on certain environments

gradle/wrapper/gradle-wrapper.properties
Seems to work OK in my mega-workspace. Should resolve an issue where you might fail to compile the game with a Java too new for our prior version of Gradle 4.x. Gradle 5.x on the other hand is bound to bring in a lot more change.
Also tested it with a sample `groovyw get` module check. Anybody else want to see if they can come up with something Gradle-related that'll break with this?
Will see if Jenkins builds this OK as well. Probably can merge pretty soon. Pinging @pollend for review, maybe anybody else with a mega-workspace and interest, like @jellysnake @eviltak @Qwertygiy  or somebody :-)
=> Bump Gradle to latest 4.x

config/groovy/util.groovy
This is to avoid issues with `groovyw get *` on different platforms.
- Windows: `get *` would expand to files in current directory
- *nix: the wildcard needs to be escaped in single quotes `get '*'`
With this PR, a unified command for getting all modules is available.
Try the new groovy command `groovyw module get-all` to retrieve all modules into a mega workspace.
Nothing. 
While looking at the code I was wondering whether we can improve the whole groovy scripting, though.
- use proper logging instead of `println` statements
- use [`CliBuilder`](http://docs.groovy-lang.org/2.4.7/html/gapi/groovy/util/CliBuilder.html) for better command line interface (less manual code)
=> Add 'get-all' command to groovy script

engine/src/main/java/org/terasology/world/internal/EntityAwareWorldProvider.java, engine/src/main/java/org/terasology/world/internal/WorldProviderCoreImpl.java
Previously, the OnChangedBlock event was not being created when blocks were placed by the player.
Additionally, the event sent to the block *region* was separate from the event sent to the *block.*
This PR corrects those two problems with minimal changes to the codebase. It should solve Terasology/SimpleLiquids#4
Wider-reaching changes, such as fully replacing usage of the BlockChange class with the OnChangedBlock event, should remain within the scope of a separate PR.
=> Adjustments to Block Updates

engine/src/main/resources/assets/ui/menu/gameDetailsScreen.ui
Partially reverts ff190cf3e59f8e1a59b6d59ddec2a63dd71071ee which removed page2 from the UI, breaking the screen entirely. 
The Biomes section of the UI will remain non-functional until a new implementation is made using BiomesAPI, but it is now merely an empty label, rather than erroring the entire screen.
To test, create any singleplayer world, return to main menu, and then click the "Details" button on that world. It should show the modules and blocks used in that world without creating an error popup.
=> Fixes Game Details screen by restoring Worlds & Biomes page

engine/src/main/resources/assets/i18n/menu_de.lang
Replaces the current german translation for "seed" which is "Unikale Weltensaat" with "Seed".
The reason is that the current translation sounds very niminy-piminy and most german people who ever came in touch with gaming or generators in the gaming context know what a "seed" is.
Start the game with german language and go to advanced world generation. Check seed field description to say "Seed".
=> Use simpler german translation for "seed"

modules/Core/src/main/java/org/terasology/core/world/generator/rasterizers/TreeRasterizer.java
Adds hard references to the blocks used by the Core tree rasterizer during the initialize stage, rather than waiting for lazy loading during generation. This fixes #3740 
Open Josharias Survival and find trees. If they have leaves, it works.
=> Add hard references to tree blocks in initialize stage

build.gradle
The engine Jenkins build started failing after #3743, the minor Gradle upgrade. At least that's my theory based on logging in Jenkins. With this version bump to the associated Artifactory plugin for Gradle it publishes normally again, at least locally. PR test won't show it (no publish step) so this PR is for doc purposes and will be merged immediately to test the fix in Jenkins.
=> Upgrade Artifactory plugin to fix compatibility issue with latest Gradle version bump

modules/Core/build.gradle
Upgrades the artifactory plugin from 4.0.0 to 4.10.0 to fix Jenkins builds for the recent Gradle upgrade, as with #3764
=> Update Core build.gradle artifactory plugin for new gradle

engine/src/main/java/org/terasology/config/flexible/AutoConfigManager.java
This addresses a warning reported by the [Checker Framework](https://checkerframework.org/).
I think having the context as a private member is not necessary here and
we can instead pass it directly to `loadConfig` where it is needed.
=> Pass `context` directly to `loadConfig` method in AutoConfigManager

engine/src/main/java/org/terasology/rendering/world/WorldRendererImpl.java
Fixes https://github.com/MovingBlocks/Terasology/issues/3323
In order to make sure that the outline shown in the issue renders on top, all the other world rendering Nodes must be processed first. This took a bit longer than it should have, but it taught me a lot about rendering and the DAG :)
As described in the issue above:
- Start the game with the GooeysQuests module active
- `give dungeonEntranceViaMountain` in the game console
- See the wireframe render above everything else
I can update the renderer map sketchboard as well: https://sketchboard.me/dAEsEaNXcHvD#/.
=> Overlay rendering order fix

config/groovy/common.groovy
Adds colored logging to `groovyw module update-all` and restructures the
logging output a bit. Overall, the noise is reduced, and the logged
messages now contain info about the branch that is currently checked
out.
Just run `./groovyw module update-all` in your workspace. Preferably, with modules in different states (clean, dirty), non-git modules, etc.
Nothing.
=> Improve logging in module update script

engine/src/main/java/org/terasology/world/block/entity/BlockCommands.java
The current implementation of the `give` command loops creates an item entity for every individual block or item, and sends an individual event for each item. This is a largely unnecessary loop, as the Inventory module is fully capable of handling arbitrarily large stacks. 
It also has the unwanted side effect of triggering the pickup-item sound many times consecutively, resulting in an absurdly loud and jarring noise whenever receiving the default 16 blocks.
This quick fix allows the give command to send as many blocks in one entity as is logical for that block; it is still only 1 item per event if the block s not stackable, but if it is stackable, it will group up to 99 together in each event, significantly reducing unnecessary overhead.
The remaining potential noise problem for …
=> Optimize give command, reduce noise spam

engine/src/main/java/org/terasology/input/InputSystem.java
Fixes #3768
* Create and save a game and exit Terasology (e.g. LaS)
* Enforce a dependency issue for some module used in the game (e.g. adapt dependency version of LaS dependency)
* Try to load the game (should result in an error dialog popping up)
* Try to click the "Ok" button
=> Fix InputSystem#inputEntities sync with localPlayer's entities.

engine/build.gradle, engine/src/main/java/org/terasology/input/InputSystem.java
Bump up gestalt version to 5.1.5
Merge after https://github.com/MovingBlocks/gestalt/pull/73
gestalt 5.1.5 contains extended logging for getProtectedDomain error.
Must help at least invistigate : https://github.com/MovingBlocks/Terasology/issues/3781
* Make Invalid Component(With @Replicate) or Event with unprocessable type in type handlers e.g:
1. make ```@Replicate``` annotation for field in Component with type ```com.google.common.collect.Multimap```(guava) or any collection not inherit from ```java.lang.Collection```
2. make any field in Event with non-java type and with non-terasology type e.g. ```BigInteger```
* Start serve
* Start client
* Connect to server
* Make something for send network event made below
* in log u can see "Cannot determinate Module for type: <invalid type>"
=> Gestalt 5.1.5

facades/PC/build.gradle
This PR adds a gradle task for FlightRecorder profiling.
This PR adds a `profile` task to gradle. It is equivalent to the IntelliJ IDEA configuration added by #3475. Running it generates a `terasology.jfr` file in the root project directory which can be opened with Java Mission Control and reviewed for performance enhancement. This is mainly for people who don't use IntelliJ (like me).
Run `gradlew jar profile` to start the game with the profiler. Once the game is finished, the `terasology.jfr` file will be created in the root project directory and can be opened with Mission Control to make sure everything is working properly.
=> Added gradle FlightRecorder profiling task

engine/src/main/java/org/terasology/logic/players/PlayerSystem.java, engine/src/main/java/org/terasology/world/chunks/remoteChunkProvider/RemoteChunkProvider.java
Added missing event source:  BeforeChunkUnload.Client's
Systems will be notified of unloaded chunks now.
Fixes https://github.com/MovingBlocks/Terasology/issues/3006
Possible fix https://github.com/MovingBlocks/Terasology/issues/2477
---
1. Multiplayer:
* Start server
* Start client
* Connect to server
* Go far from the spawn area (minimum distance to draw)
* Open Console
* Type 'kill'
* Press 'Enter'
* You on spawn area
* World load, chunks visible
---
2.  Singleplayer
* Start client
* Create game
* Go far from the spawn area (minimum distance to draw)
* Open Console
* Type 'kill'
* Press 'Enter'
* You on spawn area
* World load, chunks visible
=> BeforeChunkUnload sending now in multiplayer on invalidate. Fix Respawn in multiplayer

engine/src/main/resources/assets/shaders/chunk_vert.glsl
This prevents the interior faces of partially transparent blocks from being merged into the exterior faces of the blocks behind them.
It would be wise to only adjust interior faces, and not exterior faces, but as of yet I have been unable to determine the proper way to accomplish this. This means that currently, it will not fix z-fighting between two blocks that are both partially transparent.
To test this, create or use a block marked "translucent" with the full cube shape, and a texture that is partially transparent so that you can see inside the block. When placed adjacent to a solid block, the interior face of the transparent block should be fully visible and overlaying the face of the block behind it.
=> Fix for Z-fighting on back faces of transparent blocks

engine/src/main/java/org/terasology/world/internal/EntityAwareWorldProvider.java, engine/src/main/java/org/terasology/world/internal/WorldProviderCoreImpl.java
Previously, #3757 attempted to fix the lack of the OnChangedBlock event being called when a block was placed by the player.
For the specific use case being tested, where the listener did not care about a LocationComponent, it was sufficient. But upon further review, it was still not being properly issued. Instead of the event being sent to the *specific* world-block entity that was being updated, it was being sent to the block *type* entity.
This time, the event should be sent to the proper location, and is being sent from the proper world provider.
=> Properly implement OnChangedBlock event for setBlocks() calls

engine/src/main/java/org/terasology/rendering/opengl/GLSLShader.java
added a missing carriage return for VOLUMETRIC_FOG. 
ex: 
#define VOLUMETRIC_FOG#define ANIMATED_GRASS
=> added missing carriage return for VOLUMETRIC_FOG

engine/src/main/java/org/terasology/logic/location/LocationChangedEvent.java, engine/src/main/java/org/terasology/logic/location/LocationChangedSystem.java, engine/src/main/java/org/terasology/logic/location/LocationComponent.java
This PR adds two classes, LocationChangedEvent and LocationChangedSystem, as well as adds two variables to LocationComponent -- lastPosition and lastRotation.
This allows other systems to listen for a LocationChangedEvent to handle moving entities such as players, items, or creatures, without having to constantly check their own cache of previous locations.
Create a class that implements BaseComponentSystem and subscribes for a LocationChangedEvent. It should trigger whenever a valid entity (such as the player or their camera) moves position or rotates.
=> Create LocationChangedEvent for moving entities

engine/src/main/java/org/terasology/input/lwjgl/JInputControllerDevice.java
Fixes #3556
Probably the best way to test this is with uinput on Linux. E.g. running this python program, with the `python-uinput` python package:
```python
import uinput
events = (
uinput.BTN_JOYSTICK,
uinput.ABS_X + (0, 255, 0, 0),
uinput.ABS_Y + (0, 255, 0, 0),
)
with uinput.Device(events) as device:
while True:
pass
```
and sending a keyboard interrupt to emulate unplugging the controller.
=> Fix crash when removing controllers

engine/src/main/java/org/terasology/rendering/primitives/BlockMeshGenerator.java, engine/src/main/java/org/terasology/rendering/primitives/BlockMeshGeneratorSingleShape.java, engine/src/main/java/org/terasology/rendering/primitives/ChunkTessellator.java, engine/src/main/java/org/terasology/rendering/world/ChunkMeshUpdateManager.java, engine/src/main/java/org/terasology/rendering/world/RenderableWorldImpl.java, engine/src/main/java/org/terasology/world/block/Block.java, engine/src/main/java/org/terasology/world/block/BlockColorSource.java, engine/src/main/java/org/terasology/world/block/DefaultColorSource.java, engine/src/main/java/org/terasology/world/block/internal/BlockBuilder.java, engine/src/main/java/org/terasology/world/block/loader/BlockFamilyDefinitionFormat.java, engine/src/main/java/org/terasology/world/block/loader/SectionDefinitionData.java, engine/src/main/java/org/terasology/world/block/shapes/BlockMeshPart.java, engine/src/main/resources/assets/shaders/chunk_frag.glsl
During the extraction of biomes from the engine, block color sources and offsets were removed due to their integration with biomes. This resulted in rather dead-looking grass and leaves, as well as consequences with other color-shifted blocks not being color-shifted.
This PR re-implements the system as close to the original as possible without making reference to biomes, and instead referring to the world's humidity and temperature facets directly.
=> Restore pre-BiomeAPI foliage shading

engine-tests/src/test/java/org/terasology/world/chunks/localChunkProvider/LocalChunkProviderTest.java, engine/src/main/java/org/terasology/network/ServerInfoService.java, engine/src/main/java/org/terasology/world/chunks/localChunkProvider/ChunkFinalizer.java, engine/src/main/java/org/terasology/world/chunks/localChunkProvider/LightMergingChunkFinalizer.java, engine/src/main/java/org/terasology/world/chunks/localChunkProvider/LocalChunkProvider.java, engine/src/main/java/org/terasology/world/chunks/remoteChunkProvider/RemoteChunkProvider.java, engine/src/main/java/org/terasology/world/propagation/light/LightMerger.java
Increase chunk loading speed for client and server (not world generation).
Maximum effect should be visible on SSDs. Or in multiplayer with 6+ players who are far apart
+ Seems, fix zombie thread, that prevent close client. (maybe #3738)
Chunks:
1. Open Terasology
2. Load  world, which chunks generated with max view distance
3. try compare chunkloading speed before and after (load world before using PR and after)
Thread:
1. Open Terasology
2. Open Mutliplayer
3. Close Terasology( you can exit  from JoinServerScreen)
4. You haven't Terasology process in Task Manager/top/htop/etc
=> Increase chunkloading speed

engine/src/main/java/org/terasology/engine/subsystem/rpc/DiscordRPCSubSystem.java
I was working on a fix to address discord RPC. The RPC thread spends a majority of its time spinning on sleep. this does not seem to work on my linux machine and the RPC library is marked as depreciated by discord. The problem is ```Thread.sleep(1)``` is sleeping for 1 ms between calls.
=> fixed threading issue with discord RPC

engine/src/main/java/org/terasology/engine/paths/PathManager.java, facades/PC/src/main/java/org/terasology/engine/Terasology.java
This PR deals with errors thrown during directory detection, specifically giving a chance to run the game again if the default directory detection fails.
In case of headless servers we have defaulted to choosing the home path as the current directory.
Fixes https://github.com/MovingBlocks/Terasology/issues/3566
Run the game on Windows XP. If you can find something with XP on it or a wierd OS that throws our directory detection out of the window.
- [ x ] Still have to adjust the wiki doc 
The doc has to be updated if in case we hit any such OSes in the future.
=> Handle unexpected (old or weird) OSes that may not support our directory detection.

engine/build.gradle
I'm still trying to understand the `apiElements` and other fancy more modern Gradle stuff introduced with #3835, but I believe this tweak might be going in the right direction.
GSON not being in the `apiElements` list is why I believe the build of the Kallisti module (which admittedly won't function at runtime without security off) failed in Jenkins - it used to build OK then fail expectedly at runtime unless you ran with security disabled.
Likewise I had added JOML to the legacy `compile` configuration as it was added during the Gradle 6 upgrade finished in #3835, but now believe I understand it better, with it needing to be both `implementation` and `apiElements` - or maybe something else so we can declare it fully in just one statement. It isn't actually used at all in modulespace yet …
=> Minor Gradle dependency tweak

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/JoinGameScreen.java
Contains
The server info field "ping" remains unchanged when switching from Listed servers to Custom servers, ideally it should get refreshed according to the server whose information is being displayed at the moment.This PR fixes it.
How to test
1. Go to the join game screen 
2. Select a server in both listed and custom section  
3. Now changing the tab from listed to custom and vice-versa updates the ping field according to the server being displayed (it was not so earlier).
=> Added Refresh on changing from listed to custom in join game

.gitignore, Jenkinsfile, build.gradle, config/gradle/common.gradle, engine-tests/build.gradle, engine-tests/src/test/java/org/terasology/reflection/TypeRegistryTest.java, engine/build.gradle, engine/src/main/java/org/terasology/engine/module/ModuleManagerImpl.java, facades/PC/build.gradle, facades/TeraEd/build.gradle, modules/BiomesAPI/build.gradle, modules/BuilderSampleGameplay/build.gradle, modules/Core/build.gradle, modules/CoreSampleGameplay/build.gradle, templates/build.gradle
Although it may also hold some promise in fixing some quirks due to how with Gradle 6 we got a new default target build path (`build/classes/java/main` instead of plain `build/classes`) - turned out there were more places where that mattered than the few I found and tried to apply fixes for. 
This PR specifically fixes the ModuleTestingEnvironment, which for some reason failed to find _any_ world generators as the test for which module provided one would run into one path with the `java/main` fragment and one without. 
I tried to puzzle that out for a while but didn't really get anywhere. This solution may not be perfect (somewhat going backwards) but it reduces uncertainties while we improve stuff further and find the time to make more proper fixes. I expect a next big round might be …
=> More Gradle follow-up, more focused on code analytics

build.gradle
Adds a check for Java 8 to gradlew
Set your JAVA_HOME env var to point to some other Java version and watch gradlew complain about it
=> add java 8 check to gradlew

engine/src/main/java/org/terasology/logic/console/commands/CoreCommands.java
Fixed #3741 to harden the search for blocks. The console now shows which asset is broken when a search command is issued in the in game console . 
Break an asset (eg : ladders) and write the command 'search stone' or search for any asset in the console. The search will return 0 results and return a message indicating that ladders is broken . Then fix it and run the same command and it should work.
If it works perfectly , can also be applied to prefabs and commands in the search
=> Modified search to show if an asset is broken

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/advancedGameSetupScreen/AdvancedGameSetupScreen.java
Double-clicking on a module that has not been downloaded, doesn't break the Advanced Game Setup selection anymore.
* UI falsely indicated that (not-downloaded) module as active after double click
* Activate-Deactivate button of an activated module remained "Deactivate" no matter how many times clicked
* Activated modules no longer were in green color
Closes #3818 
* Moved the `refreshSelection();` from `onOpened()` to `updateModuleInformation()`
* Go to the Advanced settings option while creating a new world in Terasology
* Double click on a module that has not been downloaded yet
Note: The issue occurred only during **the first double click**. Meaning, if you double click an already downloaded module, and afterward double click one that is not, the issue does not occur even without the …
=> Fixed UI bug at Advanced Game Setup window, Issue #3818

Jenkinsfile, build.gradle, config/gradle/publish.gradle, engine-tests/build.gradle, engine-tests/src/main/resources/module.txt, engine/build.gradle, engine/src/main/resources/engine-module.txt, facades/subprojects.gradle, metas/subprojects.gradle, modules/BiomesAPI/build.gradle, modules/BiomesAPI/module.txt, modules/BuilderSampleGameplay/build.gradle, modules/BuilderSampleGameplay/module.txt, modules/Core/build.gradle, modules/Core/module.txt, modules/CoreSampleGameplay/build.gradle, modules/CoreSampleGameplay/module.txt, templates/build.gradle
This ate my entire weekend, although just the spare time between GSOC proposal review, baby maintenance, and so on. Up way too late so will be brief :tm: - had imagined I might merge this straight to develop then PR to master for the v3.0.0 release, but too late and now too big.
Realized I needed to be able to vary how artifacts get published, either as releases or snapshots to Artifactory. This used to be done by having two separate jobs in the legacy Jenkins, one tied to `master` that made releases, one tied to `develop` that made snapshots. The actual version numbers were modified *by hand* as part of doing a release (take off `-SNAPSHOT`, push to `master`, bump version and reattach `-SNAPSHOT` ...)
New Jenkins has a multi-branch pipeline job. Shiny. But it was publishing _everything_ …
=> More Gradle: now with makeshift release management! Ready for v3.0.0

engine/build.gradle, engine/src/main/java/org/terasology/rendering/dag/nodes/LightShaftsNode.java
Looks like the transform for light shafts was in the wrong direction so they were facing away from the light source. applying a transpose to the viewmatrix corrects the direction even. 
before: 
after:
=> bumped version of joml and resolved direction of lightshafts

engine/src/main/java/org/terasology/world/block/internal/BlockManagerImpl.java, engine/src/main/java/org/terasology/world/chunks/internal/ChunkImpl.java
As we are using shorts for block ids for some time now having only an
8-bit array in the chunk implementation will lead to blocks not being
rendered when exceeding block id 128.
Probably related to #3882 and #2516
---
Find a way to register more than 128 blocks (e.g., by getting a bunch of stairs, slopes, slopecorners, ...) and place them in the world. All blocks, including the ones with ids greater 128 should be visible.
=> fix: Use 16 bit TeraArray in ChunkImpl 

engine/src/main/java/org/terasology/rendering/nui/layers/ingame/metrics/DebugMetricsSystem.java, engine/src/main/java/org/terasology/rendering/nui/layers/ingame/metrics/DebugOverlay.java, engine/src/main/java/org/terasology/rendering/nui/layers/ingame/metrics/MetricsMode.java
Simply make both DebugMetricsSystem and MetricsMode available as `@API`.
This allows to `@In` the debug system and register a new metrics mode.
=> feat: Make DebugMetrics available to modules

engine/src/main/java/org/terasology/rendering/nui/widgets/UIText.java
Hi there! First pull request on a very easy "good first issue"! :smile: 
Fixes #3884 : allows the user to select all the text inside a `UIText` by double-clicking on it (adds a `NUIMouseDoubleClickEvent` listener).
Find any `UIText`, write some text in it and double-click on it.
=> Added a double-click listener in UIText - see #3884

engine/src/main/java/org/terasology/logic/players/FirstPersonHeldItemMountPointComponent.java
The way we build modules standalone has tended to have a fair share of quirks since the Gradle from this engine workspace gets reused in clever/evil/dumb ways. But long story short one such quirk goes away with this PR, even if it is only a workaround for #3415. Really #2611 and making VR work again should be the proper fix, which would improve handling the OpenVR natives files and so on.
In the meantime this gets us one step closer to better _advanced_ tests in module jobs in Jenkins or anywhere else other than a full engine workspace + modules. Normal unit tests are fine, but those requiring a running game environment tend to be more tricky.
See https://github.com/Terasology/ModuleTestingEnvironment/issues/12 for the next problem I've encountered. 
Testing this is problematic, really …
=> Comment out a bit more VR stuff to avoid a native resolution issue in module standalone workspaces

modules/Core/assets/prefabs/explodeTool.prefab
This PR fixes issue #198
The explosion tool caused an explosion sound effect on activation, even when no target was selected and therefore no explosion was occurring.
I solved the issue by removing the `PlaySoundAction`-Component from the `explosionTool`.
To test, start a new game using the Core Gameplay template.
The explode tool (the dynamite stick) should not cause any sound effect when activated while not pointing at a block within interaction range.
In case a target block is selected, an explosion including the sound effect should occur as expected.
=> fix: Explode tool explosion sound behavior

.gitattributes, engine/src/main/java/org/terasology/logic/common/RetainComponentsComponent.java, engine/src/main/java/org/terasology/world/internal/EntityAwareWorldProvider.java
This PR adds `RetainComponentsComponent` which is a component intended to list component classes that are supposed to be retained when placing a block.
Specifying a list of components to be retained when placing a block is necessary as on placing a block, `EntityAwareWorldProvider::updateBlockEntityComponents` removes all components from the entity of the block to be placed that
- are not any of `NetworkComponent`, `BlockComponent`, and `LocationComponent`
- don't have `retainUnalteredOnBlockChange` metadata
- are not listed in the block prefab
- are not in the set of components to be retained
This especially affects components that are added to an entity programmatically, e.g. the `ManualLabor:AssemblyTable` which receives amongst others an `InventoryComponent` in …
=> feat: add retain components component

engine/src/main/java/org/terasology/rendering/primitives/BlockMeshGeneratorSingleShape.java
Fixes bug #3889
Verify water surface is visible when under other block as in below photos:
Before:
After
=> fix: Add logic check to allow visible water under other blocks

engine/src/main/java/org/terasology/engine/bootstrap/EnvironmentSwitchHandler.java, engine/src/main/java/org/terasology/persistence/typeHandling/SpecificTypeHandlerFactory.java, engine/src/main/java/org/terasology/persistence/typeHandling/TypeHandlerFactory.java, engine/src/main/java/org/terasology/persistence/typeHandling/TypeHandlerLibrary.java
Adds an abstract class `SpecificTypeHandlerFactory` that can be inherited to reduce boilerplate when creating `TypeHandlerFactories` that create type handlers for a single type.
Also replaces a cast of the type to `Class` with `TypeInfo.of(type)` when registering type handlers using the `@RegisterTypeHandler` annotation.
=> feat(typeHandling): Add SpecificTypeHandlerFactory

engine/src/main/java/org/terasology/logic/location/Location.java, engine/src/main/java/org/terasology/logic/players/PlayerFactory.java, engine/src/main/java/org/terasology/logic/players/PlayerSystem.java, engine/src/main/java/org/terasology/math/JomlUtil.java, engine/src/main/java/org/terasology/math/SpiralIterable.java
I ported over character spawning logic to JOML. I moved `SpiralIterable` to math and I also added added and deprecated `attachChild` in Location. The changes should be functionally the same from the old code. Do we want to move `SpiralIterable`to a different namespace is the place I'm using ok? 
- create a new world
- player should spawn without issue
=> feat(JOML): Migrate PlayerFactory

engine/src/main/java/org/terasology/audio/AudioManager.java, engine/src/main/java/org/terasology/audio/nullAudio/NullAudioManager.java, engine/src/main/java/org/terasology/audio/openAL/BaseSoundSource.java, engine/src/main/java/org/terasology/audio/openAL/OpenALManager.java, engine/src/main/java/org/terasology/audio/openAL/SoundSource.java
This PR migrates the AudioManager and related classes to JOML.
Every method I converted without keeping the original was unused throughout the engine and all major modules.
(the only module I couldn't check was FlexibleMovement, which seems to be broken for unrelated reasons atm)
To verify, run the game and check if the sound is working as usual.
=> JOML migration for AudioManager

engine-tests/src/main/java/org/terasology/MapWorldProvider.java, engine-tests/src/main/java/org/terasology/testUtil/WorldProviderCoreStub.java, engine-tests/src/test/java/org/terasology/world/EntityAwareWorldProviderTest.java, engine/src/main/java/org/terasology/world/WorldProvider.java, engine/src/main/java/org/terasology/world/internal/AbstractWorldProviderDecorator.java, engine/src/main/java/org/terasology/world/internal/EntityAwareWorldProvider.java, engine/src/main/java/org/terasology/world/internal/WorldProviderCore.java, engine/src/main/java/org/terasology/world/internal/WorldProviderCoreImpl.java, engine/src/main/java/org/terasology/world/internal/WorldProviderWrapper.java
I will start going through some of the more major systems in Terasology and provide JOML alternatives that we can start to use in place of the teramath implementations. we should be able to start removing the termath methods when these endpoints get updated in module space. I think I will start to do this for some of the more major systems that terasology uses to make the transition easier. Components are another issue that will be harder to address.
These methods are now backed by their joml equivalent so any actions on a given block should be the same from before. I expect breaking blocks and placement of blocks should still work the same regardless.
=> feat(JOML): Migrate methods of WorldProvider

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/SelectionScreen.java, engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/gameDetailsScreen/GameDetailsScreen.java
Simple fix for the game UI: on the Game Select and Game Details screens, the world generator will be shown as its display name (i.e. "Perlin") rather than its code name (i.e. "facetedperlin"). If the world generator's display name cannot be found, such as if the generator was moved or deleted, it will instead display a warning and the code name.
=> Adjust game selection screen to use world generator's display name

engine/src/main/java/org/terasology/world/BlockEntityRegistry.java, engine/src/main/java/org/terasology/world/internal/EntityAwareWorldProvider.java
updated BlockEntityRegistry with joml methods. the methods themselves back up their joml implementations, same as the worldprovider PR.
=> feat(JOML): Migrate BlockEntityRegistry

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/GameManifestProvider.java, engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/advancedGameSetupScreen/AdvancedGameSetupScreen.java
Seed value gets saved at the save file of the created world.
* Seed value was not getting saved at the world's save file, thus:
* Correct seed value did not appear on Game Details Screen (it was never saved in the first place)
The problem seemed to be that the `gameManifest` never gets the seed value.
Closes #3915 
Closes #3929 
Possibly also Closes #3883 
* Added the seed value `seed` at the `gameManifest`.
1. Create different games through the Advanced Game Settings by either adding your seed value, **or** by keeping the generated one
2. Follow the How to reproduce issue #3915 **or** How to reproduce issue #3929
=> Seed ui and save issues

README.markdown
Removed Google+ link as the web page lo longer exists.
<!-- Thanks for submitting a pull request for Terasology! :-)
Removed Google+ link as Google+ has been discontinued and the link does not lead anywhere.
=> fix: Removed Google+ link

engine/src/main/java/org/terasology/particles/ParticleSystemManagerImpl.java, engine/src/main/java/org/terasology/particles/updating/ParticleUpdaterImpl.java
This PR fixes the engine's usage of particle emitters referencing the same particle pool.
It turns out that particle pools could already be shared among multiple `ParticleEmitterComponent`s.
If done, however, the engine would update and render the pools multiple times (once for each particle emitter referencing it).
Start a new game and verify that block mining causes the expected particles to be emitted.
I'll also add a PR to Terasology/WeatherManager that fixes the module's performance and relies on this one.
=> feat: Particle Pool Sharing

engine/src/main/java/org/terasology/entitySystem/entity/internal/PojoEntityManager.java, engine/src/main/java/org/terasology/logic/common/RetainComponentsComponent.java, engine/src/main/java/org/terasology/persistence/typeHandling/TypeHandlerLibrary.java, engine/src/main/java/org/terasology/persistence/typeHandling/extensionTypes/ComponentClassTypeHandler.java, engine/src/main/java/org/terasology/persistence/typeHandling/extensionTypes/factories/ComponentClassTypeHandlerFactory.java, engine/src/main/java/org/terasology/world/internal/EntityAwareWorldProvider.java
Follow up to https://github.com/MovingBlocks/Terasology/pull/3910
Potential fix for this oversight: https://github.com/Terasology/Machines/pull/29#issuecomment-620378868
I tried to write a `TypeHandler` for `Class<? extends Component>` (see https://github.com/Terasology/Machines/pull/29#issuecomment-620846792) but failed adding it to the type handler library.
Not sure what the best/easiest/recommended way to go forward is ... 🙄 
@Cervator @jdrueckert would be great if you could test this ... The set should be filled like this now:
```java
retainComponents.componentTypeNames.add(InventoryAccessComponent.class.getName());
```
=> fix: Add type handler for `Class<? extends Component>` 

config/groovy/util.groovy
Adds a flag '--local' that can be added to `groovyw module list` in
order to only list modules that are present locally as source.
The output of this command is machine readable such that it can be used
easily to perform some command for all modules.
For instance, the following Bash command will reset and update all
modules:
```sh
for m in $(./groovyw module list --local)
do
pushd modules/$m
git reset --hard HEAD
git pull
popd
done
```
=> chore(groovyw): Add command to list local modules

engine/src/main/java/org/terasology/logic/players/LocalPlayerSystem.java, engine/src/main/java/org/terasology/logic/players/event/LocalPlayerInitializedEvent.java
This PR solves that clients had to poll `LocalPlayer.isValid()` to figure out, when the injected object `LocalPlayer` object was fully initialized.
I added the `LocalPlayerInitializedEvent` to communicate the object's initialization more efficiently to clients. The event is being sent to the client-entity.
=> feat: Add event to signal that LocalPlayer is fully initialized.

templates/build.gradle
- missing direct dependencies on modules formerly added transiently by other dependencies will now result in compile errors
=> feat: disable transient dependencies

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/advancedGameSetupScreen/AdvancedGameSetupScreen.java
This will only show modules from the "augmentation" category in the
advanced game setup to slim down the overwhelming list a bit.
- Game mode modules should be selected via the game play drop down even
before entering detailed setup
- Game modes often come with their default world generator tailored for
the game mode, thus fiddling with that is also an "advanced" use case
- Special modules are ... special
- Libraries only make sense in combination with other modules anyways
- Assets may be part of that list in addition to augmentation modules...
=> feat: Only show "augmentation" modules initially

.idea/runConfigurations/TerasologyPC__permissive_security_.xml, engine/src/main/java/org/terasology/utilities/LWJGLHelper.java, engine/src/main/java/org/terasology/utilities/NativeHelper.java, facades/PC/build.gradle
We had our own NativeHelper code to try to manipulate private variables on the classloader. It didn't work very well across JRE versions, as seen in #3742. Fortunately, [LWJGL has its own mechanism for dealing with library paths](http://wiki.lwjgl.org/wiki/LWJGL_Hidden_Switches.html#Hidden_Switches).
In specific, this PR addresses the error that appeared in logs as:
```
ERROR o.terasology.utilities.NativeHelper - Couldn't link static libraries.
java.lang.NoSuchFieldException: usr_paths
at java.base/java.lang.Class.getDeclaredField
at org.terasology.utilities.NativeHelper.addLibraryPath
```
* Run Terasology in a Java 8 environment.
* Run Terasology in a Java 14 environment.
If it still works under Java 8, and it gets to the main screen in Java 14, that's better than it was before!
The …
=> Change how LWJGL path is set. Improves compat with newer JRE

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/moduleDetailsScreen/ModuleDetailsScreen.java
Fixes #3981
Even though we did check against `null` in the first place, we nevertheless accessed this possible `null` value a couple of lines later 🙄
This is fixed by simplifying the way we set the canvas mode.
=> fix: Prevent NPE in ModuleDetailsScreen

engine/src/main/java/org/terasology/logic/players/PlayerSystem.java
Fixes #3300
- Load/create game with health module
- Enable hjump cheat
- Jump to your doom
- Choose "Exit Terasology"
- Re-open the game and load the same save
- Should now have full health instead of 0
NOTE: currently, trying to test using 'kill' in the cheat menu causes an OpenALException at "Setting listener orientation" when attempting to re-spawn. Use the high-jump or another method to cause player death.
=> fix: Respawn dead player after exiting the game

templates/build.gradle
Found while working on https://github.com/Terasology/Inventory/pull/10,
which uses shiny JUnit 5 parameterized tests.
=> build(templates): Add JUnit 5 params dependency

engine/src/main/java/org/terasology/world/block/family/AttachedToSurfaceFamily.java, engine/src/main/java/org/terasology/world/block/family/BlockFamily.java, engine/src/main/java/org/terasology/world/block/family/BlockPlacementData.java, engine/src/main/java/org/terasology/world/block/family/FreeformFamily.java, engine/src/main/java/org/terasology/world/block/family/HorizontalFamily.java, engine/src/main/java/org/terasology/world/block/family/MultiConnectFamily.java, engine/src/main/java/org/terasology/world/block/family/SymmetricFamily.java, engine/src/main/java/org/terasology/world/block/items/BlockItemSystem.java
This PR enhances the `BlockFamily` interface to accept additional data for determining the orientation of new blocks.
The requirement was introduced by this PR: #3978.
The new data contains the players viewing direction and optionally the relative position, the player aimed at when placing the block (on the attachment side). This information can be used, for example, to turn blocks upside down when attached to the upper half of a block side.
The old `getBlockForPlacement()` method got deprecated in favor of the new one.
Place some Chests and Doors, and other blocks. Verify that their placement behavior has not changed.
=> feat: BlockFamily API enhancement

engine/src/main/java/org/terasology/logic/common/RetainComponentsComponent.java, engine/src/main/java/org/terasology/world/block/items/BlockItemFactory.java
Reduces code duplication in `BlockItemFactory` and unifies the way block items are created when using `BlockItemFactory::newInstance` and `BlockItemFactory::newBuilder`.
Block item creation now also takes `RetainComponentsComponent` into account when copying components from a reference entity or block prefab to the block item. 
📘 Also, full addition of JavaDoc for `BlockItemFactory`.
=> refactor(BlockItemFactory): remove code dupes; add doc; retain components

engine/src/main/java/org/terasology/world/block/family/CeilingSupportingHorizontalFamily.java, engine/src/main/java/org/terasology/world/block/items/BlockItemSystem.java
This PR improves the block placement behavior of the `CeilingSupportingHorizontalFamily`
Previously the only way to place blocks upside down, using this block family, was to attach them to a BOTTOM side. This PR makes it possible to achieve the same thing, targeting horizontal sides.
This prevents the player from having to build a temporary support structure to simply have a ceiling available, to use for the placement of a new block.
Upside down block placement, is done if any of these conditions are met:
* the target side is a BOTTOM side
* the target side is horizontal (FRONT, BACK, LEFT, RIGHT) and the player targeted the upper half of the side when placing the block
Assign the above-mentioned block family to a furnace by adding the following line to the furnace.block json file: …
=> feat: Improve block placement of ceiling-supporting family

engine/src/main/java/org/terasology/logic/players/PlayerFactory.java
This changes an error message from being a NoSuchElementException to
> java.lang.RuntimeException: Failed to find an acceptable spawn location.
is RuntimeException the right thing to use for this?
NoSuchElementException is a direct subclass of RuntimeException so it's probably not very wrong, but maybe we have a more fitting type for this kind of thing.
=> chore: more descriptive error message on spawn failure

engine/src/main/java/org/terasology/engine/module/rendering/RenderingModuleRegistry.java, engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/videoSettings/RenderingModuleSettingScreen.java, engine/src/main/java/org/terasology/rendering/world/WorldRendererImpl.java
It crashed when going through the advanced game setup and trying to enter the render settings scene.
=> fix: prevent crash entering rendering settings with no renderers

.idea/dictionaries/kevint.xml, README.markdown
Duplicated information was becoming out-of-date.
=> fix(docs): replace some develop instructions with links to the wiki.

.idea/copyright/TerasologyEngine__old_.xml, .idea/copyright/TerasologyEngine_brief.xml, .idea/copyright/Terasology_Foundation.xml, .idea/copyright/profiles_settings.xml, build.gradle, buildSrc/build.gradle.kts, buildSrc/settings.gradle.kts, templates/build.gradle
Apache says this is a "shorter variant you may use."
https://www.apache.org/foundation/license-faq.html#Apply-My-Software
this PR makes no attempt to change _all_ the existing copyright headers, but does do a few of the high-level files to set an example.
=> chore: set the default copyright header to something shorter

engine/build.gradle
Moves engine/src/dev in to engine/src/main.
Removes the special `dev` SourceSet from engine's build configuration.
mentioned in #4015, #3979
Not sure. Anyone remember why this was split out to a separate source set to begin with? I don't see any additional test failures from moving it back.
=> refactor: move o.t.benchmarks back in to main source set

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/NewGameScreen.java, engine/src/main/java/org/terasology/world/generator/plugin/DefaultWorldGeneratorPluginLibrary.java
Fixes #4024. :crossed_fingers: 
oh, and some fixes for raw type warnings that probably don't have anything to do with this error, I was just preemptively fixing warnings I ran in to while debugging in case they would lead me to something.
Test gameplay modes _other than_ Josharias Survival. (JS should still work too, of course.)
Make sure you can play the game without going to the advanced setup screen.
Make sure the world type is the one chosen by the module.txt for that mode.
Try without interacting with the Gameplay Template menu at all; get the gameplay mode you're testing to be the default one by removing other types.
Try with a fresh `config.cfg` (move your old one out of the way).
=> fix: do not skip setting default world generator

Jenkinsfile, config/gradle/common.gradle, templates/build.gradle
Fixes broken module builds after the `buildSrc` dir was added, but not made available to module.
Actually just one half of the fix, will push the other half to https://github.com/MovingBlocks/ModuleJteConfig after merging this and testing a bit more
=> Attach new Kotlin source for a Gradle build plugin used with modules

engine/src/main/java/org/terasology/engine/subsystem/lwjgl/LwjglGraphics.java, engine/src/main/java/org/terasology/particles/rendering/SpriteParticleRenderer.java, engine/src/main/java/org/terasology/rendering/ShaderManagerLwjgl.java
particles disabled when GPU or Driver not supports OpenGL 3.3 (Mesa driver issue, possible Mac OS)
Remove, when shaderland and rendering will work on OpenGL 3+
=> fix(Particles): disable particles, when driver or GPU not supports OpenGL 3.3

Jenkinsfile
The very latest version of the "Copy Artifact" plugin decided it wanted to add obnoxious security features you can't easily turn off globally. Bah humbug, get off my lawn, and other old dev grumbles.
No functional effect inside this repo, no real testing needed outside of Jenkins being able to do its thing (which I just tested elsewhere)
=> fix: security hassle from a plugin

engine/src/main/java/org/terasology/particles/components/ParticleEmitterComponent.java, engine/src/main/java/org/terasology/persistence/typeHandling/coreTypes/ObjectFieldMapTypeHandler.java
Fixes #4031. There are `FloatBuffer`s in the `ParticlePool` which don't interact well with the serialization system, so I just marked the `ParticlePool` fields in `ParticleEmitterComponent` as `transient`, so that it's excluded from serialization. Particle systems seem to persist after saving and re-loading anyway. I haven't really looked into how that works.
Also I left in the debugging output that I used to find where the error was: detect `StackOverflowError`s in `ObjectFieldMapTypeHandler`, and output the field names.
=> Don't serialize particle pools.

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/NewGameScreen.java
Fixes #4034 . Adds an informative popup if one is trying to start a game without any gameplay modules.
You can test the code by trying to start a game without having any modules.
=> Add informative popup if starting game without modules

engine/src/main/java/org/terasology/particles/ParticleData.java, engine/src/main/java/org/terasology/particles/components/ParticleDataSpriteComponent.java, engine/src/main/java/org/terasology/particles/components/affectors/AccelerationAffectorComponent.java, engine/src/main/java/org/terasology/particles/components/generators/ColorRangeGeneratorComponent.java, engine/src/main/java/org/terasology/particles/components/generators/PositionRangeGeneratorComponent.java, engine/src/main/java/org/terasology/particles/components/generators/ScaleRangeGeneratorComponent.java, engine/src/main/java/org/terasology/particles/components/generators/TextureOffsetGeneratorComponent.java, engine/src/main/java/org/terasology/particles/components/generators/VelocityRangeGeneratorComponent.java, engine/src/main/java/org/terasology/particles/functions/generators/ColorRangeGeneratorFunction.java, engine/src/main/java/org/terasology/particles/functions/generators/TextureOffsetGeneratorFunction.java, engine/src/main/java/org/terasology/particles/functions/generators/VelocityRangeGeneratorFunction.java, engine/src/main/java/org/terasology/particles/rendering/SpriteParticleRenderer.java, engine/src/main/java/org/terasology/particles/updating/ParticleUpdaterImpl.java
A lot of the logic was pretty straightforward so moving the particle system over to JOML was not too bad. There are not a lot of dependencies from this part of the codebase so moving over the rest of the components is fairly trivial when compared to other parts of the engine. This mostly focuses on porting over particles in the engine. 
Modules:
- https://github.com/Terasology/Health/pull/40
- download health module: ` ./groovyw module recurse Health` and use branch from https://github.com/Terasology/Health/pull/40
- create core world and verify that particles behave correctly when breaking blocks.
=> feat(JOML): Migrate Particle System

engine/src/main/java/org/terasology/world/internal/EntityAwareWorldProvider.java
Added RetainComponentsComponent check to setBlock so it calls the updateBlockEntity method with the correct RetainComponents set and not an empty set
Add components to RetainComponentsComponent in some module and then update the entity via WorldProvider.setBlock(). The components added should be retained after the update.
=> added RetainComponentsComponent check to SetBlock

engine/src/main/java/org/terasology/logic/behavior/CollectiveBehaviorSystem.java
Pinging @casals since he's got the only commit to this file.
Small change to correct the registration class for CollectiveBehaviorSystem
The same class is used to register the vanilla BehaviorSystem: https://github.com/MovingBlocks/Terasology/blob/95f8881bd82398ab7b175f916aa53a78b1ef25c9/engine/src/main/java/org/terasology/logic/behavior/BehaviorSystem.java#L62
This causes a race condition where the class that gets injected varies depending on class load order. Since CollectiveBehaviorSystem doesn't actually extend BehaviorSystem this causes a cast failure exception during injection, in addition to other unexpected bad things.
I got this sporadically while loading FlexibleMovementTestbed and going to the behavior editor (F5). Doesn't always reproduce. Should in theory happen sometimes …
=> set correct class for Share in CollectiveBehaviorSystem

engine/src/main/java/org/terasology/logic/behavior/core/BehaviorTreeBuilder.java
A fix for a pretty specific bug found while removing the Behaviors module dependency from FlexibleMovementTestbed.
The engine tries to fallback in some cases to a behavior tree with URI "Behaviors:fallback". Under certain failure scenarios without the Behaviors module loaded this will crash during loading.
Get https://github.com/kaen/FlexibleMovementTestbed/ and its dependencies
Checkout the FlexibleMovement branch https://github.com/kaen/FlexibleMovement/tree/feature/new-behaviors
Start new game with FlexibleMovementTestbed gameplay module and default settings.
Without this change you get the following crash:
```
09:26:19.157 [main] INFO  o.t.e.prefab.internal.PrefabFormat - Attempting to deserialize prefab FlexibleMovementTestbed:testBase with inputs …
```
=> set fallback to engine:default rather than Behaviors:fallback

engine/src/main/java/org/terasology/logic/characters/CharacterMovementComponent.java, engine/src/main/java/org/terasology/physics/bullet/BulletPhysics.java, engine/src/main/resources/assets/prefabs/player/player.prefab
The code for extending item pickup range beyond the character collider was already present, but was broken accidentally in [#3907](https://github.com/MovingBlocks/Terasology/pull/3907/files/d8689f1710fb567d6ddfa3f2f9e6d4d09aedd768#diff-65b44f3586a2bf7259ca4594f2521535), so this requires very little change.
=> fix: Increase item pickup range

engine/src/main/java/org/terasology/physics/bullet/BulletPhysics.java
The height in the CharacterMovementComponent is the total height of the capsule shape that the physics system uses for the character, including the hemispherical caps, whereas the height in the CapsuleShape is only the height of the cylinder portion of the capsule. As the CapsuleShape derived in this method is only actually used to detect things like picking up items, rather than the character's physics, it doesn't matter that much, but it's neater if the trigger capsule is properly concentric with the collider capsule.
=> fix/Make the height of the shapes derived from CharacterMovementComponents more consistent.

engine/src/main/java/org/terasology/logic/nameTags/NameTagComponent.java
Adds an `@Replicate` annotation to all fields of `NameTagComponent`. This replicates the name tag information from server to clients, so the all clients see newly generated name tags.
- Join a host game/join game world with two clients, using a module that dynamically generates name tags. ([Terasology/MetalRenegades](https://github.com/Terasology/MetalRenegades) generates city names this way)
- When the name is generated, it should appear the same on both clients.
=> Replicate NameTagComponent fields to clients, to fix name tag display issues in multiplayer

engine/src/main/java/org/terasology/logic/characters/CharacterMovementComponent.java, engine/src/main/java/org/terasology/logic/players/PlayerFactory.java
As the player prefab no longer actually has a BoxShapeComponent, the check for whether there's enough space to spawn the player should instead use the size defined in the CharacterMovementComponent, which is kept more up-to-date anyway if the player height changes.
This avoids the warning `[main] WARN  o.t.logic.players.PlayerFactory - entity org.terasology.entitySystem.entity.EntityBuilder@55158884 does not have any known extent specification - using default`, and the corresponding very minor risk of the player spawning with their head in a block if they have a greater than usual height.
=> Derive player height from CharacterMovementComponent instead of BoxShapeComponent

engine/src/main/java/org/terasology/world/block/tiles/BlockTile.java
Update for compatibility with https://github.com/Terasology/Fluid/pull/19. Add BlockTile to the API, as Fluid needs access to it in order to attach liquid blocks' textures to the corresponding fluids.
=> Update for Fluid PR 19

engine/build.gradle, facades/PC/build.gradle, libs/subprojects.gradle
Uses `includeBuild` to include subprojects in the `libs/` subdirectory. This lets Gradle easily include and substitute Gradle builds for `engine` (and other) dependencies. More information: https://docs.gradle.org/current/userguide/composite_builds.html
To test, check out a library like `CrashReporter` or `gestalt` in `libs/` (you can use `groovyw lib get` for in house libraries), check out the source of the version required by the `engine`, fix any old Gradle issues/deprecations, and build the Gradle project. `gradlew dependencies` will show the substitution as follows:
```
+--- org.terasology.crashreporter:cr-terasology:4.1.0 -> project :CrashReporter:cr-terasology
```
IntelliJ will also be able to process the substitution and rebuild its indices accordingly.
=> Add subprojects under `libs/` as included builds for easy substitution

engine/src/main/java/org/terasology/rendering/nui/layouts/FlowLayout.java
Enhancement of FlowLayout: the option to put vertical spacing in between the items included withing that FlowLayout.
Added a variable named `verticalSpacing`, which can be set within the UI file that used a `FlowLayout`. I used `RowLayout.java`'s implementation of `horizontalSpacing`.
1. Get an up-to-date version of the LightAndShadow module
2. Go to file `LightAndShadow/overrides/Inventory/ui/hud/inventoryHud/ui`
3. Find where the `"flowLayout"` is located at, and add the line `"verticalSpacing": 10,` _(or any number instead of `10`)_. Place the line somewhere between lines with `"type"` and `"contents"`, e.g. like this:
```JSON
"type": "flowLayout",
"id": "toolbar",
"verticalSpacing": 10,
"contents": [
```
4. Run your build and create/open a LaS game
5. Notice the spacing between the …
=> feat(FlowLayout): add option for vertical spacing

engine/src/main/java/org/terasology/rendering/dag/AbstractNode.java, engine/src/main/java/org/terasology/rendering/dag/RenderGraph.java
Reduce the amount of information logged to the console when setting up the render graph when nothing is actually going wrong. This should make it easier to find the debug output you're actually looking for, and if you do want all the rendering debug information, it should still be available by turning on debug output.
=> Reduce verbosity of rendering output.

engine/src/main/java/org/terasology/logic/behavior/BehaviorSystem.java, engine/src/main/java/org/terasology/logic/behavior/nui/BehaviorTreeClientSystem.java
This PR fixes #3607 which would throw a NPE when the player would open a dropdown in the Behavior Editor as a client in multiplayer. This is a temporary fix for use until a system is developed to handle client to server behavior editing. It disables the Behavior Editor screen for machines in REMOTE_CLIENT mode an enables it only for AUTHORITY mode. If in REMOTE_CLIENT mode, when you attempt to open the editor a chat message pops up saying, "Behavior Editor is only available to the Host or on Singleplayer". 
Join a multiplayer game with WildAnimals enabled. Try pressing F5, instead of opening the editor it will send the chat message.
=> fix: disable behavior editor for clients in multiplayer

engine-tests/src/test/java/org/terasology/rendering/nui/layers/mainMenu/savedGames/GameProviderTest.java, engine-tests/src/test/resources/gameManifest.json, engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/GameManifestProvider.java, engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/NewGameScreen.java, engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/savedGames/GameProvider.java, engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/savedGames/NumberedGameName.java
Fixes #3982 
Custom game name works like Default game name prefix ("Game") now.
If you create game with name as previously created new game will have name "<previous> <index>"
If previously created game name already have index, then that index will be incremented.
1. create game with name "X"
2. exit to main menu
3. create game with name "X" again
4. check save games. You have save games "X" and "X 1" now.
=> fix(GameProvider): prevent creating game with duplicate name

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/advancedGameSetupScreen/AdvancedGameSetupScreen.java
- this includes modules present as source _and_ as .jar
- https://github.com/MovingBlocks/Terasology/pull/3973 set the default to augmentation which is a perfect match for the player-workflow, but as long as the main workflow is dev/test and not player, local makes more sense
=> feat(AGS): by default show only locally present modules

engine/src/main/java/org/terasology/input/InputSystem.java
There were a couple of NPEs with Dialogs because of this. The dependencies for the InputSystem were not injected via `@In` because the system was never registered as such. This simple change should solve this issue.
=> fix: Actually register InputSystem as system

engine/src/main/java/org/terasology/entitySystem/event/BeforeAfterEvent.java
This also makes the constructor public so that events in another package (especially in modules) can also extend this event.
Follow-up to #4095
=> docs: Improve docs for BeforeAfterEvent

engine/src/main/java/org/terasology/entitySystem/event/AbstractValueModifiableEvent.java
This PR follows from https://github.com/Terasology/ClimateConditions/pull/17#discussion_r448634606 (thanks to @ktksan).
The lack of documentation makes it hard to spot quirky or unexpected behavior. In this particular case, I'd like to start a discussion to change the implementation.
Currently the result value is computed as 
```
result = max(0, <baseValue> + Σ <modifier>) * Π <multiplier> + Σ <postModifier>
```
which is counter-intuitive for many reasons (and I don't know why Marcin implemented it this way).
At first I thought that capping the value to be positive holds for the result value in general, but that's not true - only the first set of _modifiers_ is guaranteed to result in a value greater or equal to zero, both _multipliers_ and _post-modifiers_ can move the result to negative …
=> doc: Add docs and contracts for AbstractValueModifiableEvent

engine-tests/src/test/java/org/terasology/rendering/nui/layers/mainMenu/savedGames/GameProviderTest.java
The `getNextGameNameWithNumber` test in `GameProviderTest.java` sporadically fails on the CI due to timing issues leading to games being saved with the same timestamp.
Locally this test consistently succeeds.
Increasing the `TIMESTAMP_DELAY` used to wait in-between to saving actions to 1 second (1000ms) hopefully reduces or helps to completely avoid timing-based failures of this test.
=> fix(tests): reduce timing-based test failures on CI

engine/src/main/java/org/terasology/rendering/nui/layouts/FlowLayout.java
Enhancement of FlowLayout: option to change the left-to-right align of included items that it has, to a right-to-left align.
Added a variable named `rightToLeftAlign`, by which the module chooses which type of aligning to use at its FlowLayout.
Before reaching the presented changes, I had changed the code as for it to apply only left-to-right alignment. Afterwards, I incorporated the boolean and combined the before and after. Seeing the merged version right away might be tricky to get what is for which alignment, thus, you can check:
- left-to-right  code here:
https://github.com/MovingBlocks/Terasology/blob/7a86cd19a2f436740c87513166a58acf091897f7/engine/src/main/java/org/terasology/rendering/nui/layouts/FlowLayout.java#L65-L80
- right-to-left code here:
```java
public void onDraw(Canvas …
```
=> feat(FlowLayout): Add option for right-to-left align

engine/src/main/java/org/terasology/network/internal/ClientConnectionHandler.java
Our JS (now including ClimateConditions, WildAnimals, etc) play test server was taking too long for clients to successfully connect before timing out. This seems to fix it.
=> fix: Increase connection timeout for clients as heavier module setups can take a while

engine/src/main/java/org/terasology/persistence/typeHandling/extensionTypes/ModifiableValueTypeHandler.java, engine/src/main/java/org/terasology/utilities/modifiable/ModifiableValue.java
Added a ModifiableValue type to the engine which can be used by Components so that Systems changing the values of these components do not affect the real values but rather add PreModifiers, multipliers and PostModifiers which can then form a mathematically correct altered value. This PR is a result of a discussion with @skaldarnar @jellysnake @ktksan and @e-aakash after https://github.com/MovingBlocks/Terasology/pull/4063#issue-443423710 .
Components must now mention whether their data is to be modified in-place / if the data is modified via an AbstractModifiableEvent / if the data members are of ModifiableValue type, in their respective Javadocs
This PR also includes a TypeHandler to handle proper deserialization and serialization of ModifiableValue from prefabs and to persist the data …
=> feat: Add ModifiableValue type

engine/src/main/java/org/terasology/rendering/backdrop/BackdropProvider.java, engine/src/main/java/org/terasology/rendering/backdrop/Skysphere.java
The methods in this PR are migrated over in the process of fixing the problem with light shafts in https://github.com/Terasology/CoreRendering/pull/20. Testing this in an omega workspace and verifying it with a couple different modules should be sufficient.
=> feat(JOML): Migrate BackdropProvider and Skysphere

engine/src/main/java/org/terasology/engine/subsystem/headless/renderer/HeadlessWorldRenderer.java, engine/src/main/java/org/terasology/input/cameraTarget/CameraTargetSystem.java, engine/src/main/java/org/terasology/logic/players/PlayerFactory.java, engine/src/main/java/org/terasology/logic/players/PlayerSystem.java, engine/src/main/java/org/terasology/rendering/dag/nodes/PrePostCompositeNode.java, engine/src/main/java/org/terasology/rendering/world/RenderableWorldImpl.java, engine/src/main/java/org/terasology/rendering/world/viewDistance/ServerViewDistanceSystem.java, engine/src/main/java/org/terasology/rendering/world/viewDistance/ViewDistance.java
changed ViewDistance#chunkDistance to Vector3ic to avoid potential changes to properties in ViewDistance. Worked on migrating PlayerSystem to joml and made a small modification to ViewDistance. what kind of serialization do we do with ViewDistance with game settings.
=> feat(JOML): Migrate PlayerSystem

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/advancedGameSetupScreen/AdvancedGameSetupScreen.java
This fixes #3940. The thread that was holding things up there was this one that's updating the mod registry.
* Start Terasology. Push the _Exit Terasology_ button quickly, before everything has time to settle.
* Make sure the window not only closed, but the process has quit as well. i.e. you see "process finished with exit code 0" in intellij or "build successful" and a return to the command line from the gradle task.
=> fix: allow game to quit without waiting for registry updater thread

engine/build.gradle, engine/src/main/java/org/terasology/engine/subsystem/headless/renderer/HeadlessCanvasRenderer.java, engine/src/main/java/org/terasology/rendering/assets/font/FontMeshBuilder.java, engine/src/main/java/org/terasology/rendering/assets/mesh/MeshBuilder.java, engine/src/main/java/org/terasology/rendering/nui/internal/LineRenderer.java, engine/src/main/java/org/terasology/rendering/nui/internal/LwjglCanvasRenderer.java
`nuiNump` ? Oh boy. That branch name is what I get for juggling I guess. Version _bump_ for NUI, that is. At least the branch name will go away, the commit message is more proper ...
I submitted a fix from @DarkWeird via https://github.com/MovingBlocks/TeraNUI/pull/22 which will be used with this PR. It fixes an infinite serialization length issue that would cause clients trying to connect in multiplayer to hang forever and just spam the log. 
Includes #4136
Edit: Wait, didn't notice we had two NUI dependencies in Gradle - adjusting the second as I merge this
=> Use new NUI release with some fixes

engine/src/main/java/org/terasology/rendering/world/RenderableWorldImpl.java
Remove unnecessary check for rendering ready.
Removed condition saves 10ms-15ms. (activity "Queueing Visible Chunks" takes ~18ms)
Removed condition check that near chunks ready too. It's useless because LightMerger(chunk final loading) made it valid for rendering early.
Fixes #4007 
Try compare FPS changes :(
Or compare "Queueing Visible Chunks" activity changes.
=> perf: simplified check for rendering ready.

.idea/misc.xml, facades/PC/build.gradle
Was causing `gradlew distPCZip` to fail on my Win10 system, despite seemingly working fine in Jenkins, with some "invalid file path" thing as the new `distsDirectory` (replacement for deprecated `distsDi`) would turn into this long awkward property thing, not a directory. I guess maybe somehow on Linux that could translate into a valid directory? Dunno. I figure this'll work on both.
Also let a `.idea/misc.xml` change slip in that keeps toggling in my workspace for some reason. Lets see if it flips back for anybody else
=> fix: Gradley weirdness about a Directory/DirectoryProperty thing

engine/src/main/java/org/terasology/math/JomlUtil.java, engine/src/main/java/org/terasology/world/block/BlockRegion.java
I added a center function for BlockRegion and updated the API for the ore generation to use BlockRegion and JOML. At the moment the two modules that use CustomOreGeneration are Minesweeper and AnotherWorld. just verifying that those generate correctly seems more then ideal to see if these changes are implemented correctly.
=> feat(JOML): add BlockRegion#center

engine/src/main/java/org/terasology/world/block/family/MultiConnectFamily.java, engine/src/main/java/org/terasology/world/block/family/UpdatesWithNeighboursFamily.java
This is change to migrate block families to JOML. This will require changes across multiple modules. the general change is fairly straightforward since the other systems already have JOML methods that should help with migrating this code without minimal code change.
=> feat(JOML): Migrate JOML for MultiConnectFamily and UpdateWithNeighboursFamily

engine/src/main/java/org/terasology/physics/engine/PhysicsSystem.java, engine/src/main/java/org/terasology/physics/events/ChangeVelocityEvent.java, engine/src/main/java/org/terasology/physics/events/ForceEvent.java, engine/src/main/java/org/terasology/physics/events/ImpulseEvent.java, engine/src/main/java/org/terasology/world/block/entity/BlockEntitySystem.java
I migrate the rest of the physics events except MovedEvent. I made some changes to allow Vector2/3/4*c types to be serialized and de-serialized: https://github.com/MovingBlocks/Terasology/pull/4174 If we can make a decision on this then we can convert uses of BaseVector to their joml constant counterparts.
=> feat(JOML): migrate ChangeVelocity/Force, Impulse events

engine-tests/src/test/java/org/terasology/math/RotationTest.java, engine/src/main/java/org/terasology/math/Rotation.java
this is a squash from the change in: https://github.com/MovingBlocks/Terasology/pull/4124
This is a simple change for the orientation of the Rotation. This is just an api change that should help with migrating changes for JOML. this adds an orientation method that returns the Quaternionf instead of Quat4f (termath) . there are no direct impacts at the moment and should work in omega since I only deprecate the old method. I also updated the test case to test for consistency.
=> feat(JOML): add orientation for Rotation

engine-tests/src/test/java/org/terasology/math/SideTest.java, engine/src/main/java/org/terasology/logic/characters/KinematicCharacterMover.java, engine/src/main/java/org/terasology/logic/location/ImmutableBlockLocation.java, engine/src/main/java/org/terasology/math/ChunkMath.java, engine/src/main/java/org/terasology/rendering/primitives/BlockMeshGeneratorSingleShape.java
I migrated getVector3i to direction.  direction better describes the a side then getVector3i but this is an API change. There is no direct impact to modules and the change is pretty straightforward. The other way to go about this is change the API and resolve it across all the modules.
=> feat(JOML): Migrate side#getVector3i() to direction()

engine/src/main/java/org/terasology/world/chunks/internal/ChunkRelevanceRegion.java, engine/src/main/java/org/terasology/world/chunks/localChunkProvider/RelevanceSystem.java
this sort for chunk relevance adds an n^2 cost to the search. since it will try to sort the current chunks against all possible nearby chunks. this function only add the chunk from the region if its valid or creates a new chunk if its not available. This same problem is also apparent with  `ChunkTaskRelevanceComparator`. Some better strategies would need to be setup if there are a lot of relevant entities. 
```
Chunk chunk = chunkProvider.getChunk(pos);
if (chunk != null) {
region.checkIfChunkIsRelevant(chunk);
} else {
chunkProvider.createOrLoadChunk(pos);
}
```
=> tweak sort for validating chunk n^2 cost

.idea/misc.xml, engine/src/main/java/org/terasology/logic/players/LocalPlayerSystem.java, engine/src/main/java/org/terasology/physics/engine/VoxelWorldSystem.java, engine/src/main/java/org/terasology/world/block/Block.java, engine/src/main/java/org/terasology/world/block/items/BlockItemSystem.java, engine/src/main/java/org/terasology/world/block/loader/BlockFamilyDefinitionFormat.java, engine/src/main/java/org/terasology/world/block/loader/SectionDefinitionData.java, engine/src/main/java/org/terasology/world/block/shapes/BlockShape.java, engine/src/main/java/org/terasology/world/block/shapes/BlockShapeData.java, engine/src/main/java/org/terasology/world/block/shapes/BlockShapeImpl.java, engine/src/main/java/org/terasology/world/block/shapes/JsonBlockShapeLoader.java
I migrated block along with the de-serilization. this mainly affects the tint of the block and the bounds assigned to the block from the collider. The image below is a list of prefab with blocks with assigned tints that can be used to verify. The collider is a bit harder to verify if it is correct or not.
=> feat(JOML): migrate block

facades/PC/build.gradle.kts
Fix jvmArgs for `server` gradle task. 
Bug prevent server to start with error:
```
Error occurred during initialization of VM
Too small maximum heap
```
introduced in #4175
1. Checkout it
2. run `server` task.
3. check that server started (any output from server)
=> fix(gradle-server): restore missing suffix for jvmarg -Xmx

engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/advancedGameSetupScreen/AdvancedGameSetupScreen.java
- refresh selection on opening so that dependent and explicitly activated modules are colored in addition to selected gameplay module
- refresh selection even if module was previously selected to avoid weirdness for dependent modules being explicitly activated
There was some weirdness in the Advanced Game Setup (AGS):
* only the selected gameplay module was colored
* dependency modules and other explicitly activated modules (as listed in the config) were not colored
* on double-clicking an already explicitly selected module, the internal state was screwed up resulting in a "Failed to resolve world generator" error on starting the game
* on double-clicking another module (dependent or not, but not explicitly activated), the selection updated correctly
=> fix: AGS selection weirdness

engine/src/main/java/org/terasology/input/cameraTarget/PlayerTargetSystem.java, engine/src/main/java/org/terasology/input/cameraTarget/TargetSystem.java, engine/src/main/java/org/terasology/logic/players/FirstPersonClientSystem.java, engine/src/main/java/org/terasology/logic/players/FirstPersonHeldItemMountPointComponent.java, engine/src/main/java/org/terasology/logic/players/FirstPersonHeldItemTransformComponent.java, engine/src/main/java/org/terasology/world/block/entity/BlockCommands.java
This is a continuation of changes for https://github.com/MovingBlocks/Terasology/pull/4177 and https://github.com/MovingBlocks/Terasology/pull/4162 . This migrates FirstPersonHeldItem and any classes associated with this component. This is self contained and has no impact on omega. 
This mainly affects held items and targeting blocks.
=> feat(JOML): migrate FirstPeronHeldItem/Mount/Transform Component

engine/src/main/java/org/terasology/physics/engine/VoxelLiquidWorldSystem.java
Add another world mesh like the `VoxelWorldSystem`, but containing all the liquid blocks, using the LIQUID collision group. This was broken a while ago in https://github.com/MovingBlocks/Terasology/pull/4139. This PR is similar to https://github.com/MovingBlocks/Terasology/pull/4210, but that other PR doesn't actually work. This PR is necessary for https://github.com/Terasology/Fluid/pull/21 to work.
If you want to be thorough with testing, you could check that:
- things don't collide with liquids
- it's possible to target solid blocks through liquids
- it's possible to target liquid blocks with fluid containers, with the linked Fluid PR
- things that have their collision settings set so that they should be able to collide with liquids do so (as far as I know there is currently nothing …
=> Re-add collision mesh for liquid blocks

engine/build.gradle, engine/src/main/java/org/terasology/logic/chat/ChatSystem.java, engine/src/main/java/org/terasology/logic/console/ConsoleSystem.java
Bump up nui dep version to next SNAPSHOT ( https://github.com/MovingBlocks/TeraNUI/pull/35)
Change opening console and chat from DOWN key event to UP key event - prevent typing keybind key to chat/console.
1.a. merge and publish https://github.com/MovingBlocks/TeraNUI/pull/35
or
1.b. clone TeraNUI with PR#35.
2. Start game.
3. Open console or chat.
4. Check that you have clear UIText (commit `fix typing bindkey as first char in chat or console )
5. type keys, which haves bindings to moving keys (`WASD` on `QWERTY` Layout)
6. Check that you not moved, while typing at step 5.
=> fix: moving on typing, typing keybind in console/chat

facades/PC/build.gradle.kts
Reworking `classpath`, `args`, `jvmargs` handlers for game run tasks.
Extract common part of game run tasks.
Also direct dependencies in classpath on running now.
Fixes #4238
1. Run every run game task. works like should. (except profile on liberica JDK 11)
2. Run  run game task on MacOS
=> Extract  "run game" task configurations

engine/src/main/java/org/terasology/rendering/gltf/GLTFAnimationFormat.java
```java
public void updateFrame(float time, MeshAnimationFrame frame) {
int upperFrame = 0;
while (upperFrame < times.size() && times.get(upperFrame) < time) {
upperFrame++;
}
```
(https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/rendering/gltf/GLTFAnimationFormat.java#L212-L216)
In `updateFrame`, `upperFrame` is initialized to 0 and then increased if was smaller than the size of the `TFloatList times` and some other condition. This can lead to `upperFrame == times.size()`.
In the case where I faced the index out of bounds error, `TFloatList times` was the same size as `List<T> data`. This means, `upperFrame` could became equal to `data.size()` as well.
Now `lowerFrame` is set to the maximum of 0 and `upperFrame - 1` in …
=> fix: index out of bounds in `GLTFAnimationFormat`

engine/src/main/java/org/terasology/rendering/backdrop/Skysphere.java
I'm not sure whether this is just fixing symptoms or the actual root cause... Any input is appreciated. I played around with different values, see screenshot comparison below. The overall brightness is heavily influenced by the combination of video settings, so it's hard to tell whether we can find a one-size-fits-all value.
I also found that we decide on whether to use the "night exposure" values in CoreRendering based on whether the daylight value is 0. This might need adjustment with this change (as daylight will never be 0 afterwards).
=> feat(rendering): Adjust minimal amount of daylight at night

engine/src/main/java/org/terasology/input/InputSystem.java
I think the only usage of that API wrapper method (in Omega) is in Dialogs where it is used to get the associated bind for an action to display it as a hint to the user.
https://github.com/Terasology/Dialogs/blob/5a0073966afc66f18bc1d7220c7b49c8c053d9c2/src/main/java/org/terasology/dialogs/DialogSystem.java#L190
This was throwing a NPE for a while, resulting in the hint not showing up. This PR fixes that.
=> fix: InputSystem#getInputsForBindButton was throwing NPE

engine/src/main/java/org/terasology/network/PingService.java, engine/src/main/java/org/terasology/network/ServerInfoService.java
fix server info request and ping error handling (restore error showing when requiests  server info).
Fix over netty4 migration.
I used blocking request for server info request. change it on async and add handler on connection stage failing.
1. Open Terasology.
2. Go to `Join Server`
3. Click on several disabled servers
4. server info should render as red text: `Connection failed` (restoring previous behavior)
=> fix(network): fix server info request and ping error handling

engine/src/main/java/org/terasology/config/PlayerConfig.java
It felt a bit weird to be able to jump 2 blocks high, but barely being able to look over one block o.O Increased the eye height a bit to adjust for that.
=> feat(player): increase player's eye height 0.7 >>> 0.85

engine/src/main/java/org/terasology/physics/bullet/BulletPhysics.java
It looks like the item pickup radius got broken again in https://github.com/MovingBlocks/Terasology/pull/4139, probably due to incorrect merging. @pollend was that change deliberate? There are some potential issues involving this collider being used for things other than item pickup, but character movement, and world collision, are all based on a separate collider, so it should at least not affect that.
=> fix: item pickup radius (again)

engine/src/main/java/org/terasology/logic/characters/CharacterMovementSystemUtility.java, engine/src/main/java/org/terasology/world/chunks/pipeline/PositionFuture.java
**Problem:** Killing a mob in a multi-player game as connected client lead to a NPE in the `CharacterMovementSystemUtility`. I suspect this is because we try to interpolate the movement of the mob even though we already removed components (like the `CharacterMovementComponent`) from the entity. 
**Solution:** Make use of `updateComponent` functional API to only update the respective component if it is present. Otherwise, nothing will happen. 
**Question:** This (maybe) only fixes a symptom. The interpolation is called for entries in a field called `playerStates`, but those actually contain NPC entities such as the deer or sheep. Basically, all entities with `CharacterMovementComponent`, `LocationComponent`, and `AliveCharacterComponent` are considered for movement prediction. Is this …
=> fix: prevent NPE during movement interpolation

engine/src/main/java/org/terasology/utilities/procedural/BrownianNoise.java
BrownianNoise works by adding several scaled copies of the same base noise function together. Generally this works well, but it can lead to weird features at the origin, where all of the copies are aligned (the value at the origin in always 0, and it tends to have a very large gradient there). This PR fixes that, by shifting each of the copies by random amounts relative to each other. This has the effect that the spawn point is no longer always on a biome boundary and surrounded by cliffs.
I've gotten so used to the usual surrounded-by-cliffs style of spawn plateau that I don't usually notice how weird it is, but when I tested this PR, this is the spawn plateau I got:
=> feat: Remove weird features near the origin from BrownianNoise

.idea/discord.xml, engine-tests/src/test/java/org/terasology/math/BlockRegionTest.java, engine-tests/src/test/java/org/terasology/world/block/BlockRegionIterableTest.java, engine-tests/src/test/java/org/terasology/world/chunks/localChunkProvider/LocalChunkProviderTest.java, engine/src/main/java/org/terasology/persistence/typeHandling/mathTypes/BlockRegionTypeHandler.java, engine/src/main/java/org/terasology/world/block/BlockRegion.java, engine/src/main/java/org/terasology/world/block/BlockRegionIterable.java, engine/src/main/java/org/terasology/world/block/BlockRegions.java, engine/src/main/java/org/terasology/world/block/regions/BlockRegionComponent.java, engine/src/main/java/org/terasology/world/block/regions/BlockRegionSystem.java, engine/src/main/java/org/terasology/world/chunks/localChunkProvider/LocalChunkProvider.java, engine/src/main/java/org/terasology/world/chunks/remoteChunkProvider/RemoteChunkProvider.java, engine/src/main/java/org/terasology/world/propagation/StandardBatchPropagator.java
- add `createFromMinAndMax` and `createFromCenterAndExtents` helpers
- deprecate BlockRegion constructors from min and max in favor of new helpers
- add tests for `BlockRegion` and `BlockRegionIterable` 
- add helper methods to create iterables for BlockRegions
- https://github.com/Terasology/DynamicCities/pull/73
- https://github.com/Terasology/ClimateConditions/pull/38
- https://github.com/Terasology/StructureTemplates/pull/47
- https://github.com/Terasology/CombatSystem/pull/61
- https://github.com/Terasology/MetalRenegades/pull/117
---
Co-authored-by: Tobias Nett <skaldarnar@googlemail.com>
Co-authored-by: Michael Pollind <mpollind@gmail.com>
=> feat(BlockRegion): add BlockRegion helpers

engine/src/main/java/org/terasology/entitySystem/event/internal/EventSystemImpl.java, engine/src/main/java/org/terasology/logic/characters/KinematicCharacterMover.java, engine/src/main/java/org/terasology/logic/nameTags/PlayerNameTagSystem.java, engine/src/main/java/org/terasology/logic/players/ThirdPersonRemoteClientSystem.java, engine/src/main/java/org/terasology/world/chunks/localChunkProvider/LocalChunkProvider.java, facades/PC/src/main/resources/logback.xml
**Problem:** There was a lot of noise in our logs, especially on DEBUG level which is used by IntelliJ as default. This was particularly spamming from `update()` methods.
**Solutions:** Remove those debug logs, which often look like `println`-debug statements to keep track of where the execution flow goes without the need to actually step through everything in the debugger.
=> chore: remove some of the most noisy debug logs

engine/src/main/java/org/terasology/network/internal/ClientConnectionHandler.java, engine/src/main/java/org/terasology/physics/bullet/BulletPhysics.java, engine/src/main/java/org/terasology/world/chunks/pipeline/ChunkProcessingPipeline.java
Free resources for MTE.
related to https://github.com/Terasology/ModuleTestingEnvironment/issues/30
dispose physic's natives(holds TerasologyEngine)
stop threads(holds TerasologyEngine)
1. Run MTE test with client connection in loop
2. measure memory usage.
=> fix: dispose physic's natives, stop threads.

engine/src/main/java/org/terasology/world/block/BlockRegion.java
this center method was only calculating the extent of a region. this produced off center structures in MetalRenegades.
=> fix(BlockRegion): correct center calculation for BlockRegion

subsystems/TypeHandlerLibrary/build.gradle.kts
Fix single module building in Jenkins.
1. invoke `gradle publish`
2. check that you have artifact `org.terasology:TypeHandlerLibrary:<engine version>` in repo
=> ci(subsystems): Make TypeHandlerLibrary publishable with engine's version

engine/src/main/java/org/terasology/logic/players/CameraClientSystem.java
This fixes the bug where after running purgeWorld, you can't look up or down.
=> fix: don't delete camera during purgeWorld command

engine/src/main/java/org/terasology/physics/bullet/shapes/BulletBoxShape.java
box colliders had negative extent so they never worked correctly when certain objects were placed in the world. this can be verified with the door in the default template. It should be possible to walk into / open and close the door where it used to be an object missing all collision.
=> add missing absolute value for box collider extent

config/gradle/publish.gradle, engine-tests/build.gradle
From [#logistics](https://discord.com/channels/270264625419911192/633681387995660303/790717924422844466):
> oddly project.version is not working in publish.gradle for the engine (returns "unspecified")
This PR moves that code in to an `afterEvaluate` block to give it a chance to load the version first. This is the solution offered by the [gradle manual](https://docs.gradle.org/6.7.1/userguide/publishing_maven.html#publishing_maven:deferred_configuration).
`gradlew :engine:publish` is the task,  
the condition is when a `publishRepo` gradle property is **not** set.
[fixme: add more details about how to test and what to look for]
=> fix(publish): don't try to figure out the repository to publish to until after the version is set

build.gradle, config/gradle/common.gradle
Gradle's user guide [discourages the use of mavenLocal](https://docs.gradle.org/6.7.1/userguide/declaring_repositories.html#sec:case-for-maven-local). The section heading is “The case for mavenLocal()” but the text is thoroughly _against_ its use whenever possible.
I believe this project is now working sufficiently well with [included builds](https://github.com/MovingBlocks/Terasology/blob/5cfb0c66f5457d16cffe1246a697314ccc1cd328/libs/subprojects.settings.gradle#L4) that it no longer requires mavenLocal —  
but I hope for input on that, because I don't know everyone's workflows.
Removes `mavenLocal` as a place to check for dependencies.
Test your workflows that depend on in-development versions of libraries, e.g. TeraNUI or gestalt.
=> chore(gradle): remove mavenLocal from project repositories

facades/PC/build.gradle.kts
Love tiny PRs? This is the PR for you!
https://github.com/MovingBlocks/Terasology/commit/8bb63016b9bdc0b47808bcddd9735a7272c9912a improved on the run execs in Gradle to avoid a bunch of duplication, but accidentally switched `-homedir` to `-homeDir` which meant the engine couldn't recognize the argument and always defaulted your game data dir to system default.
Coincidentally this is superseded by #4157 changing all the args around anyway, but this fixes it minimally for right now.
To test: Run the game via Gradle, such as with `gradlew game` and make sure the `-homedir` argument was accepted (top of game logging, or make sure you have a save game then go to new game and check that the save path is inside your workspace)
=> fix: casing fix for homedir arg from Gradle

config/gradle/common.gradle
This removes unnecessary repositories from common.gradle  
and changes the configuration so gradle does not look in jcenter for any `org.terasology` dependency.
I was using `gradlew :modules:JoshariasSurvival:clean game --refresh-dependencies --scan` (with JoshariasSurvival as the _only_ module source checked out in `modules/`, so gradle has to get all the dependencies from remote instead of local subprojects).
It's not _quite_ sufficient as a test of how long things take with an empty cache, because gradle has cached some stuff somewhere that is not reset by `--refresh-dependencies`.
One place where the difference is clear is on the build scan under the Performance / Network Activity tab. Before this change, there were a lot more requests to jcenter for all the modules that aren't there, …
=> build: save build time by not checking jcenter for terasology dependencies

engine/src/main/java/org/terasology/world/chunks/localChunkProvider/LocalChunkProvider.java, engine/src/main/java/org/terasology/world/chunks/remoteChunkProvider/RemoteChunkProvider.java
Because the `OnChunkLoaded` event is created in world generation threads, rather than the main thread, it usually executes after `processReadyChunk` is finished, but occasionally it doesn't. The chunk only becomes readable (i.e. `getChunk` and `getBlock` will start working inside its bounds) when `chunk.markReady` is called, which used to happen at the end of `processReadyChunk`. This meant that occasionally, the event handler for `OnChunkLoaded` would not actually be able to read that chunk. This led to issues like that `NullPointerException` in `VoxelWorldSystem` and some chunks being invisible, both of which should now be fixed. (A similar issue sometimes still happens sometimes when a world is unloaded: a chunk's `OnChunkLoaded` event may not run until after the chunk has been …
=> Mark new chunks ready before triggering OnChunkLoaded events.

engine/src/main/java/org/terasology/world/block/family/MultiConnectFamily.java
pass attachmentSide to getBlockForPlacement for MultiConnectFamily.
Fixes https://github.com/MovingBlocks/Terasology/issues/4319
=> fix(#4319): add attchmentSide to getBlockForPlacement

engine/src/main/java/org/terasology/world/block/items/BlockItemSystem.java, engine/src/main/java/org/terasology/world/block/items/OnBlockItemPlaced.java
Migrates the event handler for OnBlockItemPlaced. I migrated the whole event since the only changes would need to be made in FlowingLiquid, GooeyDefence, JS and Signalling.
=> feat(JOML): migrate OnBlockItemPlaced

engine/src/main/java/org/terasology/rendering/logic/LightComponent.java
here is a straightforward migration of LightComponent. the only reference is in CoreRendering and the properties line up from Termath so there are no additional changes that would need to be made in: https://github.com/Terasology/CoreRendering
=> feat(JOML): migrate LightComponent

engine-tests/src/main/java/org/terasology/MapWorldProvider.java, engine-tests/src/main/java/org/terasology/testUtil/WorldProviderCoreStub.java, engine-tests/src/test/java/org/terasology/world/propagation/BetweenChunkPropagationTest.java, engine/src/main/java/org/terasology/world/chunks/ChunkProvider.java, engine/src/main/java/org/terasology/world/chunks/Chunks.java, engine/src/main/java/org/terasology/world/chunks/localChunkProvider/LocalChunkProvider.java, engine/src/main/java/org/terasology/world/chunks/remoteChunkProvider/RemoteChunkProvider.java, engine/src/main/java/org/terasology/world/internal/AbstractWorldProviderDecorator.java, engine/src/main/java/org/terasology/world/internal/WorldProviderCore.java, engine/src/main/java/org/terasology/world/internal/WorldProviderCoreImpl.java
I migrated the logic for isRegionRelevant. would this be ideal or would we just want to migrate it all together then bother with the intermediary step.
=> feat(JOML): migrate WorldProviderCore#isBlockRelevant

engine/src/main/java/org/terasology/logic/behavior/BehaviorSystem.java, facades/PC/build.gradle.kts
Part of some minor observations from recent testing.
* Guards against NPE in some behavior tree code, briefly discussed with @casals as a case where some state might get lost. Ideally we'd also hook up a special monitor for this via telemetry to get more intel about when it happens, how
* Increases default memory when running from Gradle - flying around in settings like Metal Renegades does not appreciate being memory starved. Goes beyond the 32-bit JVM capacity, but we honestly could have probably done that years ago, playing the game on 32-bit is one thing, developing it a whole other thing.
=> chore: Couple minor tweaks - logic hardening and memory

engine/src/main/java/org/terasology/math/Direction.java
=> feat(JOML): migrate Direction

engine-tests/src/test/java/org/terasology/world/chunks/localChunkProvider/LocalChunkProviderTest.java, engine-tests/src/test/java/org/terasology/world/propagation/BetweenChunkPropagationTest.java, engine/src/main/java/org/terasology/engine/modes/loadProcesses/AwaitCharacterSpawn.java, engine/src/main/java/org/terasology/engine/subsystem/headless/renderer/HeadlessWorldRenderer.java, engine/src/main/java/org/terasology/rendering/world/RenderableWorldImpl.java, engine/src/main/java/org/terasology/world/chunks/ChunkProvider.java, engine/src/main/java/org/terasology/world/chunks/localChunkProvider/LocalChunkProvider.java, engine/src/main/java/org/terasology/world/chunks/remoteChunkProvider/RemoteChunkProvider.java
The final stage of chunk loading, where the chunk is actually added to the ChunkProvider, its entities are created, and the OnChunkLoad event runs, needs to happen on the main thread in order to avoid concurrency issues, because it affects data that other systems running on the main thread have access to. This reverts a little bit of #4140, which moved this onto the chunk loading threads in the first place.
I have actually seen some specific issues that this fixes (e.g. OnChunkLoad event handlers running after that chunk has already been unloaded), but because the relevant code (`processReadyChunk`) could overlap with anything depending on the exact timing, the problem could potentially manifest in many different ways.
=> fix: Move the final stage of chunk loading back to the main thread.

engine/src/main/java/org/terasology/persistence/typeHandling/gson/GsonTypeHandlerAdapter.java
these interfaces don't use `serializationContext` so I just dropped them from deserilization and serilization and use the methods directly. 
```
this.serializer = (src, typeOfSrc, context) ->
((GsonPersistedData) typeHandler.serialize(src, new GsonPersistedDataSerializer()))
.getElement();
this.deserializer = (json, typeOfT, context) ->
typeHandler.deserializeOrNull(new GsonPersistedData(json));
```
=> fix: remove reflection for gson deserilization in GsonTypeHandlerAdapter

engine/src/main/java/org/terasology/logic/ai/HierarchicalAIComponent.java, engine/src/main/java/org/terasology/logic/ai/HierarchicalAISystem.java, engine/src/main/java/org/terasology/logic/ai/SimpleAIComponent.java, engine/src/main/java/org/terasology/logic/ai/SimpleAISystem.java
This is seemingly a stand-alone system in the engine. I could not find any usages of the components anywhere else, Omega still compiles just fine...
=> feat(JOML): migrate `logic.ai.*`

engine/src/main/java/org/terasology/world/chunks/internal/ChunkRelevanceRegion.java
Only return each position from the iterator once, rather than repeatedly returning it, possibly forever, or possibly busy-looping until the chunk is complete. Fix for #4385.
=> Fix: Make the chunk relevance region iterator actually terminate

engine/src/main/java/org/terasology/world/internal/ChunkViewCoreImpl.java
Avoid using `chunkFilterSize` as a `dest` argument, and thereby avoid messing up the `ChunkView` when `getExtraData` is called.
This fixes the bug where chunks containing liquids would look horribly messed up if FlowingLiquids was enabled.
=> Add the dest argument to Chunks.toRelative in ChunkViewCoreImpl

engine/src/main/java/org/terasology/rendering/assets/texture/BasicTextureRegion.java, engine/src/main/java/org/terasology/world/block/BlockAppearance.java, engine/src/main/java/org/terasology/world/block/internal/BlockBuilder.java
Tested with Metal Renegades which should use all modules affected by this PR.
All branches named `joml/migrate-BlockAppearance`.
- Terasology/Behaviors#60
- Terasology/Health#60
- Terasology/Minimap#21
=> feat(joml): migrate BlockAppearance

engine/src/main/java/org/terasology/world/internal/WorldProviderCoreImpl.java
This fixes the bug, introduced in #4408, where calls to `WorldProvider.getBlock` in the top half of a chunk would return the block that's actually in the corresponding position in the bottom half of the chunk. This manifested as various symptoms, e.g. it was often not possible to place blocks in the upper half of a chunk, you could swim 32 blocks above the ocean, and FlowingLiquids would get confused and make the ocean pour down from the sky above it.
=> Fix the upper half of each chunk behaving strangely.

engine/src/main/java/org/terasology/world/chunks/Chunks.java
I saw in a couple of places that we need to either write very verbose code or allocate more vectors than we actually need to.
For instance, to turn the location from a component into the corresponding chunk position, you currently can either do
```java
// verbose, but comprehensible. makes an unneccessary vector allocation
Vector3i pos = locationComponent.getLocation(new Vector3i());
Vector3i chunkPos = Chunks.toChunkPos(pos, new Vector3i());
```
or 
```java
// imho less comprehensible, only uses one vector allocation
Vector3i chunkPos = locationComponent.getLocation(new Vector3i());
Chunks.toChunkPos(chunkPos, chunkPos);
```
With this PR, new APIs for in-place mutation of the given argument are added. In particular, this allows to solve this in one line:
```java
Vector3i chunkPos = …
```
=> feat(world): add APIs to compute `Chunks` values in-place

Jenkinsfile, engine/build.gradle, engine/src/main/java/org/terasology/version/TerasologyVersion.java, facades/PC/build.gradle.kts, templates/VERSION, templates/version.txt
Newer replacement for #4231. Updates the engine repo just a little to prepare for a move to the new Jenkins which uses pipeline jobs, folders, and other fun things. Also includes the versioning updates noted in the older PR - I fully acknowledge that's a temporary state that'll likely change again, but I have scoped this down to where it is primarily just the migration plus a bit of assorted cleanup / clarifications. Hope that's OK until we come up with bigger and better methods for versioning and packaging.
See #4231 - primarily tested in Jenkins, but won't show full "live" results until after it is merged. See for instance http://jenkins.terasology.io/teraorg/job/Nanoware/job/Omega/job/develop/ to see a new school Omega zip having been packaged. It runs and shows the new version label …
=> Migrate Omega package from old Jenkins to new, with some minor cleanup / label improvements

engine/src/main/java/org/terasology/rendering/world/RenderableWorldImpl.java, engine/src/main/java/org/terasology/world/chunks/localChunkProvider/LocalChunkProvider.java, engine/src/main/java/org/terasology/world/chunks/remoteChunkProvider/RemoteChunkProvider.java, engine/src/main/java/org/terasology/world/internal/ChunkViewCoreImpl.java
The mesh of each chunk may depend on the contents of the adjacent chunks, for example, the lighting of a block face that is on the edge of a chunk depends on the light value in the adjacent chunk. Before this PR, chunks would only be rendered if the adjacent chunk was loaded, and the mesh would be perfect straight away. With this PR, every chunk is rendered as soon as it loads, as if adjacent unloaded chunks were full of dark air, then if the adjacent chunk is loaded, the mesh is replaced to take into account the new information.
This has several effects:
- Chunks generally become visible faster. This is particularly noticable when first loading a world when world generation is slow, as the first chunk that's created (generally the one containing the player) can render as soon as it's …
=> Render even chunks that are next to unloaded chunks.

engine/src/main/java/org/terasology/world/chunks/deflate/TeraStandardDeflator.java
This PR saves around 20% ram memory for chunks at initial stage (fresh created world without changes).
> Tested at same world with view distance 13x7x13(1183 chunks). 
> 257MB before versus 200MB after.
(P.S. 4bit TeraArrays not used anywhere. ideally use it for lightdata and sunlightdata, but it consume 2xTime for write/read versus 8bit)
Commit affects RAM usage for fields:
* `ChunkImpl#lighdata` 
* `ChunkImpl#sunlightData` 
* `ChunkImpl#blockData` 
* `ChunkImpl#extraBlockData` 
Create world with and without PR. compare ram usage by ChunkImpl and arrays.
Really this PR don't should affects any functionality, because functionality of sparse arrays not changed. only deflating.
=> perf(world): implement `deflate` for sparse TeraArray (8/16 bit)

engine/src/main/java/org/terasology/world/chunks/localChunkProvider/RelevanceSystem.java
Fixes chunk unloading, when chunk is not relevant. (logical)
Relevance region began to expand by 1,1,1 after joml migration. fixed.
1. Run over world, check chunk count.
=> fix(joml): Fix always growing relevance region

engine-tests/src/test/java/org/terasology/world/generation/facets/BaseBooleanFacetTest.java, engine-tests/src/test/java/org/terasology/world/generation/facets/BaseObjectFacetTest.java, engine/src/main/java/org/terasology/logic/selection/ApplyBlockSelectionEvent.java, engine/src/main/java/org/terasology/logic/selection/MovableSelectionEndEvent.java, engine/src/main/java/org/terasology/world/chunks/CoreChunk.java, engine/src/main/java/org/terasology/world/chunks/internal/ChunkRelevanceRegion.java, engine/src/main/java/org/terasology/world/generation/RegionImpl.java, engine/src/main/java/org/terasology/world/generation/World.java, engine/src/main/java/org/terasology/world/generation/WorldImpl.java
If I saw it correctly, there is not public API left where you must use `Region3i` with the engine anymore (we still have some deprecated APIs but offer the non-deprecated variant with `BlockRegion` in that case). :partying_face: 
=> chore(JOML): remove unused imports (Region3i) and update copyright

engine-tests/build.gradle, engine-tests/src/test/java/org/terasology/logic/location/LocationComponentTest.java, engine-tests/src/test/java/org/terasology/math/RotationTest.java, engine-tests/src/test/java/org/terasology/persistence/serializers/VectorTypeSerializerTest.java, engine-tests/src/test/java/org/terasology/persistence/typeHandling/event/VectorEventSerializer.java
this migrates the assertion logic from these TeraMath methods to the methods provided by joml-ext. 
we need to include this PR: https://github.com/MovingBlocks/joml-ext/pull/13
=> feat(JOML): migrate assertions with joml-ext

engine/build.gradle
These haven't been in use in core recently.
Removed in commit db490eae
=> chore(build): remove unused asm-related dependencies

engine/src/main/java/org/terasology/world/block/family/AttachedToSurfaceFamily.java, engine/src/main/java/org/terasology/world/block/family/BlockFamily.java, engine/src/main/java/org/terasology/world/block/family/CeilingSupportingHorizontalFamily.java, engine/src/main/java/org/terasology/world/block/family/FreeformFamily.java, engine/src/main/java/org/terasology/world/block/family/HorizontalFamily.java, engine/src/main/java/org/terasology/world/block/family/MultiConnectFamily.java, engine/src/main/java/org/terasology/world/block/family/SymmetricFamily.java, engine/src/main/java/org/terasology/world/block/family/UpdatesWithNeighboursFamily.java
The removes the deprecated method `BlockFamily#getBlockForPlacement` taking individual arguments in favor of fully migrating to `BlockPlacementData`.
This allows for all BlockFamilies to become JOML-free.
=> feat(JOML): remove deprecated API in favor of JOML for BlockFamily

engine/src/main/java/org/terasology/entitySystem/entity/internal/PojoEntityPool.java, engine/src/main/java/org/terasology/entitySystem/sectors/SectorUtil.java, engine/src/main/java/org/terasology/logic/inventory/events/DropItemEvent.java, engine/src/main/java/org/terasology/logic/location/Location.java, engine/src/main/java/org/terasology/logic/location/LocationComponent.java, engine/src/main/java/org/terasology/logic/players/LocalPlayer.java, engine/src/main/java/org/terasology/world/block/BlockComponent.java, engine/src/main/java/org/terasology/world/internal/EntityAwareWorldProvider.java
* feat(JOML): migrate `LocationComponent#getWorldPosition`
* feat(JOML): migrate `LocationComponent` constructor
* feat(JOML): fully migrate `Location
* feat(JOML): migrate deprecated `LocationComponent#getWorldPosition/Rotation/Direction`
This removes all `@Depreacted` methods using TeraMath from `LocationComponent` and migrates `Location` system to JOML.
There is still direct access to the `math.geom` members of `LocationComponent` (to be migrated in a follow-up PR).
=> feat(JOML): migrate `Location` system and (parts of) `LocationComponent` 

gradle/wrapper/gradle-wrapper.properties
From the release notes:
> fixes large performance regression when file system watching is enabled on macOs and Windows
=> build: patch upgrade to gradle 6.8.2

buildSrc/src/main/kotlin/org/terasology/gradology/exec.kt
Adds a gradle command line option to all RunTerasology tasks to set the maximum java heap size for the process.
e.g.
```
./gradlew game --max-heap 8G
```
appears in
```
./gradlew help --task game
```
=> build(PC): add gradle command-line option for max heap size

buildSrc/src/main/kotlin/terasology-module.gradle.kts
This adds slf4j to the runtime of tests and allows MTE to do logback things.
Required for https://github.com/Terasology/ModuleTestingEnvironment/pull/37
I expect this PR is low risk, though it does raise the notion that we should probably package MTE differently.
=> build(MTE): allow MTE to configure the logger.

Jenkinsfile
part of what we need to fix the lack of a versionInfo.properties artifact in the place Launcher looks.
this might be only half of it and we need to do a similar thing with Index/Jenkinsfile: https://github.com/Terasology/Index/pull/12
=> CI: fix path to versionInfo.properties

engine/src/main/java/org/terasology/rendering/ShaderManagerLwjgl.java, engine/src/main/resources/assets/shaders/initialPost_frag.glsl, engine/src/main/resources/assets/shaders/vignette_frag.glsl, engine/src/main/resources/assets/shaders/vignette_vert.glsl
This adds the vignette shader from this PR https://github.com/MovingBlocks/Terasology/pull/3604 and introduces the changes into CoreRendering: https://github.com/Terasology/CoreRendering/pull/32. I omitted the changes for VR and I think this will have to be revisited at a later point to resolve these changes.
=> feat: move vignette to seperate shader

engine/src/main/java/org/terasology/world/chunks/remoteChunkProvider/RemoteChunkProvider.java
The remote chunk provider was calculating a negative index. 
Fixes https://github.com/MovingBlocks/Terasology/issues/4505
=> fix: correct index for world view

buildSrc/src/main/kotlin/org/terasology/gradology/ModuleInfoException.kt, buildSrc/src/main/kotlin/terasology-module.gradle.kts
Straightforward refactor. If you want to test, change a `module.txt` to have a syntax error and see how it's reported when gradle next tries to configure it.
e.g. `gradlew jar` but almost any gradle command will do, including `gradlew tasks`.
=> build: factor out ModuleInfoException from terasology-module

engine/src/main/java/org/terasology/rendering/cameras/PerspectiveCamera.java
Noticed a black something in the center of my screen after setting LoD from 10 to 0. Seemed to be on the "back plane" as it disappeared behind loaded chunks. When setting LoD to 1, it didn't show anymore.
@PS-Soundwave assumed that the far clipping plane might be pulled in too far on lowest LoD and suggested this quickfix. Turned out fine, although there seems to be a larger issue, that @PS-Soundwave plans to write up (please also link it here) and investigate :+1: 
Co-authored-by: Soundwave <PS-Soundwave@users.noreply.github.com>
=> fix(rendering): clipping plane on LoD 0

engine/src/main/java/org/terasology/utilities/Jvm.java
@Cervator reported on Discord that "it may not work in some cases on Windows". 
The problematic part is in the new `Jvm` class, where
```java
String userHome = System.getenv("HOME"); 
```
eventually leads to an NPE "as my Win10 simply doesn't have an env var by that name". 
@Cervator suggested that Windows uses a different ENV variable `HOMEPATH` for this, 
and I remembered that there is also a [system property] `user.home` we could use here.
[system property]: https://docs.oracle.com/javase/7/docs/api/java/lang/System.html#getProperties()
=> fix: use system property instead of ENV to determine user home

buildSrc/src/main/kotlin/org/terasology/gradology/constants.kt, buildSrc/src/main/kotlin/org/terasology/gradology/module_build.kt, buildSrc/src/main/kotlin/terasology-module.gradle.kts
Another in this series of clean-up work for terasology-module.kts. No change in functionality expected, these changes are made in hopes that putting things in named methods makes the code less tangled and more readable.
=> build: move more implementation details about gestalt out of terasology-module

engine/src/main/java/org/terasology/engine/module/ModuleManager.java
Refactoring in anticipation of changes for gestalt v7.
I think these are all strict refactors, minimal testing required.
Open to feedback about where these methods should be ordered in the class file.
=> refactor(ModuleManager): factor initiliaztion code to multiple methods

engine/src/main/java/org/terasology/engine/bootstrap/EntitySystemSetupUtil.java, engine/src/main/java/org/terasology/engine/bootstrap/EnvironmentSwitchHandler.java, engine/src/main/java/org/terasology/world/generator/internal/WorldGeneratorManager.java
Adds errors more informative that NullPointerException to some places I ran in to when `environment.getModuleProviding` fails.
Seeing that it was the same method three times, now I wonder: do we ever use this method in a way where a null result is expected, or should the method throw a thing-not-found exception?
(cherry-picked from #4543)
=> chore: adding some null checks

Jenkinsfile
adjust for #4553
hopefully fixes http://jenkins.terasology.io/teraorg/job/Terasology/job/Modules/job/H/job/Health/job/develop/31/console
> * What went wrong:
> Included build '/home/jenkins/agent/workspace/asology_Modules_H_Health_develop/build-logic' does not exist.
=> ci: buildSrc moved to build-logic

engine-tests/build.gradle, engine/build.gradle
Changelog available here: https://github.com/google/gson/blob/master/CHANGELOG.md
I don't see any red flags there.
=> chore: upgrade gson to 2.8.6 from 2.6

build-logic/src/main/kotlin/terasology-module.gradle.kts, engine-tests/build.gradle, engine-tests/src/main/java/org/terasology/HeadlessEnvironment.java, engine-tests/src/main/java/org/terasology/ModuleEnvironmentTest.java, engine-tests/src/main/java/org/terasology/TerasologyTestingEnvironment.java, engine-tests/src/test/java/org/terasology/config/flexible/AutoConfigManagerTest.java, engine-tests/src/test/java/org/terasology/persistence/internal/StorageManagerTest.java
allows removing the dependency on Shrinkwrap.
How are there so many of these???
=> chore(engine-test): use a temp directory instead of a Shrinkwrap archive

engine-tests/src/test/java/org/terasology/rendering/nui/layers/mainMenu/savedGames/GameProviderTest.java, engine/build.gradle, engine/src/main/java/org/terasology/engine/bootstrap/EntitySystemSetupUtil.java, engine/src/main/java/org/terasology/engine/bootstrap/EnvironmentSwitchHandler.java, engine/src/main/java/org/terasology/entitySystem/entity/EntityBuilder.java, engine/src/main/java/org/terasology/entitySystem/event/internal/EventSystemImpl.java, engine/src/main/java/org/terasology/recording/EventSystemReplayImpl.java, facades/TeraEd/build.gradle
There was one function that had been deprecated long enough that it was no longer available and we had to switch to its new name.
A few other functions are no longer `@Beta` and we got to remove some "unstable api" tags from their call sites.
Seems to be working fine.
You can see info about how it resolved dependencies for guava in a [build scan](https://scans.gradle.com/s/gmljvt3zrah2i/dependencies?focusedDependency=WzIsMSw0MjEsWzIsMSxbNDIxXV1d&focusedDependencyView=versions&toggled=W1syXSxbMiwxXV0).
=> chore: upgrade guava to 30.1 from 23.0

engine/src/main/java/org/terasology/world/block/BlockComponent.java
Restrict visibility of field `block` on `BlockComponent` to `protected`. All access in Omega was already migrated to use the accessor instead.
Follow-up to #4528
=> chore!: limit API for BlockComponent (2/2)

facades/PC/src/main/java/org/terasology/engine/Terasology.java, subsystems/DiscordRPC/src/main/java/org/terasology/subsystem/discordrpc/DiscordRPCBuffer.java, subsystems/DiscordRPC/src/main/java/org/terasology/subsystem/discordrpc/DiscordRPCSubSystem.java, subsystems/DiscordRPC/src/main/java/org/terasology/subsystem/discordrpc/DiscordRPCSystem.java, subsystems/DiscordRPC/src/main/java/org/terasology/subsystem/discordrpc/DiscordRPCThread.java
to indicate it is not in engine itself.
following notes about package namespaces on #4560.
=> refactor: move DiscordRPC to org.terasology.subsystem

build-logic/src/main/kotlin/terasology-module.gradle.kts
Just some housekeeping.
I have not yet confirmed that we've removed the JUnit 4 imports from all the modules.
=> chore!: remove JUnit 4 from module dependencies

engine/src/main/java/org/terasology/engine/paths/PathManager.java
I've always found PathManager.updateDirs hard to read with it doing `createDirectories` every-other-line. I think applying `createDirectories` to a collection of all of them helps.
Not a strict-Refactor in that `getDeclaredFields` wasn't part of the logic previously.
This came out of #4543 when I thought I was going to be doing more PathManager manipulation, but it went in another direction.
Make sure all the various paths (for configs, saves, screenshots, etc) are created when you start the game.
=> refactor(PathManager): do all the `createDirectories` at once

build-logic/build.gradle.kts, build.gradle, engine-tests/build.gradle, engine/build.gradle, facades/PC/build.gradle.kts, facades/TeraEd/build.gradle, subsystems/TypeHandlerLibrary/build.gradle.kts
Using the org.terasology fork.
This is the version that gestalt-v7 uses. It might also work fine with our current one? Not too sure. Making a branch to see what CI thinks.
It's also possible that not all of these build files need the reflections dependency. e.g. do the facades make any direct use of it?
=> chore: upgrade reflections to 0.9.12-MB from 0.9.10

engine/src/main/java/org/terasology/rendering/world/RenderableWorldImpl.java, engine/src/main/java/org/terasology/world/chunks/LodChunk.java, engine/src/main/java/org/terasology/world/chunks/LodChunkProvider.java
This partially avoids the problem where, in between a chunk of one scale unloading and a chunk of a different scale replacing it, there would be just a gap in the terrain. This still happens in some cases, but if you're walking forwards, the issues will be behind you, so it's less noticable. Also, this PR slightly increases the amount of cacheing. If a LOD chunk ends up so close to the player that it needs to be replaced by higher-detail chunks, it is now hidden, rather than being discarded, in order to avoid having to re-calculate it once it becomes visible again.
It also rearranges the data in the `LodChunkProvider` a bit. Now the set of chunks at each level is stored separately, because there can be some overlap.
=> feat: Reduce the amount of gaps that appear while LOD chunks load

engine/src/main/java/org/terasology/physics/bullet/BulletPhysics.java, engine/src/main/java/org/terasology/physics/engine/PhysicsSystem.java
rigidbody triggers can get out of sync with rigid-bodies so its possible to push an object and have it change location while the trigger stays in a fixed location.
=> fix: trigger update for location component for physics update

build-logic/src/main/kotlin/terasology-module.gradle.kts
This should cause Jupiter to interrupt if any test case or setup method takes longer than four minutes to run.
=> test(modules): set default test case timeout to four minutes

engine/src/main/java/org/terasology/engine/module/ModuleManager.java
Should fix crash upon returning to menu from in-game state. I think the commit that initially caused this bug was 8ae06f0df3233422d397da23119b7bf97d8e99d4, but I have not tested the revision before.
=> ModuleManager: ensure engine module is always present in environment

engine/src/main/java/org/terasology/engine/core/paths/PathManager.java
Fixes #4587 
I've reached the point in the day when I'm wondering
_is it `==` or `.equals()`?_
_how does Java work?_
_what am I going to do about dinner?_
=> fix(PathManager): avoid calling Files method on paths that may not exist yet

engine/src/main/java/org/terasology/engine/logic/players/LocalPlayerSystem.java
Fixes a bug where the target indication box does not disappear when the player points at a block that is not within range.
- Open a world, hover over a block and rotate the camera upwards so no block is in range. The target indication box for the most recently targeted block should still be present.
- Apply the PR and repeat. The indication box should instead disappear.
=> fix(player): target box not disappearing when target is removed

engine/src/main/java/org/terasology/engine/utilities/procedural/SimplexNoise.java
File - https://github.com/mahela97/Terasology/blob/2aa5cbbf6b08bdf8826acc3b3f8517815df9eb5c/engine/src/main/java/org/terasology/engine/utilities/procedural/SimplexNoise.java
Line -73
Fix spelling errors in the documentation. The correct name of the variable is TILEABLE1DMAGICNUMBER.
- Before it was  ->
@see SimplexNoise#tileable1DMagicNumber
- Now ->
@see SimplexNoise#TILEABLE1DMAGICNUMBER
=> Fixing spelling error

engine/src/main/java/org/terasology/engine/input/lwjgl/LwjglMouseDevice.java
Fix the camera position resetting to look at the sky when the window is unfocused and then focused again. It just resets the mouse position whenever the window is focused, which also means that if you unfocus, move the mouse, and focus again, the camera doesn't move.
Start the game, move the camera, alt-tab to another window, then alt-tab back. The camera shouldn't move.
=> Don't move the camera when window is refocused

engine/src/main/java/org/terasology/engine/physics/bullet/BulletPhysics.java, engine/src/main/java/org/terasology/engine/world/block/items/BlockItemSystem.java
Disallows placing blocks inside the player. The restriction on placing blocks inside colliders was broken, so you could place blocks inside of yourself. This was mentioned briefly in the org meeting as a problem with jumping and placing blocks below you.
It turns out it was due to calling `btCollisionObject.getUserPointer()` to get a collider's attached entity, which returns a `long` which casts implicitly into an `Object` through `Long`, instead of getting `.userData`. The entity data is set with `.userData`, so it should be accessed the same way.
The margins of the bounding box had been messed up at some point as well, making it so you couldn't place blocks near the player, so I put them back to a reasonable position.
Try looking down and placing blocks inside your feet - it shouldn't …
=> fix: could place blocks inside the player

engine/src/main/java/org/terasology/engine/persistence/typeHandling/extensionTypes/UISkinTypeHandler.java, engine/src/main/java/org/terasology/engine/rendering/nui/skin/UISkinWithUrn.java
This pull request attempts to resolve https://github.com/MovingBlocks/Terasology/pull/4598#discussion_r600276900 through a work-around involving sub-classing `UISkin` into `UISkinWithUrn` in order to associate a `ResourceUrn` with it. When a `UISkin` is deserialised, then it is copied into a new `UISkinWithUrn` instance to associate it with the urn it was deserialised with.
I haven't found anywhere where the serialisation part of this code is used yet whilst debugging, so I am not sure how to test this.
This is based off #4598 and, if merged, should be merged into it.
=> TeraNUI 3.0 update: Implemented `UISkinTypeHandler.getAsString`

build-logic/build.gradle.kts, build-logic/src/main/kotlin/terasology-repositories.gradle.kts, build.gradle, config/groovy/common.groovy, templates/build.gradle, templates/facades.gradle
Replaces/removes `jcenter` usage. Fixes #4582, for the engine repo at least, both regular Gradle bits and a Groovy hit.
There are / will be a few more PRs for other repos, that's tracked decently in Trello even if the engine issue auto-closes with this PR getting merged.
Seems to work after local testing and http://jenkins.terasology.io/teraorg/job/Nanoware/job/Terasology/job/jCenter/
Also tested it in that develop branch to get a build harness to try with the Sample module, just in case: http://jenkins.terasology.io/teraorg/job/Nanoware/job/TerasologyModules/job/H/job/Sample/job/develop/6/
* Make sure the project can still be built from scratch using Gradle, with `--refresh-dependencies` thrown in or the local Gradle cache deleted
* Probably also try a super duper clean build of some …
=> logistics: Replace usage of jcenter (shutting down)

.idea/.gitignore
IntelliJ automatically generated these files in my workspace, but they are just empty or relate to local display preferences or something. I assume other people have been running into the same issue. Anyway, they aren't actually part of any changes I've made to the project and they don't need to be shared, but they show up as changed in git, which is annoying, so this should fix that.
There was an explicit comment previously about why dictionaries were not gitignored, even though it generates one per user, that the dictionaries are actually meant to be shared. There's some discussion about it at https://youtrack.jetbrains.com/issue/IDEA-208431, which seems to mostly be the Jetbrains staff arguing with their users that it's working as intended, and the users arguing that they don't want it …
=> Fix: Gitignore some more files that Intellij automatically generates.

Jenkinsfile, templates/gradle.properties
Changes the label for the engine build to a new one, defined presently using https://github.com/Cervator/pre-cached-jenkins-agent (that repo will likely move and might itself get a build in our Jenkins but - one step at a time) - see its repo readme for more technical details.
In short the goal is to use a Docker build of a custom Jenkins agent to pre-cache our main dependencies (at the moment for the TS engine, joml-ext, and modules), as well as pre-download the files needed for each Gradle wrapper version.
This PR also removes the already-default setting for the Gradle Daemon in case any attempts to experiment are desired elsewhere (has no effect normally). Loooong time since that actually mattered, the setting was changed to true by default years ago.
Label reasoning goes with a …
=> logistics: use new pre-cached builder image in Jenkins

build-logic/build.gradle.kts, build-logic/src/main/kotlin/org/terasology/gradology/module_build.kt, engine-tests/src/main/java/org/terasology/unittest/stubs/package-info.java
by avoiding use of gestalt.VersionRange
I'm not too worried about this PR needing review, but having build-related things seen by another set of eyes is always good.
the package-info in engine-test isn't really related, it's a stowaway
=> build(modules): improve matching of compatible versions in module deps

build-logic/src/main/kotlin/org/terasology/gradology/module_build.kt
**Problem:** In https://github.com/MovingBlocks/gestalt/pull/115 we changed the semantics of module version resolution to no longer include the SNAPSHOT to satisfy a non-snapshot `minVersion`. We also removed the `DependencyInfo::versionRange` accessor as it seemed to be no longer in use.
However, we missed that it's actually used in Terasology's module builds.
**Solution:** This PR unifies the way a String representation of the version range is derived from `DependencyInfo`, no longer accessing the now missing `versionRange()` method. 
In addition, it cleans up some of the build file (one corner-case handling became obsolete).
- build(module_build): use same DependencyInfo -> String logic for modules and engine
- build(module_build): remove corner case handling for min SNAPHSOT
=> build(module_build): use same DependencyInfo -> String logic for modules and engine

engine/src/main/java/org/terasology/engine/physics/bullet/BulletPhysics.java
The bulletBoxShape logic is a wrapper that provides the object and passes it back out but the implementation is already self contained within BulletPhyiscs. just easier to instantiate the objects as is then then introduce this extra level of indirection into the code.
=> chore: simplify logic for getShapeFor

engine/src/main/java/org/terasology/engine/math/Direction.java
The overhead of maintaining a map here is significantly more expensive then just using a simple switch case where the code is optimized with a jump table. I have the de-compiled bytecode to show how this ends up becoming an O(1) operation. The map in principle is also O(1) but you also incur the overhead of all the extra memory allocated on the heap + the additional fetching.  the code uses the ordinal value of the Direction and uses a jump table to jump to a statement and fetch the value. this is also O(1).
```
0: getstatic     #20                 // Field org/terasology/engine/math/Direction$1.$SwitchMap$org$terasology$engine$math$Direction:[I
3: aload_0
4: invokevirtual #21                 // Method ordinal:()I
7: iaload
8: tableswitch   { // 1 to 6
1: 56
2: 60
3: 64
4: 68
5: 52
6: 48 …
```
=> chore: replace map with switch for mapping direction

.github/labels.json, .github/release-drafter-config.yml, .github/workflows/release-draft.yml
As discussed in the org meeting we aim for consistency in the labels used on the engine and in modules. This PR adds the common configuration to `.github/labels.json`, which can be used to sync labels with https://github.com/Financial-Times/github-label-sync
We are at 32 labels now, which you can view on https://github.com/Nanoware/BrokenModule/labels. We removed a few labels as discussed in the meeting, but ended up adding two more back in: `Topic: AI` and `Topic: Stabilization`.
=> build(github): add common 'labels.json'; update release drafter config

engine/src/main/resources/org/terasology/engine/assets/shaders/post_frag.glsl
Tereasology won't run on certain nvidia cards because texture3d is deprecated.
ref: https://github.com/MovingBlocks/Terasology/pull/4636
```
13:20:41.276 [main] INFO  o.t.e.rendering.opengl.GLSLShader - Dumped Shader Path: logs/shaders/fragment_engine-post_0.glsl
13:20:41.277 [main] WARN  o.t.e.rendering.opengl.GLSLShader - Shader 'engine:post' failed to compile for features '[]'.
Shader Info: 
0(466) : error C7616: global function texture3D is removed after version 140
0(468) : warning C7533: global variable gl_FragData is deprecated after version 120
13:20:41.280 [main] INFO  o.t.e.rendering.opengl.GLSLShader - Dumped Shader Path: logs/shaders/fragment_engine-post_0.glsl
13:20:41.282 [main] ERROR o.t.engine.core.modes.StateLoading - Error while loading …
```
=> fix: texture3d is deprecated after 120 for nvidia cards

engine/src/main/java/org/terasology/engine/rendering/nui/internal/LwjglCanvasRenderer.java
Changing viewport scaling while in a world will cause the game UI to also scale. glViewport is a bit un-manged so the state of the viewport can get dirty between draw calls.  the viewport is update in WorldRenderImpl.java and in a couple other places in the engine. for StateInGame worldRender is called followed by the UI so the viewport is changed somewhere within worldRender. This doesn't seem like necessarily the correct fix to the problem though. 
There is some strange non-determinism with this that I can't quite pin down. DAG pipeline seems to be pretty non-deterministic with how its initialized and the order of things changes. can't quite pin down the behavior. 
I also managed to run into this issue: https://github.com/MovingBlocks/Terasology/issues/4542 also fiddling with screen …
=> fix: UI in game will get scaled with chaning "Resolution Scale" in world

engine/src/main/resources/org/terasology/engine/assets/shaders/post_frag.glsl
looks like I missed this when migrating post_frag. this can be verified by enabling film grain and verifying that the shader does not crash and the film grain shows up correctly in game.
=> fix: replace gl_TexCoord with v_uv0 for post_frag

Jenkinsfile, engine-tests/src/main/resources/org/terasology/unittest/module.txt, engine/src/main/resources/org/terasology/engine/engine-module.txt
This quick-fixes https://github.com/Terasology/Index/issues/16 and should let the launcher identify newer Omega zips from Jenkins, as the `versionInfo.properties` is again attached from a slightly updated path then retrieved during the Omega zip making.
Goes with https://github.com/Terasology/Index/pull/17
Additionally I think we're overdue for bumping the engine version to the next major, considering the next release will include the _major_ upgrade to Gestalt v7, that definitely deserves a bump.
If no objections we should also adjust the current milestone accordingly: https://github.com/MovingBlocks/Terasology/milestones/45/edit
And I think #4509 should probably be closed as complete as part of that? I know there are still leftovers floating around, but that core issue seems to deserve …
=> Fix for version file for launcher + increment to next major release

engine/src/main/resources/org/terasology/engine/assets/shaders/blur_frag.glsl, engine/src/main/resources/org/terasology/engine/assets/shaders/blur_vert.glsl
migrate blur shader for gls330
the blur is used for bloom, haze. 
required PR: https://github.com/Terasology/CoreRendering/pull/46
=> chore: migrate blur to glsl 330

engine-tests/build.gradle, engine-tests/src/main/java/org/terasology/unittest/stubs/StubWorldGenerator.java, engine-tests/src/test/java/org/terasology/engine/world/generator/internal/WorldGeneratorManagerTest.java, engine/build.gradle, engine/src/main/java/org/terasology/engine/world/generator/internal/WorldGeneratorManager.java
Fixes #4673.
This seems to have been not as wide in scope as I'd feared. The changes are specific to the UI in Advanced Game Setup.
Instead of changing the conditional to something other than `instanceof DirectoryFileSource`, I removed the conditional entirely. Not sure if the thing that led to the conditional is no longer relevant in gestalt-module v7. Letting it iterate over all modules instead of only some does not seem to have caused immediate problems.
Use a workspace that does have gameplay modes (e.g. CoreSampleGameplay) but does **not** have the world generators as source in `modules/`. (If you've checked them out, either remove them or temporary move them someplace else to hide them. gradle will fetch jars for dependent modules and put them in `cachedModules/`)
Start a new game …
=> fix: don't restrict world generators to a certain type of module source

engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/inputSettings/InputSettingsScreen.java
Relates to #4640 
Tested in `CoreGameplay` by removing `Inventory` as source module.
Inputs from `Inventory` module were working fine and showed up as expected in the input settings even with it being present as jar only.
=> fix: remove restriction of input bindings to source modules

engine/src/main/java/org/terasology/engine/core/TerasologyEngine.java
This makes the `@API` annotated classes and packages of the (non-)subsystem TypeHandlerLibrary visible to the APIScanner operating on the aggregated engine module.
Previously, TypeHandlerLibrary fell through the cracks of not being a real subsystem, but also not being part of the main engine source tree.
Fixes https://github.com/Terasology/Health/issues/85
=> fix(engine): explicitly register `TypeHandler.class` as representative for TypeHandlerLibrary

subsystems/DiscordRPC/src/main/java/org/terasology/subsystem/discordrpc/DiscordRPCSystem.java
This was causing a NPE exception (not sure whether on `player` or `delayManager`) on shutdown, causing the game process to stall and the game did not exit properly.
If either of `player` or `delayManager` are no longer present we just don't do anything about it and continue with the other shutdown actions.
Start the game a couple of times and close it via the (pause) menu. It should exit properly (at least it should not throw a NPE here).
=> fix(DiscordRPC): NPE on shutdown

engine/src/main/java/org/terasology/engine/core/PathManager.java, engine/src/main/java/org/terasology/engine/core/module/ModuleManager.java
This fixes the discovery of duplicate modules, such as
```
22:16:12.763 [main] ERROR o.t.g.module.TableModuleRegistry - Duplicate module CoreAdvancedAssets-1.3.0-SNAPSHOT discovered
22:16:12.763 [main] INFO  o.t.gestalt.module.ModulePathScanner - Discovered duplicate module: CoreAdvancedAssets-1.3.0-SNAPSHOT, skipping
```
This also makes sure to compare the paths with `.equals` instead of checking for reference equality with `==`.
Plus, small style change to make stream operations more readable in `ModuleManager`.
=> fix: ensure absolute path in PathManager

engine/src/main/java/org/terasology/engine/rendering/opengl/GLSLShader.java
I've run into this a few times when testing shaders. so these properties end up with empty strings and the shader end up in a misconfigured state so it fails when some property is called but missing from the shader. why does changing this order resolve the problem?
=> fix(rendering): correct order of initilization for GLSLShader

.gitignore, engine/src/main/java/org/terasology/engine/logic/console/commands/CoreCommands.java
Entity dumps are now save to files named like this:
```
2021-06-04T20:49:20.923507Z-entityDump.json
```
Previously, every entity dump was created as 'entityDump.txt'. When
working with multiple clients, or when dumping the entity state multiple
times, this required a manual rename each time.
Additionally, using the `.json` file ending helps with modern editors to
use correct syntax highlighting.
=> chore: change entity dump filename to '<timestamp>-entityDump.json'

engine/src/main/resources/org/terasology/engine/assets/shaders/lightGeometryPass_frag.glsl, engine/src/main/resources/org/terasology/engine/assets/shaders/lightGeometryPass_vert.glsl
the sphere problem is resolved with this pr: https://github.com/MovingBlocks/Terasology/pull/4744
when I made the changes for lightgeometry I forgot to pass the vertex information correctly over to the fragment shader.
https://github.com/MovingBlocks/Terasology/pull/4730
=> fix: resolve lightgeometry pass problems with nonfunctional point lights

README.markdown
If I understand this correctly, with the latest changes to rendering we now have a **minimum requirement** for a GPU supporting OpenGL 3.3. 
According to Wikipedia, the listed GPUs (both dedicated and integrated) should match that requirement.
=> doc: update minimal system requirements for OpenGL 3.3

engine/src/main/java/org/terasology/engine/rendering/AABBRenderer.java, engine/src/main/java/org/terasology/engine/rendering/assets/mesh/MeshData.java, engine/src/main/java/org/terasology/engine/rendering/assets/mesh/StandardMeshData.java, engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/AllocationType.java, engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/BufferedResource.java, engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/IndexResource.java, engine/src/main/java/org/terasology/engine/rendering/logic/RegionOutlineRenderer.java, engine/src/main/java/org/terasology/engine/rendering/opengl/OpenGLMesh.java, engine/src/main/java/org/terasology/engine/rendering/opengl/OpenGLMeshBase.java, engine/src/main/resources/org/terasology/engine/assets/shaders/lightGeometryPass_frag.glsl
Allocation type allows openGL to work out how the data is going to managed/allocated.  for RegionOutlineRenderer I just batch all the lines together and process everything in a single draw call. should work similar to immediate mode but should be significantly faster since it allows all the the lines to be drawn in a single batched call. 
I realized I also don't upsize the limit on the buffer because some operations will break the buffer it its accessed outside of the limit. umm, maybe we might want to rethink the API a bit but this is working pretty well. I was testing this with structured resources using the wall replacement thingy. maybe we should use the limit of the buffer instead of tracking a separate property for the size of the buffer :?
```
- open terminal thing
- give toolbox
- …
```
=> feature: migrate RegionOutlineRenderer and allow support to specify AllocationType

.idea/codeStyles/Project.xml, build.gradle
- build(idea): align IntelliJ line length with Checkstyle config
- build(codemetrics): use release v1.6.3 of TeraConfig
Consume changes from https://github.com/MovingBlocks/TeraConfig/pull/17
=> build: update TeraConfig to 1.6.3 and adjust IntelliJ settings

engine/src/main/java/org/terasology/engine/rendering/assets/font/FontMaterialProducer.java, engine/src/main/java/org/terasology/engine/rendering/nui/internal/LwjglCanvasRenderer.java, engine/src/main/java/org/terasology/engine/rendering/nui/internal/TerasologyCanvasImpl.java, engine/src/main/java/org/terasology/engine/rendering/world/selection/BlockSelectionRenderer.java, engine/src/main/resources/org/terasology/engine/assets/materials/ui/UIUnderline.mat, engine/src/main/resources/org/terasology/engine/assets/shaders/blockSelection.info, engine/src/main/resources/org/terasology/engine/assets/shaders/blockSelection_frag.glsl, engine/src/main/resources/org/terasology/engine/assets/shaders/block_frag.glsl, engine/src/main/resources/org/terasology/engine/assets/shaders/debug_frag.glsl, engine/src/main/resources/org/terasology/engine/assets/shaders/debug_vert.glsl, engine/src/main/resources/org/terasology/engine/assets/shaders/defaultTextured.info, engine/src/main/resources/org/terasology/engine/assets/shaders/default_frag.glsl, engine/src/main/resources/org/terasology/engine/assets/shaders/genericMeshMaterial_frag.glsl, engine/src/main/resources/org/terasology/engine/assets/shaders/particle_frag.glsl, engine/src/main/resources/org/terasology/engine/assets/shaders/particle_geom.glsl, engine/src/main/resources/org/terasology/engine/assets/shaders/particle_vert.glsl, engine/src/main/resources/org/terasology/engine/assets/shaders/simple_frag.glsl, engine/src/main/resources/org/terasology/engine/assets/shaders/simple_vert.glsl, engine/src/main/resources/org/terasology/engine/assets/shaders/ui/font.info, engine/src/main/resources/org/terasology/engine/assets/shaders/ui/font_frag.glsl, engine/src/main/resources/org/terasology/engine/assets/shaders/ui/uiLitMesh.info, engine/src/main/resources/org/terasology/engine/assets/shaders/ui/uiLitMesh_frag.glsl, engine/src/main/resources/org/terasology/engine/assets/shaders/ui/uitexture.info, engine/src/main/resources/org/terasology/engine/assets/shaders/ui/uitexture_frag.glsl
with some notes from this PR: https://github.com/MovingBlocks/Terasology/pull/4766. I made some adjustments that should hopefully get this to work on osx. 
- varying is removed from the standard
- texture2d is deprecated but I expected a warning but its been removed when compiling for osx
- gl_FragData is something I know was deprecated but threw warnings for NVIDIA and AMD but seems to be removed for osx. I use the correct api's which use layout.
=> bugfix(rendering): rework glsl for osx

engine/src/main/java/org/terasology/engine/rendering/opengl/GLSLShader.java
found out why we were not seeing any logs for mac when this PR was introduced (https://github.com/MovingBlocks/Terasology/pull/4750). looks like we're using another ARB to examine the shader but it fails because its unsupported for osx so the method does not return anything from that API call. wonder if we can test this on mac and see what those log errors are.
=> fix(rendering): remove unsupported ARB for opengl 2.0

engine/src/main/java/org/terasology/engine/world/chunks/pipeline/ChunkProcessingPipeline.java
remove some uncessary imports and replace a linkedlist with an iterable. this avoids a copy where we're moving a list to a linked list.
=> chore: minor cleanup for ChunkProcessingPipeline

engine/src/main/java/org/terasology/engine/rendering/opengl/GLSLMaterial.java
the hash code is used quite a bit in some pretty tight draw loops hashing a string plus the id is not a trivial cost.
=> chore: cache hashcode for uniform id

engine/src/main/java/org/terasology/engine/audio/system/AudioSystem.java
looks like when the player is invalid the game now crashes in audioSystem. for the initial frames I skip updating the Listener while the player is in an invalid state. 
https://github.com/MovingBlocks/Terasology/pull/4662
=> fix(audio): skip update when player is invalid

README.markdown
The link in the readme links to the old Jenkins site, which has been compromised. I replaced the link with the new Jenkins, using https
=> fix: use link to new Jenkins in readme

engine/src/main/java/org/terasology/engine/logic/players/LocalPlayer.java, engine/src/main/java/org/terasology/engine/rendering/nui/layers/ingame/metrics/DebugOverlay.java
Reverts MovingBlocks/Terasology#4662 as it seems to have broken Multiplayer
=> Revert "chore: remove finite check from LocalPlayer"

engine/src/main/java/org/terasology/engine/entitySystem/systems/RenderSystem.java, engine/src/main/java/org/terasology/engine/logic/players/LocalPlayerSystem.java, engine/src/main/java/org/terasology/engine/particles/rendering/SpriteParticleRenderer.java, engine/src/main/java/org/terasology/engine/rendering/logic/FloatingTextRenderer.java, engine/src/main/java/org/terasology/engine/rendering/logic/MeshRenderer.java, engine/src/main/java/org/terasology/engine/rendering/logic/RegionOutlineRenderer.java, engine/src/main/java/org/terasology/engine/rendering/logic/SkeletonRenderer.java, engine/src/main/java/org/terasology/engine/rendering/world/selection/BlockSelectionRenderSystem.java
I noticed a bit of clutter boilerplate code in a system implementing `RenderSystem` because of empty implementations of the method hooks for different rendering passes. With Java's default implementations for methods in interfaces we get rid of this boilerplate code by providing the empty implementation directly in the interface.
Start the game, everything should look and work the same as before.
Nothing.
=> chore: empty default implementation for RenderSystem interface

engine-tests/src/main/java/org/terasology/engine/testUtil/WithUnittestModule.java
Many current ModuleTestingEnvironment errors (#4757) come from a failure to find a module associated with some stub Components included with engine-tests.
This subsystem registers the `unittest` module containing those classes with the ModuleManager before the engine is initialized.
It's used on the MTE side by adding it to the list of subsystems given to the builder: https://github.com/Terasology/ModuleTestingEnvironment/pull/55
- Looks like we're on the right track. With this, MTE's own test suite goes from almost-all-failing to 19 pass, 3 failing.
- Very little code to implement and use.
- 💄🐷. I still feel this is a kludge that isn't exactly making things simpler. At least it using an existing extension point (subsystems), but it adds a new thing to the mix that isn't usually …
=> test: provide a subsystem to register the unittest module

build-logic/src/main/kotlin/terasology-module.gradle.kts, engine-tests/build.gradle, subsystems/TypeHandlerLibrary/build.gradle.kts
This [enables mockito to work on final types, enums, and final methods](https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#39). We already had this in engine-tests, this PR makes it available to module tests.
Also includes a minor upgrade to the version of mockito while we're at it.
PathManagerProvider does use Mockito to stub PathManager, a final class, which means this will be a requirement to use #4807 in practice.
=> test: mockito inline for modules

build-logic/src/main/kotlin/terasology-module.gradle.kts, engine-tests/src/main/java/org/terasology/engine/core/PathManagerProvider.java
We want to be able to run a module's MTE tests without it scanning `/modules/*` every test case, as explained in #4638. We made a `PathManagerProvider` extension to help with this, but when it comes to MTE, I haven't found a way for MTEExtension to declare a dependency on the PathManagerProvider extension.
As a work-around for not having a way to compose Jupiter extensions, MTEExtension wants to call some of these methods directly, which requires making them public.
To help guard against _non_-test code from using these, I've adjusted the dependencies in terasology-module so that a module's `implementation` does not have access to this code in `engine-tests`. That's only for use in `testImplementation`.
There is some risk of that change breaking existing module code, but modules really …
=> test: make parts of PathManagerProvider public for use by MTE

.idea/.gitignore, .idea/dictionaries/kevint.xml, .idea/misc.xml
Updates IntelliJ's configuration with the newer location of Terasology annotations. Assorted other updates to `/.idea/` while we're here. See individual commit messages for details.
If you squash-merge this, please be sure the contents of those commit messages are included!
I wrote this on IntelliJ 2021 Ultimate edition under Linux. It would be good to have someone test
The primary thing to look out for is diff thrashing. The intention behind checking this in is to provide a configuration that _matches_ what we use in practice. If your IDE makes changes to these files every time you start it (leaving your working directory "dirty") it may defeat the purpose.
**However,** it might be confusing for IntelliJ if git makes changes to these files _while you have IntelliJ open._ Before reporting …
=> build(IntelliJ): update annotation paths and other configurations

engine/src/main/java/org/terasology/engine/core/subsystem/lwjgl/LwjglGraphicsUtil.java, engine/src/main/java/org/terasology/engine/rendering/world/WorldRendererImpl.java
here is some minor cleanup of this logic and I also remove GL_NORMALIZED. this is not available in the standard for opengl 30: http://docs.gl/gl3/glEnable
- GL_NORMALIZE is deprecated
- cleanup unused code in WorldRenderImpl
=> chore(rendering): cleanup and remove deprecated glDisabled

engine/src/main/java/org/terasology/engine/utilities/procedural/PerlinNoise.java
An improvement to the existing Perlin noise algorithm.
Perlin noise, since deprecated in this project in favor of Simplex, produces visually significant square bias as a flaw of the algorithm's underlying design. However, the noise is still used in the project in some places. Its visual results can be greatly improved for plane-based voxel world generation, using a simple coordinate-space rotation on the 3D noise that rotates Y to point up the grid's main diagonal (<1, 1, 1>).
Without domain rotation:
With domain rotation:
You can generate the above images by temporarily dropping the following `RenderPerlin.java` into the same directory as `PerlinNoise.java` and running its main method through IntelliJ. The first image was generated without this PR's change, and the second was with it. …
=> feat(noise): Add domain rotation to mitigate Perlin squareness

engine/src/main/java/org/terasology/engine/core/modes/AbstractState.java, engine/src/main/java/org/terasology/engine/core/modes/StateLoading.java, engine/src/main/java/org/terasology/engine/core/modes/StateMainMenu.java, engine/src/main/java/org/terasology/engine/core/subsystem/headless/mode/StateHeadlessSetup.java
I was working with the StateHeadlessSetup class and noticing it has a lot of code duplicated from another class. To make it easier to see what the differences between the various classes are, I extracted the common code to some methods.
No change in functionality is intended by this PR, but I did re-order the execution of some of these components, which has the potential to break something.
I'm not thrilled about the state of things here, but it's a refactor, so please try to limit the scope of your requests to the refactoring. I'd also like to avoid getting pulled down the rabbit hole of putting _all_ the potentially related refactors we can think of into this PR.
Things it would be useful to have feedback on:
* Should this code really **not** be common between these two classes? If you …
=> refactor(GameState): extract common code from MainMenu and HeadlessSetup

engine/src/main/java/org/terasology/engine/core/subsystem/lwjgl/LwjglDisplayDevice.java
`GLFW.glfwGetWindowSize` is fairly expensive so this is only updated once per frame. should help a little bit with performance and I'm still looking into some other modifications to the render pipeline.
=> perf: avoid calling GLFW.glfwGetWindowSize

engine/build.gradle, engine/src/main/java/org/terasology/engine/network/internal/pipelineFactory/InfoRequestPipelineFactory.java, engine/src/main/java/org/terasology/engine/network/internal/pipelineFactory/TerasologyClientPipelineFactory.java, engine/src/main/java/org/terasology/engine/network/internal/pipelineFactory/TerasologyServerPipelineFactory.java
we would need to have a dry run test on a server to verify if this improves the actual network performance. Lz4 is a lot faster compression algorithm for both the consumer and reader. would it be possible to create a one off build to have this on a test server @Cervator. I also run the compress and deflation for both send and receiving packets.   
https://github.com/lz4/lz4
=> perf(network): replace de-/inflate with lz4 for both directions

build-logic/src/main/kotlin/terasology-module.gradle.kts, engine/build.gradle
because we are using our org.terasology fork of reflections.
I noticed while running MTE tests that both `org.reflections:reflections:0.9.10` and `org.terasology:reflections:0.9.12-MB` are in the classpath.
I am not _sure_ if that was contributing to the things I was trying to troubleshoot, but it seems like a bad idea.
I think the root cause is that one of our libraries has a dependency on upstream, not the fork, and we don't have anything set up to declare that the two conflict.
=> build: avoid transitive dependency on org.reflections

engine/src/main/java/org/terasology/engine/network/internal/pipelineFactory/InfoRequestPipelineFactory.java, engine/src/main/java/org/terasology/engine/network/internal/pipelineFactory/TerasologyClientPipelineFactory.java, engine/src/main/java/org/terasology/engine/network/internal/pipelineFactory/TerasologyServerPipelineFactory.java
here are some small tweaks the stream. looks like we've encoded the length of the packet like 3 times. prepend a size before the compressed frame, lz4frame prepends a length to the compressed packet, followed by another length encoding for the protobuf message. l
this is what this change does. lz4frame will split the payload into multiple frames that are sent over the wire. we need the length to be prepend to the protobuf message so we can decode individual protobuf message. 
[frame_rework.zip](https://github.com/MovingBlocks/Terasology/files/6796293/frame_rework.zip)
=> perf: remove extra length prepend

config/groovy/common.groovy
I found grgit works perfectly well with updating ssh remotes. this just drop the validity check here and if the remote does not exist then it will fail when it tries to pull. I moved the check to when the repository is either pulled or cloned. 
- validate by setting up an omega repository `./groovyw module init omega`
- update all the modules `./groovyw module update-all`
=> chore: remove url check when updating repositories

engine/src/main/java/org/terasology/engine/world/chunks/pipeline/ChunkProcessingInfo.java, engine/src/main/java/org/terasology/engine/world/chunks/pipeline/ChunkProcessingPipeline.java
I removed the lock on ChunkProcessInfo and replaced it with a concurrent queue along with the locking on the individual processing objects. the problem is this can introduce a lot of contention where the two reactor threads will have contention over locking both the concurrent map and also locking the individual processing objects. I still see a problem of thrashing where we schedule a chunk processor on one thread and then schedule it again on a different thread.
=> perf: remove extra locking in pipeline to avoid thread contention

engine/src/main/java/org/terasology/engine/rendering/logic/SkeletalMeshComponent.java
Fix - Replicates mesh and material of Skeletal Mesh Component over the network.
- Play Josharias Survival in multiplayer mode with the latest Manual Labor, with 2 players.
- Give yourself a crude shear using ```give crudeshears``` and spawn a sheep using ```spawnPrefab sheep```.
- Use shear on sheep and check if the model change is replicated for the second player
=> fix: replicate mesh and material over network

engine-tests/src/test/java/org/terasology/engine/core/module/ClasspathCompromisingModuleFactoryTest.java, engine/src/main/java/org/terasology/engine/core/modes/loadProcesses/InitialiseWorld.java, engine/src/main/java/org/terasology/engine/core/module/ClasspathCompromisingModuleFactory.java, engine/src/main/java/org/terasology/engine/core/module/ModuleManager.java
When modules run tests, the module and its dependencies are in the classpath. The test runner is unlikely to put unrelated modules in the classpath. This PR enables us to load those modules without registering everything in a `modules/` directory.
Required for some MTE improvements (PR pending).
No expected impact in normal execution, this only takes effect when the system property telling ModuleManager to use classpath modules is turned on.
I think to thing to check is that module tests that are currently passing are still passing with this branch.
I _expect_ that works; if it doesn't, this may have to wait for merge until the accompanying MTE PR is ready.
=> feat(ModuleManager): do not depend on PathManager to load modules from the classpath

engine/src/main/java/org/terasology/engine/logic/characters/CharacterSystem.java, engine/src/main/java/org/terasology/engine/logic/characters/events/ActivationPredicted.java, engine/src/main/java/org/terasology/engine/logic/characters/events/ActivationRequest.java, engine/src/main/java/org/terasology/engine/logic/common/ActivateEvent.java, engine/src/main/java/org/terasology/engine/logic/common/RangeComponent.java, engine/src/main/java/org/terasology/engine/logic/players/LocalPlayer.java
This originates from a discussion with @ahv15 and @jdrueckert on allowing ranged activation of items, e.g., to activate the magic staff in LigthAndShadow targeting a player a couple blocks away. We noticed that `ActivateEvent` fits the use case, but the computation of the `target` is bound to the interaction range as defined in the character component.
As a mitigation, this PR adds a generic `RangeComponent` to indicate some kind of ranged property, e.g., the interaction range of an item, an activation range of a tower or trap, ...
Eventually, we probably want to decouple the interaction range from the character component, and instead just use the `RangeComponent` on the player entity itself.
- feat: allow for ranged item activation
- feat: add simple RangeComponent
- feat: allow owned …
=> feat: allow for ranged item activation

engine/src/main/java/org/terasology/engine/core/TerasologyEngine.java
I reverted a part of the change introduce in this PR: https://github.com/MovingBlocks/Terasology/pull/4829
something is strange about how the context is configured.
=> fix: resolve Advance World Settings issue

engine/src/main/java/org/terasology/engine/core/ComponentSystemManager.java
* Fixes hard crash when System using optional dependency's class in method signature
* Better handling error when system crashes at registering
* ahead detection for using optional dependency  at system 
Start JS with optional dependencies:
1. without
2. with Genome
3. with BasicCrafting
=> fix: Better handling of ComponentSystem loading with optional dependencies

engine-tests/src/test/resources/logback.xml, facades/PC/src/main/resources/logback.xml
Only apply the `logOverrideLevel` to Terasology, but not 3rd party packages we explicitly set the log level for.
Additionally, adds a note how to (temporarily) adjust the configuration to tweak the log output for local testing.
=> chore: adjust default logback configuration

build-logic/src/main/kotlin/terasology-repositories.gradle.kts
This change is required to allow the CrashReporter to import the [`org.jpastebin`](https://mvnrepository.com/artifact/org/jpastebin/1.0.1) dependency which is required to fix the broken CrashReporter integration with PasteBin.
See issue #4699 
See fix https://github.com/MovingBlocks/CrashReporter/pull/44
=> chore: add maven repo that contains jpastebin

build.gradle
Load a test class in IntelliJ IDEA. Push the Run button.
It should give you a choice of whether to use the integrated test runner (icon with red/green triangles) or use gradle's test runner (Gradle elephant icon).
=> test: have IntelliJ ask if tests should be run by itself or gradle

facades/PC/build.gradle.kts, facades/PC/src/main/java/org/terasology/engine/DataSizeConverter.java, facades/PC/src/main/java/org/terasology/engine/Terasology.java
Amendment to #4147. Fixes an overly-broad JUnit dependency and adds some docs.
=> build(facade): oops, junit was supposed to be a test-only dependency

.idea/dictionaries/kevint.xml, engine/src/main/java/org/terasology/engine/rendering/primitives/ChunkMesh.java, engine/src/main/java/org/terasology/engine/rendering/world/RenderableWorldImpl.java, engine/src/main/java/org/terasology/engine/world/chunks/Chunk.java
Addressing some of the lint bits that came up in #4786. This is just clearing the way to have fewer distractions in that PR.
=> chore: some lintings and suggested simplifications

engine/src/main/java/org/terasology/engine/entitySystem/entity/internal/PojoEntityPool.java
Just reduce many stream's object creation.
See #performance channel at discord
VisualVM:
1. start CoreGamplay empty server
2. attach visualvm
3. set memory sampler and per thread allocation. (there reduce 100MB -> 30MB per second at my system)
Game:
1. start CoreGameplay(or another gameplay)
2. check that all works as previous ( any process with selecting entity with several components enough)
=> perf: replace creating streams by arrays in stream

facades/PC/src/main/resources/splash/shader/frag.glsl, facades/PC/src/main/resources/splash/shader/vert.glsl
found we have some old references for texture2D
```
13:14:24.593 [main] WARN  o.t.e.rendering.opengl.GLSLShader - Shader 'CoreRendering:chunk' failed to compile for features '[]'.
Game output: 
Game output: Shader Info: 
Game output: ERROR: 0:506: Invalid call of undeclared identifier 'texture2D'
Game output: ERROR: 0:509: Use of undeclared identifier 'maskColor'
```
ref: https://github.com/Terasology/CoreRendering/pull/72
=> bugfix: migrate deprecated texture2D

engine/src/main/java/org/terasology/engine/core/PathManager.java
A recent PathManager change (#4890) broke some tests under Jenkins module builds.
Here are the Health tests run on Nanoware with this PR applied, and its MTE tests are passing again: https://jenkins.terasology.io/teraorg/job/Nanoware/job/TerasologyModules/job/H/job/Health/job/develop/21/testReport/
=> fix(PathManager): working directory should always be a fallback

.idea/checkstyle-idea.xml, config/gradle/common.gradle
Small tweaks to how CheckStyle is setup in gradle and IntelliJ.
The most impactful one is that `scan-before-checkin`.
I was tempted to see if we could get rid of the `samedir` property, but that princess is in another castle.
=> build(IntelliJ): turn on checkstyle.scan-before-checkin

engine/src/main/java/org/terasology/engine/logic/location/LocationComponent.java, engine/src/main/java/org/terasology/engine/world/RelevanceRegionComponent.java
chore: prefer set() over new instances in copyFrom()
=> chore(LocationComponent): provide convenience constructor for Vector3i

engine-tests/src/test/java/org/terasology/engine/rendering/assets/mesh/VertexGLAttributeTest.java, engine-tests/src/test/java/org/terasology/engine/rendering/assets/mesh/VertexResourceTest.java, engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/GLAttributes.java, engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/VertexByteAttribute.java, engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/VertexByteAttributeBinding.java, engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/VertexResourceBuilder.java, engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/VertexShortAttribute.java, engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/VertexShortAttributeBinding.java, engine/src/main/java/org/terasology/engine/rendering/primitives/ChunkMesh.java, engine/src/main/java/org/terasology/engine/world/block/shapes/BlockMeshPart.java
I added attribute bindings for short and byte and also add some additional test that cover these cases.
=> feat: add vertex attribute bindings for short and byte

build-logic/src/main/kotlin/terasology-module.gradle.kts, engine-tests/build.gradle, engine/build.gradle
test: upgrade to junit 5.8.1 from 5.7, mockito 3.12.4 from 3.11
The minor upgrades to junit and mockito upgrades are _unlikely_ to break, but you could run module tests if you're feeling extra cautious.
=> test(modules): make com.google.truth assertion library available

engine-tests/src/test/java/org/terasology/engine/rendering/assets/mesh/VertexAttributeBindingTest.java, engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/VertexAttributeBinding.java, engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/VertexFloatAttributeBinding.java, engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/VertexIntegerAttributeBinding.java
I added a way to pass in multiple vertices in one pass. should make the API easier to use.
=> chore: update vertex attribute with put(T[] data)

engine/src/main/java/org/terasology/engine/world/chunks/localChunkProvider/LocalChunkProvider.java, engine/src/main/java/org/terasology/engine/world/chunks/localChunkProvider/RelevanceSystem.java, engine/src/main/java/org/terasology/engine/world/chunks/pipeline/ChunkProcessingPipeline.java
This is used by the code I'm adding so MTE knows when a region is ready.
No user-visible changes, as this method only returned `void` before.
One wrinkle is that the return value only tells you the region's _initial_ position. That's something that could change as the entity moves or resizes the region.
=> feat(RelevanceSystem): addRelevanceEntity returns the relevant region

engine/src/main/java/org/terasology/engine/core/TerasologyEngine.java, engine/src/main/java/org/terasology/engine/core/modes/AbstractState.java, engine/src/main/java/org/terasology/engine/core/modes/StateIngame.java, engine/src/main/java/org/terasology/engine/core/modes/StateLoading.java, engine/src/main/java/org/terasology/engine/core/modes/StateMainMenu.java, engine/src/main/java/org/terasology/engine/core/subsystem/headless/HeadlessInput.java, engine/src/main/java/org/terasology/engine/core/subsystem/headless/mode/StateHeadlessSetup.java, engine/src/main/java/org/terasology/engine/core/subsystem/headless/renderer/HeadlessWorldRenderer.java, engine/src/main/java/org/terasology/engine/input/InputSystem.java, engine/src/main/java/org/terasology/engine/logic/chat/ChatSystem.java, engine/src/main/java/org/terasology/engine/logic/console/ConsoleSystem.java, facades/PC/src/main/java/org/terasology/engine/Terasology.java
Removes InputSystem exception from headless 
Fixes #4481  
Fixes #3793
Removes NuiManager from headless. (yahoo ! no more screens and jpgs at headless mode - MTE, Server, headless client)
Try game in 4 modes:
1. Server(Headless)
2. Host game(from main menu)
3. Connect to server(can reuse 1)
4. Singleplayer
You should:
0. enter
1. play a bit
2. exit as usually
=> fix(headless-fixes): remove InputSystem and NuiManager from headlesses

engine/src/main/java/org/terasology/engine/core/modes/StateMainMenu.java
How to test: There are places in MTE where it logs the game state. Not sure if the headless server does by itself.
=> chore(StateMainMenu): include message in toString representation for debugging

engine/src/main/java/org/terasology/engine/core/modes/loadProcesses/StartServer.java, engine/src/main/java/org/terasology/engine/network/internal/NetworkSystemImpl.java, engine/src/main/java/org/terasology/engine/rendering/nui/skin/UISkinFormat.java
This seemingly fixes a case where you can't host the game headlessly _if you have modules active with `UISkinFormat` assets_ ! Which is probably a bit quirky. Since there's no longer a `NUIManager` available in the `Context` when you're running headlessly we really shouldn't attempt to use it during initialization. There may still be other cases where this could factor in.
Additionally I caught an exception being swallowed and a weird game state being entered in the case where you fail to establish the game host due to for instance already having the port in use. Previously that would freak out and fail to create a NUI popup informing the user which isn't very helpful when trying to start a headless server. Now it logs an error and promptly terminates the game - if headed it'll still fall …
=> fix: Avoid a couple cases where no NUIManager would cause trouble.

engine-tests/src/test/java/org/terasology/engine/rendering/assets/mesh/VertexResourceTest.java, engine/src/main/java/org/terasology/engine/persistence/typeHandling/extensionTypes/ChunkMeshTypeHandler.java, engine/src/main/java/org/terasology/engine/rendering/assets/mesh/StandardMeshData.java, engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/BufferedResource.java, engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/IndexResource.java, engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/VertexResource.java
refactored vertex resource with updated javadocs, more tests and tried to make test cases more consistent
- replaced `copyBuffer` with `replace`
- this will replace the contents of a buffer with the target one 
- introduced put commend
- will take a bytebuffer or buffered resource and append it to the existing.
=> refactor: add test cases for vertex resource and update api with put and replace

engine/src/main/java/org/terasology/engine/config/SystemConfig.java
fix for MTE tests failing to create SystemConfig on single-core VMs
=> fix(SystemConfig): ensure thread max limit is never less than one

engine/build.gradle
being able to use functions with multiple arguments as subscribers is very nice.
There's a bit of a question here whether we use the BOM they publish to specify which versions of the reactor stuff we use, or track versions of reactor-core and reactor-extra ourselves: https://projectreactor.io/docs/core/release/reference/#getting
I'm fine either way with that one.
=> chore: add reactor-extra to dependencies

Jenkinsfile
Reverts MovingBlocks/Terasology#4927 due to failing TypeHandlerLibrary test
=> Revert "build(ci): build using a java 11 toolchain"

build-logic/src/main/kotlin/facade.gradle.kts, subsystems/TypeHandlerLibrary/build.gradle.kts
I think we haven't been running the tests in TypeHandlerLibrary on CI ever since we did the unitTest / integrationTest split.
Make sure the list of test results on Jenkins includes some tests from `org.terasology.persistence`.
=> test: add unitTest target to TypeHandlerLibrary and facades

subsystems/TypeHandlerLibrary/build.gradle.kts
Otherwise it says “defaulting to no-operation (NOP) logger implementation” and we don't see messages that could help diagnose test failures.
Fixes #4943.
=> test(TypeHandlerLibrary): provide a logger during test execution

build-logic/build.gradle.kts, build-logic/src/main/kotlin/terasology-repositories.gradle.kts, build.gradle, templates/build.gradle
So today Nov 7th for no discernable reason Gradle stopped being able to resolve snapshot dependencies from our Artifactory instance. I was able to replicate it locally in a handy workspace I hadn't touched since June, so it wasn't anything we changed anywhere, including Artifactory really - it is rarely ever touched and hasn't been upgraded for years (doing so is on a todo list somewhere).
Closest guess I can make is that it is an Artifactory OSS vs Pro feature: https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-RetrieveLatestArtifact - supposedly automatically fetching the latest incremental version of a snapshot is a Pro feature. Who knew? We've been using it in the OSS version since day 1! No idea how that has worked so far if the docs are accurate. …
=> build: fix mystery Artifactory issue

engine/src/main/java/org/terasology/engine/rendering/nui/layers/ingame/metrics/DebugOverlay.java, engine/src/main/java/org/terasology/engine/rendering/nui/layers/ingame/metrics/MetricsMode.java, engine/src/main/java/org/terasology/engine/rendering/nui/layers/ingame/metrics/NetworkStatsMode.java, engine/src/main/java/org/terasology/engine/rendering/nui/layers/ingame/metrics/NullMetricsMode.java, engine/src/main/java/org/terasology/engine/rendering/nui/layers/ingame/metrics/RunningThreadsMode.java, engine/src/main/java/org/terasology/engine/rendering/nui/layers/ingame/metrics/WorldRendererMode.java, engine/src/main/java/org/terasology/engine/utilities/OperatingSystemMemory.java
Adds the data size of the process to the F3 debug overlay. This is a value from the operating system, not the JVM.
The new values are:
- **Data:** 5850.3 / 6144.0 MB (95%)
- 5850.3 MB is the size of this process's data segment and stack
- 6144.0 MB is the maximum data size allowed by the `--max-data-size=6G` option I launched the game with
- 95% is how close it is to that limit
- **Extra:** 2778.3 MB is how much larger this data size is than the _Total Memory_ number shown by the JVM
Only implemented for Linux.
Push `F3` to bring up the debug overlay while in game.
Try it with and without the [`--max-data-size`](https://github.com/MovingBlocks/Terasology/wiki/Advanced-Options#memory-usage) option on Linux.
=> feat(F3): show process data size and limit

config/gradle/common.gradle
Removes the messages that say things like `no @return` when building javadoc.
Because there is no way to suppress those on a case-by-case basis before [Java 18](https://bugs.openjdk.java.net/browse/JDK-8274926).
=> build(javadoc): disable doclint messages about missing tags

engine/src/main/java/org/terasology/engine/network/internal/NetworkSystemImpl.java
Resolves #4920
To test: start a server, make sure the removed logging doesn't show, yet the game server still works and listens for clients
=> chore: remove some slow logging

engine/src/main/java/org/terasology/engine/rendering/primitives/BlockMeshGeneratorSingleShape.java, engine/src/main/java/org/terasology/engine/rendering/primitives/BlockMeshShapeGenerator.java
After reviewing what the tesselator used to look like before the attribute changes I think its a pretty straightforward change to drop the use of the Tesselator and submit the mesh data directly. The code is already to a degree simpler so Tesselator does not seem appropriate anymore. The only other place this is referenced is within flowing liquids so I could just move this up into the interface as a default maybe?
https://github.com/MovingBlocks/Terasology/blob/c725b454517bcaec881c343d5045eb76d722868b/engine/src/main/java/org/terasology/engine/rendering/primitives/Tessellator.java
=> refactor: construct block mesh generator single shape with standard mesh data

build-logic/src/main/kotlin/org/terasology/gradology/exec.kt, build.gradle, config/.gitignore, engine/build.gradle, engine/src/main/java/org/terasology/engine/core/GameScheduler.java, engine/src/main/java/org/terasology/engine/core/subsystem/common/MonitoringSubsystem.java
This adds an option to the `gradlew game` task that configures it to accept remote JMX connections. JMX is _Java Management Extensions_, see the [Java Monitoring and Management Guide][JMnMG] for details. It gives us as Terasology developers a way to see some system stats in near real-time without figuring out how to fit them on a F3 debug overlay, and it works equally well for headless servers.
[JMnMG]: https://docs.oracle.com/en/java/javase/11/management/preface.html#GUID-416153CD-A661-4F46-ACC3-CDA94E4A8CDA
It depends on [Micrometer](https://micrometer.io/) to facilitate this, which you may recall from previous conversations around #4799.
As a demonstration for how we can use this to view Terasology-specific things, it publishes the game's current framerate as `terasology.fps`.
Demo …
=> feat: micrometer metrics over JMX

engine/src/main/java/org/terasology/engine/rendering/world/ChunkMeshWorker.java, engine/src/main/java/org/terasology/engine/rendering/world/ChunkWorker.java, engine/src/main/java/org/terasology/engine/rendering/world/RenderableWorldImpl.java, engine/src/main/java/org/terasology/engine/rendering/world/WorldRendererImpl.java, engine/src/main/java/org/terasology/engine/world/chunks/LodChunkProvider.java
so I have a separate object just for managing the chunk meshiness and I moved a lot of stuff out so we don't couple the implementation directly to the context. constructor is looking a lot worse but I rather do that then use the context in its current form. 
RenderableWorldImpl at the moment is gluing a lot of systems together not sure how this could be better organized. The way that LOD's are processed in a separate system introduces a lot of complications with control flow. 
this is just a continuation of these changes: https://github.com/MovingBlocks/Terasology/pull/4786
=> refactor: split out chunk work as a seperate helper class

engine/src/main/java/org/terasology/engine/world/chunks/Chunk.java, engine/src/main/java/org/terasology/engine/world/chunks/internal/ChunkImpl.java, engine/src/main/java/org/terasology/engine/world/chunks/internal/PreLodChunk.java
I cherry-picked this refactoring out of #4987.
This PR isn't blocking, but merging it now will make other work in the area easier to review.
=> refactor(Chunk): provide default implementations of methods where possible

engine/src/main/java/org/terasology/engine/physics/engine/PhysicsEngine.java
We have code like this in some place, seemingly to make sure the character collider is recomputed to reflect changed values on the entity's components.
```java
physicsEngine.removeCharacterCollider(entity);
physicsEngine.getCharacterCollider(entity);
```
With the ability to simply add this as default method implementation in the interface we can provide a documented implementation for this, introducing a better alternative to cryptically calling `remove...` and `get...`.
=> feat: add convenience method  PhyiscEngine#recomputeCharacterCollider(entity)

build.gradle
Update lwjgl version to 3.3.
this version  of lwjgl provide:
1. wayland support (needs code changes at current moment)
2. arm64 versions of windows/macOs/linux
Run Terasology and create/load game.
=> chore: Update lwjgl version to 3.3.1

build-logic/src/main/kotlin/org/terasology/gradology/file_operations.kt, build.gradle
Without this fix Gradle fails to find the templates directory for some reason. Exact same setup (although different JDK 11 I think) on my non-M1 Mac worked fine. Not sure if it is a base issue with M1 Macs or the JDK, but in either case this fixed it.
More issues are piled up beyond this for where there are no arm64 lib variants for the new Apple Silicon chip setup, first one is protobuf, but that's a problem for another day.
=> fix: path quirk on an M1 Mac using Azul JDK 11

.idea/.gitignore, .idea/dictionaries/kevint.xml, .idea/misc.xml
Some updates to `.idea`. Currently using IntelliJ IDEA 2022.1 (Ultimate Edition)
Build #IU-221.5080.210, built on April 11, 2022
Test plan:
- pull
- restart IntelliJ
- `git diff`: are there any changes to `.idea/misc.xml`?
I did leave out a `SwUserDefinedSpecifications` component from `misc.xml`, as that's new and I'm not sure if everyone got it or it's something peculiar to my instance.
If it turns out that's something auto-generated for everyone when upgrading to IntelliJ 2022.1, we can go ahead and add that too.
=> build(idea): update dictionary and gitignores

engine/src/main/java/org/terasology/engine/core/modes/loadProcesses/InitialiseWorld.java, engine/src/main/java/org/terasology/engine/game/GameManifest.java, engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/SelectionScreen.java, engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/gameDetailsScreen/GameDetailsScreen.java, engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/savedGames/GameInfo.java
Fixes #4912
The `mainWorldDisplayName` method I factored out to `GameManifest` is very much a "view" type of method, given the way it returns error strings. I'd accept suggestions of other places to put it. Especially if that place had dependency injection support so the caller doesn't have to explicitly pass WorldGeneratorManager.
Edit the `manifest.json` of one of your save files so the `worlds` entry is the empty set: `"worlds": {},`
Start Terasology and go to the game loading screen, make sure that doesn't crash.
Hit the "Details" button, make sure that doesn't crash.
If you proceed to try to actually load the game, _that_ will crash (we can only do so much with a broken save!). Hopefully with a relevant error message.
=> fix(SelectionScreen): be more robust in the face of save files with incomplete manifests

engine-tests/src/test/java/org/terasology/engine/persistence/internal/StorageManagerTest.java, engine/src/main/java/org/terasology/engine/persistence/internal/ReadWriteStorageManager.java, engine/src/main/java/org/terasology/engine/persistence/internal/SaveTransaction.java, engine/src/main/java/org/terasology/engine/world/generator/WorldConfigurator.java
Responding to code inspections and suggestions.
Some cleanup to reduce distractions while working on StorageManager for #4800.
Might have some conflicts with that branch, but both these branches are pretty small, shouldn't be too much trouble to resolve.
=> chore(StorageManager): typos and minor code cleanups

engine/src/main/java/org/terasology/engine/world/chunks/pipeline/ChunkProcessingPipeline.java
This is the sort of thing I wanted to fix by moving everything to consistent use of a reactor Scheduler. But it's causing test failures now: the test runner with 1.9 CPUs can't handle running 4 chunk generation threads plus the main loop and the overhead of having them all report to the jacoco monitor.
(it was managing about 2 chunks/second, blocking #5010)
Play game, see if chunk generation is at least as fast as it was.
=> fix(ChunkProcessingPipeline): base thread pool size on available processors

config/gradle/common.gradle, engine-tests/build.gradle
upgrade to jacoco 0.8.8 (from 0.8.5)
relates to #4985
Run integrationTest and unitTest
Run jacocoTestReport
check to see if test output contains loads of messages about IllegalClassFormat
It would be good to have less configuration duplication. The excludes-list is set in several places,
and there are probably places that need it but don't have it yet. (module tests? subsystem tests?)
=> fix(test): set jacoco excludes for engine-test's unitTest and integrationTest tasks

Jenkinsfile, build-logic/build.gradle.kts, build-logic/src/main/kotlin/facade.gradle.kts, build-logic/src/main/kotlin/terasology-common.gradle.kts, build-logic/src/main/kotlin/terasology-metrics.gradle.kts, build-logic/src/main/kotlin/terasology-module.gradle.kts, build.gradle, config/gradle/common.gradle, engine-tests/build.gradle, engine/build.gradle, facades/PC/build.gradle.kts, subsystems/DiscordRPC/build.gradle.kts, subsystems/TypeHandlerLibrary/build.gradle.kts, templates/build.gradle
It didn't take long to run in to other parts of #4985; #5013 didn't include configuration for module builds.
That was happening in `common.gradle`, so it seemed like a good time to extract a chunk of that stuff to `build-logic`, in line with the other gradle plans of #4015.
Removes jacoco, because it wasn't even used by CI.
Most of the stuff from `common.gradle` went to `terasology-metrics.gradle.kts`. Except the jacoco parts, they were dropped.
It does look a little weird to have moved 80% of common.gradle, but some of the last things needed more investigation, so I decided to keep scope to the various checks.
- run engine-tests locally: unitTest, integrationTest, test
- run subsystem tests locally: unitTest, test
- run module tests locally: unitTest, integrationTest, test
- run `check` …
=> build: extract project metrics/analytics to terasology-metrics gradle plugin

engine-tests/src/test/java/org/terasology/engine/registry/CoreRegistryTest.java, engine/src/main/java/org/terasology/engine/context/Context.java, engine/src/main/java/org/terasology/engine/context/internal/ContextImpl.java, engine/src/main/java/org/terasology/engine/context/internal/MockContext.java
T get(Class<? extends T> type) would mean that `type` could be a subclass of the return value.
e.g. returning a Number when asked for a Float.
That's the opposite of what we wanted!
Might break binary compatibility and trigger a lot of recompiling. I don't expect it to break source compatibility with any current code.
**Also:** 
feat(Context): add non-null and Optional get methods
=> fix(Context)!: correct signature of Context.get

engine-tests/src/test/java/org/terasology/engine/registry/InjectionHelperTest.java, engine/src/main/java/org/terasology/engine/context/Context.java, engine/src/main/java/org/terasology/engine/context/internal/ContextImpl.java, engine/src/main/java/org/terasology/engine/registry/InjectionHelper.java
Allows doing things like 
```java
Foo x = inject(new Foo(), context);
```
compared to previously, when inject() was void:
```java
Foo x = new Foo();
inject(x, context);
```
Won't break any existing code.
Also includes some minor changes to ContextImpl error messages.
=> feat(InjectionHelper): inject() returns the object for chaining

engine-tests/src/main/java/org/terasology/engine/integrationenvironment/Engines.java, engine-tests/src/test/java/org/terasology/engine/integrationenvironment/ClientConnectionTest.java
We saw a sporadic test failure on `develop` builds recently (e.g., [develop/709](https://jenkins.terasology.io/teraorg/blue/organizations/jenkins/Terasology%2Fengine/detail/develop/709/tests/) a0c6606).
```
org.opentest4j.MultipleFailuresError: Multiple Failures (1 failure)
org.opentest4j.AssertionFailedError: expected: <org.terasology.engine.core.modes.StateIngame> but was: <org.terasology.engine.core.modes.StateLoading>
```
To help understand which of the "engines" is actually in the wrong state, we add some logging information about the instances. 
This should help to figure out whether the `createClient()` method is errorneous (as it should be blocking until the client is in state _in-game_) or the failure lies with the host's engine.
Furthermore, this PR changes …
=> test: add info logs to help track down sporadic

.idea/checkstyle-idea.xml, .idea/findbugs-idea.xml, build-logic/src/main/kotlin/terasology-metrics.gradle.kts, engine-tests/src/test/java/org/terasology/documentation/ApiScraper.java, engine-tests/src/test/java/org/terasology/documentation/apiScraper/CompleteApiScraper.java, engine-tests/src/test/java/org/terasology/engine/world/generation/facets/BooleanFacetTest.java, engine-tests/src/test/java/org/terasology/math/IntegerRangeTest.java, engine/src/main/java/org/terasology/engine/rendering/dag/RenderGraph.java, engine/src/main/java/org/terasology/engine/rendering/dag/dependencyConnections/DependencyConnection.java, engine/src/main/java/org/terasology/engine/rendering/nui/widgets/browser/ui/ParagraphRenderable.java
build(spotbugs): point idea to the config/metrics file
This PR mostly motivated by some minor format change in the checkstyle-idea.xml in recent versions.
But let's use the checkstyle version (10.x) for Java 11 too.
Check [CI for this PR](https://jenkins.terasology.io/teraorg/job/Terasology/job/engine/view/change-requests/job/PR-5027/lastBuild/) to make sure it didn't lose all its checkstyle findings.
Make sure you can still run Checkstyle in IntelliJ.
=> build(checkstyle): update to version 10.2, update .idea to match

templates/override.cfg
Follow-up from the removal of the perlin world type in https://github.com/Terasology/CoreWorlds/pull/44
=> fix(templates): replace perlin with simplex as the default override.cfg

engine-tests/src/main/java/org/terasology/engine/integrationenvironment/Engines.java, engine-tests/src/main/java/org/terasology/engine/integrationenvironment/jupiter/IntegrationEnvironment.java, engine-tests/src/test/java/org/terasology/engine/integrationenvironment/ClientConnectionTest.java, engine-tests/src/test/java/org/terasology/engine/integrationenvironment/ExampleTest.java, engine-tests/src/test/java/org/terasology/engine/integrationenvironment/delay/DelayManagerTest.java
This changes MTE's default network mode from LISTEN_SERVER to NONE.
I expect this to provide in increased reliability and speed for most MTE tests, as it removes the question of whether the server port is available and the delay on network shutdown.
Those few [tests that _do_ use `createClient`](https://github.com/search?q=org%3ATerasology+createClient+-repo%3ATerasology%2FModuleTestingEnvironment&type=code) will need to adjust by setting their NetworkMode to LISTEN_SERVER or DEDICATED_SERVER.
The other potential incompatibility is that NONE does start with a Player; LISTEN_SERVER did not. That may be a problem if the environment does not provide a place for the player to spawn.
(Currently, we do not have any way of starting without either a network server _or_ a player.)
Related:
Run …
=> test(MTE)! set default NetworkMode to NONE

engine-tests/src/test/java/org/terasology/engine/integrationenvironment/ChunkRegionFutureTest.java
PR #5041 introdcued a failing test due to a missing network mode setting on the `ChunkRegionFutureTest`.
This PR adds the `networkMode = NetworkMode.LISTEN_SERVER` setting for the integration environment to fix it.
Run the integration tests for the engine and ensure no failures:
```
gradlew :engine-tests:integrationTest
```
=> fixup! test(MTE)! set default NetworkMode to NONE (#5041)

engine-tests/build.gradle, engine-tests/src/main/java/org/terasology/engine/integrationenvironment/Engines.java, engine-tests/src/main/java/org/terasology/engine/integrationenvironment/IntegrationEnvironmentSubsystem.java, engine-tests/src/main/java/org/terasology/engine/integrationenvironment/jupiter/IntegrationEnvironment.java, engine-tests/src/main/java/org/terasology/engine/integrationenvironment/jupiter/MTEExtension.java, engine-tests/src/main/java/org/terasology/engine/testUtil/Correspondences.java, engine-tests/src/main/java/org/terasology/engine/testUtil/WithUnittestModule.java, engine-tests/src/test/java/org/terasology/engine/integrationenvironment/CustomSubsystemTest.java
- **Main feature:** Allows a test to specify <code>@IntegrationEnvironment(subsystem=<b>SomeEngineSubsystem.class</b>)</code>, giving the author more control during engine initialization and much more power to shoot themselves in the foot.
- Moves some bits of configuration out of `integrationenvironment.Engines` and in to an `IntegrationEnvironmentSubsystem`. This makes it easier to guess when that code will be run (compared to usual non-MTE code), and makes it easier to override if needed. 
IntegrationEnvironmentSubsystem.registerCurrentDirectoryIfModule is a direct move of a method formerly in `integrationenvironent.Engines`.
This is an MTE-only change, so there's no player-visible impact. You could use `CustomSubsystemTest` as an example to start from if you want to experiment with it …
=> test(MTE): allow a test to add its own EngineSubsystem

subsystems/TypeHandlerLibrary/src/main/java/org/terasology/persistence/typeHandling/coreTypes/GenericMapTypeHandler.java, subsystems/TypeHandlerLibrary/src/main/java/org/terasology/persistence/typeHandling/coreTypes/ObjectFieldMapTypeHandler.java, subsystems/TypeHandlerLibrary/src/main/java/org/terasology/persistence/typeHandling/coreTypes/RuntimeDelegatingTypeHandler.java, subsystems/TypeHandlerLibrary/src/main/java/org/terasology/persistence/typeHandling/inMemory/PersistedMap.java, subsystems/TypeHandlerLibrary/src/main/java/org/terasology/persistence/typeHandling/inMemory/PersistedString.java, subsystems/TypeHandlerLibrary/src/main/java/org/terasology/reflection/reflect/ConstructorLibrary.java, subsystems/TypeHandlerLibrary/src/test/java/org/terasology/persistence/typeHandling/coreTypes/GenericMapTypeHandlerTest.java
Fixes a case in GenericMapTypeHandler where it's trying to tell you about some error it's found and uses `data.getAsString()` to describe it, but that results in _another_ error when `data` isn't` String`.
=> fix(TypeHandlerLibrary): fix error-during-error-logging in GenericMap

engine/src/main/java/org/terasology/engine/entitySystem/entity/EntityPool.java
[Java generic types are a mess][genericMethods], especially where varargs are involved. We can't use [`@SafeVarargs`][safeVarargs] on interface methods because there is no way to know the _implementations_ of the interface are safe.
In this case, in practice, there are few (if any) callers that pass more than two values.
By adding methods that explicitly take one and two values, we can present an interface the compiler doesn't need to complain about at every call site.
[genericMethods]: http://www.angelikalanger.com/GenericsFAQ/FAQSections/ProgrammingIdioms.html#Topic5 "Designing Generic Methods"
[safeVarargs]: https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/SafeVarargs.html
- find any caller of `entityManager.getEntitiesWith(SomeComponent.class)`
- notice unhappy …
=> chore(EntityPool): workaround "unchecked generics array creation" for getEntitiesWith

engine/src/main/java/org/terasology/engine/logic/behavior/BehaviorSystem.java
Fixes some of the messages about entities not having finite position or rotation.
Skips all `BehaviorSystem.update` when the time delta is zero.
The issue was coming up specifically as a result of movement actions running during this update, since they were coming up with absurd results trying to calculate changes in position over zero time.
But I figured that skipping the entire system is probably a sensible thing to do. Unless you can think of anything Behavior-related that should still be ticking during the pause menu?
Or perhaps we should have a separate variant of [UpdateSubscriberSystem](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/engine/entitySystem/systems/UpdateSubscriberSystem.java) that only updates when engine-time is advancing. …
=> fix: do not run behavior simulation while paused

facades/PC/src/main/java/org/terasology/engine/Terasology.java
It wasn't calling engine.run()
Run Terasology with the `--load-last-game` option.
If running from gradle, that's
```sh
gradlew game --args="--homedir=. --load-last-game"
```
Check `--create-last-game` too.
=> fix(facade): fix broken --load-last-game

.idea/runConfigurations/TerasologyPC__2nd_client_for_mac.xml, .idea/runConfigurations/TerasologyPC_for_mac.xml
We must have missed these run configurations when we changed the way we do our
command line argument parsing. Only changes are correcting the way the 
confiugration passes parameters to the game:
- ~~`-homedir`~~ becomes `--homedir`
- ~~`-noCrashReport`~~ becomes `--no-crash-report`
- ~~`-noSpalsh`~~ becomes `--no-splash`
=> build(idea): fix parameters in run configurations

engine/src/main/java/org/terasology/engine/utilities/Assets.java
There are only a few utility functions in `Assets` that use more than one line
of code. And even those can be simplified to fit into a single line by making
better use of the (functional) interfaces of `Optional` or by removing
unnecessary checks and early returns.
=> chore: simplify implementation in Assets to one-liners

.idea/codeInsightSettings.xml, .idea/kotlinc.xml
- exclude some things from import suggestions
- add kotlinc default configuration (seemingly added with some recent IntelliJ version?)
Restart IntelliJ and see if it complains about these files or makes changes to them.
=> build(idea): exclude some things from import suggestions

engine/src/main/java/org/terasology/engine/core/subsystem/lwjgl/LwjglGraphics.java
Trying to set the window icon on macOS results in an exception since
[glfw/glfw@9a87c2a](https://github.com/glfw/glfw/commit/9a87c2a4b49808d3666c7b093b77e8512fa23908).
This will be printed out as an error by our default handler for GLFW
errors.
However, we can easily prevent this by not attempting to use this
feature when running on macOS.
=> fix(rendering): Don't try to set window icon on macOS

engine/src/main/java/org/terasology/engine/world/block/internal/BlockManagerImpl.java
Improves the logging in `BlockManager` by printing out the (raw) block
family names in case it could not be parsed or processed correctly.
Also, adds a logging statement to a code path which was previously
silently ignored.
=> chore(world): improve logging for BlockManager

.idea/kotlinc.xml, subsystems/TypeHandlerLibrary/src/main/java/org/terasology/persistence/typeHandling/coreTypes/GenericMapTypeHandler.java, subsystems/TypeHandlerLibrary/src/test/java/org/terasology/persistence/typeHandling/coreTypes/GenericMapTypeHandlerTest.java
- detect incorrect map format (object instead of array) early, log expected format
```
"mapName": [
{ "key": "...", "value": "..." }
]
```
- add null check to avoid crashing if key "key" not found in case of incorrect map format (no map entry for "key")
- add null check to avoid crashing if key "value" not found in case of incorrect map format (no map entry for "value")
Can be tested in combination with https://github.com/Terasology/PlantPack/pull/20
=> fix: do not crash on unexpected map format in GenericMapTypeHandler

engine-tests/src/test/java/org/terasology/engine/persistence/typeHandling/extensionTypes/BlockUriTypeHandlerTest.java, engine-tests/src/test/java/org/terasology/engine/persistence/typeHandling/extensionTypes/SimpleUriTypeHandlerTest.java, engine/src/main/java/org/terasology/engine/persistence/typeHandling/TypeHandlerLibraryImpl.java, engine/src/main/java/org/terasology/engine/persistence/typeHandling/extensionTypes/BlockUriTypeHandler.java, engine/src/main/java/org/terasology/engine/persistence/typeHandling/extensionTypes/SimpleUriTypeHandler.java
New type handlers to support de-/serializing to/from [`SimpleUri`](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/engine/core/SimpleUri.java) and [`BlockUri`](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/engine/world/block/BlockUri.java).
Can be tested in combination with https://github.com/Terasology/ChangingBlocks/pull/15.
=> feat: add type handlers for SimpleUri and BlockUri
